export const PHASE4_TABLES = [
  {domain:"settings",source:"app_settings",pk:["key"]},
  {domain:"operations",source:"admin_users",pk:["user_id"]},
  {domain:"operations",source:"feature_flags",pk:["flag_key"]},
  {domain:"operations",source:"maintenance_settings",pk:["id"]},
  {domain:"operations",source:"notification_templates",pk:["id"]},
  {domain:"profiles",source:"profiles",pk:["user_id"]},
  {domain:"profiles",source:"user_preferences",pk:["user_id"]},
  {domain:"academic",source:"course_levels",pk:["id"]},
  {domain:"academic",source:"course_groups",pk:["id"]},
  {domain:"academic",source:"subjects",pk:["id"]},
  {domain:"academic",source:"syllabus_versions",pk:["id"],deferred:["supersedes_version_id"]},
  {domain:"academic",source:"exam_attempts",pk:["id"]},
  {domain:"academic",source:"chapters",pk:["id"]},
  {domain:"academic",source:"topics",pk:["id"]},
  {domain:"academic",source:"attempt_syllabus_map",pk:["id"]},
  {domain:"academic",source:"academic_change_events",pk:["id"]},
  {domain:"progress",source:"chapter_progress",pk:["user_id","chapter_id"]},
  {domain:"progress",source:"progress_events",pk:["id"],deferred:["reverts_event_id"]},
  {domain:"planner",source:"planner_events",pk:["id"]},
  {domain:"planner",source:"daily_plans",pk:["id"]},
  {domain:"planner",source:"daily_plan_items",pk:["id"]},
  {domain:"planner",source:"revision_rules",pk:["user_id"]},
  {domain:"planner",source:"revision_due_items",pk:["id"]},
  {domain:"planner",source:"tasks",pk:["id"]},
  {domain:"planner",source:"goals",pk:["id"]},
  {domain:"planner",source:"user_calendar_events",pk:["id"]},
  {domain:"planner",source:"dashboard_events",pk:["id"]},
  {domain:"planner",source:"forecast_snapshots",pk:["id"]},
  {domain:"study",source:"study_sessions",pk:["id"]},
  {domain:"study",source:"study_timer_state",pk:["user_id"]},
  {domain:"resources",source:"notes",pk:["id"]},
  {domain:"resources",source:"note_tags",pk:["id"]},
  {domain:"resources",source:"note_tag_map",pk:["note_id","tag_id"]},
  {domain:"resources",source:"uploaded_resources",pk:["id"]},
  {domain:"resources",source:"resource_subject_map",pk:["resource_id","subject_id"]},
  {domain:"resources",source:"resource_attempt_map",pk:["resource_id","attempt_id"]},
  {domain:"resources",source:"resource_reports",pk:["id"]},
  {domain:"resources",source:"resource_moderation",pk:["id"]},
  {domain:"community",source:"community_channels",pk:["id"]},
  {domain:"community",source:"community_messages",pk:["id"],deferred:["reply_to_message_id"]},
  {domain:"community",source:"community_message_mentions",pk:["message_id","user_id"]},
  {domain:"community",source:"message_reactions",pk:["message_id","user_id","emoji"]},
  {domain:"community",source:"pinned_messages",pk:["channel_id","message_id"]},
  {domain:"community",source:"channel_read_state",pk:["channel_id","user_id"]},
  {domain:"community",source:"community_notifications",pk:["id"]},
  {domain:"community",source:"message_reports",pk:["id"]},
  {domain:"community",source:"chat_blocks",pk:["id"]},
  {domain:"community",source:"moderation_actions",pk:["id"]},
  {domain:"billing",source:"subscription_plans",pk:["id"]},
  {domain:"billing",source:"plan_entitlements",pk:["id"]},
  {domain:"billing",source:"payment_orders",pk:["id"]},
  {domain:"billing",source:"payment_events",pk:["id"]},
  {domain:"billing",source:"user_subscriptions",pk:["id"]},
  {domain:"billing",source:"subscription_events",pk:["id"]},
  {domain:"icai",source:"icai_sources",pk:["id"]},
  {domain:"icai",source:"icai_sync_runs",pk:["id"]},
  {domain:"icai",source:"icai_source_snapshots",pk:["id"]},
  {domain:"icai",source:"icai_resources",pk:["id"],deferred:["replaced_by_resource_id"]},
  {domain:"icai",source:"exam_events",pk:["id"]},
  {domain:"icai",source:"icai_change_events",pk:["id"]},
  {domain:"icai",source:"icai_review_queue",pk:["id"]},
  {domain:"icai",source:"system_health_log",pk:["id"]},
  {domain:"operations",source:"admin_audit_logs",pk:["id"]},

  // These source tables are expected only after CA Mentor Phases 1/2 are actually applied to the source database.
  {domain:"mentor",source:"mentor_model_versions",pk:["id"],optionalSource:true},
  {domain:"mentor",source:"mentor_intelligence_sources",pk:["id"],optionalSource:true},
  {domain:"mentor",source:"mentor_evidence",pk:["id"],optionalSource:true},
  {domain:"mentor",source:"mentor_exam_intelligence",pk:["id"],optionalSource:true},
  {domain:"mentor",source:"mentor_learning_intelligence",pk:["id"],optionalSource:true},
  {domain:"mentor",source:"mentor_personalization_rules",pk:["metric_key"],optionalSource:true},
  {domain:"mentor",source:"mentor_personalization_eligibility",pk:["user_id","metric_key"],optionalSource:true},
  {domain:"mentor",source:"mentor_recommendation_explanations",pk:["id"],optionalSource:true},
  {domain:"mentor",source:"academic_catalog_nodes",pk:["canonical_id"],optionalSource:true,deferred:["parent_canonical_id"]},
  {domain:"mentor",source:"academic_catalog_version_items",pk:["id"],optionalSource:true},
  {domain:"mentor",source:"academic_catalog_aliases",pk:["id"],optionalSource:true},
  {domain:"mentor",source:"academic_catalog_lineage",pk:["id"],optionalSource:true},
];

export const REPRESENTATIVE_USER_TABLES = [
  "profiles","chapter_progress","progress_events","planner_events","daily_plans","daily_plan_items","revision_due_items","tasks","goals","user_calendar_events","study_sessions","notes","uploaded_resources","community_messages","community_notifications","user_subscriptions","payment_orders","payment_events","mentor_personalization_eligibility","mentor_recommendation_explanations",
];

export const INTENTIONAL_SQLITE_DIFFERENCES = Object.freeze([
  "PostgreSQL uuid columns are D1 TEXT and imported values are preserved verbatim.",
  "PostgreSQL timestamptz/date/time values are canonical ISO/date/time TEXT in D1.",
  "PostgreSQL boolean values are D1 INTEGER 0/1.",
  "PostgreSQL json/jsonb and array values are canonical JSON TEXT with json_valid checks where applicable.",
  "PostgreSQL numeric values used as scores/limits map to D1 REAL; integer money/reference values stay INTEGER.",
  "PostgreSQL RLS/auth.uid()/auth.jwt() are replaced by trusted Worker authorization; migration scripts never treat browser identity as authority.",
  "PostgreSQL RPC/trigger/locking semantics are implemented by Worker transaction/idempotency logic rather than D1 security triggers.",
  "Supabase Auth password/token internals are intentionally not copied; only stable application identity and provider identity metadata are migrated.",
]);
