"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdminCapability } from "@/lib/authorization/server";
import { createPolicyDraft, createUserPromotion, grantEntitlementOverride, publishPolicy, savePolicyBasics, savePolicyFeature, savePolicyPage, scheduleUserPlanChange } from "@/lib/billing/granular-policy";
const v=(d:FormData,k:string)=>String(d.get(k)??"").trim();
const done=(notice:string)=>{revalidatePath("/admin/plans");revalidatePath("/pricing");redirect(`/admin/plans?notice=${encodeURIComponent(notice)}`);};
export async function createPolicyDraftAction(d:FormData){const a=await requireAdminCapability("billing.plan.configure");await createPolicyDraft({planId:v(d,"planId"),reason:v(d,"reason"),actor:{userId:a.user.id,role:a.role}});done("Draft created");}
export async function savePolicyBasicsAction(d:FormData){const a=await requireAdminCapability("billing.plan.configure");await savePolicyBasics({policyId:v(d,"policyId"),name:v(d,"name"),description:v(d,"description"),priceRupees:v(d,"priceRupees"),durationValue:v(d,"durationValue"),durationUnit:v(d,"durationUnit"),trialDays:v(d,"trialDays"),graceDays:v(d,"graceDays"),effectiveAt:v(d,"effectiveAt"),reason:v(d,"reason"),actor:{userId:a.user.id,role:a.role}});done("Plan details saved");}
export async function savePolicyPageAction(d:FormData){const a=await requireAdminCapability("billing.plan.configure");await savePolicyPage({policyId:v(d,"policyId"),pageKey:v(d,"pageKey"),enabled:d.get("enabled")==="on",reason:v(d,"reason"),actor:{userId:a.user.id,role:a.role}});done("Page access saved");}
export async function savePolicyFeatureAction(d:FormData){const a=await requireAdminCapability("billing.plan.configure");await savePolicyFeature({policyId:v(d,"policyId"),pageKey:v(d,"pageKey"),featureKey:v(d,"featureKey"),enabled:d.get("enabled")==="on",quantityLimit:v(d,"quantityLimit"),timeLimit:v(d,"timeLimit"),storageLimitMb:v(d,"storageLimitMb"),fileSizeLimitMb:v(d,"fileSizeLimitMb"),resetPeriod:v(d,"resetPeriod"),retentionDays:v(d,"retentionDays"),dependencies:v(d,"dependencies"),upgradeMessage:v(d,"upgradeMessage"),reason:v(d,"reason"),actor:{userId:a.user.id,role:a.role}});done("Feature rule saved");}
export async function publishPolicyAction(d:FormData){const a=await requireAdminCapability("billing.plan.configure");await publishPolicy({policyId:v(d,"policyId"),reason:v(d,"reason"),actor:{userId:a.user.id,role:a.role}});done("Policy published");}
export async function grantOverrideAction(d:FormData){const a=await requireAdminCapability("entitlements.override");await grantEntitlementOverride({userId:v(d,"userId"),featureKey:v(d,"featureKey"),enabled:d.get("enabled")==="on",quantityLimit:v(d,"quantityLimit"),expiresAt:v(d,"expiresAt"),reason:v(d,"reason"),actor:{userId:a.user.id,role:a.role}});done("User override saved");}
export async function schedulePlanChangeAction(d:FormData){const a=await requireAdminCapability("billing.manage");await scheduleUserPlanChange({userId:v(d,"userId"),toPlanId:v(d,"toPlanId"),effectiveAt:v(d,"effectiveAt"),reason:v(d,"reason"),actor:{userId:a.user.id,role:a.role}});done("Plan change scheduled");}
export async function createPromotionAction(d:FormData){const a=await requireAdminCapability("billing.manage");await createUserPromotion({name:v(d,"name"),policyId:v(d,"policyId"),userId:v(d,"userId"),startsAt:v(d,"startsAt"),endsAt:v(d,"endsAt"),reason:v(d,"reason"),actor:{userId:a.user.id,role:a.role}});done("Promotion granted");}
