import { execute, query, transaction } from "./database";
import type { SqlStatement } from "./schema";
import { parseCommunityRealtimeEvent } from "../../../lib/community/realtime-events";

export type LocalCommunityChannel = { key:string; title:string; latestSequence:number; unreadCount:number; draft:string; lastMessageAt:string|null; preview:string };
export type LocalCommunityMessage = { localId:string; serverId:string|null; clientMessageId:string|null; channelKey:string; sequence:number|null; authorId:string; authorLabel:string; body:string; sentAt:string; state:"sending"|"sent"|"failed"|"retrying"; moderationStatus:string; reactions:Array<{emoji:string;count:number;mine:boolean}>; pinned:boolean; attachment:Record<string,unknown>|null };
export type CommunitySnapshot = { channels:LocalCommunityChannel[]; activeChannel:string|null; messages:LocalCommunityMessage[]; hasOlder:boolean; lastSequence:number; draft:string };
export type RemoteCommunityMessage = { id:string; sequence:number; channelId:string; userId:string; authorLabel:string; body:string; createdAt:string; moderationStatus:string; reactions?:Array<{emoji:string;count:number;reactedByViewer:boolean}>; isPinned?:boolean; attachment?:Record<string,unknown>|null; clientMessageId?:string|null };
export type PendingCommunityMessage={clientMessageId:string;channelKey:string;body:string};

const now=()=>new Date().toISOString();
const json=(value:unknown)=>JSON.stringify(value??{});
const parse=<T>(value:string|null|undefined,fallback:T):T=>{try{return value?JSON.parse(value) as T:fallback;}catch{return fallback;}};
const localMessageId=(accountId:string,serverId:string)=>`community-message:${accountId}:${serverId}`;

function upsertMessage(accountId:string,channelKey:string,message:RemoteCommunityMessage):SqlStatement[] {
  const localId=localMessageId(accountId,message.id),timestamp=now(),deleted=message.moderationStatus==="deleted"?timestamp:null;
  return [{sql:`INSERT INTO community_messages(local_id,server_id,server_version,account_id,local_state,created_at,updated_at,deleted_at,channel_key,author_id,body,sent_at,payload_json,sequence_id,client_message_id,delivery_state,moderation_status,attachment_json)
    VALUES(?,?,1,?,'synced',?,?,?,?,?,?,?,?,?,?,'sent',?,?)
    ON CONFLICT(account_id,server_id) DO UPDATE SET server_version=MAX(community_messages.server_version,excluded.server_version),sequence_id=excluded.sequence_id,author_id=excluded.author_id,body=excluded.body,sent_at=excluded.sent_at,payload_json=excluded.payload_json,attachment_json=excluded.attachment_json,moderation_status=excluded.moderation_status,deleted_at=excluded.deleted_at,delivery_state='sent',local_state='synced',updated_at=excluded.updated_at`,args:[localId,message.id,accountId,timestamp,timestamp,deleted,channelKey,message.userId,message.body,message.createdAt,json({authorLabel:message.authorLabel,reactions:message.reactions||[],isPinned:Boolean(message.isPinned)}),message.sequence,message.clientMessageId||null,message.moderationStatus,json(message.attachment||null)]}];
}

export async function readCommunitySnapshot(accountId:string,channelKey?:string|null):Promise<CommunitySnapshot>{
  const channels=await query<{channel_key:string;title:string;latest_sequence:number;unread_count:number;draft_text:string;last_message_at:string|null;payload_json:string}>("SELECT channel_key,title,latest_sequence,unread_count,draft_text,last_message_at,payload_json FROM community_channels WHERE account_id=? AND deleted_at IS NULL ORDER BY COALESCE(last_message_at,updated_at) DESC",[accountId]);
  const active=channelKey||channels[0]?.channel_key||null;
  const rows=active?await query<{local_id:string;server_id:string|null;client_message_id:string|null;channel_key:string;sequence_id:number|null;author_id:string;body:string;sent_at:string;delivery_state:LocalCommunityMessage["state"];moderation_status:string;payload_json:string;attachment_json:string|null}>("SELECT local_id,server_id,client_message_id,channel_key,sequence_id,author_id,body,sent_at,delivery_state,moderation_status,payload_json,attachment_json FROM community_messages WHERE account_id=? AND channel_key=? ORDER BY CASE WHEN sequence_id IS NULL THEN 1 ELSE 0 END,sequence_id,sent_at,local_id LIMIT 200",[accountId,active]):[];
  const oldest=rows.find(row=>row.sequence_id!==null)?.sequence_id??0;
  return {channels:channels.map(row=>{const payload=parse<Record<string,unknown>>(row.payload_json,{});return{key:row.channel_key,title:row.title,latestSequence:Number(row.latest_sequence),unreadCount:Number(row.unread_count),draft:row.draft_text,lastMessageAt:row.last_message_at,preview:String(payload.preview||"")};}),activeChannel:active,messages:rows.map(row=>{const payload=parse<{authorLabel?:string;reactions?:Array<{emoji:string;count:number;reactedByViewer?:boolean}>;isPinned?:boolean}>(row.payload_json,{});return{localId:row.local_id,serverId:row.server_id,clientMessageId:row.client_message_id,channelKey:row.channel_key,sequence:row.sequence_id===null?null:Number(row.sequence_id),authorId:row.author_id,authorLabel:payload.authorLabel||"Community member",body:row.moderation_status==="deleted"?"This message was removed by moderation.":row.body,sentAt:row.sent_at,state:row.delivery_state,moderationStatus:row.moderation_status,reactions:(payload.reactions||[]).map(item=>({emoji:item.emoji,count:item.count,mine:Boolean(item.reactedByViewer)})),pinned:Boolean(payload.isPinned),attachment:parse<Record<string,unknown>|null>(row.attachment_json,null)};}),hasOlder:oldest>1,lastSequence:Math.max(0,...rows.map(row=>Number(row.sequence_id||0))),draft:channels.find(row=>row.channel_key===active)?.draft_text||""};
}

export async function storeCommunityChannels(accountId:string,channels:Array<{key:string;title:string;latestSequence?:number|null;unreadCount?:number;latestAt?:string|null;latestBody?:string|null}>){const timestamp=now();await transaction(channels.map(channel=>({sql:"INSERT INTO community_channels(local_id,server_id,account_id,channel_key,title,last_message_at,payload_json,latest_sequence,unread_count,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(account_id,channel_key) DO UPDATE SET title=excluded.title,last_message_at=excluded.last_message_at,payload_json=excluded.payload_json,latest_sequence=MAX(community_channels.latest_sequence,excluded.latest_sequence),unread_count=excluded.unread_count,updated_at=excluded.updated_at,deleted_at=NULL",args:[`community-channel:${accountId}:${channel.key}`,channel.key,accountId,channel.key,channel.title,channel.latestAt||null,json({preview:channel.latestBody||""}),channel.latestSequence||0,channel.unreadCount||0,timestamp,timestamp]})));}

export async function storeCommunityPage(accountId:string,channelKey:string,messages:RemoteCommunityMessage[],latestSequence?:number){const timestamp=now();const statements=messages.flatMap(message=>upsertMessage(accountId,channelKey,message));statements.push({sql:"UPDATE community_channels SET latest_sequence=MAX(latest_sequence,?),last_message_at=COALESCE(?,last_message_at),payload_json=CASE WHEN ?<>'' THEN ? ELSE payload_json END,updated_at=? WHERE account_id=? AND channel_key=?",args:[latestSequence??Math.max(0,...messages.map(item=>item.sequence)),messages.at(-1)?.createdAt||null,messages.at(-1)?.body||"",json({preview:messages.at(-1)?.body||""}),timestamp,accountId,channelKey]});await transaction(statements);}

export async function applyCommunityEvent(accountId:string,channelKey:string,value:unknown){const event=parseCommunityRealtimeEvent(value);if(!event||!("sequence" in event)||event.sequence<1)return false;const existing=await query<{entity_version:number}>("SELECT entity_version FROM community_event_log WHERE account_id=? AND channel_key=? AND sequence_id=?",[accountId,channelKey,event.sequence]);if(existing[0]&&Number(existing[0].entity_version)>=event.version)return false;const statements:SqlStatement[]=[];if(event.type.startsWith("message.")){const payload=event.payload as unknown as RemoteCommunityMessage;if(event.type==="message.deleted")statements.push({sql:"UPDATE community_messages SET moderation_status='deleted',body='',deleted_at=?,server_version=?,updated_at=? WHERE account_id=? AND channel_key=? AND server_id=?",args:[now(),event.version,now(),accountId,channelKey,event.entityId]});else statements.push(...upsertMessage(accountId,channelKey,{...payload,id:event.entityId,sequence:event.sequence,channelId:event.channelId,moderationStatus:String(payload.moderationStatus||"active")}));}else if(event.type==="reaction.changed")statements.push({sql:"UPDATE community_messages SET payload_json=?,server_version=?,updated_at=? WHERE account_id=? AND server_id=?",args:[json(event.payload),event.version,now(),accountId,event.entityId]});else if(event.type==="pin.changed"){if(event.payload.pinned)statements.push({sql:"INSERT OR REPLACE INTO community_pins(account_id,channel_key,message_server_id,sequence_id,updated_at) VALUES(?,?,?,?,?)",args:[accountId,channelKey,event.entityId,event.sequence,now()]});else statements.push({sql:"DELETE FROM community_pins WHERE account_id=? AND channel_key=? AND message_server_id=?",args:[accountId,channelKey,event.entityId]});}else if(event.type==="read.changed")statements.push({sql:"INSERT INTO community_read_state(account_id,channel_key,last_read_server_id,last_read_sequence,server_version,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(account_id,channel_key) DO UPDATE SET last_read_sequence=MAX(last_read_sequence,excluded.last_read_sequence),server_version=MAX(server_version,excluded.server_version),updated_at=excluded.updated_at",args:[accountId,channelKey,event.entityId,Number(event.payload.sequence||event.sequence),event.version,now()]});statements.push({sql:"INSERT OR REPLACE INTO community_event_log(account_id,channel_key,sequence_id,event_type,entity_id,entity_version,received_at) VALUES(?,?,?,?,?,?,?)",args:[accountId,channelKey,event.sequence,event.type,event.entityId,event.version,now()]},{sql:"UPDATE community_channels SET latest_sequence=MAX(latest_sequence,?),updated_at=? WHERE account_id=? AND channel_key=?",args:[event.sequence,now(),accountId,channelKey]});await transaction(statements);return true;}

export async function saveCommunityDraft(accountId:string,channelKey:string,draft:string){await execute("UPDATE community_channels SET draft_text=?,updated_at=? WHERE account_id=? AND channel_key=?",[draft.slice(0,4000),now(),accountId,channelKey]);}
export async function queueCommunityMessage(accountId:string,channelKey:string,authorId:string,authorLabel:string,body:string){const localId=crypto.randomUUID(),clientMessageId=crypto.randomUUID(),timestamp=now();await transaction([{sql:"INSERT INTO community_messages(local_id,account_id,channel_key,author_id,body,sent_at,payload_json,client_message_id,delivery_state,local_state,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'pending',?,?)",args:[localId,accountId,channelKey,authorId,body.trim(),timestamp,json({authorLabel,reactions:[]}),clientMessageId,"sending",timestamp,timestamp]},{sql:"INSERT INTO mutation_outbox(mutation_id,account_id,entity_type,entity_local_id,operation,idempotency_key,payload_json,status,attempts,created_at,updated_at,endpoint) VALUES(?,?,?,?,?,?,?,?,0,?,?,?)",args:[crypto.randomUUID(),accountId,"community_message",localId,"create",clientMessageId,json({body:body.trim(),clientMessageId,channelKey}),"pending",timestamp,timestamp,`/api/v1/community/channels/${encodeURIComponent(channelKey)}/messages`]}]);return{localId,clientMessageId};}
export async function acknowledgeCommunityMessage(accountId:string,clientMessageId:string,message:RemoteCommunityMessage){await transaction([{sql:"UPDATE community_messages SET server_id=?,sequence_id=?,server_version=1,delivery_state='sent',local_state='synced',sent_at=?,updated_at=?,payload_json=? WHERE account_id=? AND client_message_id=?",args:[message.id,message.sequence,message.createdAt,now(),json({authorLabel:message.authorLabel,reactions:message.reactions||[]}),accountId,clientMessageId]},{sql:"DELETE FROM mutation_outbox WHERE account_id=? AND idempotency_key=?",args:[accountId,clientMessageId]}]);}
export async function failCommunityMessage(accountId:string,clientMessageId:string){await execute("UPDATE community_messages SET delivery_state='failed',local_state='failed',updated_at=? WHERE account_id=? AND client_message_id=?",[now(),accountId,clientMessageId]);}
export async function pendingCommunityMessages(accountId:string):Promise<PendingCommunityMessage[]>{const rows=await query<{client_message_id:string;channel_key:string;body:string}>("SELECT client_message_id,channel_key,body FROM community_messages WHERE account_id=? AND client_message_id IS NOT NULL AND delivery_state IN ('sending','failed','retrying') ORDER BY created_at LIMIT 50",[accountId]);return rows.map(row=>({clientMessageId:row.client_message_id,channelKey:row.channel_key,body:row.body}));}
export async function retryCommunityMessage(accountId:string,clientMessageId:string){await execute("UPDATE community_messages SET delivery_state='retrying',local_state='pending',updated_at=? WHERE account_id=? AND client_message_id=?",[now(),accountId,clientMessageId]);}
export async function markCommunityReadLocal(accountId:string,channelKey:string,sequence:number){await transaction([{sql:"INSERT INTO community_read_state(account_id,channel_key,last_read_sequence,updated_at) VALUES(?,?,?,?) ON CONFLICT(account_id,channel_key) DO UPDATE SET last_read_sequence=MAX(last_read_sequence,excluded.last_read_sequence),updated_at=excluded.updated_at",args:[accountId,channelKey,sequence,now()]},{sql:"UPDATE community_channels SET unread_count=0,updated_at=? WHERE account_id=? AND channel_key=?",args:[now(),accountId,channelKey]}]);}
export async function pruneCommunityHistory(accountId:string,channelKey:string,keep=500){await execute("DELETE FROM community_messages WHERE account_id=? AND channel_key=? AND local_id IN (SELECT local_id FROM community_messages WHERE account_id=? AND channel_key=? AND delivery_state='sent' AND moderation_status<>'deleted' ORDER BY sequence_id DESC LIMIT -1 OFFSET ?)",[accountId,channelKey,accountId,channelKey,Math.max(100,keep)]);}
