import { execute, openLocalDatabase, query, transaction, wipeDatabase, type DatabaseState } from "./database";

export type LocalSyncState = "synced" | "pending" | "conflict" | "failed";
export type LocalTimer = { mode: "focus" | "stopwatch"; status: "idle" | "running" | "paused"; startedAt: string | null; elapsedSeconds: number; updatedAt: string };
export type LocalDashboard = { today: Array<{ title: string; meta: string; state: string }>; progress: { value: string; hint: string }; community: Array<{ channel: string; preview: string; time: string }> };
export type LocalAcademicContext={contextKey:string|null;level:string;attempt:string;subjects:Array<{id:string;title:string}>;chapters:Array<{id:string;title:string;subjectId:string|null;number:string|null}>;attempts:Array<{key:string;label:string;examDate:string|null;verified:boolean}>;lastUpdatedAt:string|null};
export type LocalProgressItem={localId:string;serverId:string|null;chapterId:string;title:string;stage:string|null;understanding:number|null;state:LocalSyncState;payload:Record<string,unknown>};
export type LocalPlannerItem={localId:string;serverId:string|null;title:string;dueAt:string|null;completedAt:string|null;kind:string;state:LocalSyncState};
export type LocalRevisionSettings={intervalDays:number[];preferredWeekdays:number[];revisionMinutes:number;newChapterMinutes:number;testMinutes:number;updatedAt:string|null};
export type LocalFocusContext={subjectId:string|null;chapterId:string|null;focusMinutes:number;breakMinutes:number};
export type LocalNote={localId:string;serverId:string|null;title:string;body:string;updatedAt:string;state:LocalSyncState};
export type LocalProfile={displayName:string;level:string|null;group:string|null;attempt:string|null;timezone:string|null;dailyTargetMinutes:number|null};
export type LocalActivity={id:string;title:string;kind:string;occurredAt:string;xp:number};
export type LocalBuddy={id:string;name:string;state:string};
export type LocalWorkspace={academic:LocalAcademicContext;dashboard:LocalDashboard;progress:LocalProgressItem[];planner:LocalPlannerItem[];notes:LocalNote[];profile:LocalProfile;activity:LocalActivity[];leaderboard:{rank:number|null;score:number;category:string};buddies:LocalBuddy[];pending:number;conflicts:number;lastSyncedAt:string|null};
export type LocalAccountRepository = {
  accountId: string; database: DatabaseState;
  readDashboard(): Promise<LocalDashboard>;
  readWorkspace():Promise<LocalWorkspace>;
  readTimer(): Promise<LocalTimer>;
  readFocusContext():Promise<LocalFocusContext>;
  readRevisionSettings():Promise<LocalRevisionSettings>;
  saveTimer(timer: LocalTimer,context?:LocalFocusContext): Promise<void>;
  discardTimer(timer:LocalTimer):Promise<void>;
  saveRevisionSettings(settings:LocalRevisionSettings):Promise<void>;
  createTask(title:string,dueAt:string):Promise<string>;
  createGoal(title:string,dueDate:string):Promise<string>;
  toggleTask(localId:string,done:boolean):Promise<void>;
  toggleGoal(localId:string,done:boolean):Promise<void>;
  setProgressStage(localId:string,stage:"completed"|"revision_1"|"revision_2",enabled:boolean):Promise<void>;
  saveNote(input:{localId?:string;title:string;body:string}):Promise<string>;
  finishTimer(timer:LocalTimer):Promise<string>;
  saveSessionReview(localId:string,understanding:number,focus:"poor"|"okay"|"focused"):Promise<void>;
  subscribe(listener: () => void): () => void;
  lock(): Promise<void>; removeFromDevice(): Promise<void>; cleanup(maxBytes?: number): Promise<number>;
};

const listeners = new Map<string, Set<() => void>>();
export const notifyLocalAccountChanged = (accountId: string) => { for (const listener of listeners.get(accountId) || []) listener(); };
const notify = notifyLocalAccountChanged;
const now = () => new Date().toISOString();
const safeJson=(value:string|null|undefined)=>{try{return value?JSON.parse(value) as Record<string,unknown>:{};}catch{return {};}};
const contextFor=async(accountId:string)=>{const rows=await query<{scope:string}>("SELECT scope FROM sync_cursors WHERE account_id=? ORDER BY updated_at DESC LIMIT 1",[accountId]);return rows[0]?.scope||"unscoped";};
const mutationId=()=>crypto.randomUUID();
function outboxStatement(accountId:string,input:{type:string;localId:string;endpoint:string;body:Record<string,unknown>;expected:Record<string,unknown>|null;baseVersion?:number|null;predecessor?:string|null}){const id=mutationId(),timestamp=now();return{sql:"INSERT INTO mutation_outbox(mutation_id,account_id,entity_type,entity_local_id,operation,idempotency_key,payload_json,status,attempts,created_at,updated_at,endpoint,expected_json,base_server_version,predecessor_mutation_id) VALUES(?,?,?,?,?,?,?,?,0,?,?,?,?,?,?)",args:[id,accountId,input.type,input.localId,String(input.body.action||"upsert"),id,JSON.stringify({...input.body,offlineOccurredAt:timestamp}),"pending",timestamp,timestamp,input.endpoint,input.expected===null?null:JSON.stringify(input.expected),input.baseVersion??null,input.predecessor??null]};}

export async function openAccountRepository(account: { id: string; displayName: string }, unlock = false): Promise<LocalAccountRepository | null> {
  const database = await openLocalDatabase();
  if (!database.available) return null;
  const timestamp = now();
  await execute("INSERT INTO local_accounts(account_id,display_name,state,last_opened_at,created_at) VALUES(?,?,'active',?,?) ON CONFLICT(account_id) DO UPDATE SET display_name=excluded.display_name,last_opened_at=excluded.last_opened_at", [account.id, account.displayName, timestamp, timestamp]);
  const state=await query<{state:string}>("SELECT state FROM local_accounts WHERE account_id=? LIMIT 1",[account.id]);
  if(state[0]?.state==="locked"&&!unlock)return null;
  if(unlock)await execute("UPDATE local_accounts SET state='active' WHERE account_id=?",[account.id]);
  const existing = await query<{ count: number }>("SELECT COUNT(*) AS count FROM dashboard_projection WHERE account_id=?", [account.id]);
  if (Number(existing[0]?.count || 0) === 0) {
    const id = crypto.randomUUID();
    const dashboard: LocalDashboard = { today: [{ title: "Continue your next chapter", meta: "Open Progress to choose a chapter", state: "Ready" }, { title: "Plan today's study", meta: "Saved locally on this device", state: "Local" }], progress: { value: "—", hint: "Waiting for first secure sync" }, community: [{ channel: "Announcements", preview: "Recent conversations will be retained on this device.", time: "Saved" }] };
    await transaction([
      { sql: "INSERT INTO dashboard_projection(local_id,account_id,projection_key,payload_json,created_at,updated_at) VALUES(?,?, 'home',?,?,?)", args: [id, account.id, JSON.stringify(dashboard), timestamp, timestamp] },
      { sql: "INSERT OR IGNORE INTO timer_state(account_id,mode,status,elapsed_seconds,updated_at) VALUES(?,'focus','idle',0,?)", args: [account.id, timestamp] },
    ]);
  }

  return {
    accountId: account.id, database,
    async readDashboard() { const rows = await query<{ payload_json: string }>("SELECT payload_json FROM dashboard_projection WHERE account_id=? AND projection_key='home' AND deleted_at IS NULL LIMIT 1", [account.id]); return JSON.parse(rows[0]?.payload_json || "{}") as LocalDashboard; },
    async readWorkspace(){
      const contextRows=await query<{scope:string;updated_at:string}>("SELECT scope,updated_at FROM sync_cursors WHERE account_id=? ORDER BY updated_at DESC LIMIT 1",[account.id]);
      const activeScope=contextRows[0]?.scope||"unscoped";
      const [dashboardRows,subjects,chapters,attempts,progress,planner,notes,profile,activity,leaderboard,buddies,pending,conflicts,cursor]=await Promise.all([
        query<{payload_json:string}>("SELECT payload_json FROM dashboard_projection WHERE account_id=? AND projection_key='home' AND deleted_at IS NULL LIMIT 1",[account.id]),
        query<{server_id:string|null;title:string}>("SELECT server_id,title FROM academic_catalog WHERE account_id=? AND academic_context_key=? AND entity_type='subject' AND deleted_at IS NULL ORDER BY title",[account.id,activeScope]),
        query<{server_id:string|null;title:string;parent_server_id:string|null;payload_json:string}>("SELECT server_id,title,parent_server_id,payload_json FROM academic_catalog WHERE account_id=? AND academic_context_key=? AND entity_type='chapter' AND deleted_at IS NULL ORDER BY parent_server_id,title",[account.id,activeScope]),
        query<{server_id:string|null;title:string;payload_json:string}>("SELECT server_id,title,payload_json FROM academic_catalog WHERE account_id=? AND academic_context_key=? AND entity_type='attempt' AND deleted_at IS NULL ORDER BY title",[account.id,activeScope]),
        query<{local_id:string;server_id:string|null;chapter_id:string|null;stage:string|null;understanding:number|null;local_state:LocalSyncState;payload_json:string}>("SELECT local_id,server_id,chapter_id,stage,understanding,local_state,payload_json FROM progress_records WHERE account_id=? AND academic_context_key=? AND deleted_at IS NULL ORDER BY updated_at DESC",[account.id,activeScope]),
        query<{local_id:string;server_id:string|null;title:string;due_at:string|null;completed_at:string|null;item_kind:string;local_state:LocalSyncState}>("SELECT local_id,server_id,title,due_at,completed_at,item_kind,local_state FROM planner_items WHERE account_id=? AND academic_context_key=? AND deleted_at IS NULL ORDER BY completed_at IS NOT NULL,due_at,created_at",[account.id,activeScope]),
        query<{local_id:string;server_id:string|null;title:string;body_text:string;updated_at:string;local_state:LocalSyncState}>("SELECT local_id,server_id,title,body_text,updated_at,local_state FROM notes WHERE account_id=? AND academic_context_key=? AND deleted_at IS NULL ORDER BY updated_at DESC",[account.id,activeScope]),
        query<{display_name:string;level_code:string|null;attempt_key:string|null;timezone:string|null;daily_target_minutes:number|null;payload_json:string}>("SELECT display_name,level_code,attempt_key,timezone,daily_target_minutes,payload_json FROM profile_projection WHERE account_id=? AND academic_context_key=? AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 1",[account.id,activeScope]),
        query<{local_id:string;title:string;activity_kind:string;occurred_at:string;xp_amount:number}>("SELECT local_id,title,activity_kind,occurred_at,xp_amount FROM activity_projection WHERE account_id=? AND academic_context_key=? AND deleted_at IS NULL ORDER BY occurred_at DESC LIMIT 40",[account.id,activeScope]),
        query<{rank:number|null;score:number;category:string}>("SELECT rank,score,category FROM leaderboard_projection WHERE account_id=? AND academic_context_key=? AND deleted_at IS NULL ORDER BY updated_at DESC LIMIT 1",[account.id,activeScope]),
        query<{local_id:string;buddy_name:string;relationship_state:string}>("SELECT local_id,buddy_name,relationship_state FROM study_buddy_projection WHERE account_id=? AND academic_context_key=? AND deleted_at IS NULL ORDER BY updated_at DESC",[account.id,activeScope]),
        query<{count:number}>("SELECT COUNT(*) AS count FROM mutation_outbox WHERE account_id=?",[account.id]),query<{count:number}>("SELECT COUNT(*) AS count FROM conflicts WHERE account_id=? AND resolved_at IS NULL",[account.id]),query<{updated_at:string}>("SELECT updated_at FROM sync_cursors WHERE account_id=? ORDER BY updated_at DESC LIMIT 1",[account.id]),
      ]);
      const profileRow=profile[0],dashboard=JSON.parse(dashboardRows[0]?.payload_json||"{}") as LocalDashboard,chapterTitles=new Map(chapters.map(row=>[row.server_id,row.title]));
      const progressByChapter=new Map(progress.map(row=>[row.chapter_id||String(safeJson(row.payload_json).chapterId||""),row]));
      const catalogIds=new Set(chapters.map(row=>row.server_id).filter((value):value is string=>Boolean(value)));
      const fullProgress:LocalProgressItem[]=chapters.map(chapter=>{const chapterId=chapter.server_id||String(safeJson(chapter.payload_json).id||"");const saved=progressByChapter.get(chapterId);const payload=saved?safeJson(saved.payload_json):{chapterId,chapterTitle:chapter.title,subjectId:chapter.parent_server_id,completedAt:null,revision1At:null,revision2At:null,test1At:null,test2At:null};return{localId:saved?.local_id||`${account.id}:progress:${chapterId}`,serverId:saved?.server_id||null,chapterId,title:chapter.title,stage:saved?.stage||null,understanding:saved?.understanding??null,state:saved?.local_state||"synced",payload};}).filter(item=>Boolean(item.chapterId));
      for(const row of progress){const payload=safeJson(row.payload_json),chapterId=row.chapter_id||String(payload.chapterId||row.server_id||row.local_id);if(catalogIds.has(chapterId))continue;fullProgress.push({localId:row.local_id,serverId:row.server_id,chapterId,title:String(payload.chapterTitle||chapterTitles.get(row.chapter_id||row.server_id)||payload.title||"Chapter progress"),stage:row.stage,understanding:row.understanding,state:row.local_state,payload});}
      return{academic:{contextKey:contextRows[0]?.scope||null,level:profileRow?.level_code||"Not selected",attempt:profileRow?.attempt_key||"Not selected",subjects:subjects.map(row=>({id:row.server_id||row.title,title:row.title})),chapters:chapters.map(row=>{const payload=safeJson(row.payload_json);return{id:row.server_id||String(payload.id||row.title),title:row.title,subjectId:row.parent_server_id||String(payload.subjectId||"")||null,number:payload.number===null||payload.number===undefined?null:String(payload.number)};}),attempts:attempts.map(row=>{const payload=safeJson(row.payload_json),raw=payload.startDate??payload.examDate??payload.date;const examDate=typeof raw==="string"&&Number.isFinite(Date.parse(raw))?raw:null;return{key:String(payload.attemptKey||row.server_id||""),label:row.title,examDate,verified:String(payload.verificationStatus||"").toLowerCase()==="verified"};}).filter(row=>row.key),lastUpdatedAt:contextRows[0]?.updated_at||null},dashboard,progress:fullProgress,planner:planner.map(row=>({localId:row.local_id,serverId:row.server_id,title:row.title,dueAt:row.due_at,completedAt:row.completed_at,kind:row.item_kind,state:row.local_state})),notes:notes.map(row=>({localId:row.local_id,serverId:row.server_id,title:row.title,body:row.body_text,updatedAt:row.updated_at,state:row.local_state})),profile:{displayName:profileRow?.display_name||account.displayName,level:profileRow?.level_code||null,group:profileRow?String(safeJson(profileRow.payload_json).group||""):null,attempt:profileRow?.attempt_key||null,timezone:profileRow?.timezone||null,dailyTargetMinutes:profileRow?.daily_target_minutes??null},activity:activity.map(row=>({id:row.local_id,title:row.title,kind:row.activity_kind,occurredAt:row.occurred_at,xp:Number(row.xp_amount)})),leaderboard:{rank:leaderboard[0]?.rank??null,score:Number(leaderboard[0]?.score||0),category:leaderboard[0]?.category||"overall"},buddies:buddies.map(row=>({id:row.local_id,name:row.buddy_name,state:row.relationship_state})),pending:Number(pending[0]?.count||0),conflicts:Number(conflicts[0]?.count||0),lastSyncedAt:cursor[0]?.updated_at||null};
    },
    async readTimer() { const rows = await query<{ mode: "focus"|"stopwatch"; status: "idle"|"running"|"paused"; started_at: string|null; elapsed_seconds: number; updated_at:string }>("SELECT mode,status,started_at,elapsed_seconds,updated_at FROM timer_state WHERE account_id=? LIMIT 1", [account.id]); const row=rows[0]; return { mode: row?.mode || "focus", status: row?.status || "idle", startedAt: row?.started_at || null, elapsedSeconds: Number(row?.elapsed_seconds || 0), updatedAt: row?.updated_at || now() }; },
    async readFocusContext(){const rows=await query<{value_json:string}>("SELECT value_json FROM application_config WHERE account_id=? AND config_key='focus_context' AND deleted_at IS NULL LIMIT 1",[account.id]);const value=safeJson(rows[0]?.value_json);return{subjectId:typeof value.subjectId==="string"&&value.subjectId?value.subjectId:null,chapterId:typeof value.chapterId==="string"&&value.chapterId?value.chapterId:null,focusMinutes:Math.min(720,Math.max(1,Number(value.focusMinutes||25))),breakMinutes:Math.min(120,Math.max(0,Number(value.breakMinutes??5)))};},
    async readRevisionSettings(){const rows=await query<{value_json:string;updated_at:string}>("SELECT value_json,updated_at FROM application_config WHERE account_id=? AND config_key='revision_settings' AND deleted_at IS NULL LIMIT 1",[account.id]);const value=safeJson(rows[0]?.value_json);return{intervalDays:Array.isArray(value.intervalDays)?value.intervalDays.map(Number).filter(Number.isFinite):[1,7,21],preferredWeekdays:Array.isArray(value.preferredWeekdays)?value.preferredWeekdays.map(Number).filter(Number.isFinite):[1,2,3,4,5,6],revisionMinutes:Number(value.revisionMinutes||45),newChapterMinutes:Number(value.newChapterMinutes||90),testMinutes:Number(value.testMinutes||60),updatedAt:rows[0]?.updated_at||null};},
    async saveTimer(timer,focusContext) { const previous=(await query<{mode:string;status:string;started_at:string|null;elapsed_seconds:number;updated_at:string}>("SELECT mode,status,started_at,elapsed_seconds,updated_at FROM timer_state WHERE account_id=? LIMIT 1",[account.id]))[0];const predecessor=(await query<{mutation_id:string}>("SELECT mutation_id FROM mutation_outbox WHERE account_id=? AND entity_local_id='timer' ORDER BY created_at DESC LIMIT 1",[account.id]))[0]?.mutation_id||null;const action=previous?.status==="paused"&&timer.status==="running"?"resume":timer.status==="paused"?"pause":"start";const context=focusContext||{subjectId:null,chapterId:null,focusMinutes:25,breakMinutes:5};const body=action==="start"?{action,clientId:crypto.randomUUID(),mode:timer.mode==="focus"?"pomodoro":"stopwatch",timezone:"Asia/Kolkata",focusMinutes:context.focusMinutes,breakMinutes:context.breakMinutes,subjectId:context.subjectId,chapterId:context.chapterId}:{action,timezone:"Asia/Kolkata"};const expected=previous&&previous.status!=="idle"?{status:previous.status,started_at:previous.started_at,elapsed_seconds:previous.elapsed_seconds,running_since:previous.status==="running"?previous.updated_at:null,paused_at:previous.status==="paused"?previous.updated_at:null}:null;const timestamp=now(),academicContext=await contextFor(account.id);await transaction([{sql:"INSERT INTO timer_state(account_id,mode,status,started_at,elapsed_seconds,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(account_id) DO UPDATE SET mode=excluded.mode,status=excluded.status,started_at=excluded.started_at,elapsed_seconds=excluded.elapsed_seconds,updated_at=excluded.updated_at",args:[account.id,timer.mode,timer.status,timer.startedAt,timer.elapsedSeconds,timer.updatedAt]},{sql:"INSERT INTO application_config(local_id,server_id,server_version,account_id,academic_context_key,local_state,created_at,updated_at,config_key,value_json) VALUES(?,NULL,0,?,?,'synced',?,?,'focus_context',?) ON CONFLICT(account_id,config_key) DO UPDATE SET academic_context_key=excluded.academic_context_key,value_json=excluded.value_json,updated_at=excluded.updated_at,deleted_at=NULL",args:[account.id+":focus_context",account.id,academicContext,timestamp,timestamp,JSON.stringify(context)]},outboxStatement(account.id,{type:"focus_session",localId:"timer",endpoint:"/api/study/timer",body,expected,predecessor})]); notify(account.id); },
    async discardTimer(timer){void timer;const previous=(await query<{status:string;started_at:string|null;elapsed_seconds:number;updated_at:string}>("SELECT status,started_at,elapsed_seconds,updated_at FROM timer_state WHERE account_id=? LIMIT 1",[account.id]))[0];if(!previous||previous.status==="idle")return;const predecessor=(await query<{mutation_id:string}>("SELECT mutation_id FROM mutation_outbox WHERE account_id=? AND entity_local_id='timer' ORDER BY created_at DESC LIMIT 1",[account.id]))[0]?.mutation_id||null;const timestamp=now(),body={action:"discard",timezone:"Asia/Kolkata"},expected={status:previous.status,started_at:previous.started_at,elapsed_seconds:previous.elapsed_seconds,running_since:previous.status==="running"?previous.updated_at:null,paused_at:previous.status==="paused"?previous.updated_at:null};await transaction([{sql:"UPDATE timer_state SET status='idle',started_at=NULL,elapsed_seconds=0,updated_at=? WHERE account_id=?",args:[timestamp,account.id]},outboxStatement(account.id,{type:"focus_session",localId:"timer",endpoint:"/api/study/timer",body,expected,predecessor})]);notify(account.id);},
    async saveRevisionSettings(settings){const timestamp=now(),context=await contextFor(account.id),id=`${account.id}:revision_settings:${account.id}`,body={clientId:account.id,intervalDays:settings.intervalDays,preferredWeekdays:settings.preferredWeekdays,revisionMinutes:settings.revisionMinutes,newChapterMinutes:settings.newChapterMinutes,testMinutes:settings.testMinutes};await transaction([{sql:"INSERT INTO application_config(local_id,server_id,server_version,account_id,academic_context_key,local_state,created_at,updated_at,config_key,value_json) VALUES(?,?,0,?,?,'pending',?,?,'revision_settings',?) ON CONFLICT(local_id) DO UPDATE SET academic_context_key=excluded.academic_context_key,value_json=excluded.value_json,updated_at=excluded.updated_at,local_state='pending'",args:[id,account.id,account.id,context,timestamp,timestamp,JSON.stringify(body)]},outboxStatement(account.id,{type:"revision_settings",localId:id,endpoint:"/api/planner/revision-settings",body,expected:null,baseVersion:0})]);notify(account.id);},
    async createGoal(title,dueDate){const clientId=crypto.randomUUID(),id=`${account.id}:planner_goal:${clientId}`,timestamp=now(),context=await contextFor(account.id),date=dueDate.slice(0,10),body={action:"create",clientId,title:title.trim(),description:"",dueDate:date,goalKind:"custom",targetValue:1,startsOn:null};await transaction([{sql:"INSERT INTO planner_items(local_id,server_id,server_version,account_id,academic_context_key,local_state,created_at,updated_at,item_kind,title,due_at,payload_json) VALUES(?,NULL,0,?,?,'pending',?,?,'goal',?,?,?)",args:[id,account.id,context,timestamp,timestamp,title.trim(),date,JSON.stringify({...body,status:"active",completedAt:null})]},outboxStatement(account.id,{type:"planner_goal",localId:id,endpoint:"/api/planner/goals",body,expected:null,baseVersion:0})]);notify(account.id);return id;},
    async toggleGoal(localId,done){const rows=await query<{server_id:string|null;title:string;due_at:string|null;completed_at:string|null;server_version:number;payload_json:string}>("SELECT server_id,title,due_at,completed_at,server_version,payload_json FROM planner_items WHERE account_id=? AND local_id=? AND item_kind='goal' AND deleted_at IS NULL LIMIT 1",[account.id,localId]);const row=rows[0];if(!row)throw new Error("Goal is unavailable.");const payload=safeJson(row.payload_json),id=row.server_id||String(payload.clientId||localId.split(":").at(-1)||localId),timestamp=now(),body={action:"toggle",id,done};const expected={title:row.title,description:payload.description?String(payload.description):null,due_date:(row.due_at||"").slice(0,10),status:row.completed_at?"completed":"active",completed_at:row.completed_at};await transaction([{sql:"UPDATE planner_items SET completed_at=?,local_state='pending',updated_at=?,payload_json=? WHERE account_id=? AND local_id=?",args:[done?timestamp:null,timestamp,JSON.stringify({...payload,status:done?"completed":"active",completedAt:done?timestamp:null}),account.id,localId]},outboxStatement(account.id,{type:"planner_goal",localId,endpoint:"/api/planner/goals",body,expected,baseVersion:row.server_version})]);notify(account.id);},
    async createTask(title,dueAt){const clientId=crypto.randomUUID(),id=`${account.id}:planner_task:${clientId}`,timestamp=now(),context=await contextFor(account.id),body={action:"create",clientId,title:title.trim(),dueAt,taskKind:"study",scheduleMode:"flexible",estimatedMinutes:30};await transaction([{sql:"INSERT INTO planner_items(local_id,server_id,server_version,account_id,academic_context_key,local_state,created_at,updated_at,item_kind,title,due_at,payload_json) VALUES(?,NULL,0,?,?,'pending',?,?,'task',?,?,?)",args:[id,account.id,context,timestamp,timestamp,title.trim(),dueAt,JSON.stringify(body)]},outboxStatement(account.id,{type:"planner_task",localId:id,endpoint:"/api/planner/tasks",body,expected:null,baseVersion:0})]);notify(account.id);return id;},
    async toggleTask(localId,done){const rows=await query<{server_id:string|null;title:string;due_at:string|null;completed_at:string|null;server_version:number;payload_json:string}>("SELECT server_id,title,due_at,completed_at,server_version,payload_json FROM planner_items WHERE account_id=? AND local_id=? AND deleted_at IS NULL LIMIT 1",[account.id,localId]);const row=rows[0];if(!row)throw new Error("Task is unavailable.");const id=row.server_id||localId,timestamp=now(),body={action:"toggle",id,done};const expected={title:row.title,notes:safeJson(row.payload_json).notes??null,status:row.completed_at?"done":"todo",subject_id:safeJson(row.payload_json).subjectId??null,chapter_id:safeJson(row.payload_json).chapterId??null,due_at:row.due_at,estimated_minutes:Number(safeJson(row.payload_json).estimatedMinutes||30)};await transaction([{sql:"UPDATE planner_items SET completed_at=?,local_state='pending',updated_at=? WHERE account_id=? AND local_id=?",args:[done?timestamp:null,timestamp,account.id,localId]},outboxStatement(account.id,{type:"planner_task",localId,endpoint:"/api/planner/tasks",body,expected,baseVersion:row.server_version})]);notify(account.id);},
    async setProgressStage(localId,stage,enabled){const rows=await query<{server_id:string|null;chapter_id:string|null;server_version:number;payload_json:string}>("SELECT server_id,chapter_id,server_version,payload_json FROM progress_records WHERE account_id=? AND local_id=? AND deleted_at IS NULL LIMIT 1",[account.id,localId]);const row=rows[0];const timestamp=now(),context=await contextFor(account.id);if(!row){const prefix=account.id+":progress:";const chapterId=localId.startsWith(prefix)?localId.slice(prefix.length):"";const catalog=(await query<{server_id:string|null;title:string;parent_server_id:string|null}>("SELECT server_id,title,parent_server_id FROM academic_catalog WHERE account_id=? AND academic_context_key=? AND entity_type='chapter' AND server_id=? AND deleted_at IS NULL LIMIT 1",[account.id,context,chapterId]))[0];if(!catalog?.server_id)throw new Error("Progress item is unavailable.");const payload:Record<string,unknown>={chapterId:catalog.server_id,chapterTitle:catalog.title,subjectId:catalog.parent_server_id,completedAt:null,revision1At:null,revision2At:null,test1At:null,test2At:null};const key=stage==="completed"?"completedAt":stage==="revision_1"?"revision1At":"revision2At";payload[key]=enabled?timestamp:null;const body={action:"set_stage",chapterId:catalog.server_id,stage,enabled};const expected={completed_at:null,revision_1_at:null,revision_2_at:null,test_1_at:null,test_2_at:null};await transaction([{sql:"INSERT INTO progress_records(local_id,server_id,server_version,account_id,academic_context_key,local_state,created_at,updated_at,subject_id,chapter_id,stage,understanding,payload_json) VALUES(?,NULL,0,?,?,'pending',?,?,?,?,?,NULL,?)",args:[localId,account.id,context,timestamp,timestamp,catalog.parent_server_id,catalog.server_id,stage,JSON.stringify(payload)]},outboxStatement(account.id,{type:"progress",localId,endpoint:"/api/progress",body,expected,baseVersion:0})]);notify(account.id);return;}const payload=safeJson(row.payload_json),expected={completed_at:payload.completedAt??null,revision_1_at:payload.revision1At??null,revision_2_at:payload.revision2At??null,test_1_at:payload.test1At??null,test_2_at:payload.test2At??null},chapterId=row.chapter_id||String(payload.chapterId||row.server_id||"");const key=stage==="completed"?"completedAt":stage==="revision_1"?"revision1At":"revision2At";payload[key]=enabled?timestamp:null;const body={action:"set_stage",chapterId,stage,enabled};await transaction([{sql:"UPDATE progress_records SET payload_json=?,stage=?,local_state='pending',updated_at=? WHERE account_id=? AND local_id=?",args:[JSON.stringify(payload),stage,timestamp,account.id,localId]},outboxStatement(account.id,{type:"progress",localId,endpoint:"/api/progress",body,expected,baseVersion:row.server_version})]);notify(account.id);},
    async saveNote(input){const clientId=input.localId?.split(":").at(-1)||crypto.randomUUID(),id=input.localId||`${account.id}:note:${clientId}`,timestamp=now(),context=await contextFor(account.id),rows=input.localId?await query<{server_id:string|null;server_version:number;title:string;body_text:string;updated_at:string;baseline_json:string|null}>("SELECT server_id,server_version,title,body_text,updated_at,baseline_json FROM notes WHERE account_id=? AND local_id=? LIMIT 1",[account.id,id]):[],row=rows[0],body={...(row?.server_id?{id:row.server_id}:{clientId}),title:input.title.trim(),bodyHtml:`<p>${input.body.replace(/[<>&]/g,value=>({"<":"&lt;",">":"&gt;","&":"&amp;"}[value]!))}</p>`,visibility:"private"};await transaction([{sql:"INSERT INTO notes(local_id,server_id,server_version,account_id,academic_context_key,local_state,created_at,updated_at,title,body_text) VALUES(?,?,?,?,?,'pending',?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET title=excluded.title,body_text=excluded.body_text,updated_at=excluded.updated_at,local_state='pending'",args:[id,row?.server_id||null,row?.server_version||0,account.id,context,timestamp,timestamp,input.title.trim(),input.body]},outboxStatement(account.id,{type:"note",localId:id,endpoint:"/api/notes",body,expected:row?.server_id?row.baseline_json?safeJson(row.baseline_json):null:null,baseVersion:row?.server_version||0})]);notify(account.id);return id;},
    async finishTimer(timer){const timestamp=now(),clientId=crypto.randomUUID(),id=`${account.id}:focus_session:${clientId}`,context=await contextFor(account.id),duration=Math.max(0,timer.elapsedSeconds+(timer.status==="running"&&timer.startedAt?Math.floor((Date.now()-Date.parse(timer.startedAt))/1000):0)),body={action:"finish",clientId,timezone:"Asia/Kolkata"},predecessor=(await query<{mutation_id:string}>("SELECT mutation_id FROM mutation_outbox WHERE account_id=? AND entity_local_id='timer' ORDER BY created_at DESC LIMIT 1",[account.id]))[0]?.mutation_id||null,expected={status:timer.status,started_at:timer.startedAt,elapsed_seconds:timer.elapsedSeconds,running_since:timer.status==="running"?timer.updatedAt:null,paused_at:timer.status==="paused"?timer.updatedAt:null};await transaction([{sql:"INSERT INTO study_sessions(local_id,server_id,server_version,account_id,academic_context_key,local_state,created_at,updated_at,started_at,ended_at,duration_seconds,payload_json) VALUES(?,NULL,0,?,?,'pending',?,?,?,?,?,?)",args:[id,account.id,context,timestamp,timestamp,timer.startedAt||timestamp,timestamp,duration,JSON.stringify(body)]},{sql:"UPDATE timer_state SET status='idle',started_at=NULL,elapsed_seconds=0,updated_at=? WHERE account_id=?",args:[timestamp,account.id]},outboxStatement(account.id,{type:"focus_session",localId:id,endpoint:"/api/study/timer",body,expected,predecessor})]);notify(account.id);return id;},
    async saveSessionReview(localId,understanding,focus){const rows=await query<{server_id:string|null;payload_json:string}>("SELECT server_id,payload_json FROM study_sessions WHERE account_id=? AND local_id=? LIMIT 1",[account.id,localId]);const row=rows[0];if(!row)throw new Error("Study session is unavailable.");const sessionId=row.server_id||localId.split(":").at(-1)||"",payload={...safeJson(row.payload_json),understandingScore:understanding,focusRating:focus,reflectionSavedAt:now()},body={sessionId,understandingScore:understanding,focusRating:focus};await transaction([{sql:"UPDATE study_sessions SET payload_json=?,local_state='pending',updated_at=? WHERE account_id=? AND local_id=?",args:[JSON.stringify(payload),now(),account.id,localId]},outboxStatement(account.id,{type:"session_review",localId,endpoint:"/api/study/reflection",body,expected:{understanding_score:null,focus_rating:null,reflection_saved_at:null}})]);notify(account.id);},
    subscribe(listener) { const accountListeners=listeners.get(account.id) || new Set(); accountListeners.add(listener); listeners.set(account.id,accountListeners); return () => { accountListeners.delete(listener); if(!accountListeners.size) listeners.delete(account.id); }; },
    async lock() { await execute("UPDATE local_accounts SET state='locked' WHERE account_id=?",[account.id]); notify(account.id); },
    async removeFromDevice() { await execute("DELETE FROM local_accounts WHERE account_id=?",[account.id]); listeners.delete(account.id); },
    async cleanup(maxBytes=250*1024*1024) { const total=await query<{total:number}>("SELECT COALESCE(SUM(byte_size),0) AS total FROM local_file_index WHERE account_id=?",[account.id]); let remaining=Number(total[0]?.total||0); if(remaining<=maxBytes)return 0; const candidates=await query<{file_id:string;byte_size:number}>("SELECT f.file_id,f.byte_size FROM local_file_index f WHERE f.account_id=? AND f.pinned=0 AND f.pending_upload=0 AND NOT EXISTS(SELECT 1 FROM mutation_outbox m WHERE m.account_id=f.account_id AND m.entity_local_id=f.resource_local_id AND m.status IN ('pending','failed')) ORDER BY f.last_accessed_at ASC",[account.id]); let evicted=0; for(const item of candidates){if(remaining<=maxBytes)break;await execute("DELETE FROM local_file_index WHERE account_id=? AND file_id=?",[account.id,item.file_id]);remaining-=Number(item.byte_size);evicted++;}return evicted; },
  };
}

export async function wipeAllOfflineData() { listeners.clear(); await wipeDatabase(); }
