import {execute,query,transaction} from "./database";

export type LocalResource={localId:string;serverId:string;ownerId:string;title:string;filename:string;mimeType:string;byteSize:number;checksum:string|null;syncState:"metadata"|"downloading"|"available"|"uploading"|"failed";localFileId:string|null;thumbnailFileId:string|null;updatedAt:string};
export type LocalNotification={id:string;type:string;title:string;body:string;actionHref:string|null;readAt:string|null;createdAt:string};
export type RemoteResource={id:string;ownerId:string;title:string;filename:string;mimeType:string;byteSize:number;updatedAt:string;checksum?:string|null};
export type RemoteNotification={id:string;notificationType:string;title:string;body:string;actionHref?:string|null;readAt:string|null;createdAt:string};
const now=()=>new Date().toISOString();const localId=(accountId:string,id:string)=>`resource:${accountId}:${id}`;

export async function storeResourceMetadata(accountId:string,resources:RemoteResource[]){const timestamp=now();await transaction(resources.map(item=>({sql:"INSERT INTO resource_metadata(local_id,server_id,account_id,local_state,created_at,updated_at,title,resource_type,byte_size,owner_id,mime_type,checksum,sync_state) VALUES(?,?,?,'synced',?,?,?,?,?,?,?,?, 'metadata') ON CONFLICT(local_id) DO UPDATE SET title=excluded.title,byte_size=excluded.byte_size,owner_id=excluded.owner_id,mime_type=excluded.mime_type,checksum=COALESCE(excluded.checksum,resource_metadata.checksum),updated_at=excluded.updated_at,deleted_at=NULL",args:[localId(accountId,item.id),item.id,accountId,timestamp,item.updatedAt||timestamp,item.title,item.filename,item.byteSize,item.ownerId,item.mimeType,item.checksum||null]})));}
export async function readResources(accountId:string){const rows=await query<{local_id:string;server_id:string;owner_id:string|null;title:string;resource_type:string;mime_type:string|null;byte_size:number;checksum:string|null;sync_state:LocalResource["syncState"];local_file_id:string|null;thumbnail_file_id:string|null;updated_at:string}>("SELECT local_id,server_id,owner_id,title,resource_type,mime_type,byte_size,checksum,sync_state,local_file_id,thumbnail_file_id,updated_at FROM resource_metadata WHERE account_id=? AND deleted_at IS NULL ORDER BY updated_at DESC",[accountId]);return rows.map(row=>({localId:row.local_id,serverId:row.server_id,ownerId:row.owner_id||accountId,title:row.title,filename:row.resource_type,mimeType:row.mime_type||"application/octet-stream",byteSize:Number(row.byte_size),checksum:row.checksum,syncState:row.sync_state,localFileId:row.local_file_id,thumbnailFileId:row.thumbnail_file_id,updatedAt:row.updated_at}));}
export async function beginFileTransfer(accountId:string,resource:LocalResource,direction:"download"|"upload"){const transferId=crypto.randomUUID(),timestamp=now(),key=`${direction}:${accountId}:${resource.localId}:${resource.checksum||resource.updatedAt}`;await transaction([{sql:"INSERT OR IGNORE INTO file_transfers(transfer_id,account_id,resource_local_id,direction,state,total_bytes,idempotency_key,created_at,updated_at) VALUES(?,?,?,?, 'queued',?,?,?,?)",args:[transferId,accountId,resource.localId,direction,resource.byteSize,key,timestamp,timestamp]},{sql:"UPDATE resource_metadata SET sync_state=?,updated_at=? WHERE account_id=? AND local_id=?",args:[direction==="download"?"downloading":"uploading",timestamp,accountId,resource.localId]}]);return{transferId,idempotencyKey:key};}
export async function updateFileTransfer(accountId:string,transferId:string,input:{state:"running"|"paused"|"failed"|"completed"|"cancelled";bytesComplete?:number;error?:string|null;resumeToken?:string|null}){await execute("UPDATE file_transfers SET state=?,bytes_complete=MAX(bytes_complete,?),resume_token=COALESCE(?,resume_token),last_error=?,attempts=attempts+CASE WHEN ?='failed' THEN 1 ELSE 0 END,next_attempt_at=CASE WHEN ?='failed' THEN datetime('now','+'||(MIN(attempts+1,10)*15)||' seconds') ELSE NULL END,updated_at=? WHERE account_id=? AND transfer_id=?",[input.state,input.bytesComplete||0,input.resumeToken||null,input.error||null,input.state,input.state,now(),accountId,transferId]);}
export async function completeDownload(accountId:string,resource:LocalResource,transferId:string,file:{fileId:string;nativePath:string;byteSize:number;checksum:string}){if(resource.checksum&&resource.checksum!==file.checksum)throw new Error("Downloaded file integrity check failed.");const timestamp=now();await transaction([{sql:"INSERT OR REPLACE INTO local_file_index(file_id,account_id,native_path,resource_local_id,byte_size,checksum,last_accessed_at,pinned,pending_upload,created_at) VALUES(?,?,?,?,?,?,?,0,0,?)",args:[file.fileId,accountId,file.nativePath,resource.localId,file.byteSize,file.checksum,timestamp,timestamp]},{sql:"UPDATE resource_metadata SET local_file_id=?,checksum=?,sync_state='available',last_accessed_at=?,updated_at=? WHERE account_id=? AND local_id=?",args:[file.fileId,file.checksum,timestamp,timestamp,accountId,resource.localId]},{sql:"UPDATE file_transfers SET state='completed',bytes_complete=total_bytes,updated_at=? WHERE account_id=? AND transfer_id=?",args:[timestamp,accountId,transferId]}]);}
export async function recoverFileTransfers(accountId:string){return query<{transfer_id:string;resource_local_id:string;direction:"download"|"upload";state:string;resume_token:string|null;attempts:number}>("SELECT transfer_id,resource_local_id,direction,state,resume_token,attempts FROM file_transfers WHERE account_id=? AND state IN ('queued','running','paused','failed') AND (next_attempt_at IS NULL OR next_attempt_at<=datetime('now')) ORDER BY created_at LIMIT 20",[accountId]);}
export async function removeLocalFile(accountId:string,resource:LocalResource){if(resource.localFileId)await transaction([{sql:"DELETE FROM local_file_index WHERE account_id=? AND file_id=?",args:[accountId,resource.localFileId]},{sql:"UPDATE resource_metadata SET local_file_id=NULL,sync_state='metadata',updated_at=? WHERE account_id=? AND local_id=?",args:[now(),accountId,resource.localId]}]);}
export async function storeNotifications(accountId:string,items:RemoteNotification[]){await transaction(items.map(item=>({sql:"INSERT INTO notifications(local_id,server_id,account_id,local_state,created_at,updated_at,notification_type,title,body,read_at,payload_json) VALUES(?,?,?,'synced',?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET title=excluded.title,body=excluded.body,read_at=excluded.read_at,payload_json=excluded.payload_json,updated_at=excluded.updated_at",args:[`notification:${accountId}:${item.id}`,item.id,accountId,item.createdAt,now(),item.notificationType,item.title,item.body,item.readAt,JSON.stringify({actionHref:item.actionHref||null})]})));}
export async function readNotifications(accountId:string){const rows=await query<{local_id:string;server_id:string|null;notification_type:string;title:string;body:string|null;read_at:string|null;created_at:string;payload_json:string}>("SELECT local_id,server_id,notification_type,title,body,read_at,created_at,payload_json FROM notifications WHERE account_id=? AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 100",[accountId]);return rows.map(row=>{let actionHref:null|string=null;try{actionHref=JSON.parse(row.payload_json).actionHref||null;}catch{}return{id:row.server_id||row.local_id,type:row.notification_type,title:row.title,body:row.body||"",actionHref,readAt:row.read_at,createdAt:row.created_at};});}
export async function markNotificationReadLocal(accountId:string,id:string|null){await execute(id?"UPDATE notifications SET read_at=COALESCE(read_at,?),updated_at=? WHERE account_id=? AND server_id=?":"UPDATE notifications SET read_at=COALESCE(read_at,?),updated_at=? WHERE account_id=?",id?[now(),now(),accountId,id]:[now(),now(),accountId]);}
