import {execute,query,transaction} from "./database";

export type LocalResource={localId:string;serverId:string;ownerId:string;title:string;filename:string;mimeType:string;byteSize:number;checksum:string|null;syncState:"metadata"|"downloading"|"available"|"outdated"|"uploading"|"failed";localFileId:string|null;thumbnailFileId:string|null;pinned:boolean;updatedAt:string};
export type LocalNotification={id:string;type:string;title:string;body:string;actionHref:string|null;readAt:string|null;createdAt:string;pendingRead:boolean};
export type RemoteResource={id:string;ownerId:string;title:string;filename:string;mimeType:string;byteSize:number;updatedAt:string;checksum?:string|null};
export type RemoteNotification={id:string;notificationType:string;title:string;body:string;actionHref?:string|null;readAt:string|null;createdAt:string};
const now=()=>new Date().toISOString();const localId=(accountId:string,id:string)=>`resource:${accountId}:${id}`;

export async function storeResourceMetadata(accountId:string,resources:RemoteResource[]){const timestamp=now();await transaction(resources.map(item=>({sql:"INSERT INTO resource_metadata(local_id,server_id,account_id,local_state,created_at,updated_at,title,resource_type,byte_size,owner_id,mime_type,checksum,sync_state) VALUES(?,?,?,'synced',?,?,?,?,?,?,?,?, 'metadata') ON CONFLICT(local_id) DO UPDATE SET title=excluded.title,byte_size=excluded.byte_size,owner_id=excluded.owner_id,mime_type=excluded.mime_type,checksum=COALESCE(excluded.checksum,resource_metadata.checksum),updated_at=excluded.updated_at,deleted_at=NULL",args:[localId(accountId,item.id),item.id,accountId,timestamp,item.updatedAt||timestamp,item.title,item.filename,item.byteSize,item.ownerId,item.mimeType,item.checksum||null]})));}
export async function readResources(accountId:string){const rows=await query<{local_id:string;server_id:string;owner_id:string|null;title:string;resource_type:string;mime_type:string|null;byte_size:number;checksum:string|null;sync_state:LocalResource["syncState"];local_file_id:string|null;thumbnail_file_id:string|null;pinned:number;updated_at:string;stored_checksum:string|null}>("SELECT r.local_id,r.server_id,r.owner_id,r.title,r.resource_type,r.mime_type,r.byte_size,r.checksum,r.sync_state,r.local_file_id,r.thumbnail_file_id,r.pinned,r.updated_at,f.checksum AS stored_checksum FROM resource_metadata r LEFT JOIN local_file_index f ON f.account_id=r.account_id AND f.file_id=r.local_file_id WHERE r.account_id=? AND r.deleted_at IS NULL ORDER BY r.updated_at DESC",[accountId]);return rows.map(row=>({localId:row.local_id,serverId:row.server_id,ownerId:row.owner_id||accountId,title:row.title,filename:row.resource_type,mimeType:row.mime_type||"application/octet-stream",byteSize:Number(row.byte_size),checksum:row.checksum,syncState:row.local_file_id&&!row.stored_checksum?"metadata":row.local_file_id&&row.checksum&&row.stored_checksum&&row.checksum!==row.stored_checksum?"outdated":row.sync_state,localFileId:row.stored_checksum?row.local_file_id:null,thumbnailFileId:row.thumbnail_file_id,pinned:Boolean(row.pinned),updatedAt:row.updated_at}));}
export async function readOfflineStorageSummary(accountId:string){const rows=await query<{bytes:number;files:number;pinned:number}>("SELECT COALESCE(SUM(byte_size),0) AS bytes,COUNT(*) AS files,COALESCE(SUM(pinned),0) AS pinned FROM local_file_index WHERE account_id=?",[accountId]);return{bytes:Number(rows[0]?.bytes||0),files:Number(rows[0]?.files||0),pinned:Number(rows[0]?.pinned||0)};}
export async function setResourcePinned(accountId:string,resource:LocalResource,pinned:boolean){if(!resource.localFileId)throw new Error("Download this file before pinning it.");await transaction([{sql:"UPDATE local_file_index SET pinned=? WHERE account_id=? AND file_id=?",args:[pinned?1:0,accountId,resource.localFileId]},{sql:"UPDATE resource_metadata SET pinned=?,updated_at=? WHERE account_id=? AND local_id=? AND local_file_id=?",args:[pinned?1:0,now(),accountId,resource.localId,resource.localFileId]}]);}
export async function beginFileTransfer(accountId:string,resource:LocalResource,direction:"download"|"upload"){const transferId=crypto.randomUUID(),timestamp=now(),key=`${direction}:${accountId}:${resource.localId}:${resource.checksum||resource.updatedAt}`;await transaction([{sql:"INSERT OR IGNORE INTO file_transfers(transfer_id,account_id,resource_local_id,direction,state,total_bytes,idempotency_key,created_at,updated_at) VALUES(?,?,?,?, 'queued',?,?,?,?)",args:[transferId,accountId,resource.localId,direction,resource.byteSize,key,timestamp,timestamp]},{sql:"UPDATE file_transfers SET state='queued',last_error=NULL,updated_at=? WHERE account_id=? AND idempotency_key=? AND state IN ('paused','failed','cancelled')",args:[timestamp,accountId,key]},{sql:"UPDATE resource_metadata SET sync_state=?,updated_at=? WHERE account_id=? AND local_id=?",args:[direction==="download"?"downloading":"uploading",timestamp,accountId,resource.localId]}]);const existing=await query<{transfer_id:string}>("SELECT transfer_id FROM file_transfers WHERE account_id=? AND idempotency_key=? LIMIT 1",[accountId,key]);if(!existing[0])throw new Error("Transfer could not be queued.");return{transferId:existing[0].transfer_id,idempotencyKey:key};}
export async function updateFileTransfer(accountId:string,transferId:string,input:{state:"running"|"paused"|"failed"|"completed"|"cancelled";bytesComplete?:number;error?:string|null;resumeToken?:string|null}){await execute("UPDATE file_transfers SET state=?,bytes_complete=MAX(bytes_complete,?),resume_token=COALESCE(?,resume_token),last_error=?,attempts=attempts+CASE WHEN ?='failed' THEN 1 ELSE 0 END,next_attempt_at=CASE WHEN ?='failed' THEN datetime('now','+'||(MIN(attempts+1,10)*15)||' seconds') ELSE NULL END,updated_at=? WHERE account_id=? AND transfer_id=?",[input.state,input.bytesComplete||0,input.resumeToken||null,input.error||null,input.state,input.state,now(),accountId,transferId]);}
export async function completeDownload(accountId:string,resource:LocalResource,transferId:string,file:{fileId:string;nativePath:string;byteSize:number;checksum:string}){if(resource.checksum&&resource.checksum!==file.checksum)throw new Error("Downloaded file integrity check failed.");const timestamp=now();await transaction([{sql:"INSERT OR REPLACE INTO local_file_index(file_id,account_id,native_path,resource_local_id,byte_size,checksum,last_accessed_at,pinned,pending_upload,created_at) VALUES(?,?,?,?,?,?,?,?,0,?)",args:[file.fileId,accountId,file.nativePath,resource.localId,file.byteSize,file.checksum,timestamp,resource.pinned?1:0,timestamp]},{sql:"UPDATE resource_metadata SET local_file_id=?,checksum=?,sync_state='available',last_accessed_at=?,updated_at=? WHERE account_id=? AND local_id=?",args:[file.fileId,file.checksum,timestamp,timestamp,accountId,resource.localId]},{sql:"UPDATE file_transfers SET state='completed',bytes_complete=total_bytes,updated_at=? WHERE account_id=? AND transfer_id=?",args:[timestamp,accountId,transferId]}]);}
export async function recoverFileTransfers(accountId:string){return query<{transfer_id:string;resource_local_id:string;direction:"download"|"upload";state:string;resume_token:string|null;attempts:number}>("SELECT transfer_id,resource_local_id,direction,state,resume_token,attempts FROM file_transfers WHERE account_id=? AND state IN ('queued','running','paused','failed') AND (next_attempt_at IS NULL OR next_attempt_at<=datetime('now')) ORDER BY created_at LIMIT 20",[accountId]);}
export async function removeLocalFile(accountId:string,resource:LocalResource){if(resource.localFileId)await transaction([{sql:"DELETE FROM local_file_index WHERE account_id=? AND file_id=?",args:[accountId,resource.localFileId]},{sql:"UPDATE resource_metadata SET local_file_id=NULL,sync_state='metadata',updated_at=? WHERE account_id=? AND local_id=?",args:[now(),accountId,resource.localId]}]);}
export async function removeSupersededFileIndex(accountId:string,fileId:string){await execute("DELETE FROM local_file_index WHERE account_id=? AND file_id=? AND file_id NOT IN (SELECT local_file_id FROM resource_metadata WHERE account_id=? AND deleted_at IS NULL)",[accountId,fileId,accountId]);}
export async function readUnreferencedFileIds(accountId:string){const rows=await query<{file_id:string}>("SELECT f.file_id FROM local_file_index f WHERE f.account_id=? AND f.pending_upload=0 AND f.file_id NOT IN (SELECT r.local_file_id FROM resource_metadata r WHERE r.account_id=? AND r.local_file_id IS NOT NULL AND r.deleted_at IS NULL) ORDER BY f.last_accessed_at LIMIT 25",[accountId,accountId]);return rows.map(row=>row.file_id);}
export async function storeNotifications(accountId:string,items:RemoteNotification[]){const existing=await query<{server_id:string;payload_json:string;read_at:string|null}>("SELECT server_id,payload_json,read_at FROM notifications WHERE account_id=?",[accountId]);const previous=new Map(existing.map(row=>[row.server_id,row]));await transaction(items.map(item=>{const prior=previous.get(item.id);let pendingRead=false;try{pendingRead=Boolean(JSON.parse(prior?.payload_json||"{}").pendingRead);}catch{}return{sql:"INSERT INTO notifications(local_id,server_id,account_id,local_state,created_at,updated_at,notification_type,title,body,read_at,payload_json) VALUES(?,?,?,'synced',?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET title=excluded.title,body=excluded.body,read_at=COALESCE(notifications.read_at,excluded.read_at),payload_json=excluded.payload_json,updated_at=excluded.updated_at",args:[`notification:${accountId}:${item.id}`,item.id,accountId,item.createdAt,now(),item.notificationType,item.title,item.body,item.readAt,JSON.stringify({actionHref:item.actionHref||null,pendingRead:pendingRead&&!item.readAt})]};}));}
export async function readNotifications(accountId:string){const rows=await query<{local_id:string;server_id:string|null;notification_type:string;title:string;body:string|null;read_at:string|null;created_at:string;payload_json:string}>("SELECT local_id,server_id,notification_type,title,body,read_at,created_at,payload_json FROM notifications WHERE account_id=? AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 100",[accountId]);return rows.map(row=>{let actionHref:null|string=null,pendingRead=false;try{const payload=JSON.parse(row.payload_json);actionHref=payload.actionHref||null;pendingRead=Boolean(payload.pendingRead);}catch{}return{id:row.server_id||row.local_id,type:row.notification_type,title:row.title,body:row.body||"",actionHref,readAt:row.read_at,createdAt:row.created_at,pendingRead};});}
export async function markNotificationReadLocal(accountId:string,id:string|null){const rows=await query<{server_id:string;payload_json:string;read_at:string|null}>(id?"SELECT server_id,payload_json,read_at FROM notifications WHERE account_id=? AND server_id=?":"SELECT server_id,payload_json,read_at FROM notifications WHERE account_id=?",id?[accountId,id]:[accountId]);const timestamp=now();await transaction(rows.filter(row=>!row.read_at).map(row=>{let payload:Record<string,unknown>={};try{payload=JSON.parse(row.payload_json);}catch{}return{sql:"UPDATE notifications SET read_at=?,payload_json=?,updated_at=? WHERE account_id=? AND server_id=?",args:[timestamp,JSON.stringify({...payload,pendingRead:true}),timestamp,accountId,row.server_id]};}));}
export async function acknowledgeNotificationRead(accountId:string,id:string){const rows=await query<{payload_json:string}>("SELECT payload_json FROM notifications WHERE account_id=? AND server_id=?",[accountId,id]);if(!rows[0])return;let payload:Record<string,unknown>={};try{payload=JSON.parse(rows[0].payload_json);}catch{}await execute("UPDATE notifications SET payload_json=?,updated_at=? WHERE account_id=? AND server_id=?",[JSON.stringify({...payload,pendingRead:false}),now(),accountId,id]);}
