import { execute, query, transaction } from "./database";
import type { SqlStatement } from "./schema";
import { notifyLocalAccountChanged } from "./repository";

export type SyncVisualState="idle"|"updating"|"offline"|"pending"|"conflict"|"failed";
export type SyncTransport=(path:string,init?:RequestInit)=>Promise<unknown>;
type RemoteEntity={entity_type:string;entity_id:string;entity_version:number;payload_json:string|null;deleted_at?:string|null;operation?:"upsert"|"delete";occurred_at?:string};
type Bootstrap={accountId:string;academicContextKey:string;cursor:string;entities:RemoteEntity[]};
type Pull={academicContextKey:string;cursor:string;hasMore:boolean;changes:Array<RemoteEntity&{sequence:number}>};
type Outbox={mutation_id:string;entity_type:string;entity_local_id:string;payload_json:string;endpoint:string|null;expected_json:string|null;predecessor_mutation_id:string|null;attempts:number;base_server_version:number|null};

const endpointFor:Record<string,string>={progress:"/api/progress",planner_task:"/api/planner/tasks",planner_goal:"/api/planner/goals",revision_settings:"/api/planner/revision-settings",note:"/api/notes",focus_session:"/api/study/timer",session_review:"/api/study/reflection"};
const tableFor:Record<string,string>={progress:"progress_records",planner_task:"planner_items",planner_goal:"planner_items",revision_settings:"application_config",note:"notes",focus_session:"study_sessions",session_review:"study_sessions"};
const now=()=>new Date().toISOString();
const parse=(value:string|null)=>{try{return value?JSON.parse(value) as Record<string,unknown>:{};}catch{return {};}};
const localId=(accountId:string,type:string,id:string)=>`${accountId}:${type}:${id}`;

function applyEntity(accountId:string,contextKey:string,entity:RemoteEntity):SqlStatement[]{
  const id=localId(accountId,entity.entity_type,entity.entity_id);const payload=parse(entity.payload_json);const timestamp=entity.occurred_at||now();
  if(entity.entity_type==="academic_subject"||entity.entity_type==="academic_chapter"||entity.entity_type==="attempt")return[{sql:"INSERT INTO academic_catalog(local_id,server_id,server_version,account_id,academic_context_key,local_state,created_at,updated_at,entity_type,slug,title,parent_server_id,payload_json) VALUES(?,?,?,?,?,'synced',?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET academic_context_key=excluded.academic_context_key,server_version=excluded.server_version,title=excluded.title,payload_json=excluded.payload_json,updated_at=excluded.updated_at,deleted_at=NULL,local_state='synced'",args:[id,entity.entity_id,entity.entity_version,accountId,contextKey,timestamp,timestamp,entity.entity_type==="academic_subject"?"subject":entity.entity_type==="academic_chapter"?"chapter":"attempt",payload.slug??payload.attemptKey??null,String(payload.title||payload.label||"Academic item"),payload.subjectId??null,JSON.stringify(payload)]}];
  if(entity.entity_type==="profile")return[{sql:"INSERT INTO profile_projection(local_id,server_id,server_version,account_id,academic_context_key,local_state,created_at,updated_at,display_name,level_code,attempt_key,timezone,daily_target_minutes,payload_json) VALUES(?,?,?,?,?,'synced',?,?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET academic_context_key=excluded.academic_context_key,server_version=excluded.server_version,display_name=excluded.display_name,level_code=excluded.level_code,attempt_key=excluded.attempt_key,timezone=excluded.timezone,daily_target_minutes=excluded.daily_target_minutes,payload_json=excluded.payload_json,updated_at=excluded.updated_at,deleted_at=NULL,local_state='synced'",args:[id,entity.entity_id,entity.entity_version,accountId,contextKey,timestamp,timestamp,String(payload.displayName||"CA Progress student"),payload.level??null,payload.attempt??null,payload.timezone??null,payload.dailyTargetMinutes??null,JSON.stringify(payload)]}];
  if(entity.entity_type==="activity")return[{sql:"INSERT INTO activity_projection(local_id,server_id,server_version,account_id,academic_context_key,local_state,created_at,updated_at,activity_kind,title,occurred_at,xp_amount,payload_json) VALUES(?,?,?,?,?,'synced',?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET academic_context_key=excluded.academic_context_key,server_version=excluded.server_version,title=excluded.title,occurred_at=excluded.occurred_at,xp_amount=excluded.xp_amount,payload_json=excluded.payload_json,updated_at=excluded.updated_at,deleted_at=NULL,local_state='synced'",args:[id,entity.entity_id,entity.entity_version,accountId,contextKey,timestamp,timestamp,String(payload.kind||"activity"),String(payload.title||"Study activity"),String(payload.occurredAt||timestamp),Number(payload.xp||0),JSON.stringify(payload)]}];
  if(entity.entity_type==="leaderboard")return[{sql:"INSERT INTO leaderboard_projection(local_id,server_id,server_version,account_id,academic_context_key,local_state,created_at,updated_at,category,rank,score,public_alias,payload_json) VALUES(?,?,?,?,?,'synced',?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET academic_context_key=excluded.academic_context_key,server_version=excluded.server_version,rank=excluded.rank,score=excluded.score,public_alias=excluded.public_alias,payload_json=excluded.payload_json,updated_at=excluded.updated_at,deleted_at=NULL,local_state='synced'",args:[id,entity.entity_id,entity.entity_version,accountId,contextKey,timestamp,timestamp,String(payload.category||"overall"),payload.rank??null,Number(payload.score||0),payload.alias??null,JSON.stringify(payload)]}];
  if(entity.entity_type==="study_buddy")return[{sql:"INSERT INTO study_buddy_projection(local_id,server_id,server_version,account_id,academic_context_key,local_state,created_at,updated_at,relationship_id,buddy_name,relationship_state,payload_json) VALUES(?,?,?,?,?,'synced',?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET academic_context_key=excluded.academic_context_key,server_version=excluded.server_version,buddy_name=excluded.buddy_name,relationship_state=excluded.relationship_state,payload_json=excluded.payload_json,updated_at=excluded.updated_at,deleted_at=NULL,local_state='synced'",args:[id,entity.entity_id,entity.entity_version,accountId,contextKey,timestamp,timestamp,payload.relationshipId??entity.entity_id,String(payload.name||"Study buddy"),String(payload.state||"pending"),JSON.stringify(payload)]}];
  if(entity.entity_type==="session_review")return[{sql:"UPDATE study_sessions SET server_version=?,payload_json=?,updated_at=?,local_state=CASE WHEN local_state='conflict' THEN local_state ELSE 'synced' END WHERE account_id=? AND (server_id=? OR local_id=?)",args:[entity.entity_version,JSON.stringify(payload),timestamp,accountId,entity.entity_id,localId(accountId,"focus_session",entity.entity_id)]}];
  if(entity.entity_type==="planner_goal")return[{sql:"INSERT INTO planner_items(server_id,server_version,account_id,academic_context_key,payload_json,created_at,updated_at,local_id,item_kind,title,due_at,completed_at) VALUES(?,?,?,?,?,?,?,?,'goal',?,?,?) ON CONFLICT(local_id) DO UPDATE SET academic_context_key=excluded.academic_context_key,server_id=excluded.server_id,server_version=excluded.server_version,payload_json=excluded.payload_json,title=excluded.title,due_at=excluded.due_at,completed_at=excluded.completed_at,updated_at=excluded.updated_at,deleted_at=NULL,local_state='synced' WHERE planner_items.local_state='synced'",args:[entity.entity_id,entity.entity_version,accountId,contextKey,JSON.stringify(payload),timestamp,timestamp,id,String(payload.title||"Goal"),payload.dueDate??null,payload.completedAt??null]}];
  if(entity.entity_type==="revision_settings")return[{sql:"INSERT INTO application_config(local_id,server_id,server_version,account_id,academic_context_key,local_state,created_at,updated_at,config_key,value_json) VALUES(?,?,?,?,?,'synced',?,?,'revision_settings',?) ON CONFLICT(local_id) DO UPDATE SET academic_context_key=excluded.academic_context_key,server_id=excluded.server_id,server_version=excluded.server_version,value_json=excluded.value_json,updated_at=excluded.updated_at,deleted_at=NULL,local_state='synced' WHERE application_config.local_state='synced'",args:[id,entity.entity_id,entity.entity_version,accountId,contextKey,timestamp,timestamp,JSON.stringify(payload)]}];
  const table=tableFor[entity.entity_type];if(!table)return[];
  if(entity.operation==="delete"||entity.deleted_at)return[
    {sql:`UPDATE ${table} SET deleted_at=?,server_version=?,local_state='synced',updated_at=? WHERE account_id=? AND server_id=?`,args:[entity.deleted_at||timestamp,entity.entity_version,timestamp,accountId,entity.entity_id]},
    {sql:"INSERT INTO tombstones(account_id,entity_type,server_id,server_version,deleted_at) VALUES(?,?,?,?,?) ON CONFLICT(account_id,entity_type,server_id) DO UPDATE SET server_version=excluded.server_version,deleted_at=excluded.deleted_at",args:[accountId,entity.entity_type,entity.entity_id,entity.entity_version,entity.deleted_at||timestamp]},
  ];
  const common=[entity.entity_id,entity.entity_version,accountId,contextKey,JSON.stringify(payload),timestamp,timestamp,id];
  if(entity.entity_type==="progress")return[{sql:"INSERT INTO progress_records(server_id,server_version,account_id,academic_context_key,payload_json,created_at,updated_at,local_id,subject_id,chapter_id,stage,understanding) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET academic_context_key=excluded.academic_context_key,server_version=excluded.server_version,payload_json=excluded.payload_json,updated_at=excluded.updated_at,deleted_at=NULL,local_state='synced' WHERE progress_records.local_state='synced'",args:[...common,payload.subjectId??null,payload.chapterId??entity.entity_id,payload.stage??null,payload.understanding??null]}];
  if(entity.entity_type==="planner_task")return[{sql:"INSERT INTO planner_items(server_id,server_version,account_id,academic_context_key,payload_json,created_at,updated_at,local_id,item_kind,title,due_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET academic_context_key=excluded.academic_context_key,server_version=excluded.server_version,payload_json=excluded.payload_json,title=excluded.title,due_at=excluded.due_at,completed_at=excluded.completed_at,updated_at=excluded.updated_at,deleted_at=NULL,local_state='synced' WHERE planner_items.local_state='synced'",args:[...common,"task",String(payload.title||"Task"),payload.dueAt??null,payload.completedAt??null]}];
  if(entity.entity_type==="note")return[{sql:"INSERT INTO notes(server_id,server_version,account_id,academic_context_key,created_at,updated_at,local_id,title,body_text,subject_id,chapter_id) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET academic_context_key=excluded.academic_context_key,server_version=excluded.server_version,title=excluded.title,body_text=excluded.body_text,updated_at=excluded.updated_at,deleted_at=NULL,local_state='synced' WHERE notes.local_state='synced'",args:[entity.entity_id,entity.entity_version,accountId,contextKey,timestamp,timestamp,id,String(payload.title||"Note"),String(payload.body||payload.bodyHtml||""),payload.subjectId??null,payload.chapterId??null]}];
  return[{sql:"INSERT INTO study_sessions(server_id,server_version,account_id,academic_context_key,payload_json,created_at,updated_at,local_id,started_at,ended_at,duration_seconds,subject_id,chapter_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET academic_context_key=excluded.academic_context_key,server_version=excluded.server_version,payload_json=excluded.payload_json,updated_at=excluded.updated_at,local_state='synced' WHERE study_sessions.local_state='synced'",args:[...common,String(payload.startedAt||timestamp),payload.endedAt??null,Number(payload.durationSeconds||0),payload.subjectId??null,payload.chapterId??null]}];
}

async function commitPage(accountId:string,contextKey:string,cursor:string,entities:RemoteEntity[]){
  const statements=entities.flatMap(entity=>applyEntity(accountId,contextKey,entity));
  statements.push({sql:"INSERT INTO sync_cursors(account_id,scope,cursor,updated_at) VALUES(?,?,?,?) ON CONFLICT(account_id,scope) DO UPDATE SET cursor=excluded.cursor,updated_at=excluded.updated_at",args:[accountId,contextKey,cursor,now()]});
  await transaction(statements);
  notifyLocalAccountChanged(accountId);
}

export function conflictPolicy(type:string){return ({progress:"merge-independent-stages",planner_task:"field-review",planner_goal:"field-review",revision_settings:"last-write-explicit",note:"retain-both",focus_session:"immutable-client-id",read_state:"greatest-sequence",notification:"monotonic-read",profile:"explicit-review"} as Record<string,string>)[type]||"explicit-review";}

export function createSyncCoordinator(input:{accountId:string;transport:SyncTransport;onState?:(state:SyncVisualState)=>void}){
  let running:Promise<void>|null=null;let stopped=false;const state=(value:SyncVisualState)=>input.onState?.(value);
  async function push(contextKey:string){
    const rows=await query<Outbox>("SELECT mutation_id,entity_type,entity_local_id,payload_json,endpoint,expected_json,predecessor_mutation_id,attempts,base_server_version FROM mutation_outbox WHERE account_id=? AND entity_type<>'community_message' AND status IN ('pending','failed') AND (next_attempt_at IS NULL OR next_attempt_at<=?) ORDER BY created_at,rowid LIMIT 50",[input.accountId,now()]);if(!rows.length)return;
    const mutations=rows.map(row=>({mutationId:row.mutation_id,contextKey,endpoint:row.endpoint||endpointFor[row.entity_type],body:parse(row.payload_json),expected:row.expected_json?parse(row.expected_json):null,predecessor:row.predecessor_mutation_id,baseVersion:row.base_server_version}));
    try{const response=await input.transport("/api/v1/sync/push",{method:"POST",body:JSON.stringify({mutations})}) as {results:Array<{mutationId:string;status:string;response?:unknown}>};for(const result of response.results){const row=rows.find(item=>item.mutation_id===result.mutationId);if(result.status==="applied"){const table=row?tableFor[row.entity_type]:null;await transaction([...(table?[{sql:`UPDATE ${table} SET local_state='synced',updated_at=? WHERE account_id=? AND local_id=?`,args:[now(),input.accountId,row!.entity_local_id]}]:[]),{sql:"DELETE FROM mutation_outbox WHERE account_id=? AND mutation_id=?",args:[input.accountId,result.mutationId]}]);}else if(result.status==="conflict"){await transaction([{sql:"UPDATE mutation_outbox SET status='conflict',last_error='conflict',updated_at=? WHERE account_id=? AND mutation_id=?",args:[now(),input.accountId,result.mutationId]},{sql:"INSERT OR IGNORE INTO conflicts(conflict_id,account_id,entity_type,entity_local_id,local_json,server_json,baseline_version,created_at) VALUES(?,?,?,?,?,?,0,?)",args:[crypto.randomUUID(),input.accountId,row?.entity_type||"unknown",row?.entity_local_id||"unknown",row?.payload_json||"{}",JSON.stringify(result.response||{}),now()]}]);}else if(result.status==="blocked")await execute("UPDATE mutation_outbox SET status='failed',last_error='dependency_conflict',updated_at=? WHERE account_id=? AND mutation_id=?",[now(),input.accountId,result.mutationId]);else{const attempts=(row?.attempts||0)+1;const delay=Math.min(3600,Math.pow(2,attempts)*5)*(0.75+Math.random()*0.5);await execute("UPDATE mutation_outbox SET status='failed',attempts=?,next_attempt_at=?,last_error='retryable',updated_at=? WHERE account_id=? AND mutation_id=?",[attempts,new Date(Date.now()+delay*1000).toISOString(),now(),input.accountId,result.mutationId]);}}}catch(error){state("offline");throw error;}
  }
  async function synchronize(){if(stopped)return;if(running)return running;running=(async()=>{state("updating");try{const stored=(await query<{cursor:string|null;scope:string}>("SELECT cursor,scope FROM sync_cursors WHERE account_id=? ORDER BY updated_at DESC LIMIT 1",[input.accountId]))[0];let cursor=stored?.cursor;let contextKey=stored?.scope;const bootstrap=await input.transport("/api/v1/sync/bootstrap") as Bootstrap;if(bootstrap.accountId!==input.accountId)throw new Error("SYNC_ACCOUNT_MISMATCH: Server identity does not match this device account.");if(contextKey&&bootstrap.academicContextKey!==contextKey){const queued=await query<{count:number}>("SELECT COUNT(*) AS count FROM mutation_outbox WHERE account_id=?",[input.accountId]);if(Number(queued[0]?.count))throw new Error("Academic context changed while edits are pending.");}contextKey=bootstrap.academicContextKey;await commitPage(input.accountId,contextKey,bootstrap.cursor,bootstrap.entities);cursor=bootstrap.cursor;await push(contextKey);let more=true;while(more){const delta=await input.transport(`/api/v1/sync/pull?context=${encodeURIComponent(contextKey)}&cursor=${encodeURIComponent(cursor||"0")}`) as Pull;if(delta.academicContextKey!==contextKey)throw new Error("Academic context changed during synchronization.");await commitPage(input.accountId,contextKey,delta.cursor,delta.changes);cursor=delta.cursor;more=delta.hasMore;}const conflicts=await query<{count:number}>("SELECT COUNT(*) AS count FROM conflicts WHERE account_id=? AND resolved_at IS NULL",[input.accountId]);const pending=await query<{count:number}>("SELECT COUNT(*) AS count FROM mutation_outbox WHERE account_id=?",[input.accountId]);state(Number(conflicts[0]?.count)?"conflict":Number(pending[0]?.count)?"pending":"idle");}catch(error){if(navigator.onLine)state("failed");else state("offline");throw error;}finally{running=null;}})();return running;}
  return{synchronize,stop(){stopped=true;},resume(){stopped=false;return synchronize();}};
}
