import { execute, query, transaction } from "./database";
import type { SqlStatement } from "./schema";

export type SyncVisualState="idle"|"updating"|"offline"|"pending"|"conflict"|"failed";
export type SyncTransport=(path:string,init?:RequestInit)=>Promise<unknown>;
type RemoteEntity={entity_type:string;entity_id:string;entity_version:number;payload_json:string|null;deleted_at?:string|null;operation?:"upsert"|"delete";occurred_at?:string};
type Bootstrap={academicContextKey:string;cursor:string;entities:RemoteEntity[]};
type Pull={academicContextKey:string;cursor:string;hasMore:boolean;changes:Array<RemoteEntity&{sequence:number}>};
type Outbox={mutation_id:string;entity_type:string;entity_local_id:string;payload_json:string;endpoint:string|null;expected_json:string|null;predecessor_mutation_id:string|null;attempts:number;base_server_version:number|null};

const endpointFor:Record<string,string>={progress:"/api/progress",planner_task:"/api/planner/tasks",note:"/api/notes",focus_session:"/api/study/timer"};
const tableFor:Record<string,string>={progress:"progress_records",planner_task:"planner_items",note:"notes",focus_session:"study_sessions"};
const now=()=>new Date().toISOString();
const parse=(value:string|null)=>{try{return value?JSON.parse(value) as Record<string,unknown>:{};}catch{return {};}};
const localId=(accountId:string,type:string,id:string)=>`${accountId}:${type}:${id}`;

function applyEntity(accountId:string,contextKey:string,entity:RemoteEntity):SqlStatement[]{
  const table=tableFor[entity.entity_type];if(!table)return[];
  const id=localId(accountId,entity.entity_type,entity.entity_id);const payload=parse(entity.payload_json);const timestamp=entity.occurred_at||now();
  if(entity.operation==="delete"||entity.deleted_at)return[
    {sql:`UPDATE ${table} SET deleted_at=?,server_version=?,local_state='synced',updated_at=? WHERE account_id=? AND server_id=?`,args:[entity.deleted_at||timestamp,entity.entity_version,timestamp,accountId,entity.entity_id]},
    {sql:"INSERT INTO tombstones(account_id,entity_type,server_id,server_version,deleted_at) VALUES(?,?,?,?,?) ON CONFLICT(account_id,entity_type,server_id) DO UPDATE SET server_version=excluded.server_version,deleted_at=excluded.deleted_at",args:[accountId,entity.entity_type,entity.entity_id,entity.entity_version,entity.deleted_at||timestamp]},
  ];
  const common=[entity.entity_id,entity.entity_version,accountId,contextKey,JSON.stringify(payload),timestamp,timestamp,id];
  if(entity.entity_type==="progress")return[{sql:"INSERT INTO progress_records(server_id,server_version,account_id,academic_context_key,payload_json,created_at,updated_at,local_id,subject_id,chapter_id,stage,understanding) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET server_version=excluded.server_version,payload_json=excluded.payload_json,updated_at=excluded.updated_at,deleted_at=NULL,local_state='synced'",args:[...common,payload.subjectId??null,payload.chapterId??entity.entity_id,payload.stage??null,payload.understanding??null]}];
  if(entity.entity_type==="planner_task")return[{sql:"INSERT INTO planner_items(server_id,server_version,account_id,academic_context_key,payload_json,created_at,updated_at,local_id,item_kind,title,due_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET server_version=excluded.server_version,payload_json=excluded.payload_json,title=excluded.title,due_at=excluded.due_at,completed_at=excluded.completed_at,updated_at=excluded.updated_at,deleted_at=NULL,local_state='synced'",args:[...common,"task",String(payload.title||"Task"),payload.dueAt??null,payload.completedAt??null]}];
  if(entity.entity_type==="note")return[{sql:"INSERT INTO notes(server_id,server_version,account_id,academic_context_key,created_at,updated_at,local_id,title,body_text,subject_id,chapter_id) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET server_version=excluded.server_version,title=excluded.title,body_text=excluded.body_text,updated_at=excluded.updated_at,deleted_at=NULL,local_state='synced'",args:[entity.entity_id,entity.entity_version,accountId,contextKey,timestamp,timestamp,id,String(payload.title||"Note"),String(payload.body||payload.bodyHtml||""),payload.subjectId??null,payload.chapterId??null]}];
  return[{sql:"INSERT INTO study_sessions(server_id,server_version,account_id,academic_context_key,payload_json,created_at,updated_at,local_id,started_at,ended_at,duration_seconds,subject_id,chapter_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(local_id) DO UPDATE SET server_version=excluded.server_version,payload_json=excluded.payload_json,updated_at=excluded.updated_at,local_state='synced'",args:[...common,String(payload.startedAt||timestamp),payload.endedAt??null,Number(payload.durationSeconds||0),payload.subjectId??null,payload.chapterId??null]}];
}

async function commitPage(accountId:string,contextKey:string,cursor:string,entities:RemoteEntity[]){
  const statements=entities.flatMap(entity=>applyEntity(accountId,contextKey,entity));
  statements.push({sql:"INSERT INTO sync_cursors(account_id,scope,cursor,updated_at) VALUES(?,?,?,?) ON CONFLICT(account_id,scope) DO UPDATE SET cursor=excluded.cursor,updated_at=excluded.updated_at",args:[accountId,contextKey,cursor,now()]});
  await transaction(statements);
}

export function conflictPolicy(type:string){return ({progress:"merge-independent-stages",planner_task:"field-review",note:"retain-both",focus_session:"immutable-client-id",read_state:"greatest-sequence",notification:"monotonic-read",profile:"explicit-review"} as Record<string,string>)[type]||"explicit-review";}

export function createSyncCoordinator(input:{accountId:string;transport:SyncTransport;onState?:(state:SyncVisualState)=>void}){
  let running:Promise<void>|null=null;let stopped=false;const state=(value:SyncVisualState)=>input.onState?.(value);
  async function push(contextKey:string){
    const rows=await query<Outbox>("SELECT mutation_id,entity_type,entity_local_id,payload_json,endpoint,expected_json,predecessor_mutation_id,attempts,base_server_version FROM mutation_outbox WHERE account_id=? AND status IN ('pending','failed') AND (next_attempt_at IS NULL OR next_attempt_at<=?) ORDER BY created_at LIMIT 50",[input.accountId,now()]);if(!rows.length)return;
    const mutations=rows.map(row=>({mutationId:row.mutation_id,contextKey,endpoint:row.endpoint||endpointFor[row.entity_type],body:parse(row.payload_json),expected:row.expected_json?parse(row.expected_json):null,predecessor:row.predecessor_mutation_id,baseVersion:row.base_server_version}));
    try{const response=await input.transport("/api/v1/sync/push",{method:"POST",body:JSON.stringify({mutations})}) as {results:Array<{mutationId:string;status:string;response?:unknown}>};for(const result of response.results){const row=rows.find(item=>item.mutation_id===result.mutationId);if(result.status==="applied")await execute("DELETE FROM mutation_outbox WHERE account_id=? AND mutation_id=?",[input.accountId,result.mutationId]);else if(result.status==="conflict"){await transaction([{sql:"UPDATE mutation_outbox SET status='conflict',last_error='conflict',updated_at=? WHERE account_id=? AND mutation_id=?",args:[now(),input.accountId,result.mutationId]},{sql:"INSERT OR IGNORE INTO conflicts(conflict_id,account_id,entity_type,entity_local_id,local_json,server_json,baseline_version,created_at) VALUES(?,?,?,?,?,?,0,?)",args:[crypto.randomUUID(),input.accountId,row?.entity_type||"unknown",row?.entity_local_id||"unknown",row?.payload_json||"{}",JSON.stringify(result.response||{}),now()]}]);}else if(result.status==="blocked")await execute("UPDATE mutation_outbox SET status='failed',last_error='dependency_conflict',updated_at=? WHERE account_id=? AND mutation_id=?",[now(),input.accountId,result.mutationId]);else{const attempts=(row?.attempts||0)+1;const delay=Math.min(3600,Math.pow(2,attempts)*5)*(0.75+Math.random()*0.5);await execute("UPDATE mutation_outbox SET status='failed',attempts=?,next_attempt_at=?,last_error='retryable',updated_at=? WHERE account_id=? AND mutation_id=?",[attempts,new Date(Date.now()+delay*1000).toISOString(),now(),input.accountId,result.mutationId]);}}}catch(error){state("offline");throw error;}
  }
  async function synchronize(){if(stopped)return;if(running)return running;running=(async()=>{state("updating");try{let cursor=(await query<{cursor:string|null}>("SELECT cursor FROM sync_cursors WHERE account_id=? ORDER BY updated_at DESC LIMIT 1",[input.accountId]))[0]?.cursor;let contextKey:string;if(!cursor){const bootstrap=await input.transport("/api/v1/sync/bootstrap") as Bootstrap;contextKey=bootstrap.academicContextKey;await commitPage(input.accountId,contextKey,bootstrap.cursor,bootstrap.entities);cursor=bootstrap.cursor;}else{const scope=(await query<{scope:string}>("SELECT scope FROM sync_cursors WHERE account_id=? ORDER BY updated_at DESC LIMIT 1",[input.accountId]))[0];contextKey=scope.scope;}await push(contextKey);let more=true;while(more){const delta=await input.transport(`/api/v1/sync/pull?context=${encodeURIComponent(contextKey)}&cursor=${encodeURIComponent(cursor||"0")}`) as Pull;if(delta.academicContextKey!==contextKey)throw new Error("Academic context changed during synchronization.");await commitPage(input.accountId,contextKey,delta.cursor,delta.changes);cursor=delta.cursor;more=delta.hasMore;}const conflicts=await query<{count:number}>("SELECT COUNT(*) AS count FROM conflicts WHERE account_id=? AND resolved_at IS NULL",[input.accountId]);const pending=await query<{count:number}>("SELECT COUNT(*) AS count FROM mutation_outbox WHERE account_id=?",[input.accountId]);state(Number(conflicts[0]?.count)?"conflict":Number(pending[0]?.count)?"pending":"idle");}catch(error){if(navigator.onLine)state("failed");else state("offline");throw error;}finally{running=null;}})();return running;}
  return{synchronize,stop(){stopped=true;},resume(){stopped=false;return synchronize();}};
}
