import "server-only";
import { getD1RuntimeDatabase, type D1DatabaseLike } from "@/lib/data/d1/client";
import type { AppRole } from "@/lib/authorization/roles";

type Severity="info"|"warning"|"critical";
type Finding={checkKey:string;severity:Severity;scope:string;summary:string;evidence:Record<string,unknown>;resolution:string;preview?:string;safeFix?:"stale_job_fail"};
type Actor={userId:string;role:AppRole};
type Check={key:string;run:(db:D1DatabaseLike)=>Promise<Finding[]>};
const count=async(db:D1DatabaseLike,sql:string)=>(await db.prepare(sql).first<{count:number}>())?.count??0;
const one=(key:string,severity:Severity,scope:string,summary:string,evidence:Record<string,unknown>,resolution:string,preview?:string,safeFix?:"stale_job_fail"):Finding=>({checkKey:key,severity,scope,summary,evidence,resolution,preview,safeFix});

export const CONSISTENCY_CHECK_KEYS=["academic_scope_leakage","orphaned_academic_records","semantic_duplicates","historical_marked_current","exam_mapping_conflicts","impossible_progress","navigation_entitlement_disagreement","feature_definition_conflicts","stale_offline_and_guest_migrations","unavailable_notification_targets","ownership_omissions","unbounded_query_guard","background_job_heartbeats","admin_audit_omissions"] as const;

const checks:Check[]=[
 {key:"academic_scope_leakage",run:async db=>{const n=await count(db,`SELECT COUNT(*) count FROM academic_content_mappings m LEFT JOIN subjects s ON s.id=m.subject_id LEFT JOIN course_groups g ON g.id=m.group_id WHERE m.mapping_status='mapped' AND (s.id IS NULL OR s.level_id<>m.level_id OR (m.group_id IS NOT NULL AND (g.id IS NULL OR s.group_id<>m.group_id)))`);return n?[one("academic_scope_leakage","critical","academic mappings",`${n} mapped records cross their canonical level or group.`,{count:n},"Quarantine each mapping and resolve it to one canonical hierarchy.")]:[];}},
 {key:"orphaned_academic_records",run:async db=>{const n=await count(db,`SELECT COUNT(*) count FROM chapters c LEFT JOIN subjects s ON s.id=c.subject_id LEFT JOIN syllabus_versions v ON v.id=c.syllabus_version_id WHERE s.id IS NULL OR v.id IS NULL OR c.module_id IS NULL`);return n?[one("orphaned_academic_records","critical","chapters",`${n} academic records have a missing parent.`,{count:n},"Restore the parent reference or quarantine the record before publishing.")]:[];}},
 {key:"semantic_duplicates",run:async db=>{const n=await count(db,`SELECT COUNT(*) count FROM academic_duplicate_candidates WHERE status='open'`);return n?[one("semantic_duplicates","warning","academic catalogue",`${n} possible semantic duplicates await review.`,{count:n},"Review and merge aliases without rewriting stable identifiers.")]:[];}},
 {key:"historical_marked_current",run:async db=>{const n=await count(db,`SELECT COUNT(*) count FROM academic_content_mappings m JOIN syllabus_versions v ON v.id=m.syllabus_version_id WHERE m.mapping_status='mapped' AND v.status NOT IN ('current','active','published')`);return n?[one("historical_marked_current","critical","student content",`${n} current mappings point at historical syllabi.`,{count:n},"Mark the mapping historical or remap it to the published syllabus.")]:[];}},
 {key:"exam_mapping_conflicts",run:async db=>{const n=await count(db,`SELECT COUNT(*) count FROM exam_attempts WHERE (start_date IS NULL)<>(end_date IS NULL) OR (start_date IS NOT NULL AND end_date<start_date)`);return n?[one("exam_mapping_conflicts","critical","exam attempts",`${n} attempts have missing or conflicting date windows.`,{count:n},"Review the official or admin date source and publish a valid from–till window.")]:[];}},
 {key:"impossible_progress",run:async db=>{const n=await count(db,`SELECT COUNT(*) count FROM chapter_progress WHERE (revision_1_at IS NOT NULL AND completed_at IS NULL) OR (revision_2_at IS NOT NULL AND revision_1_at IS NULL) OR (test_2_at IS NOT NULL AND test_1_at IS NULL)`);return n?[one("impossible_progress","warning","student progress",`${n} progress rows contain impossible stage ordering.`,{count:n},"Rebuild the materialized row from immutable progress events.")]:[];}},
 {key:"navigation_entitlement_disagreement",run:async db=>{const n=await count(db,`SELECT COUNT(*) count FROM plan_policy_pages p LEFT JOIN plan_policy_versions v ON v.id=p.policy_version_id WHERE v.id IS NULL`);return n?[one("navigation_entitlement_disagreement","critical","plans and navigation",`${n} page policies have no parent policy.`,{count:n},"Correct the draft policy and preview navigation before publication.")]:[];}},
 {key:"feature_definition_conflicts",run:async db=>{const n=await count(db,`SELECT COUNT(*) count FROM plan_policy_features f LEFT JOIN plan_policy_pages p ON p.policy_version_id=f.policy_version_id AND p.page_key=f.page_key WHERE p.page_key IS NULL OR f.quantity_limit<0 OR f.time_limit_minutes<0 OR f.storage_limit_bytes<0 OR f.file_size_limit_bytes<0`);return n?[one("feature_definition_conflicts","critical","feature catalogue",`${n} feature definitions are missing a page or contain contradictory limits.`,{count:n},"Repair the draft Plan → Page → Feature definition before publication.")]:[];}},
 {key:"stale_offline_and_guest_migrations",run:async db=>{const n=await count(db,`SELECT COUNT(*) count FROM guest_account_migrations WHERE status='running' AND updated_at<datetime('now','-30 minutes')`);return n?[one("stale_offline_and_guest_migrations","warning","guest migrations",`${n} guest migrations have stopped before completion.`,{count:n},"Resume from the durable mutation receipts; do not discard guest data.")]:[];}},
 {key:"unavailable_notification_targets",run:async db=>{const n=await count(db,`SELECT COUNT(*) count FROM in_app_notifications WHERE action_href IS NOT NULL AND (action_href NOT LIKE '/%' OR action_href LIKE '//%')`);return n?[one("unavailable_notification_targets","warning","notifications",`${n} notifications link outside the available route contract.`,{count:n},"Correct the template target and supersede affected notifications.")]:[];}},
 {key:"ownership_omissions",run:async db=>{const n=await count(db,`SELECT (SELECT COUNT(*) FROM notes WHERE user_id IS NULL)+(SELECT COUNT(*) FROM uploaded_resources WHERE owner_user_id IS NULL) count`);return n?[one("ownership_omissions","critical","private student records",`${n} private records have no owner.`,{count:n},"Recover ownership from immutable creation evidence; destructive reassignment requires authorization.")]:[];}},
 {key:"unbounded_query_guard",run:async()=>[]},
 {key:"background_job_heartbeats",run:async db=>{const n=await count(db,`SELECT COUNT(*) count FROM background_jobs WHERE status='running' AND updated_at<datetime('now','-15 minutes')`);return n?[one("background_job_heartbeats","critical","background jobs",`${n} running jobs have a stale heartbeat.`,{count:n,olderThanMinutes:15},"Fail only the stale running rows so their normal retry policy can recover them.",`UPDATE background_jobs SET status='failed', finished_at=CURRENT_TIMESTAMP, last_error='Phase 10: stale heartbeat', updated_at=CURRENT_TIMESTAMP WHERE status='running' AND updated_at<datetime('now','-15 minutes')`,"stale_job_fail")]:[];}},
 {key:"admin_audit_omissions",run:async db=>{const n=await count(db,`SELECT COUNT(*) count FROM admin_control_requests r LEFT JOIN admin_audit_events a ON a.target_id=r.target_id AND a.actor_user_id=r.actor_user_id WHERE a.id IS NULL`);return n?[one("admin_audit_omissions","critical","admin mutations",`${n} control-centre mutations have no matching immutable audit event.`,{count:n},"Investigate the transaction boundary. Do not fabricate historical audit records.")]:[];}},
];

export async function runConsistencyScan(input:{trigger:"scheduled"|"manual"|"deployment";actorUserId?:string}){
 const db=getD1RuntimeDatabase(),id=crypto.randomUUID();await db.prepare("INSERT INTO consistency_scan_runs(id,trigger_type,started_by) VALUES(?1,?2,?3)").bind(id,input.trigger,input.actorUserId??null).run();const findings:Finding[]=[];
 try{for(const check of checks){try{findings.push(...await check.run(db));}catch(error){findings.push(one(check.key,"critical","scanner",`Check ${check.key} could not complete.`,{error:error instanceof Error?error.message:"Unknown check failure"},"Repair the check or schema mismatch before trusting the health report."));}}
  if(findings.length)await db.batch(findings.map(f=>db.prepare(`INSERT INTO consistency_findings(id,scan_id,fingerprint,check_key,severity,affected_scope,summary,evidence_json,proposed_resolution,repair_preview,safe_auto_fix) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11)`).bind(crypto.randomUUID(),id,`${f.checkKey}:${JSON.stringify(f.evidence)}`,f.checkKey,f.severity,f.scope,f.summary,JSON.stringify(f.evidence),f.resolution,f.preview??null,f.safeFix??null)));
  await db.prepare("UPDATE consistency_scan_runs SET status='completed',checks_total=?1,findings_total=?2,critical_total=?3,completed_at=CURRENT_TIMESTAMP WHERE id=?4").bind(checks.length,findings.length,findings.filter(f=>f.severity==='critical').length,id).run();return{id,findings:findings.length,critical:findings.filter(f=>f.severity==='critical').length};
 }catch(error){await db.prepare("UPDATE consistency_scan_runs SET status='failed',error_summary=?1,completed_at=CURRENT_TIMESTAMP WHERE id=?2").bind(error instanceof Error?error.message:"Scan failed",id).run();throw error;}
}

export async function getConsistencyReport(){const db=getD1RuntimeDatabase();const [run,rows]=await Promise.all([db.prepare("SELECT * FROM consistency_scan_runs ORDER BY started_at DESC LIMIT 1").first<Record<string,unknown>>(),db.prepare("SELECT * FROM consistency_findings WHERE state<>'resolved' ORDER BY CASE severity WHEN 'critical' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END,created_at DESC LIMIT 200").all<Record<string,unknown>>()]);return{run,findings:rows.results??[]};}
export async function acknowledgeFinding(input:{id:string;note:string;actor:Actor}){const note=input.note.trim();if(note.length<8)throw new Error("Add an acknowledgement note of at least 8 characters.");await getD1RuntimeDatabase().prepare("UPDATE consistency_findings SET state='acknowledged',acknowledged_by=?1,acknowledged_at=CURRENT_TIMESTAMP,acknowledgement_note=?2 WHERE id=?3 AND state='open'").bind(input.actor.userId,note.slice(0,1000),input.id).run();}
export async function applySafeRepair(input:{id:string;idempotencyKey:string;actor:Actor}){const db=getD1RuntimeDatabase();const prior=await db.prepare("SELECT result_json FROM consistency_repair_receipts WHERE idempotency_key=?1").bind(input.idempotencyKey).first<{result_json:string}>();if(prior)return JSON.parse(prior.result_json);const finding=await db.prepare("SELECT safe_auto_fix,state FROM consistency_findings WHERE id=?1").bind(input.id).first<{safe_auto_fix:string|null;state:string}>();if(finding?.safe_auto_fix!=="stale_job_fail"||finding.state==='resolved')throw new Error("This finding has no available safe repair.");const result={repair:"stale_job_fail",findingId:input.id};const rows=await db.batch([db.prepare("UPDATE background_jobs SET status='failed',finished_at=CURRENT_TIMESTAMP,last_error='Phase 10: stale heartbeat',updated_at=CURRENT_TIMESTAMP WHERE status='running' AND updated_at<datetime('now','-15 minutes')"),db.prepare("UPDATE consistency_findings SET state='resolved',resolved_at=CURRENT_TIMESTAMP WHERE id=?1").bind(input.id),db.prepare("INSERT INTO consistency_repair_receipts(idempotency_key,finding_id,repair_key,actor_user_id,result_json) VALUES(?1,?2,'stale_job_fail',?3,?4)").bind(input.idempotencyKey,input.id,input.actor.userId,JSON.stringify(result)),db.prepare(`INSERT INTO admin_audit_events(id,actor_user_id,actor_role,capability,action,target_type,target_id,reason,new_value,trace_id,reversible,created_at) VALUES(?1,?2,?3,'system.recovery','consistency.repair','consistency_finding',?4,'Idempotent stale-heartbeat recovery',?5,?6,0,?7)`).bind(crypto.randomUUID(),input.actor.userId,input.actor.role,input.id,JSON.stringify(result),crypto.randomUUID(),new Date().toISOString())]);if(rows.some(r=>r.success===false))throw new Error("Safe repair was not applied atomically.");return result;}
export async function assertNoCriticalConsistencyBlockers(){const n=await count(getD1RuntimeDatabase(),`SELECT COUNT(*) count FROM consistency_findings f JOIN consistency_scan_runs r ON r.id=f.scan_id WHERE f.severity='critical' AND f.state='open' AND r.id=(SELECT id FROM consistency_scan_runs WHERE status='completed' ORDER BY started_at DESC LIMIT 1)`);if(n)throw new Error(`Publishing blocked by ${n} open critical consistency finding${n===1?'':'s'}. Review /admin/consistency.`);}
