import {acknowledgeCommunityMessage,applyCommunityEvent,failCommunityMessage,pendingCommunityMessages,pruneCommunityHistory,retryCommunityMessage,storeCommunityChannels,storeCommunityPage,type RemoteCommunityMessage} from "../../../packages/mobile-data/src";
import {parseCommunityRealtimeEvent} from "../../../lib/community/realtime-events";

type Transport=(path:string,init?:RequestInit)=>Promise<unknown>;
const POLL_MS=5000;

export function createNativeCommunityCoordinator(input:{accountId:string;transport:Transport;onChanged:()=>void}){
  let stopped=false,timer:number|null=null,socket:WebSocket|null=null,activeChannel:string|null=null,lastSequence=0;
  const schedule=()=>{if(!stopped){if(timer!==null)window.clearTimeout(timer);timer=window.setTimeout(()=>void reconcile(),POLL_MS);}};
  async function channels(){const result=await input.transport("/api/v1/community/channels") as {channels:Array<{key:string;title:string;latestSequence:number|null;unreadCount:number;latestAt:string|null;latestBody:string|null}>};await storeCommunityChannels(input.accountId,result.channels||[]);input.onChanged();return result.channels||[];}
  async function deliver(channel:string,clientMessageId:string,body:string){await retryCommunityMessage(input.accountId,clientMessageId);const result=await input.transport(`/api/v1/community/channels/${encodeURIComponent(channel)}/messages`,{method:"POST",body:JSON.stringify({body,clientMessageId})}) as {message:RemoteCommunityMessage};await acknowledgeCommunityMessage(input.accountId,clientMessageId,result.message);lastSequence=Math.max(lastSequence,result.message.sequence||0);}
  async function drain(){for(const item of await pendingCommunityMessages(input.accountId)){try{await deliver(item.channelKey,item.clientMessageId,item.body);}catch{await failCommunityMessage(input.accountId,item.clientMessageId);}}}
  async function reconcile(){if(stopped||!navigator.onLine||!activeChannel){schedule();return;}try{await drain();let cursor=lastSequence,more=true;while(more){const result=await input.transport(`/api/v1/community/channels/${encodeURIComponent(activeChannel)}/messages?afterSequence=${cursor}&limit=100`) as {messages:RemoteCommunityMessage[];latestSequence:number;hasMore:boolean};await storeCommunityPage(input.accountId,activeChannel,result.messages||[],result.latestSequence);cursor=Math.max(cursor,...(result.messages||[]).map(item=>item.sequence));more=Boolean(result.hasMore&&cursor<result.latestSequence);}lastSequence=cursor;const recent=await input.transport(`/api/v1/community/channels/${encodeURIComponent(activeChannel)}/messages?beforeSequence=${lastSequence+1}&limit=50`) as {messages:RemoteCommunityMessage[];latestSequence:number};await storeCommunityPage(input.accountId,activeChannel,recent.messages||[],recent.latestSequence);await pruneCommunityHistory(input.accountId,activeChannel);input.onChanged();}finally{schedule();}}
  function connect(channel:string){socket?.close();if(typeof WebSocket==="undefined"||!navigator.onLine)return;const protocol=location.protocol==="https:"?"wss:":"ws:";try{socket=new WebSocket(`${protocol}//${location.host}/api/community/channels/${encodeURIComponent(channel)}/realtime`);socket.addEventListener("message",event=>{if(typeof event.data!=="string")return;let parsed:unknown;try{parsed=JSON.parse(event.data);}catch{return;}const typed=parseCommunityRealtimeEvent(parsed);if(typed&&"sequence" in typed){void applyCommunityEvent(input.accountId,channel,typed).then(changed=>{if(changed){lastSequence=Math.max(lastSequence,typed.sequence);input.onChanged();}});}else void reconcile();});socket.addEventListener("close",()=>{socket=null;schedule();});socket.addEventListener("error",()=>socket?.close());}catch{schedule();}}
  async function open(channel:string,storedSequence:number){activeChannel=channel;lastSequence=storedSequence;connect(channel);await reconcile();}
  async function older(beforeSequence:number){if(!activeChannel||!navigator.onLine)return;const result=await input.transport(`/api/v1/community/channels/${encodeURIComponent(activeChannel)}/messages?beforeSequence=${beforeSequence}&limit=50`) as {messages:RemoteCommunityMessage[];latestSequence:number};await storeCommunityPage(input.accountId,activeChannel,result.messages||[],result.latestSequence);input.onChanged();}
  async function send(clientMessageId:string,body:string){if(!activeChannel)return;try{await deliver(activeChannel,clientMessageId,body);input.onChanged();}catch(error){await failCommunityMessage(input.accountId,clientMessageId);input.onChanged();throw error;}}
  void channels().catch(()=>undefined);
  return{open,older,send,refreshChannels:channels,stop(){stopped=true;if(timer!==null)window.clearTimeout(timer);socket?.close();}};
}
