import { classifyResource, detectAttemptKeys, detectLevels, detectPublishedDate, normalizeComparable } from "./classify";
import { extractOfficialLinks } from "./html";
import type { IcaiLevelCode, IcaiSourceConfig, ParsedExamEvent, ParsedIcaiResource, ParsedSourcePayload } from "./types";

type SubjectLookup = { id: string; title: string; levelCode: IcaiLevelCode };
const GENERIC_NAV = /^(home|about|contact|students?|members?|login|search|read more|click here|view all|next|previous|committees?|departments?)$/i;
const ACADEMIC_SIGNAL = /\b(exam|examination|rtp|revision test|mtp|mock test|study material|statutory|amendment|question paper|suggested answer|date sheet|schedule|announcement|notification|corrigendum|addendum)\b/i;
function matchedSubjects(text: string, subjects: SubjectLookup[]) { const normalized = normalizeComparable(text); return subjects.filter((subject) => { const title = normalizeComparable(subject.title); return title.length >= 8 && normalized.includes(title); }).map((subject) => subject.id); }
function shouldIncludeLink(title: string, url: string, source: IcaiSourceConfig) { if (GENERIC_NAV.test(title.trim()) || url === source.officialUrl) return false; const parsed = new URL(url); const isDocument = /\.(pdf|docx?|xlsx?|zip)$/i.test(parsed.pathname) || parsed.hostname.toLowerCase().startsWith("resource.cdn."); if (source.adapterKey === "resource_hub") return isDocument || ACADEMIC_SIGNAL.test(`${title} ${url}`); return parsed.pathname.includes("/post/") || isDocument || ACADEMIC_SIGNAL.test(title); }
function parsedEventFromTitle(title: string, url: string, attemptKeys: string[], levels: IcaiLevelCode[], subjectIds: string[]): ParsedExamEvent[] { if (!/\b(exam|examination|reschedul|postpon|date sheet|time table|timetable)\b/i.test(title)) return []; const date = detectPublishedDate(title); if (!date || attemptKeys.length !== 1 || levels.length !== 1) return []; return [{ attemptKey: attemptKeys[0], levelCode: levels[0], eventType: /\b(date sheet|schedule|time table|timetable)\b/i.test(title) ? "schedule_release" : "exam_paper", title, eventDate: date, startTime: null, endTime: null, subjectId: subjectIds.length === 1 ? subjectIds[0] : null, sourceUrl: url, confidence: 0.82 }]; }
export function parseOfficialSource(html: string, source: IcaiSourceConfig, subjects: SubjectLookup[]): ParsedSourcePayload {
  const links = extractOfficialLinks(html, source.officialUrl).filter((link) => shouldIncludeLink(link.title, link.url, source)); const resources: ParsedIcaiResource[] = []; const attempts = new Map<string, { attemptKey: string; label: string; levelCodes: IcaiLevelCode[]; startDate: null; endDate: null; confidence: number }>(); const events: ParsedExamEvent[] = [];
  for (const link of links) { const combined = `${link.title} ${link.url}`; const levels = detectLevels(combined, source.levelCodes); const attemptKeys = /\b(exam|examination|attempt|rtp|revision test|mtp|mock test|question paper|suggested answer|date sheet|schedule)\b/i.test(combined) ? detectAttemptKeys(combined) : []; const subjectIds = matchedSubjects(combined, subjects); const type = classifyResource(link.title, link.url); resources.push({ title: link.title, officialUrl: link.url, summary: null, resourceType: type, levelCodes: levels, attemptKeys, subjectIds, publishedOn: detectPublishedDate(link.title) }); for (const attemptKey of attemptKeys) { const identity = `${attemptKey}:${levels.slice().sort().join(",")}`; if (!attempts.has(identity)) { const date = new Date(`${attemptKey}-01T00:00:00Z`); const label = Number.isNaN(date.getTime()) ? attemptKey : new Intl.DateTimeFormat("en-IN", { month: "long", year: "numeric", timeZone: "UTC" }).format(date); attempts.set(identity, { attemptKey, label, levelCodes: levels, startDate: null, endDate: null, confidence: 0.8 }); } } events.push(...parsedEventFromTitle(link.title, link.url, attemptKeys, levels, subjectIds)); }
  return { resources, attempts: [...attempts.values()], events };
}
