import "server-only";

import { getD1RuntimeDatabase, type D1DatabaseLike } from "@/lib/data/d1/client";

export type IcaiReviewDecision = "approve" | "reject";
type ReviewRow = { id:string; change_event_id:number; source_id:string; entity_type:string; entity_id:string; proposed_patch:string|Record<string,unknown>; status:string };

export function normalizeIcaiReviewDecision(value:unknown):IcaiReviewDecision|null {
  const raw=String(value??"").trim().toLowerCase();
  if(raw==="approve"||raw==="approved")return "approve";
  if(raw==="reject"||raw==="rejected")return "reject";
  return null;
}

function patchObject(value:unknown):Record<string,unknown>{if(value&&typeof value==="object"&&!Array.isArray(value))return value as Record<string,unknown>;if(typeof value==="string"){try{const parsed=JSON.parse(value) as unknown;return parsed&&typeof parsed==="object"&&!Array.isArray(parsed)?parsed as Record<string,unknown>:{};}catch{return {};}}return {};}
function text(value:unknown,fallback:string){return typeof value==="string"&&value.length?value:fallback;}
function nullableText(value:unknown){return typeof value==="string"&&value.length?value:null;}
function jsonValue(value:unknown,fallback:unknown){return JSON.stringify(value&&typeof value==="object"?value:fallback??{});}

async function releaseClaim(db:D1DatabaseLike,id:string){await db.prepare("UPDATE icai_review_queue SET status='pending',reviewed_by=NULL,reviewed_at=NULL,decision_notes=NULL,updated_at=?1 WHERE id=?2 AND status='applying'").bind(new Date().toISOString(),id).run();}

async function claimReview(db:D1DatabaseLike,id:string,reviewerUserId:string,notes:string|null){const now=new Date().toISOString();const row=await db.prepare("UPDATE icai_review_queue SET status='applying',reviewed_by=?1,reviewed_at=?2,decision_notes=?3,updated_at=?2 WHERE id=?4 AND status='pending' RETURNING id,change_event_id,source_id,entity_type,entity_id,proposed_patch,status").bind(reviewerUserId,now,notes,id).first<ReviewRow>();if(row)return row;const existing=await db.prepare("SELECT status FROM icai_review_queue WHERE id=?1").bind(id).first<{status:string}>();if(!existing)throw new Error("ICAI review item was not found.");throw new Error(`ICAI review item is already ${existing.status}.`);}

async function approvedPatchStatement(db:D1DatabaseLike,review:ReviewRow,now:string){const patch=patchObject(review.proposed_patch);if(review.entity_type==="exam_attempt"){const current=await db.prepare("SELECT * FROM exam_attempts WHERE id=?1").bind(review.entity_id).first<Record<string,unknown>>();if(!current)throw new Error("Reviewed exam attempt no longer exists.");const startDate=nullableText(patch.start_date)??nullableText(current.start_date);const endDate=nullableText(patch.end_date)??nullableText(current.end_date);return db.prepare("UPDATE exam_attempts SET start_date=?1,end_date=?2,label=?3,status=?4,verification_status='verified',verification_method='official_sync',source_id=?5,source_url=?6,source_snapshot_id=?7,content_hash=?8,metadata=?9,last_seen_at=?10,last_changed_at=?10,updated_at=?10 WHERE id=?11").bind(startDate,endDate,text(patch.label,String(current.label??"")),text(patch.status,String(current.status??"scheduled")),review.source_id,text(patch.source_url,String(current.source_url??"")),patch.source_snapshot_id??current.source_snapshot_id??null,text(patch.content_hash,String(current.content_hash??"")),jsonValue(patch.metadata,current.metadata),now,review.entity_id);}
  if(review.entity_type==="exam_event"){const current=await db.prepare("SELECT * FROM exam_events WHERE id=?1").bind(review.entity_id).first<Record<string,unknown>>();if(!current)throw new Error("Reviewed exam event no longer exists.");const eventDate=text(patch.event_date,String(current.event_date??""));const startTime=Object.hasOwn(patch,"start_time")?nullableText(patch.start_time):nullableText(current.start_time);const endTime=Object.hasOwn(patch,"end_time")?nullableText(patch.end_time):nullableText(current.end_time);const subjectId=Object.hasOwn(patch,"subject_id")?nullableText(patch.subject_id):nullableText(current.subject_id);return db.prepare("UPDATE exam_events SET event_date=?1,start_time=?2,end_time=?3,title=?4,subject_id=?5,verification_status='verified',source_id=?6,source_url=?7,source_snapshot_id=?8,content_hash=?9,metadata=?10,last_seen_at=?11,last_changed_at=?11,updated_at=?11 WHERE id=?12").bind(eventDate,startTime,endTime,text(patch.title,String(current.title??"")),subjectId,review.source_id,text(patch.source_url,String(current.source_url??"")),patch.source_snapshot_id??current.source_snapshot_id??null,text(patch.content_hash,String(current.content_hash??"")),jsonValue(patch.metadata,current.metadata),now,review.entity_id);}
  throw new Error(`Unsupported ICAI review entity type: ${review.entity_type}`);}

export async function decideIcaiReview({reviewId,decision,reviewerUserId,notes=null,db=getD1RuntimeDatabase()}:{reviewId:string;decision:IcaiReviewDecision;reviewerUserId:string;notes?:string|null;db?:D1DatabaseLike}){if(!reviewId||!reviewerUserId)throw new Error("Review id and reviewer are required.");const review=await claimReview(db,reviewId,reviewerUserId,notes);const now=new Date().toISOString();try{const statements=[];if(decision==="approve")statements.push(await approvedPatchStatement(db,review,now));statements.push(db.prepare("UPDATE icai_review_queue SET status=?1,reviewed_by=?2,reviewed_at=?3,decision_notes=?4,updated_at=?3 WHERE id=?5 AND status='applying'").bind(decision==="approve"?"approved":"rejected",reviewerUserId,now,notes,reviewId));statements.push(db.prepare("UPDATE icai_change_events SET decision_status=?1,review_notes=?2,reviewed_by=?3,applied_at=?4 WHERE id=?5").bind(decision==="approve"?"approved":"rejected",notes,reviewerUserId,decision==="approve"?now:null,review.change_event_id));await db.batch(statements);return{ok:true,status:decision==="approve"?"approved":"rejected"};}catch(error){await releaseClaim(db,reviewId).catch(()=>undefined);throw error;}}
