interface CloudflareEnv {
  NEXT_PUBLIC_APP_NAME: string;
  NEXT_PUBLIC_APP_ENV: string;
  NEXT_PUBLIC_APP_VERSION: string;
  NEXT_PUBLIC_SUPABASE_URL?: string;
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY?: string;
  SUPABASE_SERVICE_ROLE_KEY?: string;
  ICAI_CRON_SECRET?: string;
  ICAI_SYNC_ENABLED?: string;
  ICAI_SYNC_USER_AGENT?: string;
  HEALTH_LOG_DB?: string;
}
