// The public Worker is intentionally thin: it owns OpenNext middleware/routing,
// static assets and the existing ICAI cron, then delegates dynamic SSR/API work
// to private domain Workers through Cloudflare Service Bindings.
// @ts-expect-error Generated by the OpenNext build.
import { runWithCloudflareRequestContext } from "./.open-next/cloudflare/init.js";
// @ts-expect-error Generated by the OpenNext build.
import { handler as middlewareHandler } from "./.open-next/middleware/handler.mjs";

type ServiceBinding = { fetch(request: Request): Promise<Response> };
type WorkerEnv = {
  CORE_WEB_SERVICE?: ServiceBinding;
  ADMIN_WEB_SERVICE?: ServiceBinding;
  COMMUNITY_WEB_SERVICE?: ServiceBinding;
  PLANNING_WEB_SERVICE?: ServiceBinding;
  ICAI_SYNC_SERVICE?: ServiceBinding;
  NEXT_PUBLIC_SUPABASE_URL?: string;
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY?: string;
  SUPABASE_SERVICE_ROLE_KEY?: string;
  ICAI_SYNC_ENABLED?: string;
  ICAI_SYNC_USER_AGENT?: string;
};
type WorkerContext = { waitUntil(promise: Promise<unknown>): void };
type ScheduledController = { scheduledTime: number; cron: string };

function routeService(pathname: string, env: WorkerEnv) {
  if (pathname === "/admin" || pathname.startsWith("/admin/") || pathname.startsWith("/api/admin/")) {
    return env.ADMIN_WEB_SERVICE;
  }
  if (
    pathname === "/community" || pathname.startsWith("/community/") ||
    pathname === "/notes" || pathname.startsWith("/notes/") ||
    pathname === "/resources" || pathname.startsWith("/resources/") ||
    pathname === "/updates" ||
    pathname.startsWith("/api/community/") || pathname === "/api/notes" || pathname.startsWith("/api/notes/") ||
    pathname.startsWith("/api/resources/")
  ) {
    return env.COMMUNITY_WEB_SERVICE;
  }
  if (
    pathname === "/activity" || pathname === "/analytics" || pathname.startsWith("/analytics/") ||
    pathname === "/calendar" || pathname === "/goals" ||
    pathname === "/planner" || pathname.startsWith("/planner/") ||
    pathname === "/progress" || pathname.startsWith("/progress/") ||
    pathname === "/study" || pathname.startsWith("/study/") ||
    pathname.startsWith("/subjects/") ||
    pathname.startsWith("/api/planner/") || pathname === "/api/progress" || pathname.startsWith("/api/study/")
  ) {
    return env.PLANNING_WEB_SERVICE;
  }
  return env.CORE_WEB_SERVICE;
}

function internalRequest(request: Request, env: WorkerEnv) {
  const headers = new Headers(request.headers);
  headers.set("x-ca-progress-next-internal", "ca-progress-v2-router");
  if (env.NEXT_PUBLIC_SUPABASE_URL) headers.set("x-ca-progress-supabase-url", env.NEXT_PUBLIC_SUPABASE_URL);
  if (env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY) headers.set("x-ca-progress-supabase-publishable-key", env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);
  if (env.SUPABASE_SERVICE_ROLE_KEY) headers.set("x-ca-progress-service-role", env.SUPABASE_SERVICE_ROLE_KEY);
  return new Request(request, { headers });
}

const worker = {
  fetch(request: Request, env: WorkerEnv, ctx: WorkerContext) {
    return runWithCloudflareRequestContext(request, env, ctx, async () => {
      const routed = await middlewareHandler(request, env, ctx);
      if (routed instanceof Response) return routed;
      const pathname = new URL(routed.url).pathname;
      const service = routeService(pathname, env);
      if (!service) return new Response("Application service unavailable", { status: 503 });
      return service.fetch(internalRequest(routed, env));
    });
  },
  scheduled(controller: ScheduledController, env: WorkerEnv, ctx: WorkerContext) {
    const task = (async () => {
      if (!env.ICAI_SYNC_SERVICE) throw new Error("ICAI_SYNC_SERVICE binding is missing from the Cloudflare Worker.");
      if (!env.NEXT_PUBLIC_SUPABASE_URL || !env.SUPABASE_SERVICE_ROLE_KEY) throw new Error("V2 Supabase runtime configuration is missing for scheduled ICAI sync.");
      const response = await env.ICAI_SYNC_SERVICE.fetch(new Request("https://icai-sync.internal/run", {
        method: "POST",
        headers: {
          "content-type": "application/json",
          "x-ca-progress-internal": "ca-progress-v2-web",
          "x-ca-progress-supabase-url": env.NEXT_PUBLIC_SUPABASE_URL,
          "x-ca-progress-service-role": env.SUPABASE_SERVICE_ROLE_KEY,
          "x-ca-progress-icai-user-agent": env.ICAI_SYNC_USER_AGENT || "CA Progress V2 Official ICAI Monitor/phase8",
          "x-ca-progress-icai-enabled": env.ICAI_SYNC_ENABLED || "true",
          "x-ca-progress-scheduled-at": new Date(controller.scheduledTime).toISOString(),
        },
        body: JSON.stringify({ trigger: "cron", requestedBy: null }),
      }));
      if (!response.ok) {
        const body = await response.text();
        throw new Error(`Phase 8 scheduled sync service failed (${response.status}): ${body.slice(0, 500)}`);
      }
    })();
    ctx.waitUntil(task);
  },
};

export default worker;
