import {NextResponse,type NextRequest} from "next/server";
import {createCommunityMessage} from "@/lib/community/service";
import {getPhase19CommunityDelta} from "@/lib/community/phase7";
import {MOBILE_API_HEADERS} from "@/lib/mobile/contract";
import {nativeCorsHeaders,nativeOptions} from "@/lib/auth/native-cors";
export const dynamic="force-dynamic";
const json=(request:NextRequest,data:unknown,status=200)=>NextResponse.json(data,{status,headers:{...MOBILE_API_HEADERS,...nativeCorsHeaders(request),"Cache-Control":"private, no-store"}});
export const OPTIONS=(request:NextRequest)=>nativeOptions(request);
export async function GET(request:NextRequest,{params}:{params:Promise<{channel:string}>}){const{channel}=await params;const after=Number(request.nextUrl.searchParams.get("afterSequence"));const before=Number(request.nextUrl.searchParams.get("beforeSequence"));try{return json(request,await getPhase19CommunityDelta({channelSlug:channel,afterSequence:Number.isSafeInteger(after)&&after>=0?after:undefined,beforeSequence:Number.isSafeInteger(before)&&before>0?before:undefined,limit:Number(request.nextUrl.searchParams.get("limit"))||50}));}catch(error){return json(request,{error:{code:"COMMUNITY_DELTA_FAILED",message:error instanceof Error?error.message:"Community update failed.",retryable:true}},409);}}
export async function POST(request:NextRequest,{params}:{params:Promise<{channel:string}>}){const{channel}=await params;const body=await request.json().catch(()=>null) as {body?:unknown;clientMessageId?:unknown}|null;if(!body||typeof body.body!=="string"||typeof body.clientMessageId!=="string")return json(request,{error:{code:"INVALID_MESSAGE",message:"Message and client message ID are required.",retryable:false}},400);try{const created=await createCommunityMessage({channelSlug:channel,body:body.body,clientMessageId:body.clientMessageId});const delta=await getPhase19CommunityDelta({channelSlug:channel,afterSequence:Math.max(0,created.sequence-1),limit:1});return json(request,{ok:true,clientMessageId:body.clientMessageId,message:delta.messages.find(item=>item.id===created.id)||{...created,channelId:delta.channelId,body:body.body}},201);}catch(error){return json(request,{error:{code:"MESSAGE_SEND_FAILED",message:error instanceof Error?error.message:"Message could not be sent.",retryable:true}},409);}}
