type D1Result<T = Record<string, unknown>> = { results?: T[]; success?: boolean };
type D1Statement = { bind(...values: unknown[]): D1Statement; first<T = Record<string, unknown>>(): Promise<T | null>; all<T = Record<string, unknown>>(): Promise<D1Result<T>>; run<T = Record<string, unknown>>(): Promise<D1Result<T>> };
type D1Database = { prepare(query: string): D1Statement; batch<T = Record<string, unknown>>(statements: D1Statement[]): Promise<D1Result<T>[]> };
type Env = { DB?: D1Database; RAZORPAY_KEY_ID?: string; RAZORPAY_KEY_SECRET?: string; RAZORPAY_WEBHOOK_SECRET?: string };
type InternalContext = { userId: string | null };
type PaymentEntity = { id: string; order_id: string | null; amount: number; currency: string; status: string; created_at?: number };

const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json", "cache-control": "no-store" } });
const nowIso = () => new Date().toISOString();
const id = () => crypto.randomUUID();

function database(env: Env) { if (!env.DB) throw new Error("Billing D1 binding is missing."); return env.DB; }
function requireInternal(request: Request): InternalContext {
  if (request.headers.get("x-ca-progress-internal") !== "ca-progress-v2-web") throw new Error("Internal billing service only.");
  return { userId: request.headers.get("x-ca-progress-user-id")?.trim() || null };
}
function requireProvider(env: Env) {
  const keyId = env.RAZORPAY_KEY_ID?.trim(); const keySecret = env.RAZORPAY_KEY_SECRET?.trim();
  if (!keyId || !keySecret) throw new Error("Razorpay checkout is not configured on V2 production yet.");
  return { keyId, keySecret };
}
function basicAuth(keyId: string, keySecret: string) { return `Basic ${btoa(`${keyId}:${keySecret}`)}`; }
async function razorpayJson(path: string, provider: { keyId: string; keySecret: string }, init: RequestInit = {}) {
  const headers = new Headers(init.headers); headers.set("authorization", basicAuth(provider.keyId, provider.keySecret)); headers.set("content-type", "application/json");
  const response = await fetch(`https://api.razorpay.com/v1/${path}`, { ...init, headers }); const text = await response.text(); const data = text ? JSON.parse(text) : null;
  if (!response.ok) throw new Error(data?.error?.description || `Razorpay request failed (${response.status}).`); return data;
}
async function hmacHex(secret: string, value: string) { const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(secret), { name:"HMAC",hash:"SHA-256" }, false, ["sign"]); const signature = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(value)); return [...new Uint8Array(signature)].map((byte)=>byte.toString(16).padStart(2,"0")).join(""); }
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i+=1)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
async function sha256(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(bytes)].map((byte)=>byte.toString(16).padStart(2,"0")).join("");}
async function fetchPayment(paymentId:string,provider:{keyId:string;keySecret:string}):Promise<PaymentEntity>{return await razorpayJson(`payments/${encodeURIComponent(paymentId)}`,provider) as PaymentEntity;}

function addDuration(startIso:string,value:number,unit:string){const date=new Date(startIso);if(unit==="day")date.setUTCDate(date.getUTCDate()+value);else if(unit==="week")date.setUTCDate(date.getUTCDate()+value*7);else if(unit==="month")date.setUTCMonth(date.getUTCMonth()+value);else if(unit==="year")date.setUTCFullYear(date.getUTCFullYear()+value);else if(unit==="lifetime")return null;else throw new Error("Unsupported subscription duration unit.");return date.toISOString();}

async function reconcile(env:Env,input:{orderId:string;paymentId:string;payment:PaymentEntity;source:"verify"|"webhook";eventType:string;eventKey:string}){
  const db=database(env); const order=await db.prepare("SELECT * FROM payment_orders WHERE provider_order_id=?1 LIMIT 1").bind(input.orderId).first<Record<string,unknown>>();
  if(!order) throw new Error("Payment order not found."); if(Number(order.amount_subunits)!==Number(input.payment.amount)||String(order.currency)!==input.payment.currency) throw new Error("Payment amount or currency does not match the server order.");
  const duplicate=await db.prepare("SELECT id,verified FROM payment_events WHERE provider='razorpay' AND provider_event_key=?1 LIMIT 1").bind(input.eventKey).first<Record<string,unknown>>();
  if(duplicate) return {ok:true,idempotent:true,paymentEventId:duplicate.id,granted:String(order.status)==="paid"};
  const paymentEventId=id(); const paidAt=input.payment.created_at?new Date(input.payment.created_at*1000).toISOString():nowIso(); const captured=input.payment.status==="captured"; const failed=input.payment.status==="failed";
  const eventStatement=db.prepare("INSERT INTO payment_events(id,payment_order_id,user_id,provider,source,event_type,provider_event_key,provider_order_id,provider_payment_id,provider_status,amount_subunits,currency,verified,payload,created_at) VALUES(?1,?2,?3,'razorpay',?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14)")
    .bind(paymentEventId,order.id,order.user_id,input.source,input.eventType,input.eventKey,input.orderId,input.paymentId,input.payment.status,input.payment.amount,input.payment.currency,captured?1:0,JSON.stringify({payment_status:input.payment.status,payment_id:input.paymentId,order_id:input.orderId}),nowIso());
  if(failed){await db.batch([eventStatement,db.prepare("UPDATE payment_orders SET provider_payment_id=?1,status=CASE WHEN status='paid' THEN 'paid' ELSE 'failed' END,updated_at=?2 WHERE id=?3").bind(input.paymentId,nowIso(),order.id)]);return{ok:true,idempotent:false,granted:false,providerStatus:input.payment.status};}
  if(!captured){await db.batch([eventStatement,db.prepare("UPDATE payment_orders SET provider_payment_id=?1,status=CASE WHEN status='paid' THEN 'paid' ELSE 'attempted' END,updated_at=?2 WHERE id=?3").bind(input.paymentId,nowIso(),order.id)]);return{ok:true,idempotent:false,granted:false,providerStatus:input.payment.status};}
  const already=await db.prepare("SELECT id,ends_at FROM user_subscriptions WHERE source='razorpay' AND source_order_id=?1 LIMIT 1").bind(input.orderId).first<Record<string,unknown>>();
  if(already){await db.batch([eventStatement,db.prepare("UPDATE payment_orders SET provider_payment_id=?1,status='paid',paid_at=COALESCE(paid_at,?2),updated_at=?2 WHERE id=?3").bind(input.paymentId,paidAt,order.id)]);return{ok:true,idempotent:false,granted:true,alreadyGranted:true,subscriptionId:already.id};}
  const plan=await db.prepare("SELECT * FROM subscription_plans WHERE id=?1 AND active=1 LIMIT 1").bind(order.plan_id).first<Record<string,unknown>>(); if(!plan)throw new Error("Subscription plan not found.");
  const existing=await db.prepare("SELECT * FROM user_subscriptions WHERE user_id=?1 AND plan_id=?2 AND status='active' AND (ends_at IS NULL OR ends_at>?3) ORDER BY ends_at DESC LIMIT 1").bind(order.user_id,order.plan_id,nowIso()).first<Record<string,unknown>>();
  const startsAt=existing?String(existing.starts_at):paidAt; const base=existing?.ends_at&&Date.parse(String(existing.ends_at))>Date.now()?String(existing.ends_at):paidAt; const endsAt=addDuration(base,Number(plan.duration_value),String(plan.duration_unit)); const subscriptionId=existing?String(existing.id):id(); const eventType=existing?"extended":"granted";
  const statements=[eventStatement];
  if(existing) statements.push(db.prepare("UPDATE user_subscriptions SET ends_at=?1,source_payment_id=?2,updated_at=?3 WHERE id=?4").bind(endsAt,input.paymentId,nowIso(),subscriptionId));
  else statements.push(db.prepare("INSERT INTO user_subscriptions(id,user_id,plan_id,status,starts_at,ends_at,source,source_order_id,source_payment_id,created_at,updated_at) VALUES(?1,?2,?3,'active',?4,?5,'razorpay',?6,?7,?8,?8)").bind(subscriptionId,order.user_id,order.plan_id,startsAt,endsAt,input.orderId,input.paymentId,nowIso()));
  statements.push(db.prepare("INSERT INTO subscription_events(id,subscription_id,user_id,plan_id,payment_event_id,event_type,source,starts_at,ends_at,metadata,created_at) VALUES(?1,?2,?3,?4,?5,?6,'payment',?7,?8,'{}',?9)").bind(id(),subscriptionId,order.user_id,order.plan_id,paymentEventId,eventType,startsAt,endsAt,nowIso()));
  statements.push(db.prepare("UPDATE payment_orders SET provider_payment_id=?1,status='paid',paid_at=COALESCE(paid_at,?2),updated_at=?2 WHERE id=?3").bind(input.paymentId,paidAt,order.id));
  await db.batch(statements); return{ok:true,idempotent:false,granted:true,alreadyGranted:false,subscriptionId,eventType,endsAt};
}

async function createOrder(request:Request,env:Env,ctx:InternalContext){if(!ctx.userId)return json({error:"Sign in to choose a paid plan."},401);const body=await request.json().catch(()=>null) as {planId?:unknown}|null;const planId=typeof body?.planId==="string"?body.planId:"";if(!planId)return json({error:"Choose a subscription plan."},400);const provider=requireProvider(env);const plan=await database(env).prepare("SELECT id,tier_key,billing_cycle,name,price_subunits,currency,duration_value,duration_unit FROM subscription_plans WHERE id=?1 AND active=1 AND checkout_enabled=1 LIMIT 1").bind(planId).first<Record<string,unknown>>();if(!plan||plan.tier_key==="free"||!Number.isInteger(Number(plan.price_subunits))||Number(plan.price_subunits)<100)return json({error:"This paid plan is not available for checkout yet."},409);const receipt=`cp_${crypto.randomUUID().replaceAll("-","").slice(0,28)}`;const order=await razorpayJson("orders",provider,{method:"POST",body:JSON.stringify({amount:Number(plan.price_subunits),currency:plan.currency,receipt,notes:{ca_progress_user_id:ctx.userId,ca_progress_plan_id:plan.id}})}) as {id?:string;amount?:number;currency?:string};if(!order.id||Number(order.amount)!==Number(plan.price_subunits)||order.currency!==plan.currency)throw new Error("Razorpay returned an invalid order response.");await database(env).prepare("INSERT INTO payment_orders(id,user_id,plan_id,provider,provider_order_id,receipt,amount_subunits,currency,status,created_at,updated_at) VALUES(?1,?2,?3,'razorpay',?4,?5,?6,?7,'created',?8,?8)").bind(id(),ctx.userId,plan.id,order.id,receipt,Number(plan.price_subunits),plan.currency,nowIso()).run();return json({orderId:order.id,amount:Number(plan.price_subunits),currency:plan.currency,planName:plan.name,billingCycle:plan.billing_cycle,keyId:provider.keyId});}

async function verifyPayment(request:Request,env:Env,ctx:InternalContext){if(!ctx.userId)return json({error:"Sign in to verify this payment."},401);const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const orderId=typeof body?.razorpay_order_id==="string"?body.razorpay_order_id:"";const paymentId=typeof body?.razorpay_payment_id==="string"?body.razorpay_payment_id:"";const signature=typeof body?.razorpay_signature==="string"?body.razorpay_signature:"";if(!orderId||!paymentId||!signature)return json({error:"Payment verification details are incomplete."},400);const provider=requireProvider(env);const order=await database(env).prepare("SELECT * FROM payment_orders WHERE provider_order_id=?1 AND user_id=?2 LIMIT 1").bind(orderId,ctx.userId).first<Record<string,unknown>>();if(!order)return json({error:"This payment order does not belong to your account."},404);const expected=await hmacHex(provider.keySecret,`${order.provider_order_id}|${paymentId}`);if(!safeEqual(expected,signature.toLowerCase()))return json({error:"Payment signature verification failed."},400);const payment=await fetchPayment(paymentId,provider);if(payment.order_id!==order.provider_order_id||payment.amount!==Number(order.amount_subunits)||payment.currency!==order.currency)return json({error:"Razorpay payment details do not match the server order."},409);const result=await reconcile(env,{orderId:String(order.provider_order_id),paymentId,payment,source:"verify",eventType:`payment.${payment.status}`,eventKey:`verify:${order.provider_order_id}:${paymentId}`});return json({ok:true,reconciliation:result,providerStatus:payment.status});}

async function webhook(request:Request,env:Env,ctx:InternalContext){void ctx;const secret=env.RAZORPAY_WEBHOOK_SECRET?.trim();if(!secret)return json({error:"Razorpay webhook is not configured on V2 production yet."},503);const rawBody=await request.text();const supplied=request.headers.get("x-razorpay-signature")?.trim().toLowerCase()||"";if(!supplied)return json({error:"Webhook signature is missing."},400);const expected=await hmacHex(secret,rawBody);if(!safeEqual(expected,supplied))return json({error:"Webhook signature verification failed."},400);const event=JSON.parse(rawBody) as {event?:string;payload?:{payment?:{entity?:PaymentEntity}}};if(event.event!=="payment.captured"&&event.event!=="payment.failed")return json({ok:true,ignored:true});const entity=event.payload?.payment?.entity;if(!entity?.id||!entity.order_id)return json({error:"Webhook payment payload is incomplete."},400);const provider=requireProvider(env);const payment=await fetchPayment(entity.id,provider);if(payment.order_id!==entity.order_id||payment.amount!==entity.amount||payment.currency!==entity.currency||payment.status!==entity.status)return json({error:"Webhook payment does not match Razorpay API state."},409);const order=await database(env).prepare("SELECT * FROM payment_orders WHERE provider_order_id=?1 LIMIT 1").bind(entity.order_id).first<Record<string,unknown>>();if(!order)return json({ok:true,ignored:true,reason:"unknown_order"});if(payment.amount!==Number(order.amount_subunits)||payment.currency!==order.currency)return json({error:"Webhook amount or currency does not match the server order."},409);const eventKey=request.headers.get("x-razorpay-event-id")?.trim()||`webhook:${await sha256(`${supplied}:${rawBody}`)}`;const result=await reconcile(env,{orderId:entity.order_id,paymentId:entity.id,payment,source:"webhook",eventType:event.event,eventKey});return json({ok:true,reconciliation:result});}

const billingWorker = {async fetch(request:Request,env:Env){try{const ctx=requireInternal(request);const path=new URL(request.url).pathname;if(request.method==="POST"&&path==="/create-order")return await createOrder(request,env,ctx);if(request.method==="POST"&&path==="/verify")return await verifyPayment(request,env,ctx);if(request.method==="POST"&&path==="/webhook")return await webhook(request,env,ctx);if(request.method==="GET"&&path==="/health")return json({ok:true,databaseConfigured:Boolean(env.DB),providerConfigured:Boolean(env.RAZORPAY_KEY_ID&&env.RAZORPAY_KEY_SECRET),webhookConfigured:Boolean(env.RAZORPAY_WEBHOOK_SECRET),persistence:"cloudflare-d1"});return json({error:"Not found."},404);}catch(error){const message=error instanceof Error?error.message:"Billing service failed.";const status=/not configured|binding is missing/i.test(message)?503:/not found/i.test(message)?404:/Internal billing/i.test(message)?403:500;return json({error:message},status);}}};

export default billingWorker;
