import legacyWorker from "./index";

type D1Result<T=Record<string,unknown>>={results?:T[];success?:boolean;meta?:{changes?:number}};
type D1Statement={bind(...values:unknown[]):D1Statement;first<T=Record<string,unknown>>():Promise<T|null>;all<T=Record<string,unknown>>():Promise<D1Result<T>>;run<T=Record<string,unknown>>():Promise<D1Result<T>>};
type D1Database={prepare(query:string):D1Statement;batch<T=Record<string,unknown>>(statements:D1Statement[]):Promise<D1Result<T>[]>};
type Env={DB?:D1Database;RAZORPAY_KEY_ID?:string;RAZORPAY_KEY_SECRET?:string;RAZORPAY_WEBHOOK_SECRET?:string};
type InternalContext={userId:string|null};
type Row=Record<string,unknown>;
type Provider={keyId:string;keySecret:string};
type ProviderPlan={id:string;period:string;interval:number;item?:{amount?:number;currency?:string;name?:string};created_at?:number};
type ProviderOffer={id:string;active?:boolean;entity?:string};
type ProviderSubscription={id:string;plan_id:string;status:string;offer_id?:string|null;current_start?:number|null;current_end?:number|null;ended_at?:number|null;charge_at?:number|null;start_at?:number|null;end_at?:number|null;auth_attempts?:number;total_count?:number;paid_count?:number;remaining_count?:number;has_scheduled_changes?:boolean;created_at?:number};
type ProviderPayment={id:string;subscription_id?:string|null;invoice_id?:string|null;amount:number;currency:string;status:string;created_at?:number;captured_at?:number};
type Commercial={planId:string;tierKey:string;billingCycle:"monthly"|"annual";name:string;policyVersionId:string;recurringPrice:number;currency:string;durationValue:number;durationUnit:"month"|"year";trialDays:number;graceDays:number;introPrice:number|null;introCycles:number;introProviderOfferId:string|null;cancellationMode:"period_end"|"immediate_if_unpaid"};
type Mapping={id:string;providerPlanId:string;priceKind:"recurring"|"intro";amount:number;currency:string;period:"monthly"|"yearly";intervalValue:number};

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json","cache-control":"private, no-store"}});
const nowIso=()=>new Date().toISOString();
const uuid=()=>crypto.randomUUID();
const database=(env:Env)=>{if(!env.DB)throw new Error("Billing D1 binding is missing.");return env.DB;};
const provider=(env:Env):Provider=>{const keyId=env.RAZORPAY_KEY_ID?.trim(),keySecret=env.RAZORPAY_KEY_SECRET?.trim();if(!keyId||!keySecret)throw new Error("Razorpay recurring checkout is not configured.");return{keyId,keySecret};};
const auth=(p:Provider)=>`Basic ${btoa(`${p.keyId}:${p.keySecret}`)}`;
const internal=(request:Request):InternalContext=>{if(request.headers.get("x-ca-progress-internal")!=="ca-progress-v2-web")throw new Error("Internal billing service only.");return{userId:request.headers.get("x-ca-progress-user-id")?.trim()||null};};
const iso=(value:unknown)=>{const n=Number(value);return Number.isFinite(n)&&n>0?new Date(n*1000).toISOString():null;};
const addDays=(value:string,days:number)=>new Date(Date.parse(value)+days*86400000).toISOString();
const safeId=(value:unknown,prefix:string)=>{const text=String(value??"").trim();if(!new RegExp(`^${prefix}_[A-Za-z0-9]+$`).test(text))throw new Error(`Invalid ${prefix} identifier.`);return text;};
const requestKey=(value:unknown)=>{const text=String(value??"").trim();if(!/^[A-Za-z0-9_-]{16,100}$/.test(text))throw new Error("A valid idempotency request key is required.");return text;};
async function sha256(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return[...new Uint8Array(bytes)].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
async function hmac(secret:string,value:string){const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const signature=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(value));return[...new Uint8Array(signature)].map(byte=>byte.toString(16).padStart(2,"0")).join("");}
function equal(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i+=1)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
async function rp<T>(path:string,p:Provider,init:RequestInit={}):Promise<T>{const headers=new Headers(init.headers);headers.set("authorization",auth(p));headers.set("content-type","application/json");const response=await fetch(`https://api.razorpay.com/v1/${path}`,{...init,headers});const text=await response.text();const data=text?JSON.parse(text):null;if(!response.ok)throw new Error(data?.error?.description||`Razorpay request failed (${response.status}).`);return data as T;}
const getSubscription=(id:string,p:Provider)=>rp<ProviderSubscription>(`subscriptions/${encodeURIComponent(id)}`,p);
const getPayment=(id:string,p:Provider)=>rp<ProviderPayment>(`payments/${encodeURIComponent(id)}`,p);

async function resolveCommercial(db:D1Database,planId:string,userId:string):Promise<Commercial>{
  const now=nowIso();
  const row=await db.prepare(`SELECT sp.id plan_id,sp.tier_key,sp.billing_cycle,pv.name,pv.id policy_version_id,pv.price_subunits,pv.currency,pv.billing_duration_value,pv.billing_duration_unit,pv.trial_days,pv.grace_days,ot.intro_price_subunits,COALESCE(ot.intro_billing_cycles,0) intro_billing_cycles,ot.provider_offer_id,COALESCE(ot.cancellation_mode,'period_end') cancellation_mode
    FROM subscription_plans sp JOIN plan_policy_versions pv ON pv.plan_id=sp.id LEFT JOIN plan_policy_offer_terms ot ON ot.policy_version_id=pv.id
    WHERE sp.id=?1 AND sp.active=1 AND sp.checkout_enabled=1 AND sp.tier_key<>'free' AND pv.state='published' AND (pv.effective_at IS NULL OR pv.effective_at<=?2)
      AND pv.id=(SELECT active.id FROM plan_policy_versions active WHERE active.plan_id=sp.id AND active.state='published' AND (active.effective_at IS NULL OR active.effective_at<=?2) ORDER BY COALESCE(active.effective_at,active.published_at,active.created_at) DESC,active.version DESC LIMIT 1) LIMIT 1`).bind(planId,now).first<Row>();
  if(!row)throw new Error("This recurring plan is not available for checkout.");
  const cycle=String(row.billing_cycle);if(cycle!=="monthly"&&cycle!=="annual")throw new Error("Only monthly or annual products can create recurring subscriptions.");
  const unit=String(row.billing_duration_unit);if((cycle==="monthly"&&unit!=="month")||(cycle==="annual"&&unit!=="year"))throw new Error("The published billing interval is not compatible with recurring checkout.");
  const recurring=Number(row.price_subunits??0),duration=Number(row.billing_duration_value??0);if(!Number.isInteger(recurring)||recurring<100||!Number.isInteger(duration)||duration<1||String(row.currency)!=="INR")throw new Error("The published recurring terms are not chargeable.");
  const [legacy,p3]=await Promise.all([
    db.prepare(`SELECT COUNT(*) paid_count FROM payment_orders po JOIN subscription_plans sp ON sp.id=po.plan_id WHERE po.user_id=?1 AND po.status='paid' AND sp.tier_key=?2`).bind(userId,row.tier_key).first<{paid_count:number}>(),
    db.prepare(`SELECT COALESCE(SUM(rs.paid_count),0) paid_count FROM razorpay_subscriptions rs JOIN subscription_plans sp ON sp.id=rs.plan_id WHERE rs.user_id=?1 AND sp.tier_key=?2 AND rs.financial_state<>'mismatch'`).bind(userId,row.tier_key).first<{paid_count:number}>(),
  ]);
  const used=Number(legacy?.paid_count??0)+Number(p3?.paid_count??0),introCycles=Number(row.intro_billing_cycles??0),introRaw=row.intro_price_subunits==null?null:Number(row.intro_price_subunits),introRemaining=Math.max(0,introCycles-used),intro=introRaw!==null&&introRemaining>0?introRaw:null;
  if(intro!==null&&(!Number.isInteger(intro)||intro<100||intro>recurring))throw new Error("The published introductory price is invalid.");
  return{planId:String(row.plan_id),tierKey:String(row.tier_key),billingCycle:cycle,name:String(row.name),policyVersionId:String(row.policy_version_id),recurringPrice:recurring,currency:String(row.currency),durationValue:duration,durationUnit:unit as "month"|"year",trialDays:Number(row.trial_days??0),graceDays:Number(row.grace_days??0),introPrice:intro,introCycles:intro===null?0:introRemaining,introProviderOfferId:intro===null?null:(String(row.provider_offer_id??"").trim()||null),cancellationMode:String(row.cancellation_mode)==="immediate_if_unpaid"?"immediate_if_unpaid":"period_end"};
}

function providerFrequency(terms:Commercial){return{period:(terms.billingCycle==="monthly"?"monthly":"yearly") as "monthly"|"yearly",interval:terms.durationValue,totalCount:terms.billingCycle==="monthly"?Math.max(1,Math.floor(1200/terms.durationValue)):Math.max(1,Math.floor(100/terms.durationValue))};}
async function ensurePlan(env:Env,terms:Commercial,kind:"recurring"|"intro",amount:number):Promise<Mapping>{
  const db=database(env),p=provider(env),frequency=providerFrequency(terms);let row=await db.prepare("SELECT * FROM razorpay_plan_mappings WHERE policy_version_id=?1 AND price_kind=?2 LIMIT 1").bind(terms.policyVersionId,kind).first<Row>();
  if(row?.provider_plan_id&&row.state==="ready"){if(Number(row.amount_subunits)!==amount||String(row.currency)!==terms.currency)throw new Error("Stored Razorpay plan mapping no longer matches the immutable pricing version.");return{id:String(row.id),providerPlanId:String(row.provider_plan_id),priceKind:kind,amount:Number(row.amount_subunits),currency:String(row.currency),period:String(row.period) as "monthly"|"yearly",intervalValue:Number(row.interval_value)};}
  if(!row){const mappingId=uuid();await db.prepare("INSERT OR IGNORE INTO razorpay_plan_mappings(id,policy_version_id,internal_plan_id,price_kind,period,interval_value,amount_subunits,currency,state) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,'creating')").bind(mappingId,terms.policyVersionId,terms.planId,kind,frequency.period,frequency.interval,amount,terms.currency).run();row=await db.prepare("SELECT * FROM razorpay_plan_mappings WHERE policy_version_id=?1 AND price_kind=?2 LIMIT 1").bind(terms.policyVersionId,kind).first<Row>();}
  if(!row)throw new Error("Could not reserve the Razorpay plan mapping.");
  const token=uuid(),now=nowIso(),lease=new Date(Date.now()+30000).toISOString();const claimed=await db.prepare("UPDATE razorpay_plan_mappings SET sync_token=?1,lease_until=?2,state='creating',last_error=NULL,updated_at=?3 WHERE id=?4 AND provider_plan_id IS NULL AND (sync_token IS NULL OR lease_until IS NULL OR lease_until<?3 OR state='failed')").bind(token,lease,now,row.id).run();
  if(Number(claimed.meta?.changes??0)!==1){const ready=await db.prepare("SELECT * FROM razorpay_plan_mappings WHERE id=?1 AND state='ready' LIMIT 1").bind(row.id).first<Row>();if(ready?.provider_plan_id)return{id:String(ready.id),providerPlanId:String(ready.provider_plan_id),priceKind:kind,amount:Number(ready.amount_subunits),currency:String(ready.currency),period:String(ready.period) as "monthly"|"yearly",intervalValue:Number(ready.interval_value)};throw new Error("Razorpay plan provisioning is already in progress. Retry this checkout request.");}
  try{
    const created=await rp<ProviderPlan>("plans",p,{method:"POST",body:JSON.stringify({period:frequency.period,interval:frequency.interval,item:{name:`CA Progress ${terms.name}${kind==="intro"?" introductory":""}`,amount,currency:terms.currency,description:`${terms.billingCycle} subscription · policy ${terms.policyVersionId}`},notes:{ca_progress_policy_version_id:terms.policyVersionId,ca_progress_plan_id:terms.planId,price_kind:kind}})});
    if(!created.id||created.period!==frequency.period||Number(created.interval)!==frequency.interval||Number(created.item?.amount)!==amount||String(created.item?.currency)!==terms.currency)throw new Error("Razorpay returned a plan that does not match the approved pricing version.");
    const snapshot=JSON.stringify({id:created.id,period:created.period,interval:created.interval,amount:created.item?.amount,currency:created.item?.currency,created_at:created.created_at??null});
    await db.prepare("UPDATE razorpay_plan_mappings SET provider_plan_id=?1,state='ready',provider_snapshot_json=?2,last_checked_at=?3,sync_token=NULL,lease_until=NULL,updated_at=?3 WHERE id=?4 AND sync_token=?5").bind(created.id,snapshot,nowIso(),row.id,token).run();
    return{id:String(row.id),providerPlanId:created.id,priceKind:kind,amount,currency:terms.currency,period:frequency.period,intervalValue:frequency.interval};
  }catch(error){await db.prepare("UPDATE razorpay_plan_mappings SET state='failed',last_error=?1,sync_token=NULL,lease_until=NULL,updated_at=?2 WHERE id=?3 AND sync_token=?4").bind(error instanceof Error?error.message.slice(0,500):"provider_plan_failed",nowIso(),row.id,token).run();throw error;}
}

async function requireIntroOffer(env:Env,terms:Commercial){
  if(terms.introPrice===null)return null;
  const offerId=String(terms.introProviderOfferId??"").trim();
  if(!/^offer_[A-Za-z0-9]+$/.test(offerId))throw new Error("Introductory Razorpay Subscription Offer is not configured.");
  const offer=await rp<ProviderOffer>(`offers/${encodeURIComponent(offerId)}`,provider(env));
  if(!offer?.id||offer.id!==offerId||offer.active===false)throw new Error("The configured Razorpay Subscription Offer is unavailable or disabled.");
  return offerId;
}

function safeSubscriptionState(value:ProviderSubscription){return JSON.stringify({id:value.id,plan_id:value.plan_id,status:value.status,current_start:value.current_start??null,current_end:value.current_end??null,ended_at:value.ended_at??null,charge_at:value.charge_at??null,start_at:value.start_at??null,end_at:value.end_at??null,auth_attempts:value.auth_attempts??0,total_count:value.total_count??null,paid_count:value.paid_count??0,remaining_count:value.remaining_count??null,has_scheduled_changes:Boolean(value.has_scheduled_changes),offer_id:value.offer_id??null,created_at:value.created_at??null});}
async function recordCharge(db:D1Database,local:Row,payment:ProviderPayment,mapping:Row|null){
  const offerBound=Boolean(String(local.provider_offer_id??"").trim()),previousPaid=Math.max(0,Number(local.paid_count??0)),introCycles=Math.max(0,Number(local.intro_billing_cycles??0)),expectedAmount=offerBound&&previousPaid<introCycles?Number(local.initial_price_subunits??0):Number(mapping?.amount_subunits??0);const mismatch=payment.status==="captured"&&(!mapping||expectedAmount!==payment.amount||String(mapping.currency)!==payment.currency);const captured=payment.status==="captured"?iso(payment.captured_at??payment.created_at):null;
  await db.prepare(`INSERT INTO razorpay_subscription_charges(provider_payment_id,razorpay_subscription_id,provider_subscription_id,provider_invoice_id,amount_subunits,currency,status,provider_created_at,captured_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10) ON CONFLICT(provider_payment_id) DO UPDATE SET status=excluded.status,provider_invoice_id=COALESCE(excluded.provider_invoice_id,razorpay_subscription_charges.provider_invoice_id),captured_at=COALESCE(excluded.captured_at,razorpay_subscription_charges.captured_at),updated_at=excluded.updated_at`).bind(payment.id,local.id,local.provider_subscription_id,payment.invoice_id??null,payment.amount,payment.currency,payment.status,iso(payment.created_at),captured,nowIso()).run();
  return mismatch;
}

async function maybeScheduleIntro(_env:Env,_local:Row,_subscription:ProviderSubscription){
  // Phase 3: introductory pricing is a Razorpay Subscription Offer on the stable recurring plan.
  // Never PATCH a provider plan after UPI/eMandate authorisation.
  return;
}

async function reconcile(env:Env,providerSubscription:ProviderSubscription,payment:ProviderPayment|null,eventType:string){
  const db=database(env);let local=await db.prepare("SELECT * FROM razorpay_subscriptions WHERE provider_subscription_id=?1 LIMIT 1").bind(providerSubscription.id).first<Row>();if(!local)return{ignored:true,reason:"unknown_subscription"};
  const previousPlanId=String(local.plan_id),previousPolicyId=String(local.policy_version_id),mapping=await db.prepare("SELECT rpm.*,pv.plan_id mapped_plan_id FROM razorpay_plan_mappings rpm JOIN plan_policy_versions pv ON pv.id=rpm.policy_version_id WHERE rpm.provider_plan_id=?1 AND rpm.state='ready' LIMIT 1").bind(providerSubscription.plan_id).first<Row>();
  if(!mapping){await db.prepare("UPDATE razorpay_subscriptions SET financial_state='mismatch',provider_state_json=?1,last_reconciled_at=?2,updated_at=?2 WHERE id=?3").bind(safeSubscriptionState(providerSubscription),nowIso(),local.id).run();return{mismatch:true,reason:"unknown_provider_plan",userId:String(local.user_id)};}
  const expectedOffer=String(local.provider_offer_id??"").trim();if(expectedOffer&&String(providerSubscription.offer_id??"")!==expectedOffer){await db.prepare("UPDATE razorpay_subscriptions SET financial_state='mismatch',provider_state_json=?1,last_reconciled_at=?2,updated_at=?2 WHERE id=?3").bind(safeSubscriptionState(providerSubscription),nowIso(),local.id).run();return{mismatch:true,reason:"provider_offer_mismatch",userId:String(local.user_id)};}
  if(payment&&payment.subscription_id&&payment.subscription_id!==providerSubscription.id)return{mismatch:true,reason:"payment_subscription_mismatch",userId:String(local.user_id)};
  const paidCount=Number(providerSubscription.paid_count??local.paid_count??0),authorizationOnly=Boolean(payment&&paidCount===0&&providerSubscription.status==="authenticated"),chargeMismatch=payment&&!authorizationOnly?await recordCharge(db,local,payment,mapping):false;
  if(chargeMismatch){await db.prepare("UPDATE razorpay_subscriptions SET financial_state='mismatch',provider_state_json=?1,last_reconciled_at=?2,updated_at=?2 WHERE id=?3").bind(safeSubscriptionState(providerSubscription),nowIso(),local.id).run();return{mismatch:true,reason:"charge_amount_or_currency",userId:String(local.user_id)};}
  const targetPlanId=String(mapping.mapped_plan_id),targetPolicy=String(mapping.policy_version_id),currentEnd=iso(providerSubscription.current_end),previousPaid=local.paid_through_at?String(local.paid_through_at):null,paidThrough=paidCount>0&&currentEnd?currentEnd:previousPaid;
  const providerStatus=String(providerSubscription.status);let financial=String(local.financial_state??"unpaid");if(payment?.status==="failed")financial="failed";else if((payment?.status==="captured"&&!authorizationOnly)||paidCount>0)financial="paid";
  let graceUntil:string|null=null;if((providerStatus==="pending"||providerStatus==="halted")&&paidThrough&&Number(local.grace_days??0)>0)graceUntil=addDays(paidThrough,Number(local.grace_days));
  const startAt=iso(providerSubscription.start_at)||String(local.start_at||"")||null,currentStart=iso(providerSubscription.current_start),trialEligible=providerStatus==="authenticated"&&Number(local.trial_days??0)>0&&startAt&&Date.parse(startAt)>Date.now();let accessEnd:string|null=null;
  if(providerStatus==="active"&&paidThrough)accessEnd=paidThrough;else if(trialEligible)accessEnd=startAt;else if((providerStatus==="pending"||providerStatus==="halted"||providerStatus==="paused")&&paidThrough)accessEnd=graceUntil&&Date.parse(graceUntil)>Date.parse(paidThrough)?graceUntil:paidThrough;else if((providerStatus==="cancelled"||providerStatus==="completed"||providerStatus==="expired")&&paidThrough)accessEnd=paidThrough;
  const now=nowIso(),introRemaining=Math.max(0,Number(local.intro_billing_cycles??0)-paidCount);await db.prepare(`UPDATE razorpay_subscriptions SET plan_id=?1,policy_version_id=?2,provider_plan_id=?3,status=?4,financial_state=?5,paid_count=?6,remaining_count=?7,auth_attempts=?8,start_at=?9,current_start=?10,current_end=?11,charge_at=?12,ended_at=?13,paid_through_at=?14,grace_until=?15,intro_remaining_cycles=?16,provider_verified=1,provider_state_json=?17,last_reconciled_at=?18,updated_at=?18 WHERE id=?19`).bind(targetPlanId,targetPolicy,providerSubscription.plan_id,providerStatus,financial,paidCount,providerSubscription.remaining_count??null,Number(providerSubscription.auth_attempts??0),startAt,currentStart,currentEnd,iso(providerSubscription.charge_at),iso(providerSubscription.ended_at),paidThrough,graceUntil,introRemaining,safeSubscriptionState(providerSubscription),now,local.id).run();
  local=await db.prepare("SELECT * FROM razorpay_subscriptions WHERE id=?1").bind(local.id).first<Row>() as Row;
  const existing=await db.prepare("SELECT * FROM user_subscriptions WHERE provider_subscription_id=?1 LIMIT 1").bind(providerSubscription.id).first<Row>();const validAccess=Boolean(accessEnd&&Date.parse(accessEnd)>Date.now());
  if(validAccess){const accessStatus=(providerStatus==="pending"||providerStatus==="halted"||providerStatus==="paused")?"paused":(providerStatus==="cancelled"||providerStatus==="completed"||providerStatus==="expired")?"cancelled":"active";const starts=currentStart||startAt||String(existing?.starts_at||now);const accessId=existing?String(existing.id):uuid();
    if(existing)await db.prepare("UPDATE user_subscriptions SET plan_id=?1,status=?2,starts_at=?3,ends_at=?4,source_payment_id=COALESCE(?5,source_payment_id),updated_at=?6 WHERE id=?7").bind(targetPlanId,accessStatus,starts,accessEnd,payment?.id??null,now,accessId).run();
    else await db.prepare("INSERT INTO user_subscriptions(id,user_id,plan_id,status,starts_at,ends_at,source,source_order_id,source_payment_id,provider_subscription_id,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,'razorpay',?7,?8,?7,?9,?9)").bind(accessId,local.user_id,targetPlanId,accessStatus,starts,accessEnd,providerSubscription.id,payment?.id??null,now).run();
    await db.prepare(`INSERT INTO subscription_policy_contracts(subscription_id,policy_version_id,grandfathered,decision_reason) VALUES(?1,?2,1,'Verified Razorpay recurring subscription policy') ON CONFLICT(subscription_id) DO UPDATE SET policy_version_id=excluded.policy_version_id,decision_reason='Verified cycle-end provider transition'`).bind(accessId,targetPolicy).run();
    const previousStatus=existing?String(existing.status):null,event=existing?(accessStatus==="paused"&&previousStatus!=="paused"?"paused":accessStatus==="active"&&previousStatus==="paused"?"resumed":accessStatus==="cancelled"?"cancelled":payment?.status==="captured"&&!authorizationOnly?"extended":null):"granted";
    if(event)await db.prepare("INSERT INTO subscription_events(id,subscription_id,user_id,plan_id,payment_event_id,event_type,source,starts_at,ends_at,metadata,created_at) VALUES(?1,?2,?3,?4,NULL,?5,'razorpay_subscription',?6,?7,?8,?9)").bind(uuid(),accessId,local.user_id,targetPlanId,event,starts,accessEnd,JSON.stringify({provider_subscription_id:providerSubscription.id,provider_event:eventType}),now).run();
    await db.prepare("UPDATE razorpay_subscriptions SET linked_access_subscription_id=?1 WHERE id=?2").bind(accessId,local.id).run();
  }else if(existing&&(providerStatus==="cancelled"||providerStatus==="completed"||providerStatus==="expired")){
    await db.prepare("UPDATE user_subscriptions SET status='expired',ends_at=COALESCE(ends_at,?1),updated_at=?1 WHERE id=?2").bind(now,existing.id).run();
  }
  if(targetPlanId!==previousPlanId||targetPolicy!==previousPolicyId)await db.prepare("UPDATE scheduled_plan_changes SET state='applied',applied_at=?1 WHERE user_id=?2 AND to_plan_id=?3 AND state='scheduled' AND effective_at<=?1").bind(now,local.user_id,targetPlanId).run();
  await maybeScheduleIntro(env,local,providerSubscription);
  return{ignored:false,status:providerStatus,accessUntil:accessEnd,financialState:financial,paidCount,authorizationOnly,userId:String(local.user_id)};
}

async function createSubscription(request:Request,env:Env,ctx:InternalContext){
  if(!ctx.userId)return json({error:"Sign in to start a subscription."},401);const body=await request.json().catch(()=>null) as {planId?:unknown;requestId?:unknown}|null;const planId=String(body?.planId??"").trim(),key=requestKey(body?.requestId);if(!planId)return json({error:"Choose a subscription plan."},400);const db=database(env),p=provider(env);
  const prior=await db.prepare("SELECT * FROM razorpay_subscriptions WHERE checkout_key=?1 AND user_id=?2 LIMIT 1").bind(key,ctx.userId).first<Row>();if(prior)return json({subscriptionId:prior.provider_subscription_id,keyId:p.keyId,billingCycle:prior.billing_cycle,recurringAmount:prior.recurring_price_subunits,policyVersionId:prior.policy_version_id,idempotent:true});
  const open=await db.prepare("SELECT * FROM razorpay_subscriptions WHERE user_id=?1 AND status IN ('created','authenticated','active','pending','halted','paused') ORDER BY created_at DESC LIMIT 1").bind(ctx.userId).first<Row>();if(open){if(String(open.plan_id)===planId&&(open.status==="created"||open.status==="authenticated"))return json({subscriptionId:open.provider_subscription_id,keyId:p.keyId,billingCycle:open.billing_cycle,recurringAmount:open.recurring_price_subunits,policyVersionId:open.policy_version_id,reused:true});return json({error:"An existing recurring subscription is already open. Use Billing to change, pause or cancel it."},409);}
  const terms=await resolveCommercial(db,planId,ctx.userId),recurring=await ensurePlan(env,terms,"recurring",terms.recurringPrice),introOfferId=await requireIntroOffer(env,terms),frequency=providerFrequency(terms);
  const paidAccess=await db.prepare("SELECT ends_at FROM user_subscriptions WHERE user_id=?1 AND ends_at>?2 AND status IN ('active','cancelled','paused') ORDER BY ends_at DESC LIMIT 1").bind(ctx.userId,nowIso()).first<{ends_at:string}>();const trialStart=terms.trialDays>0?Math.floor((Date.now()+terms.trialDays*86400000)/1000):0,existingStart=paidAccess?.ends_at?Math.floor(Date.parse(paidAccess.ends_at)/1000):0,startAt=Math.max(trialStart,existingStart),payload:Record<string,unknown>={plan_id:recurring.providerPlanId,total_count:frequency.totalCount,quantity:1,customer_notify:true,notes:{ca_progress_user_id:ctx.userId,ca_progress_plan_id:terms.planId,ca_progress_policy_version_id:terms.policyVersionId,checkout_key:key}};if(introOfferId)payload.offer_id=introOfferId;if(startAt>Math.floor(Date.now()/1000)+60)payload.start_at=startAt;
  const created=await rp<ProviderSubscription>("subscriptions",p,{method:"POST",body:JSON.stringify(payload)});if(!created.id||created.plan_id!==recurring.providerPlanId||!["created","authenticated"].includes(created.status)||(introOfferId&&created.offer_id!==introOfferId))throw new Error("Razorpay returned an invalid subscription or did not attach the required Subscription Offer.");
  const initialAmount=terms.introPrice??terms.recurringPrice,now=nowIso();await db.prepare(`INSERT INTO razorpay_subscriptions(id,checkout_key,user_id,plan_id,policy_version_id,provider_subscription_id,provider_plan_id,recurring_provider_plan_id,status,financial_state,recurring_price_subunits,initial_price_subunits,currency,billing_cycle,billing_duration_value,billing_duration_unit,trial_days,grace_days,intro_billing_cycles,intro_remaining_cycles,cancellation_mode,total_count,paid_count,remaining_count,auth_attempts,start_at,current_start,current_end,charge_at,ended_at,provider_verified,provider_state_json,provider_offer_id,created_at,updated_at,last_reconciled_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?7,?8,'unpaid',?9,?10,?11,?12,?13,?14,?15,?16,?17,?17,?18,?19,?20,?21,?22,?23,?24,?25,?26,?27,1,?28,?29,?30,?30,?30)`).bind(uuid(),key,ctx.userId,terms.planId,terms.policyVersionId,created.id,recurring.providerPlanId,created.status,terms.recurringPrice,initialAmount,terms.currency,terms.billingCycle,terms.durationValue,terms.durationUnit,terms.trialDays,terms.graceDays,terms.introCycles,terms.cancellationMode,frequency.totalCount,Number(created.paid_count??0),created.remaining_count??frequency.totalCount,Number(created.auth_attempts??0),iso(created.start_at),iso(created.current_start),iso(created.current_end),iso(created.charge_at),iso(created.ended_at),safeSubscriptionState(created),introOfferId,now).run();
  return json({subscriptionId:created.id,keyId:p.keyId,billingCycle:terms.billingCycle,planName:terms.name,recurringAmount:terms.recurringPrice,trialDays:terms.trialDays,introApplied:terms.introPrice!==null,policyVersionId:terms.policyVersionId,providerOfferApplied:Boolean(introOfferId)});
}

async function verifySubscription(request:Request,env:Env,ctx:InternalContext){
  if(!ctx.userId)return json({error:"Sign in to verify this subscription."},401);const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const subscriptionId=safeId(body?.razorpay_subscription_id,"sub"),paymentId=safeId(body?.razorpay_payment_id,"pay"),signature=String(body?.razorpay_signature??"").trim().toLowerCase();if(!signature)return json({error:"Subscription verification details are incomplete."},400);const db=database(env),local=await db.prepare("SELECT * FROM razorpay_subscriptions WHERE provider_subscription_id=?1 AND user_id=?2 LIMIT 1").bind(subscriptionId,ctx.userId).first<Row>();if(!local)return json({error:"This subscription does not belong to your account."},404);const p=provider(env),expected=await hmac(p.keySecret,`${paymentId}|${subscriptionId}`);if(!equal(expected,signature))return json({error:"Subscription signature verification failed."},400);
  const [sub,payment]=await Promise.all([getSubscription(subscriptionId,p),getPayment(paymentId,p)]);if(payment.subscription_id!==subscriptionId)return json({error:"Razorpay payment does not belong to this subscription."},409);const result=await reconcile(env,sub,payment,"checkout.verified"),eventId=`verify:${subscriptionId}:${paymentId}`,outcome=(result as {mismatch?:boolean}).mismatch?"mismatch":"reconciled";await db.prepare("INSERT OR IGNORE INTO razorpay_subscription_events(id,provider_event_id,razorpay_subscription_id,provider_subscription_id,provider_payment_id,event_type,payload_sha256,evidence_json,outcome,received_at,processed_at) VALUES(?1,?2,?3,?4,?5,'checkout.verified',?6,?7,?8,?9,?9)").bind(uuid(),eventId,local.id,subscriptionId,paymentId,await sha256(`${subscriptionId}|${paymentId}|verified`),JSON.stringify({subscription_id:subscriptionId,payment_id:paymentId,subscription_status:sub.status,payment_status:payment.status,authorization_only:(result as {authorizationOnly?:boolean}).authorizationOnly===true}),outcome,nowIso()).run();return json({ok:true,providerStatus:sub.status,reconciliation:result,userId:ctx.userId});
}

async function action(request:Request,env:Env,ctx:InternalContext){
  if(!ctx.userId)return json({error:"Sign in to manage your subscription."},401);const body=await request.json().catch(()=>null) as {subscriptionId?:unknown;action?:unknown;targetPlanId?:unknown;requestId?:unknown}|null;const subscriptionId=safeId(body?.subscriptionId,"sub"),kind=String(body?.action??""),key=requestKey(body?.requestId);if(!["sync","pause","resume","cancel_period_end","cancel_immediate","change_plan"].includes(kind))return json({error:"Unsupported subscription action."},400);const db=database(env),p=provider(env),local=await db.prepare("SELECT * FROM razorpay_subscriptions WHERE provider_subscription_id=?1 AND user_id=?2 LIMIT 1").bind(subscriptionId,ctx.userId).first<Row>();if(!local)return json({error:"Subscription not found."},404);
  const existing=await db.prepare("SELECT * FROM subscription_action_requests WHERE request_key=?1 AND user_id=?2 LIMIT 1").bind(key,ctx.userId).first<Row>();if(existing?.state==="completed")return json({ok:true,idempotent:true,effectiveAt:existing.effective_at,userId:ctx.userId});await db.prepare("INSERT OR IGNORE INTO subscription_action_requests(request_key,user_id,razorpay_subscription_id,action,target_plan_id,state) VALUES(?1,?2,?3,?4,?5,'started')").bind(key,ctx.userId,local.id,kind,body?.targetPlanId?String(body.targetPlanId):null).run();
  try{let sub=await getSubscription(subscriptionId,p),effectiveAt:string|null=null,decision:Record<string,unknown>={provider_status_before:sub.status};
    if(kind==="pause"){if(sub.status!=="active")throw new Error("Only an active subscription can be paused.");await rp(`subscriptions/${encodeURIComponent(subscriptionId)}/pause`,p,{method:"POST",body:JSON.stringify({pause_at:"now"})});decision={...decision,pause_at:"now"};}
    else if(kind==="resume"){if(sub.status==="cancelled")return json({error:"A cancelled Razorpay subscription cannot be resumed. Start a new checkout to reactivate.",reactivationRequiresCheckout:true},409);if(sub.status!=="paused")throw new Error("Only a paused subscription can be resumed.");await rp(`subscriptions/${encodeURIComponent(subscriptionId)}/resume`,p,{method:"POST",body:JSON.stringify({resume_at:"now"})});decision={...decision,resume_at:"now"};}
    else if(kind==="cancel_period_end"||kind==="cancel_immediate"){const immediate=kind==="cancel_immediate";if(immediate&&(String(local.cancellation_mode)!=="immediate_if_unpaid"||(local.paid_through_at&&Date.parse(String(local.paid_through_at))>Date.now())))throw new Error("Immediate cancellation is not permitted while paid-through access remains.");await rp(`subscriptions/${encodeURIComponent(subscriptionId)}/cancel`,p,{method:"POST",body:JSON.stringify({cancel_at_cycle_end:immediate?0:1})});effectiveAt=immediate?nowIso():(iso(sub.current_end)||String(local.paid_through_at||"")||null);decision={...decision,cancel_at_cycle_end:immediate?0:1};await db.prepare("UPDATE razorpay_subscriptions SET cancel_at_period_end=?1,updated_at=?2 WHERE id=?3").bind(immediate?0:1,nowIso(),local.id).run();}
    else if(kind==="change_plan"){if(sub.status!=="active")throw new Error("Only an active subscription can change plan at cycle end.");const targetPlanId=String(body?.targetPlanId??"").trim(),cycleEnd=iso(sub.current_end);if(!targetPlanId||targetPlanId===String(local.plan_id))throw new Error("Choose a different paid plan.");if(!cycleEnd)throw new Error("Razorpay did not provide a current billing-cycle end for this change.");const terms=await resolveCommercial(db,targetPlanId,ctx.userId),mapping=await ensurePlan(env,{...terms,introPrice:null,introCycles:0},"recurring",terms.recurringPrice);await rp(`subscriptions/${encodeURIComponent(subscriptionId)}`,p,{method:"PATCH",body:JSON.stringify({plan_id:mapping.providerPlanId,schedule_change_at:"cycle_end",customer_notify:true})});effectiveAt=cycleEnd;decision={...decision,target_plan_id:targetPlanId,target_policy_version_id:terms.policyVersionId,schedule_change_at:"cycle_end",proration:"none"};await db.batch([db.prepare("UPDATE razorpay_subscriptions SET scheduled_target_plan_id=?1,scheduled_target_policy_version_id=?2,scheduled_target_provider_plan_id=?3,updated_at=?4 WHERE id=?5").bind(targetPlanId,terms.policyVersionId,mapping.providerPlanId,nowIso(),local.id),db.prepare("INSERT INTO scheduled_plan_changes(id,user_id,from_plan_id,to_plan_id,effective_at,state,reason,created_by) VALUES(?1,?2,?3,?4,?5,'scheduled','Student recurring subscription change at provider cycle end',NULL)").bind(uuid(),ctx.userId,local.plan_id,targetPlanId,effectiveAt)]);}
    sub=await getSubscription(subscriptionId,p);const reconciled=await reconcile(env,sub,null,`user.${kind}`);await db.prepare("UPDATE subscription_action_requests SET state='completed',effective_at=?1,decision_json=?2,completed_at=?3 WHERE request_key=?4").bind(effectiveAt,JSON.stringify(decision),nowIso(),key).run();return json({ok:true,providerStatus:sub.status,effectiveAt,reconciliation:reconciled,userId:ctx.userId});
  }catch(error){await db.prepare("UPDATE subscription_action_requests SET state='failed',error_code=?1,completed_at=?2 WHERE request_key=?3").bind(error instanceof Error?error.message.slice(0,300):"subscription_action_failed",nowIso(),key).run();throw error;}
}

async function recordWebhookEvent(db:D1Database,input:{eventId:string;local:Row;subscriptionId:string;paymentId?:string|null;invoiceId?:string|null;eventType:string;createdAt?:number;raw:string;evidence:Record<string,unknown>}){
  const receipt=db.prepare("INSERT OR IGNORE INTO razorpay_subscription_events(id,provider_event_id,razorpay_subscription_id,provider_subscription_id,provider_payment_id,provider_invoice_id,event_type,provider_created_at,payload_sha256,evidence_json,outcome,received_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,'received',?11)");
  const result=await receipt.bind(uuid(),input.eventId,input.local.id,input.subscriptionId,input.paymentId??null,input.invoiceId??null,input.eventType,iso(input.createdAt),await sha256(input.raw),JSON.stringify(input.evidence),nowIso()).run();return Number(result.meta?.changes??0)===1;
}

async function webhook(request:Request,env:Env){
  const secret=env.RAZORPAY_WEBHOOK_SECRET?.trim();if(!secret)return json({error:"Razorpay webhook is not configured."},503);const legacyRequest=request.clone(),raw=await request.text(),signature=request.headers.get("x-razorpay-signature")?.trim().toLowerCase()||"";if(!signature)return json({error:"Webhook signature is missing."},400);const expected=await hmac(secret,raw);if(!equal(expected,signature))return json({error:"Webhook signature verification failed."},400);const payload=JSON.parse(raw) as {event?:string;created_at?:number;payload?:{subscription?:{entity?:ProviderSubscription};payment?:{entity?:ProviderPayment};refund?:{entity?:{payment_id?:string;amount?:number;status?:string}};dispute?:{entity?:{payment_id?:string;status?:string}}}};const eventType=String(payload.event??""),embeddedSub=payload.payload?.subscription?.entity,embeddedPayment=payload.payload?.payment?.entity,subscriptionId=embeddedSub?.id||embeddedPayment?.subscription_id||null,db=database(env),p=provider(env);
  let local:Row|null=subscriptionId?await db.prepare("SELECT * FROM razorpay_subscriptions WHERE provider_subscription_id=?1 LIMIT 1").bind(subscriptionId).first<Row>():null;
  let charge:Row|null=null;if(!local&&(eventType.startsWith("refund.")||eventType.startsWith("payment.dispute."))){const paymentId=embeddedPayment?.id||payload.payload?.refund?.entity?.payment_id||payload.payload?.dispute?.entity?.payment_id||null;if(paymentId){charge=await db.prepare("SELECT c.*,rs.provider_subscription_id,rs.id subscription_row_id FROM razorpay_subscription_charges c JOIN razorpay_subscriptions rs ON rs.id=c.razorpay_subscription_id WHERE c.provider_payment_id=?1 LIMIT 1").bind(paymentId).first<Row>();if(charge)local=await db.prepare("SELECT * FROM razorpay_subscriptions WHERE id=?1").bind(charge.subscription_row_id).first<Row>();}}
  if(!local||!local.provider_subscription_id){if(eventType==="payment.captured"||eventType==="payment.failed")return legacyWorker.fetch(legacyRequest,env);return json({ok:true,ignored:true,reason:"not_phase3_subscription"});}
  const resolvedSubscriptionId=String(local.provider_subscription_id),eventId=request.headers.get("x-razorpay-event-id")?.trim()||`webhook:${await sha256(`${signature}:${raw}`)}`,paymentId=embeddedPayment?.id||payload.payload?.refund?.entity?.payment_id||payload.payload?.dispute?.entity?.payment_id||null,invoiceId=embeddedPayment?.invoice_id??null;
  const inserted=await recordWebhookEvent(db,{eventId,local,subscriptionId:resolvedSubscriptionId,paymentId,invoiceId,eventType,createdAt:payload.created_at,raw,evidence:{event:eventType,subscription_id:resolvedSubscriptionId,payment_id:paymentId,invoice_id:invoiceId,embedded_subscription_status:embeddedSub?.status??null,embedded_payment_status:embeddedPayment?.status??null}});if(!inserted)return json({ok:true,idempotent:true,userId:String(local.user_id)});
  try{
    if(eventType.startsWith("refund.")){if(paymentId){const state=eventType==="refund.failed"?"failed":eventType==="refund.processed"?"full":"partial";await db.prepare("UPDATE razorpay_subscription_charges SET refund_state=?1,updated_at=?2 WHERE provider_payment_id=?3").bind(state,nowIso(),paymentId).run();await db.prepare("UPDATE razorpay_subscriptions SET financial_state=?1,updated_at=?2 WHERE id=?3").bind(state==="failed"?String(local.financial_state):"refunded",nowIso(),local.id).run();}await db.prepare("UPDATE razorpay_subscription_events SET outcome='reconciled',processed_at=?1 WHERE provider_event_id=?2").bind(nowIso(),eventId).run();return json({ok:true,reconciled:true,userId:String(local.user_id)});}
    if(eventType.startsWith("payment.dispute.")){if(paymentId)await db.prepare("UPDATE razorpay_subscription_charges SET dispute_state=?1,updated_at=?2 WHERE provider_payment_id=?3").bind(eventType.replace("payment.dispute.",""),nowIso(),paymentId).run();await db.prepare("UPDATE razorpay_subscriptions SET financial_state='disputed',updated_at=?1 WHERE id=?2").bind(nowIso(),local.id).run();await db.prepare("UPDATE razorpay_subscription_events SET outcome='reconciled',processed_at=?1 WHERE provider_event_id=?2").bind(nowIso(),eventId).run();return json({ok:true,reconciled:true,userId:String(local.user_id)});}
    const sub=await getSubscription(resolvedSubscriptionId,p);let payment:ProviderPayment|null=null;if(paymentId)payment=await getPayment(String(paymentId),p);const result=await reconcile(env,sub,payment,eventType);await db.prepare("UPDATE razorpay_subscription_events SET outcome=?1,processed_at=?2 WHERE provider_event_id=?3").bind((result as {mismatch?:boolean}).mismatch?"mismatch":"reconciled",nowIso(),eventId).run();return json({ok:true,reconciliation:result,userId:String(local.user_id)});
  }catch(error){await db.prepare("UPDATE razorpay_subscription_events SET outcome='failed',error_code=?1,processed_at=?2 WHERE provider_event_id=?3").bind(error instanceof Error?error.message.slice(0,300):"reconciliation_failed",nowIso(),eventId).run();throw error;}
}

const worker={async fetch(request:Request,env:Env){try{const ctx=internal(request),path=new URL(request.url).pathname;if(request.method==="POST"&&path==="/create-subscription")return createSubscription(request,env,ctx);if(request.method==="POST"&&path==="/verify-subscription")return verifySubscription(request,env,ctx);if(request.method==="POST"&&path==="/subscription-action")return action(request,env,ctx);if(request.method==="POST"&&path==="/webhook")return webhook(request,env);return legacyWorker.fetch(request,env);}catch(error){const message=error instanceof Error?error.message:"Recurring billing service failed.";const status=/not configured|binding is missing/i.test(message)?503:/not found/i.test(message)?404:/already open|not permitted|cannot be resumed|Choose a different|provisioning is already/i.test(message)?409:/required|invalid|unsupported|Only an|does not belong|signature/i.test(message)?400:/Internal billing/i.test(message)?403:500;return json({error:message},status);}}};
export default worker;
