import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
const root = new URL("../", import.meta.url).pathname; const read = (path) => readFileSync(join(root, path), "utf8");
test("desktop login keeps the auth card contained beside the marketing panel", () => { const css=read("app/styles/auth-login-fix.css"); assert.match(css,/public-content:has\(\.auth-v2-layout\)/); assert.match(css,/max-width:\s*620px/); assert.match(css,/@media \(min-width:\s*900px\)/); assert.match(css,/grid-template-columns:\s*minmax\(0,\s*1fr\)/); assert.match(css,/\.auth-v2-intro\s*\{\s*display:\s*none/); assert.match(css,/\.auth-v2-card\s*\{[\s\S]*?max-width:\s*440px/); });
test("smaller screens retain the richer login intro in a single-column flow", () => { const css=read("app/styles/auth-login-fix.css"); assert.match(css,/@media \(max-width:\s*899px\)/); assert.match(css,/gap:\s*var\(--space-6\)/); assert.match(css,/\.auth-v2-intro\s*\{\s*padding:\s*var\(--space-2\) 0 0/); });
test("public login copy is product-facing rather than internal phase/debug language", () => { const shell=read("components/shell/public-shell.tsx"); const login=read("components/auth/login-panel.tsx"); assert.doesNotMatch(shell,/Phase 1 UX|Phase 1 establishes/); assert.doesNotMatch(login,/Phase 2 identity|Supabase RLS|hydration|Server Components/); assert.match(login,/Continue with Google/); assert.match(login,/Continue with LinkedIn/); assert.match(login,/Continue as Guest/); assert.match(login,/Remember this device/); });
test("manual Cloudflare staging deployment remains on the clean Phase 11 baseline", () => { const workflow=read(".github/workflows/deploy-staging.yml"); assert.match(workflow,/NEXT_PUBLIC_APP_VERSION:\s*phase-11/); assert.doesNotMatch(workflow,/NEXT_PUBLIC_APP_VERSION:\s*phase-12/); });
