import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("Phase 18 local schema covers every core projection",async()=>{const schema=await read("packages/mobile-data/src/schema.ts");for(const table of ["academic_catalog","dashboard_projection","progress_records","planner_items","study_sessions","timer_state","notes","profile_projection","activity_projection","leaderboard_projection","study_buddy_projection"])assert.match(schema,new RegExp(table));assert.match(schema,/LOCAL_SCHEMA_VERSION = [3-9]/);});

test("all daily student screens query the account-scoped SQLite repository",async()=>{const [main,repository]=await Promise.all([read("apps/mobile/src/main.tsx"),read("packages/mobile-data/src/repository.ts")]);for(const screen of ["Today","Progress","Syllabus","Planner","Focus","Notes","Profile","Activity","Buddy"])assert.match(main,new RegExp(`function ${screen}\\(`));for(const table of ["academic_catalog","progress_records","planner_items","notes","profile_projection","activity_projection","leaderboard_projection","study_buddy_projection"])assert.match(repository,new RegExp(`FROM ${table} WHERE account_id=\\?`));assert.doesNotMatch(main,/fetch\(/);});

test("cached content remains mounted while background synchronization runs",async()=>{const main=await read("apps/mobile/src/main.tsx");assert.match(main,/setWorkspace\(snapshot\)/);assert.match(main,/createSyncCoordinator/);assert.match(main,/sync\(\);return/);assert.doesNotMatch(main,/if\s*\(syncState===['"]updating['"]\).*loading/is);assert.match(main,/StableEmpty/);assert.match(main,/Offline · showing saved data/);});

test("optimistic edits and their outbox record commit in one local transaction",async()=>{const source=await read("packages/mobile-data/src/repository.ts");for(const method of ["saveTimer","createTask","toggleTask","setProgressStage","saveNote","finishTimer","saveSessionReview"]){const start=source.indexOf(`async ${method}`);assert.ok(start>0,method);const section=source.slice(start,source.indexOf("notify(account.id)",start));assert.match(section,/await transaction\(\[/);assert.match(section,/outboxStatement\(/);}assert.match(source,/status.*pending/);assert.match(source,/base_server_version/);assert.match(source,/predecessor_mutation_id/);});

test("reactive updates target repository subscribers without route refresh",async()=>{const [main,repository]=await Promise.all([read("apps/mobile/src/main.tsx"),read("packages/mobile-data/src/repository.ts")]);assert.match(repository,/const listeners = new Map/);assert.match(repository,/notify\(account\.id\)/);assert.match(main,/value\.subscribe/);assert.match(main,/setWorkspace\(next\)/);assert.doesNotMatch(main,/location\.reload|router\.refresh/);});

test("slow, intermittent and absent network preserve the last local frame",async()=>{let frame={tasks:["cached"],status:"idle"};const render=()=>JSON.stringify(frame.tasks);const before=render();const slow=new Promise(resolve=>setTimeout(()=>resolve(["cloud"]),25));frame={...frame,status:"updating"};assert.equal(render(),before);frame={tasks:await slow,status:"idle"};assert.equal(render(),JSON.stringify(["cloud"]));frame={...frame,status:"offline"};assert.equal(render(),JSON.stringify(["cloud"]));const attempts=[];for(const result of ["network-loss","network-loss","success"]){attempts.push(result);if(result!=="success")assert.deepEqual(frame.tasks,["cloud"]);}assert.deepEqual(attempts,["network-loss","network-loss","success"]);});

test("bootstrap refresh converges web data without overwriting pending native edits",async()=>{const [sync,bootstrap]=await Promise.all([read("packages/mobile-data/src/sync.ts"),read("app/api/v1/sync/bootstrap/route.ts")]);assert.match(sync,/transport\("\/api\/v1\/sync\/bootstrap"\)/);for(const table of ["progress_records","planner_items","notes","study_sessions"])assert.match(sync,new RegExp(`WHERE ${table}\\.local_state='synced'`));for(const type of ["academic_subject","academic_chapter","attempt","profile","activity","leaderboard","study_buddy"])assert.match(bootstrap,new RegExp(`'${type}' AS entity_type`));});

test("Phase 18 status preserves its original Phase 19 boundary",async()=>{const status=await read("docs/mobile-local-first/PHASE_18_STATUS.md");assert.match(status,/At Phase 18 completion, Phase 19 had not been started/);});
