import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");

test("Phase 19 defines typed persistent and ephemeral realtime events",async()=>{const source=await read("lib/community/realtime-events.ts");for(const type of ["message.created","message.updated","message.deleted","reaction.changed","pin.changed","read.changed","typing.changed","presence.changed"])assert.match(source,new RegExp(type.replace(".","\\.")));assert.match(source,/channelId/);assert.match(source,/sequence/);assert.match(source,/entityId/);assert.match(source,/version/);});
test("Durable Object uses hibernation handlers and cannot persist Community data",async()=>{const source=await read("community-coordinator.ts");for(const method of ["acceptWebSocket","webSocketMessage","webSocketClose","webSocketError","getWebSockets"])assert.match(source,new RegExp(method));assert.doesNotMatch(source,/INSERT INTO|UPDATE community_messages|DELETE FROM community_messages/);});
test("D1 migration adds idempotent client message IDs and ordered events",async()=>{const source=await read("d1/migrations/0066_mobile_phase19_community.sql");assert.match(source,/client_message_id/);assert.match(source,/UNIQUE INDEX/);assert.match(source,/community_sequence_events/);assert.match(source,/PRIMARY KEY\(channel_id,sequence_id\)/);});
test("authorized mobile endpoints support forward delta and backward pagination",async()=>{const [route,phase7]=await Promise.all([read("app/api/v1/community/channels/[channel]/messages/route.ts"),read("lib/community/phase7.ts")]);assert.match(route,/afterSequence/);assert.match(route,/beforeSequence/);assert.match(phase7,/m\.sequence_id>\?/);assert.match(phase7,/m\.sequence_id<\?/);assert.match(route,/clientMessageId/);});
test("SQLite v4 stores sequences drafts pins tombstones and delivery state",async()=>{const schema=await read("packages/mobile-data/src/schema.ts");assert.match(schema,/LOCAL_SCHEMA_VERSION = 4/);for(const field of ["latest_sequence","draft_text","sequence_id","client_message_id","delivery_state","community_pins","community_event_log"])assert.match(schema,new RegExp(field));assert.match(schema,/moderation_status/);});
test("local Community reducer deduplicates events and orders messages by sequence",async()=>{const source=await read("packages/mobile-data/src/community.ts");assert.match(source,/community_event_log/);assert.match(source,/entity_version/);assert.match(source,/ORDER BY CASE WHEN sequence_id IS NULL/);assert.match(source,/ON CONFLICT\(account_id,server_id\)/);assert.match(source,/This message was removed by moderation/);});
test("native Community opens SQLite first then reconciles and polls bounded deltas",async()=>{const [screen,sync]=await Promise.all([read("apps/mobile/src/main.tsx"),read("apps/mobile/src/community-sync.ts")]);assert.match(screen,/readCommunitySnapshot/);assert.match(screen,/queueCommunityMessage/);assert.match(screen,/Load older messages/);assert.match(sync,/afterSequence/);assert.match(sync,/beforeSequence/);assert.match(sync,/POLL_MS=5000/);assert.match(sync,/WebSocket/);assert.doesNotMatch(screen,/location\.reload|router\.refresh/);});
test("optimistic send acknowledgement failure and bounded retention are durable",async()=>{const source=await read("packages/mobile-data/src/community.ts");for(const method of ["queueCommunityMessage","acknowledgeCommunityMessage","failCommunityMessage","pruneCommunityHistory","saveCommunityDraft","markCommunityReadLocal"])assert.match(source,new RegExp(`function ${method}`));for(const state of ["sending","sent","failed","retrying"])assert.match(source,new RegExp(state));assert.match(source,/mutation_outbox/);});
