import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {build} from 'esbuild';
import {fixture} from './helpers/payment-worker-fixture.mjs';
import {readWebhookBytes} from '../lib/billing/webhook-body.mjs';
const dir=await mkdtemp(join(tmpdir(),'payment-p4-')),bundle=join(dir,'worker.mjs');
await build({entryPoints:['workers/billing/payment-p4.ts'],outfile:bundle,bundle:true,format:'esm',platform:'neutral'});
const builtWorker=await import(pathToFileURL(bundle)),worker=builtWorker.default;
const cacheBundle=join(dir,'feature-cache.mjs');
await build({entryPoints:['lib/cache/public.ts'],outfile:cacheBundle,bundle:true,format:'esm',platform:'neutral',plugins:[{name:'fixture-runtime',setup(build){
 build.onResolve({filter:/^(server-only|@\/lib\/env|\.\/user-feature-version)$/},args=>({path:args.path,namespace:'fixture'}));
 build.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:args.path==='server-only'?'':args.path==='@/lib/env'?"export function getPublicRuntimeConfig(){return {appName:'fixture'}}":"export async function readUserFeatureRevision(user){return globalThis.readFixtureRevision(user)}",loader:'js'}));
}}]});
const featureCache=await import(pathToFileURL(cacheBundle));
after(()=>rm(dir,{recursive:true,force:true}));
function setup(){const f=fixture(worker),jobs=[];f.env.BILLING_OPS_QUEUE={async send(body){jobs.push(body);}};return {...f,jobs};}
function payload(f,type='subscription.charged'){return {event:type,created_at:f.invoices[0].billing_start,payload:{subscription:{entity:{...f.sub}},payment:{entity:{...f.payments.get('pay_1')}}}};}
function request(raw,id='evt1',secret='fixture-webhook'){return new Request('https://billing.internal/webhook',{method:'POST',headers:{'x-ca-progress-internal':'ca-progress-v2-web','x-razorpay-signature':createHmac('sha256',secret).update(raw).digest('hex'),'x-razorpay-event-id':id},body:raw});}
async function ingest(f,data=payload(f),id='evt1'){const raw=typeof data==='string'?data:JSON.stringify(data);return worker.fetch(request(raw,id),f.env);}
async function consume(f,job=f.jobs.shift()){let ack=0,retry=0;await worker.queue({messages:[{body:job,ack(){ack++;},retry(){retry++;}}]},f.env);return {ack,retry};}
const count=(f,table)=>Number(f.sql.prepare(`SELECT COUNT(*) n FROM ${table}`).get().n);
function renewal(f){const first=f.invoices[0],next={...first,id:'inv_2',payment_id:'pay_2',billing_start:first.billing_end,billing_end:first.billing_end+28*86400,amount:5000,amount_paid:5000};f.invoices.push(next);f.payments.set('pay_2',{...f.payments.get('pay_1'),id:'pay_2',invoice_id:'inv_2',amount:5000,created_at:next.billing_start});Object.assign(f.sub,{paid_count:2,current_start:next.billing_start,current_end:next.billing_end});return next;}
test('signed raw inbox is persisted before 202 and queue contains only event identity',async()=>{const f=setup();try{const raw='  '+JSON.stringify(payload(f))+'\n';const response=await ingest(f,raw);assert.equal(response.status,202);const row=f.sql.prepare('SELECT * FROM billing_webhook_inbox').get();assert.equal(row.raw_body,raw);assert.equal(row.state,'received');assert.deepEqual(f.jobs,[{kind:'inbox',eventKey:'evt1'}]);assert.equal(f.calls.length,0);assert.equal(count(f,'user_subscriptions'),0);}finally{f.cleanup();}});
test('bad signatures, changed raw bytes and invalid JSON never enter the inbox',async()=>{const f=setup();try{const raw=JSON.stringify(payload(f));const wrong=request(raw);wrong.headers.set('x-razorpay-signature','0'.repeat(64));assert.equal((await worker.fetch(wrong,f.env)).status,400);assert.equal((await worker.fetch(request('not json'),f.env)).status,400);const modified=request(raw);const supplied=modified.headers.get('x-razorpay-signature');const changed=request(raw+' ');changed.headers.set('x-razorpay-signature',supplied);assert.equal((await worker.fetch(changed,f.env)).status,400);assert.equal(count(f,'billing_webhook_inbox'),0);assert.equal(f.jobs.length,0);}finally{f.cleanup();}});
test('persist failure receives no successful acknowledgement',async()=>{const f=setup();try{f.env.DB={...f.db,prepare(){throw new Error('D1 unavailable');}};assert.equal((await ingest(f)).status,503);assert.equal(f.jobs.length,0);}finally{f.cleanup();}});
test('same event ID with conflicting payload fails without replacing accepted work',async()=>{const f=setup();try{await ingest(f);const changed=payload(f);changed.event='subscription.cancelled';assert.equal((await ingest(f,changed)).status,409);assert.equal(count(f,'billing_webhook_inbox'),1);assert.equal(f.sql.prepare('SELECT event_type FROM billing_webhook_inbox').get().event_type,'subscription.charged');}finally{f.cleanup();}});
test('duplicate event and callbacks converge to one access, cycle, change and notification',async()=>{const f=setup();try{for(let n=0;n<2;n++)await ingest(f);while(f.jobs.length)assert.equal((await consume(f)).ack,1);const sig=createHmac('sha256','fixture-secret').update('pay_1|sub_1').digest('hex');for(let n=0;n<2;n++)assert.equal((await worker.fetch(new Request('https://billing.internal/verify-subscription',{method:'POST',headers:{'x-ca-progress-internal':'ca-progress-v2-web','x-ca-progress-user-id':'user1','content-type':'application/json'},body:JSON.stringify({razorpay_subscription_id:'sub_1',razorpay_payment_id:'pay_1',razorpay_signature:sig})}),f.env)).status,200);assert.equal(count(f,'user_subscriptions'),1);assert.equal(count(f,'payment_subscription_cycles'),1);assert.equal(count(f,'subscription_events'),1);assert.equal(count(f,'billing_access_outbox'),1);assert.equal(count(f,'notification_outbox'),1);assert.equal(f.sql.prepare('SELECT state FROM billing_webhook_inbox').get().state,'processed');assert.ok(f.calls.every(c=>c.method==='GET'));}finally{f.cleanup();}});
test('provider failure remains retryable; replay uses the same ID and converges once',async()=>{const f=setup();try{await ingest(f);const good=globalThis.fetch;globalThis.fetch=async()=>new Response('offline',{status:503});assert.equal((await consume(f)).retry,1);let row=f.sql.prepare('SELECT * FROM billing_webhook_inbox').get();assert.equal(row.state,'retry');assert.equal(row.attempts,1);assert.equal(count(f,'user_subscriptions'),0);globalThis.fetch=good;f.sql.prepare("UPDATE billing_webhook_inbox SET available_at='2000-01-01T00:00:00.000Z'").run();await ingest(f);assert.equal((await consume(f)).ack,1);row=f.sql.prepare('SELECT * FROM billing_webhook_inbox').get();assert.equal(row.state,'processed');assert.equal(row.attempts,2);assert.equal(count(f,'notification_outbox'),1);}finally{f.cleanup();}});
test('queue outage after durable acceptance is recovered by scheduled scan',async()=>{const f=setup();try{f.env.BILLING_OPS_QUEUE.send=async()=>{throw new Error('queue outage');};assert.equal((await ingest(f)).status,202);await worker.scheduled({scheduledTime:Date.now()},f.env);assert.equal(f.sql.prepare('SELECT state FROM billing_webhook_inbox').get().state,'processed');assert.equal(count(f,'user_subscriptions'),1);assert.equal(count(f,'notification_outbox'),1);}finally{f.cleanup();}});
test('missing webhook and browser callback are reconciled from captured invoice service dates',async()=>{const f=setup();try{f.sql.prepare("UPDATE razorpay_subscriptions SET last_reconciled_at=NULL").run();await worker.scheduled({scheduledTime:Date.now()},f.env);const access=f.sql.prepare('SELECT * FROM user_subscriptions').get();assert.equal(access.ends_at,new Date(f.invoices[0].billing_end*1000).toISOString());assert.equal(count(f,'billing_webhook_inbox'),0);assert.equal(count(f,'notification_outbox'),1);}finally{f.cleanup();}});
test('late intro and failed events cannot overwrite a full paid renewal',async()=>{const f=setup();try{const old=payload(f),next=renewal(f);await ingest(f,payload(f),'new');await consume(f);const id=f.sql.prepare('SELECT id FROM user_subscriptions').get().id;await ingest(f,old,'old');await consume(f);f.payments.set('pay_failed',{id:'pay_failed',subscription_id:'sub_1',invoice_id:null,status:'failed',method:'upi',amount:5000,currency:'INR'});const failed=payload(f,'payment.failed');failed.payload.payment.entity=f.payments.get('pay_failed');await ingest(f,failed,'failed');await consume(f);const access=f.sql.prepare('SELECT * FROM user_subscriptions').get();assert.equal(access.id,id);assert.equal(access.ends_at,new Date(next.billing_end*1000).toISOString());assert.equal(count(f,'payment_subscription_cycles'),2);assert.equal(count(f,'subscription_events'),1);assert.equal(count(f,'notification_outbox'),1);assert.equal(f.sql.prepare('SELECT financial_state FROM razorpay_subscriptions').get().financial_state,'paid');}finally{f.cleanup();}});
test('captured payment-only webhook resolves its actual subscription through the invoice',async()=>{const f=setup();try{const body=payload(f,'payment.captured');delete body.payload.subscription;delete body.payload.payment.entity.subscription_id;delete f.payments.get('pay_1').subscription_id;const original=globalThis.fetch;globalThis.fetch=async(url,init)=>new URL(url).pathname==='/v1/invoices/inv_1'?Response.json(f.invoices[0]):original(url,init);await ingest(f,body);assert.equal((await consume(f)).ack,1);assert.equal(count(f,'user_subscriptions'),1);}finally{f.cleanup();}});
test('reordered old active webhook after cancellation retains paid end and cancelled state',async()=>{const f=setup();try{const old=payload(f);await ingest(f);await consume(f);f.sub.status='cancelled';await ingest(f,payload(f,'subscription.cancelled'),'cancel');await consume(f);await ingest(f,old,'late');await consume(f);const access=f.sql.prepare('SELECT * FROM user_subscriptions').get();assert.equal(access.status,'cancelled');assert.equal(access.ends_at,new Date(f.invoices[0].billing_end*1000).toISOString());assert.equal(count(f,'subscription_events'),2);}finally{f.cleanup();}});
test('access, policy, notification outbox and durable revision roll back together',async()=>{const f=setup();try{f.sql.exec("CREATE TRIGGER inject_failure BEFORE INSERT ON subscription_policy_contracts BEGIN SELECT RAISE(ABORT,'injected transaction failure');END;");await ingest(f);assert.equal((await consume(f)).retry,1);for(const table of ['user_subscriptions','subscription_events','billing_access_outbox','notification_outbox','user_feature_revisions','billing_projection_guards'])assert.equal(count(f,table),0);assert.equal(f.sql.prepare('SELECT projection_version FROM razorpay_subscriptions').get().projection_version,0);f.sql.exec('DROP TRIGGER inject_failure');f.sql.prepare("UPDATE billing_webhook_inbox SET available_at='2000-01-01'").run();await ingest(f);assert.equal((await consume(f)).ack,1);assert.equal(count(f,'user_subscriptions'),1);assert.equal(count(f,'notification_outbox'),1);}finally{f.cleanup();}});
test('simultaneous events serialize one contract and retry the losing worker',async()=>{const f=setup();try{await ingest(f,payload(f),'a');await ingest(f,payload(f),'b');const jobs=f.jobs.splice(0),results=await Promise.all(jobs.map(j=>consume(f,j)));assert.equal(results.reduce((n,r)=>n+r.ack,0),1);assert.equal(results.reduce((n,r)=>n+r.retry,0),1);f.sql.prepare("UPDATE billing_webhook_inbox SET available_at='2000-01-01'").run();await worker.scheduled({scheduledTime:Date.now()},f.env);assert.equal(count(f,'user_subscriptions'),1);assert.equal(count(f,'billing_access_outbox'),1);assert.equal(count(f,'notification_outbox'),1);}finally{f.cleanup();}});
test('expired processing lease recovers; duplicate active lease does not process twice',async()=>{const f=setup();try{await ingest(f);f.sql.prepare("UPDATE billing_webhook_inbox SET state='processing',lease_token='crashed',lease_until='2000-01-01'").run();assert.equal((await consume(f)).ack,1);await ingest(f);assert.equal(f.jobs.length,0);assert.equal(count(f,'user_subscriptions'),1);}finally{f.cleanup();}});
test('poisoned evidence reaches visible review after bounded attempts without granting access',async()=>{const f=setup();try{await ingest(f);f.sql.prepare('UPDATE billing_webhook_inbox SET attempts=11').run();f.payments.get('pay_1').amount=5000;assert.equal((await consume(f)).retry,1);const row=f.sql.prepare('SELECT * FROM billing_webhook_inbox').get();assert.equal(row.state,'review');assert.equal(row.attempts,12);assert.equal(count(f,'user_subscriptions'),0);assert.equal(count(f,'notification_outbox'),0);}finally{f.cleanup();}});
test('accepted previous-secret event can finish after secret rotation without revalidation',async()=>{const f=setup();try{f.env.RAZORPAY_WEBHOOK_SECRET_PREVIOUS='old-secret';const r=await worker.fetch(request(JSON.stringify(payload(f)),'rotated','old-secret'),f.env);assert.equal(r.status,202);delete f.env.RAZORPAY_WEBHOOK_SECRET_PREVIOUS;f.env.RAZORPAY_WEBHOOK_SECRET='next-secret';assert.equal((await consume(f)).ack,1);assert.equal(count(f,'user_subscriptions'),1);}finally{f.cleanup();}});
test('stale pending notifications are superseded and repeated dispatch cannot duplicate delivery',async()=>{const f=setup();try{await f.sync();renewal(f);await f.sync();let rows=f.sql.prepare('SELECT state FROM billing_access_outbox ORDER BY id').all();assert.deepEqual(rows.map(r=>r.state),['superseded','pending']);await builtWorker.dispatchAccessOutbox(f.env);await builtWorker.dispatchAccessOutbox(f.env);assert.equal(count(f,'notification_outbox'),1);assert.equal(f.sql.prepare('SELECT revision FROM user_feature_revisions').get().revision,3);}finally{f.cleanup();}});
test('untrusted private invocation cannot ingest or process webhook work',async()=>{const f=setup();try{const r=request(JSON.stringify(payload(f)));r.headers.delete('x-ca-progress-internal');assert.equal((await worker.fetch(r,f.env)).status,403);assert.equal(count(f,'billing_webhook_inbox'),0);}finally{f.cleanup();}});
test('feature caches consult a request-scoped durable revision before reuse across locations',async()=>{const source=await readFile('lib/cache/public.ts','utf8'),version=await readFile('lib/cache/user-feature-version.ts','utf8');assert.match(source,/await readUserFeatureRevision\(input.userId\)/);assert.match(version,/cache\(async\(userId/);assert.match(version,/SELECT revision FROM user_feature_revisions/);assert.doesNotMatch(version,/max-age|setTimeout/);});
test('two primed edge caches immediately observe queue grants and access revocation',async()=>{const f=setup(),oldCaches=globalThis.caches,oldRevision=globalThis.readFixtureRevision;try{
 const edge=()=>{const values=new Map();return {async match(request){return values.get(request.url)?.clone();},async put(request,response){values.set(request.url,response.clone());},async delete(request){return values.delete(request.url);}};},locations=[edge(),edge()];
 globalThis.readFixtureRevision=user=>String(f.sql.prepare('SELECT revision FROM user_feature_revisions WHERE user_id=?').get(user)?.revision??0);
 const load=async()=>Boolean(f.sql.prepare("SELECT id FROM user_subscriptions WHERE user_id='user1' AND status='active'").get());
 const read=()=>featureCache.getCachedUserFeature({userId:'user1',featureKey:'paid.feature',load});
 for(const location of locations){globalThis.caches={default:location};assert.equal(await read(),false);assert.equal(await read(),false);}
 await ingest(f);await consume(f);
 for(const location of locations){globalThis.caches={default:location};assert.equal(await read(),true);}
 f.sql.prepare("UPDATE user_subscriptions SET status='expired'").run();
 for(const location of locations){globalThis.caches={default:location};assert.equal(await read(),false);}
 }finally{globalThis.caches=oldCaches;globalThis.readFixtureRevision=oldRevision;f.cleanup();}});
test('campaign inbox failure replays the original event and full-price renewal once',async()=>{const f=setup();try{
 f.sql.exec("INSERT INTO billing_campaign_versions VALUES('cv1','fixed',2500,1);INSERT INTO billing_campaign_claims VALUES('claim1','offer_1',1,'cv1');UPDATE razorpay_subscriptions SET campaign_claim_id='claim1'");
 await ingest(f);const good=globalThis.fetch;globalThis.fetch=async()=>new Response('offline',{status:503});assert.equal((await consume(f)).retry,1);globalThis.fetch=good;f.sql.prepare("UPDATE billing_webhook_inbox SET available_at='2000-01-01'").run();await ingest(f);assert.equal((await consume(f)).ack,1);const next=renewal(f);await ingest(f,payload(f),'next');assert.equal((await consume(f)).ack,1);await ingest(f,payload(f),'duplicate-next');assert.equal((await consume(f)).ack,1);assert.equal(count(f,'user_subscriptions'),1);assert.equal(count(f,'payment_subscription_cycles'),2);assert.equal(count(f,'notification_outbox'),2);assert.equal(f.sql.prepare('SELECT ends_at FROM user_subscriptions').get().ends_at,new Date(next.billing_end*1000).toISOString());
 }finally{f.cleanup();}});
test('historical failed receipt is retried rather than mistaken for completed work',async()=>{const f=setup();try{
 await ingest(f);const row=f.sql.prepare('SELECT * FROM billing_webhook_inbox').get();f.sql.prepare("INSERT INTO razorpay_subscription_events(id,provider_event_id,razorpay_subscription_id,provider_subscription_id,event_type,payload_sha256,evidence_json,outcome) VALUES('receipt1','evt1','local1','sub_1','subscription.charged',?,'{}','failed')").run(row.payload_sha256);
 assert.equal((await consume(f)).ack,1);assert.equal(f.sql.prepare("SELECT outcome FROM razorpay_subscription_events WHERE provider_event_id='evt1'").get().outcome,'reconciled');assert.equal(count(f,'user_subscriptions'),1);
 }finally{f.cleanup();}});
test('expired projection lease is fenced before any access/outbox transaction commits',async()=>{const f=setup();try{
 f.sql.exec("CREATE TRIGGER expire_projection_lease AFTER INSERT ON payment_subscription_cycles BEGIN UPDATE billing_subscription_leases SET lease_until='2000-01-01';END;");await ingest(f);assert.equal((await consume(f)).retry,1);assert.equal(count(f,'user_subscriptions'),0);assert.equal(count(f,'billing_access_outbox'),0);assert.equal(f.sql.prepare('SELECT projection_version FROM razorpay_subscriptions').get().projection_version,0);
 }finally{f.cleanup();}});
test('financial hold arriving during verification fences a stale paid projection',async()=>{const f=setup();try{
 f.sql.exec("CREATE TRIGGER hold_during_verification AFTER INSERT ON payment_subscription_cycles BEGIN UPDATE razorpay_subscriptions SET financial_state='refunded';END;");await ingest(f);assert.equal((await consume(f)).retry,1);assert.equal(count(f,'user_subscriptions'),0);assert.equal(count(f,'billing_access_outbox'),0);assert.equal(f.sql.prepare('SELECT financial_state FROM razorpay_subscriptions').get().financial_state,'refunded');
 }finally{f.cleanup();}});
test('shared signed-ingress limit returns retryable 429 without losing accepted work',async()=>{const f=setup();try{
 f.env.BILLING_WEBHOOK_MAX_PER_MINUTE='1';assert.equal((await ingest(f)).status,202);assert.equal((await ingest(f,payload(f),'second')).status,429);assert.equal(count(f,'billing_webhook_inbox'),1);assert.equal(f.jobs.length,1);assert.equal((await consume(f)).ack,1);assert.equal(count(f,'user_subscriptions'),1);
 }finally{f.cleanup();}});
test('oversized streaming bodies are cancelled before inbox persistence',async()=>{const f=setup();try{
 const raw=JSON.stringify({event:'subscription.charged',payload:{},padding:'a'.repeat(512000)});assert.equal((await ingest(f,raw)).status,413);assert.equal(count(f,'billing_webhook_inbox'),0);assert.equal(count(f,'billing_webhook_rate_windows'),0);
 }finally{f.cleanup();}});
test('streamed byte reader preserves split Unicode and rejects overflow',async()=>{
 const raw=new TextEncoder().encode('₹25\n'),chunks=[raw.slice(0,1),raw.slice(1,2),raw.slice(2)];const stream=new ReadableStream({pull(controller){const next=chunks.shift();if(next)controller.enqueue(next);else controller.close();}});
 const bytes=await readWebhookBytes(new Request('https://fixture',{method:'POST',body:stream,duplex:'half'}));assert.deepEqual(new Uint8Array(bytes),raw);await assert.rejects(()=>readWebhookBytes(new Request('https://fixture',{method:'POST',body:'12345'}),4),e=>e.status===413);
});
function replayRequest(input,role='owner'){return new Request('https://billing.internal/admin/replay-event',{method:'POST',headers:{'x-ca-progress-internal':'ca-progress-v2-web','x-ca-progress-user-id':'operator1','x-ca-progress-actor-role':role,'content-type':'application/json'},body:JSON.stringify(input)});}
test('owner review replay is audited and idempotent, then completes the original event',async()=>{const f=setup();try{
 await ingest(f);f.jobs.length=0;f.sql.prepare("UPDATE billing_webhook_inbox SET state='review',attempts=12").run();const input={eventKey:'evt1',requestId:'replay_request_001',reason:'Provider outage resolved; retry verified evidence'};
 assert.equal((await worker.fetch(replayRequest(input),f.env)).status,202);assert.equal((await worker.fetch(replayRequest(input),f.env)).status,200);assert.equal(count(f,'billing_inbox_replays'),1);assert.equal(f.jobs.length,1);assert.equal((await consume(f)).ack,1);assert.equal(count(f,'user_subscriptions'),1);assert.equal(f.sql.prepare('SELECT state FROM billing_webhook_inbox').get().state,'processed');
 }finally{f.cleanup();}});
test('review replay rejects other roles and conflicting request reuse without resetting work',async()=>{const f=setup();try{
 await ingest(f);f.jobs.length=0;f.sql.prepare("UPDATE billing_webhook_inbox SET state='review'").run();const input={eventKey:'evt1',requestId:'replay_request_001',reason:'Original reviewed recovery reason'};assert.equal((await worker.fetch(replayRequest(input,'admin'),f.env)).status,403);assert.equal(count(f,'billing_inbox_replays'),0);assert.equal((await worker.fetch(replayRequest(input),f.env)).status,202);assert.equal((await worker.fetch(replayRequest({...input,reason:'Different reason for reused request'}),f.env)).status,409);assert.equal(count(f,'billing_inbox_replays'),1);
 }finally{f.cleanup();}});
test('processed events cannot be reset through the replay endpoint',async()=>{const f=setup();try{
 await ingest(f);await consume(f);assert.equal((await worker.fetch(replayRequest({eventKey:'evt1',requestId:'replay_request_002',reason:'Attempt to replay completed work'}),f.env)).status,409);assert.equal(count(f,'billing_inbox_replays'),0);assert.equal(count(f,'notification_outbox'),1);
 }finally{f.cleanup();}});
