import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("../", import.meta.url).pathname; const read = (p) => readFileSync(join(root,p), "utf8");
test("four-step onboarding wizard and profile surface exist", () => { for (const file of ["components/auth/onboarding-wizard.tsx","app/(public)/onboarding/page.tsx","app/api/onboarding/route.ts","app/(student)/settings/profile/page.tsx","components/auth/profile-form.tsx","app/api/profile/route.ts","app/api/profile/avatar/route.ts"]) assert.equal(existsSync(join(root,file)), true, file); const wizard = read("components/auth/onboarding-wizard.tsx"); assert.match(wizard, /Step \{step\} of 4/); assert.match(wizard, /Choose your CA level/); assert.match(wizard, /Choose your group/); assert.match(wizard, /Choose your attempt/); assert.match(wizard, /daily target and confirm/i); });
test("onboarding saves drafts and completion separately", () => { const api = read("app/api/onboarding/route.ts"); assert.match(api, /body\.action === "complete"/); assert.match(api, /onboardingCompletedAt/); assert.match(api, /onboardingStep/); assert.match(api, /loadAttemptOptions/); });
test("first-run routing skips completed onboarding but resumes incomplete profiles", () => { const page = read("app/(public)/onboarding/page.tsx"); const server = read("lib/auth/server.ts"); assert.match(page, /onboarding_completed_at/); assert.match(server, /!profile\?\.onboarding_completed_at/); assert.match(server, /\/onboarding\?next=/); });
test("restricted profile surface preserves its intended destination", () => { const page = read("app/(student)/settings/profile/page.tsx"); const prompt = read("components/auth/login-required.tsx"); assert.match(page, /next="\/settings\/profile"/); assert.match(prompt, /loginPathFor\(next\)/); });
test("onboarding uses student-facing copy and a simple Continue action", () => { const wizard = read("components/auth/onboarding-wizard.tsx"); assert.doesNotMatch(wizard, /V2 workspace|Phase 3 academic catalog|Save & continue/); assert.match(wizard, />Continue <Icon name="arrow"/); assert.match(wizard, /Only attempts available for your selected CA level are shown/); assert.match(wizard, /Choose the group you want to study and track/); });
