import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
const root=new URL("../",import.meta.url).pathname; const read=(path)=>readFileSync(join(root,path),"utf8"); const routes=["study","planner","goals","calendar","activity"];
test("all Phase 6 product routes are real server-backed surfaces",()=>{for(const route of routes){const page=`app/(student)/${route}/page.tsx`;assert.equal(existsSync(join(root,page)),true,page);assert.doesNotMatch(read(page),/ProductPreviewPage|PlaceholderPage/);}assert.match(read("app/(student)/study/page.tsx"),/getStudyPageModel/);assert.match(read("app/(student)/planner/page.tsx"),/getPlannerPageModel/);assert.match(read("app/(student)/calendar/page.tsx"),/getCalendarPageModel/);assert.match(read("app/(student)/calendar/page.tsx"),/@\/lib\/planner\/calendar/);assert.match(read("app/(student)/activity/page.tsx"),/getActivityPageModel/);});
test("each Phase 6 route has explicit loading and error states",()=>{for(const route of routes)for(const file of ["loading.tsx","error.tsx"])assert.equal(existsSync(join(root,`app/(student)/${route}/${file}`)),true,`${route}/${file}`);});
test("Phase 6 navigation is available on desktop and mobile",()=>{const nav=read("components/shell/navigation.tsx");const mobile=read("components/shell/mobile-nav-placeholder.tsx");for(const href of ["/study","/planner","/goals","/calendar","/activity"])assert.match(nav,new RegExp(href.replace("/","\\/")));assert.match(mobile,/studentSections/);assert.match(mobile,/studentSections\.map/);assert.match(mobile,/\/goals/);assert.match(mobile,/\/calendar/);assert.match(mobile,/\/activity/);});
test("Phase 6 has independent responsive mobile contracts and horizontal calendar protection",()=>{const css=read("app/styles/phase6.css");assert.match(css,/@media\(max-width:1050px\)/);assert.match(css,/@media\(max-width:720px\)/);assert.match(css,/@media\(max-width:440px\)/);assert.match(css,/overflow-x:auto/);assert.match(css,/prefers-reduced-motion/);});
