import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
const root=new URL("../",import.meta.url).pathname; const read=(p)=>readFileSync(join(root,p),"utf8");
test("unread count is derived from last-read sequence and excludes own messages",()=>{const sql=read("supabase/migrations/20260830190000_phase10_community_v2.sql");assert.match(sql,/m\.user_id<>auth\.uid\(\)/);assert.match(sql,/m\.sequence_id>coalesce\(\(select r\.last_read_sequence/);assert.match(sql,/greatest\(public\.channel_read_state\.last_read_sequence,excluded\.last_read_sequence\)/);});
test("older messages use stable sequence cursor pagination instead of full history",()=>{const sql=read("supabase/migrations/20260830190000_phase10_community_v2.sql");const service=read("lib/community/service.ts");const client=read("components/community/community-chat.tsx");assert.match(sql,/sequence_id bigint generated by default as identity unique/);assert.match(service,/const PAGE_SIZE = 30/);assert.match(service,/\.lt\("sequence_id", cursor\)/);assert.match(service,/limit\(PAGE_SIZE \+ 1\)/);assert.match(service,/nextCursor/);assert.match(client,/Load older messages/);});
