import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("../", import.meta.url).pathname; const read = (p) => readFileSync(join(root,p), "utf8");
test("five-step onboarding and profile surface exist", () => { for (const file of ["components/auth/onboarding-wizard.tsx","app/(public)/onboarding/page.tsx","app/api/onboarding/route.ts","app/(student)/settings/profile/page.tsx","components/auth/profile-form.tsx","app/api/profile/route.ts","app/api/profile/avatar/route.ts"]) assert.equal(existsSync(join(root,file)), true, file); const wizard = read("components/auth/onboarding-wizard.tsx"); assert.match(wizard, /Step \{step\} of 5/); assert.match(wizard, /Choose your CA level/); assert.match(wizard, /Choose your group/); assert.match(wizard, /Choose your attempt/); assert.match(wizard, /What will you use CA Progress most for\?/); assert.match(wizard, /daily target and confirm/i); });
test("choice cards save and advance without Save & continue buttons", () => { const wizard = read("components/auth/onboarding-wizard.tsx"); assert.match(wizard, /chooseLevel/); assert.match(wizard, /chooseGroup/); assert.match(wizard, /chooseAttempt/); assert.match(wizard, /choosePrimaryUse/); assert.doesNotMatch(wizard, /Save & continue/); assert.match(wizard, /Choose an option to continue/); });
test("attempt choice uses buttons instead of an onboarding dropdown", () => { const wizard = read("components/auth/onboarding-wizard.tsx"); assert.match(wizard, /attempt-choice-grid/); assert.match(wizard, /applicableAttempts\.map/); assert.doesNotMatch(wizard, /<Select label="Attempt"/); });
test("onboarding saves drafts and completion separately", () => { const api = read("app/api/onboarding/route.ts"); assert.match(api, /body\.action === "complete"/); assert.match(api, /onboarding_completed_at/); assert.match(api, /onboarding_step/); assert.match(api, /primary_use/); assert.match(api, /loadAttemptOptions/); });
test("first-run routing skips completed onboarding and requires the guide until it is finished or skipped", () => { const page = read("app/(public)/onboarding/page.tsx"); const server = read("lib/auth/server.ts"); assert.match(page, /onboarding_completed_at/); assert.match(server, /!profile\?\.onboarding_completed_at/); assert.match(server, /feature_guide_completed_at/); assert.match(server, /\/onboarding\/guide\?next=/); });
test("personalized feature guide is skippable and offers popular features after the selected tour", () => { for (const file of ["components/auth/feature-guide.tsx","app/(public)/onboarding/guide/page.tsx","app/api/onboarding/guide/route.ts"]) assert.equal(existsSync(join(root,file)), true, file); const guide = read("components/auth/feature-guide.tsx"); assert.match(guide, /Skip guide/); assert.match(guide, /Want a quick look at popular features too\?/); assert.match(guide, /community/); assert.match(guide, /resources/); assert.match(guide, /finish\("skip"\)/); });
test("restricted profile surface preserves its intended destination", () => { const page = read("app/(student)/settings/profile/page.tsx"); const prompt = read("components/auth/login-required.tsx"); assert.match(page, /next="\/settings\/profile"/); assert.match(prompt, /loginPathFor\(next\)/); });
test("authenticated users can reach a refined logout confirmation without completing onboarding", () => { const topbar = read("components/shell/topbar-controls.tsx"); const logout = read("app/(public)/logout/page.tsx"); assert.match(topbar, /Sign out of this device/); assert.match(topbar, /\/logout\?next=/); assert.match(logout, /Sign out of CA Progress\?/); assert.match(logout, /Stay signed in/); assert.match(logout, /\/auth\/signout/); });
test("onboarding copy is product-facing", () => { const wizard = read("components/auth/onboarding-wizard.tsx"); assert.doesNotMatch(wizard, /V2 workspace|Phase 3 academic catalog|Save & continue/); assert.match(wizard, /Choose the group you want to study and track/); assert.match(wizard, /Choose the exam attempt you are currently preparing for/); });
