import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
const read=(file)=>readFileSync(new URL(`../${file}`,import.meta.url),"utf8");

test("Phase 9 models Plan to Page to Feature with every allowance",()=>{const sql=read("d1/migrations/0046_product_consistency_phase9_granular_entitlements.sql");for(const value of ["plan_policy_versions","plan_policy_pages","plan_policy_features","quantity_limit","time_limit_minutes","storage_limit_bytes","file_size_limit_bytes","reset_period","retention_days"])assert.match(sql,new RegExp(value));});
test("Phase 9 supports versioning grandfathering promotions overrides and scheduled changes",()=>{const sql=read("d1/migrations/0046_product_consistency_phase9_granular_entitlements.sql");for(const value of ["plan_policy_publications","subscription_policy_contracts","grandfathered","entitlement_overrides","plan_promotions","plan_promotion_grants","scheduled_plan_changes","payment_order_policy_snapshots"])assert.match(sql,new RegExp(value));});
test("Phase 9 has atomic idempotent quota reservations",()=>{const source=read("lib/billing/granular-policy.ts");const sql=read("d1/migrations/0046_product_consistency_phase9_granular_entitlements.sql");assert.match(sql,/idempotency_key TEXT PRIMARY KEY/);assert.match(source,/reserveEntitlementUsage/);assert.match(source,/database\.batch/);assert.match(source,/used_value\+excluded\.used_value<=\?5/);});
test("published policy drives server enforcement checkout and frontend",()=>{const worker=read("workers/billing/index.ts"),access=read("lib/billing/feature-access.ts"),pricing=read("components/billing/pricing-client.tsx");assert.match(worker,/plan_policy_publications/);assert.match(worker,/payment_order_policy_snapshots/);assert.match(worker,/subscription_policy_contracts/);assert.match(access,/entitlement\.allowed/);assert.match(pricing,/entitlements\.find/);assert.doesNotMatch(pricing,/monthlyPriceInr/);});
test("admin can duplicate edit publish rollback preview meter promote schedule and override",()=>{const page=read("app/(admin)/admin/plans/page.tsx"),actions=read("app/(admin)/admin/plans/actions.ts"),service=read("lib/billing/granular-policy.ts");for(const value of ["Duplicate as draft","Publish policy","Restore this version","View all plans","Student usage meters","Grant a promotion","Schedule a plan change","Per-student override"])assert.match(page,new RegExp(value));for(const capability of ["billing.plan.configure","billing.manage","entitlements.override"])assert.match(actions,new RegExp(capability.replace(".","\\.")));assert.match(service,/invalidateSharedPublicCache/);assert.match(service,/invalidateUserFeatureCache/);});
test("Phase 9 retained migration is deployed after Phase 8",()=>{const runner=read("scripts/apply-retained-d1-migrations.mjs");assert.match(runner,/0046_product_consistency_phase9_granular_entitlements/);assert.match(runner,/BETWEEN '0012' AND '0046'/);});
