import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const read=(path)=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");

test("P3 adds durable provider plan, subscription, event, charge and action state",()=>{const sql=read("d1/migrations/0051_refinement_phase3_razorpay_subscriptions.sql");for(const table of ["razorpay_plan_mappings","razorpay_subscriptions","razorpay_subscription_events","razorpay_subscription_charges","subscription_action_requests"])assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(sql,/provider_event_id TEXT NOT NULL UNIQUE/);assert.match(sql,/payload_sha256 TEXT NOT NULL/);assert.match(sql,/provider_subscription_id TEXT/);assert.match(sql,/Razorpay access requires verified provider evidence/);assert.match(sql,/trg_razorpay_subscription_plan_change_applied/);assert.match(read("scripts/apply-retained-d1-migrations.mjs"),/0051_refinement_phase3_razorpay_subscriptions\.sql/);});

test("P3 uses Razorpay Plans and Subscriptions without accepting browser price or currency",()=>{const worker=read("workers/billing/p3.ts"),pricing=read("components/billing/pricing-client.tsx");assert.match(worker,/rp<ProviderPlan>\("plans"/);assert.match(worker,/rp<ProviderSubscription>\("subscriptions"/);assert.match(worker,/body\?\.planId/);assert.doesNotMatch(worker,/body\?\.amount/);assert.doesNotMatch(worker,/body\?\.currency/);assert.match(pricing,/subscription_id:created\.subscriptionId/);});

test("P3 verifies subscription checkout using payment id plus subscription id and re-fetches provider state",()=>{const worker=read("workers/billing/p3.ts");assert.match(worker,/`\$\{paymentId\}\|\$\{subscriptionId\}`/);assert.match(worker,/getSubscription\(subscriptionId,p\)/);assert.match(worker,/getPayment\(paymentId,p\)/);assert.match(worker,/payment\.subscription_id!==subscriptionId/);});

test("P3 signed webhooks are replay safe, evidence-bounded and provider-state reconciled",()=>{const worker=read("workers/billing/p3.ts");assert.match(worker,/x-razorpay-signature/);assert.match(worker,/x-razorpay-event-id/);assert.match(worker,/INSERT OR IGNORE INTO razorpay_subscription_events/);assert.match(worker,/payload_sha256/);assert.match(worker,/safeSubscriptionState/);assert.match(worker,/eventType/);assert.doesNotMatch(worker,/evidence_json[^\n]*raw/);});

test("P3 implements paid-through grace, pause resume cancellation and cycle-end plan changes",()=>{const worker=read("workers/billing/p3.ts");assert.match(worker,/graceUntil/);assert.match(worker,/subscriptions\/\$\{encodeURIComponent\(subscriptionId\)\}\/pause/);assert.match(worker,/subscriptions\/\$\{encodeURIComponent\(subscriptionId\)\}\/resume/);assert.match(worker,/cancel_at_cycle_end/);assert.match(worker,/schedule_change_at:\"cycle_end\"/);assert.match(worker,/proration:\"none\"/);assert.match(worker,/cancelled Razorpay subscription cannot be resumed/);});

test("P3 pricing and billing use recurring checkout and remove manual renewal wording",()=>{const pricing=read("components/billing/pricing-client.tsx"),billing=read("app/(student)/billing/page.tsx"),settings=read("app/(student)/settings/page.tsx");assert.match(pricing,/create-subscription/);assert.match(pricing,/verify-subscription/);assert.match(pricing,/subscription_id/);assert.doesNotMatch(pricing,/create-order/);assert.doesNotMatch(`${billing}\n${settings}`,/Manual renewal/i);assert.match(billing,/SubscriptionControls/);assert.match(settings,/recurring Razorpay state/i);});
