import Link from "next/link";
import { requireAdminPageCapability } from "@/lib/authorization/server";
import { getBillingOperations } from "@/lib/billing/p4-admin";
import { createBillingCampaign, publishBillingCampaign, retireBillingCampaign, grantBillingCampaignAccess, updateCampaignAllowlist, runBillingOperation } from "./actions";

export const dynamic="force-dynamic";

const money=(value:unknown)=>`₹${(Number(value??0)/100).toFixed(2)}`;
const date=(value:unknown)=>value?new Date(String(value)).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"}):"—";
const text=(value:unknown)=>value===null||value===undefined||value===""?"—":String(value);
const input="rounded-lg border bg-background px-3 py-2 text-sm";
function Stat({label,value}:{label:string;value:unknown}){return <div className="rounded-xl border p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 text-2xl font-semibold">{String(value??0)}</div></div>;}

export default async function AdminBillingPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const actor=await requireAdminPageCapability("billing.read"),params=await searchParams;
  const one=(key:string)=>typeof params[key]==="string"?String(params[key]):"";
  const model=await getBillingOperations({query:one("q"),state:one("state"),planId:one("plan"),dateFrom:one("from"),dateTo:one("to"),mismatchOnly:one("mismatch")==="1"});
  const canManage=actor.role==="owner"||actor.role==="parent_owner",metrics=model.metrics??{};
  return <main className="mx-auto w-full max-w-[1500px] space-y-6 p-4 md:p-6">
    <header className="flex flex-col gap-2 md:flex-row md:items-end md:justify-between"><div><h1 className="text-2xl font-semibold">Billing operations</h1><p className="text-sm text-muted-foreground">Razorpay reconciliation, settlement evidence, access grants and campaign controls.</p></div><div className="text-xs text-muted-foreground">Read: billing.read · Mutations: Owner / Parent Owner</div></header>

    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Stat label="Open subscriptions" value={metrics.open_subscriptions}/><Stat label="Financial attention" value={metrics.financial_attention}/><Stat label="Open cases" value={metrics.open_cases}/><Stat label="Critical alerts" value={metrics.critical_alerts}/><Stat label="Campaign redemptions" value={metrics.campaign_redemptions}/><Stat label="Campaign liability" value={money(metrics.campaign_liability)}/></section>

    <form className="grid gap-3 rounded-xl border p-4 md:grid-cols-7">
      <input name="q" defaultValue={model.filters.query} placeholder="Email, user, order, payment, subscription" className={`${input} md:col-span-2`}/>
      <input name="state" defaultValue={model.filters.state} placeholder="Provider state" className={input}/><input name="plan" defaultValue={model.filters.planId} placeholder="Plan ID" className={input}/>
      <label className="text-xs text-muted-foreground">From<input name="from" type="date" defaultValue={model.filters.dateFrom} className={`${input} mt-1 w-full text-foreground`}/></label><label className="text-xs text-muted-foreground">To<input name="to" type="date" defaultValue={model.filters.dateTo} className={`${input} mt-1 w-full text-foreground`}/></label>
      <label className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><input type="checkbox" name="mismatch" value="1" defaultChecked={model.filters.mismatchOnly}/>Mismatch only</label>
      <button className="rounded-lg bg-foreground px-4 py-2 text-sm text-background md:col-span-7">Apply filters</button>
    </form>

    <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Mismatch queue</h2><span className="text-xs text-muted-foreground">{model.cases.length} visible</span></div><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[940px] text-left text-sm"><thead className="border-b bg-muted/30 text-xs"><tr><th className="p-3">Severity</th><th>Reason</th><th>User</th><th>Subscription</th><th>State</th><th>Last seen</th>{canManage&&<th>Recovery</th>}</tr></thead><tbody>{model.cases.map(row=><tr key={text(row.id)} className="border-b last:border-0"><td className="p-3">{text(row.severity)}</td><td>{text(row.reason_code)}</td><td>{row.user_id?<Link className="underline" href={`/admin/users/${encodeURIComponent(String(row.user_id))}/subscription-access`}>{text(row.user_id)}</Link>:"—"}</td><td>{text(row.provider_subscription_id)}</td><td>{text(row.state)}</td><td>{date(row.last_seen_at)}</td>{canManage&&<td className="py-2 pr-3"><form action={runBillingOperation} className="flex gap-2"><input type="hidden" name="requestId" value={crypto.randomUUID().replaceAll("-","")}/><input type="hidden" name="caseId" value={text(row.id)}/><input type="hidden" name="action" value="ack_case"/><input type="hidden" name="confirmation" value="CONFIRM ACK CASE"/><input type="hidden" name="reason" value="Owner acknowledged reconciliation case"/><button className="rounded-md border px-2 py-1 text-xs">Acknowledge</button></form></td>}</tr>)}{!model.cases.length&&<tr><td className="p-6 text-muted-foreground" colSpan={7}>No open reconciliation cases.</td></tr>}</tbody></table></div></section>

    {canManage&&<section className="grid gap-4 lg:grid-cols-2"><form action={runBillingOperation} className="space-y-3 rounded-xl border p-4"><div><h2 className="font-semibold">Bounded recovery action</h2><p className="text-xs text-muted-foreground">Provider state remains authoritative. There is intentionally no “mark paid” control.</p></div><input type="hidden" name="requestId" value={crypto.randomUUID().replaceAll("-","")}/><input name="subscriptionId" required placeholder="Razorpay subscription ID (sub_…)" className={`w-full ${input}`}/><select name="action" className={`w-full ${input}`}><option value="reconcile">Reconcile now</option><option value="pause">Pause</option><option value="resume">Resume</option><option value="cancel_period_end">Cancel at period end</option><option value="change_plan">Change plan at cycle end</option></select><input name="targetPlanId" placeholder="Target plan ID (plan change only)" className={`w-full ${input}`}/><input name="confirmation" required placeholder="CONFIRM RECONCILE / PAUSE / RESUME / CANCEL PERIOD END / CHANGE PLAN" className={`w-full ${input}`}/><textarea name="reason" required minLength={3} placeholder="Operational reason" className="min-h-20 w-full rounded-lg border bg-background px-3 py-2 text-sm"/><button className="rounded-lg bg-foreground px-4 py-2 text-sm text-background">Run operation</button></form>

      <form action={createBillingCampaign} className="grid gap-3 rounded-xl border p-4 sm:grid-cols-2"><div className="sm:col-span-2"><h2 className="font-semibold">Create campaign draft</h2><p className="text-xs text-muted-foreground">Paid campaigns publish only with a positive internal discount rule and an approved Razorpay Offer. Free/reward campaigns require a target plan and access period.</p></div><input name="campaignId" placeholder="Existing campaign ID for new version" className={input}/><input name="campaignKey" required placeholder="campaign-key" className={input}/><input name="name" required placeholder="Campaign name" className={input}/><select name="campaignType" className={input}><option value="discount">Discount</option><option value="intro">Intro</option><option value="free_access">Free access</option><option value="reward">Reward</option></select><select name="discountKind" className={input}><option value="none">No monetary discount</option><option value="fixed">Fixed subunits</option><option value="percentage">Percentage (basis points)</option></select><input name="discountValue" type="number" min="0" defaultValue="0" placeholder="Discount value" className={input}/><input name="providerOfferId" placeholder="offer_… for paid discount" className={input}/><input name="promoCode" placeholder="Promo code" className={input}/><input name="targetPlanId" placeholder="Target plan ID" className={input}/><input name="attemptKey" placeholder="Attempt key (optional)" className={input}/><input name="maxRedemptions" type="number" min="1" placeholder="Max redemptions" className={input}/><input name="firstNLimit" type="number" min="1" placeholder="First-N cap" className={input}/><input name="perUserLimit" type="number" min="1" defaultValue="1" className={input}/><input name="freeAccessDays" type="number" min="0" defaultValue="0" placeholder="Free access days" className={input}/><input name="discountCycles" type="number" min="1" defaultValue="1" className={input}/><input name="priority" type="number" defaultValue="100" className={input}/><label className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><input type="checkbox" name="requireAllowlist"/>Require allowlist</label><input name="startsAt" type="datetime-local" required className={input}/><input name="endsAt" type="datetime-local" required className={input}/><input name="claimStartsAt" type="datetime-local" required className={input}/><input name="claimEndsAt" type="datetime-local" required className={input}/><textarea name="description" placeholder="Description" className="min-h-16 rounded-lg border bg-background px-3 py-2 text-sm sm:col-span-2"/><textarea name="reason" required minLength={3} placeholder="Change reason" className="min-h-16 rounded-lg border bg-background px-3 py-2 text-sm sm:col-span-2"/><button className="rounded-lg bg-foreground px-4 py-2 text-sm text-background sm:col-span-2">Create draft</button></form>

      <form action={updateCampaignAllowlist} className="space-y-3 rounded-xl border p-4 lg:col-span-2"><div><h2 className="font-semibold">Campaign allowlist</h2><p className="text-xs text-muted-foreground">Used only by campaigns configured to require an allowlist.</p></div><div className="grid gap-3 md:grid-cols-5"><input name="versionId" required placeholder="Campaign version ID" className={input}/><input name="userId" required placeholder="User ID" className={input}/><select name="allowed" className={input}><option value="1">Allow</option><option value="0">Remove</option></select><input name="reason" required minLength={3} placeholder="Reason" className={input}/><button className="rounded-lg border px-4 py-2 text-sm">Update allowlist</button></div></form></section>}

    <section className="space-y-3"><h2 className="text-lg font-semibold">Campaigns</h2><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[1180px] text-left text-sm"><thead className="border-b bg-muted/30 text-xs"><tr><th className="p-3">Campaign</th><th>Version</th><th>Type</th><th>State</th><th>Claims</th><th>Inventory</th><th>Liability</th><th>Window</th>{canManage&&<th>Controls</th>}</tr></thead><tbody>{model.campaigns.map(row=><tr key={text(row.id)} className="border-b last:border-0"><td className="p-3"><div className="font-medium">{text(row.name)}</div><div className="text-xs text-muted-foreground">{text(row.campaign_key)}</div></td><td>{text(row.version)}</td><td>{text(row.campaign_type)}</td><td>{text(row.state)}</td><td>{text(row.applied_claims)}</td><td>{row.max_redemptions==null?"Unlimited":Math.max(0,Number(row.max_redemptions)-Number(row.claimed_count??0))}</td><td>{money(row.liability_subunits)}</td><td>{date(row.claim_starts_at)} → {date(row.claim_ends_at)}</td>{canManage&&<td className="py-2 pr-3"><div className="space-y-2">{text(row.state)==="draft"&&<form action={publishBillingCampaign} className="flex gap-2"><input type="hidden" name="versionId" value={text(row.id)}/><input name="reason" required minLength={3} placeholder="Publish reason" className="w-36 rounded-md border px-2 py-1 text-xs"/><button className="rounded-md border px-2 py-1 text-xs">Publish</button></form>}{text(row.state)==="published"&&["free_access","reward"].includes(text(row.campaign_type))&&<form action={grantBillingCampaignAccess} className="flex flex-wrap gap-2"><input type="hidden" name="requestId" value={crypto.randomUUID().replaceAll("-","")}/><input type="hidden" name="versionId" value={text(row.id)}/><input name="userId" required placeholder="User ID" className="w-32 rounded-md border px-2 py-1 text-xs"/><input name="reason" required minLength={8} placeholder="Grant reason" className="w-36 rounded-md border px-2 py-1 text-xs"/><button className="rounded-md border px-2 py-1 text-xs">Grant</button></form>}{text(row.state)==="published"&&<form action={retireBillingCampaign} className="flex gap-2"><input type="hidden" name="versionId" value={text(row.id)}/><input name="reason" required minLength={3} placeholder="Retire reason" className="w-32 rounded-md border px-2 py-1 text-xs"/><button className="rounded-md border px-2 py-1 text-xs">Retire</button></form>}</div></td>}</tr>)}{!model.campaigns.length&&<tr><td className="p-6 text-muted-foreground" colSpan={9}>No campaigns yet.</td></tr>}</tbody></table></div></section>

    <section className="space-y-3"><div className="flex flex-wrap items-end justify-between gap-2"><div><h2 className="text-lg font-semibold">Subscriptions & provider financial state</h2><p className="text-xs text-muted-foreground">Open a user’s access record to inspect/revoke manual grants without altering Razorpay payment history.</p></div></div><div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="border-b bg-muted/30 text-xs"><tr><th className="p-3">User</th><th>Email</th><th>Plan</th><th>Provider subscription</th><th>Provider state</th><th>Financial</th><th>Paid through</th><th>Last reconciled</th><th>Access record</th></tr></thead><tbody>{model.subscriptions.map(row=><tr key={text(row.id)} className="border-b last:border-0"><td className="p-3">{text(row.user_id)}</td><td>{text(row.email)}</td><td>{text(row.plan_name)}</td><td>{text(row.provider_subscription_id)}</td><td>{text(row.status)}</td><td>{text(row.financial_state)}</td><td>{date(row.paid_through_at)}</td><td>{date(row.last_reconciled_at)}</td><td><Link className="underline" href={`/admin/users/${encodeURIComponent(String(row.user_id))}/subscription-access`}>Timeline & grants</Link></td></tr>)}{!model.subscriptions.length&&<tr><td className="p-6 text-muted-foreground" colSpan={9}>No recurring subscriptions match these filters.</td></tr>}</tbody></table></div></section>

    <section className="space-y-3"><h2 className="text-lg font-semibold">Unified billing timeline</h2><div className="max-h-[620px] overflow-auto rounded-xl border">{model.timeline.map((item,index)=>{const evidence="evidence" in item?String(item.evidence??""):"";return <article key={`${item.kind}:${item.id}:${index}`} className="grid gap-2 border-b p-3 text-sm last:border-0 md:grid-cols-[130px_180px_1fr_170px]"><div><strong>{item.kind}</strong><div className="text-xs text-muted-foreground">{date(item.at)}</div></div><div>{item.userId&&item.userId!=="—"?<Link className="underline" href={`/admin/users/${encodeURIComponent(item.userId)}/subscription-access`}>{item.userId}</Link>:"—"}</div><div><div className="font-mono text-xs">{item.id}</div><div>{item.detail}</div>{evidence?<details className="mt-2"><summary className="cursor-pointer text-xs underline">Safe evidence</summary><pre className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap rounded-md border p-2 text-xs">{evidence}</pre></details>:null}</div><div>{item.status}</div></article>;})}{!model.timeline.length?<p className="p-6 text-sm text-muted-foreground">No billing timeline entries for the current result set.</p>:null}</div></section>

    <section className="grid gap-4 xl:grid-cols-2"><div className="space-y-3"><h2 className="text-lg font-semibold">Orders & payments</h2><div className="max-h-[520px] overflow-auto rounded-xl border">{model.orders.map(row=><div key={text(row.id)} className="grid grid-cols-2 gap-2 border-b p-3 text-sm last:border-0"><span>{text(row.provider_order_id)}</span><span>{text(row.provider_payment_id)}</span><span>{text(row.plan_name)}</span><span>{money(row.amount_subunits)} · {text(row.status)}</span></div>)}</div></div><div className="space-y-3"><h2 className="text-lg font-semibold">Recurring charges</h2><div className="max-h-[520px] overflow-auto rounded-xl border">{model.charges.map(row=><div key={text(row.provider_payment_id)} className="grid grid-cols-2 gap-2 border-b p-3 text-sm last:border-0"><span>{text(row.provider_payment_id)}</span><span>{money(row.amount_subunits)} · {text(row.status)}</span><span>Refund: {text(row.refund_state)}</span><span>Dispute: {text(row.dispute_state)}</span></div>)}</div></div><div className="space-y-3"><h2 className="text-lg font-semibold">Webhook deliveries</h2><div className="max-h-[520px] overflow-auto rounded-xl border">{model.events.map(row=><div key={text(row.id)} className="border-b p-3 text-sm last:border-0"><div className="grid grid-cols-2 gap-2"><span>{text(row.event_type)}</span><span>{text(row.outcome)}</span><span>{text(row.provider_event_id)}</span><span>{date(row.received_at)}</span></div>{row.evidence_json?<details className="mt-2"><summary className="cursor-pointer text-xs underline">Evidence</summary><pre className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap rounded-md border p-2 text-xs">{text(row.evidence_json)}</pre></details>:null}</div>)}</div></div><div className="space-y-3"><h2 className="text-lg font-semibold">Access grants</h2><div className="max-h-[520px] overflow-auto rounded-xl border">{model.access.map(row=><div key={text(row.id)} className="grid grid-cols-2 gap-2 border-b p-3 text-sm last:border-0"><span>{text(row.plan_name)}</span><span>{text(row.status)}</span><span>{text(row.source)}</span><span>{date(row.ends_at)}</span></div>)}</div></div></section>

    <section className="grid gap-4 lg:grid-cols-2"><div><h2 className="mb-3 text-lg font-semibold">Reconciliation runs</h2><div className="rounded-xl border">{model.runs.map(row=><div key={text(row.id)} className="grid grid-cols-3 gap-2 border-b p-3 text-sm last:border-0"><span>{text(row.trigger_kind)} · {text(row.state)}</span><span>{text(row.scanned_count)} scanned / {text(row.queued_count)} queued</span><span>{date(row.started_at)}</span></div>)}</div></div><div><h2 className="mb-3 text-lg font-semibold">Operational alerts</h2><div className="rounded-xl border">{model.alerts.map(row=><div key={text(row.id)} className="border-b p-3 text-sm last:border-0"><div className="font-medium">{text(row.severity)} · {text(row.alert_type)}</div><div className="text-muted-foreground">{text(row.message)}</div></div>)}</div></div></section>
  </main>;
}
