// @ts-expect-error Generated by the OpenNext build.
import { runWithCloudflareRequestContext } from "../../.open-next/cloudflare/init.js";
// @ts-expect-error Generated by the OpenNext build.
import { handler } from "../../.open-next/server-functions/community/handler.mjs";
import { runNextServer } from "../next-runtime";

type WorkerContext = { waitUntil(promise: Promise<unknown>): void };

const communityWebWorker = {
  fetch(request: Request, env: Record<string, unknown>, ctx: WorkerContext) {
    return runWithCloudflareRequestContext(request, env, ctx, () => runNextServer(request, env, ctx, handler));
  },
};

export default communityWebWorker;
