// @ts-expect-error Generated by the OpenNext build.
import { runWithCloudflareRequestContext } from "../../.open-next/cloudflare/init.js";
// @ts-expect-error Generated by the OpenNext build.
import { handler } from "../../.open-next/server-functions/community/index.mjs";
import { runNextServer } from "../next-runtime";

type WorkerContext = { waitUntil(promise: Promise<unknown>): void };

const communityWebWorker = {
  fetch(request: Request, env: Record<string, unknown>, ctx: WorkerContext) {
    return runNextServer(request, env, ctx, (runtimeEnv) =>
      runWithCloudflareRequestContext(request, runtimeEnv, ctx, () => handler(request, runtimeEnv, ctx, request.signal)),
    );
  },
};

export default communityWebWorker;
