import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHeader } from "@/components/ui/page-header";
import { getAdminUserById } from "@/lib/admin/phase1";
import { getUserSubscriptionAccess,listGrantablePlans } from "@/lib/admin/subscription-access";
import { hasAdminCapability } from "@/lib/authorization/capabilities.mjs";
import { requireAdminPageCapability } from "@/lib/authorization/server";
import { changeManualExpiryAction,grantManualAccessAction,revokeManualAccessAction } from "./actions";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Subscription access | CA Progress Admin"};
const when=(value:unknown)=>typeof value==="string"?new Date(value).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"}):"—";
const localInput=(date:Date)=>new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16);

export default async function SubscriptionAccessPage({params,searchParams}:{params:Promise<{userId:string}>;searchParams:Promise<Record<string,string|undefined>>}){
  const current=await requireAdminPageCapability("billing.read"),{userId:encoded}=await params,query=await searchParams;
  const userId=decodeURIComponent(encoded),user=await getAdminUserById(userId);if(!user)notFound();
  const [access,plans]=await Promise.all([getUserSubscriptionAccess(userId),listGrantablePlans()]);
  const canManage=hasAdminCapability(current.role,"billing.manage")&&["owner","parent_owner"].includes(current.role);
  const now=new Date(),month=new Date(now);month.setUTCMonth(month.getUTCMonth()+1);
  return <main className="admin-page">
    <PageHeader preview={false} eyebrow="Users · Billing" title="Subscription access" description={`${user.displayName??user.email??user.userId} · Explain and manage access without creating fake payments.`}/>
    <div className="admin-user-actions"><Link className="ui-button ui-button--ghost" href={`/admin/users/${encodeURIComponent(userId)}`}>← User detail</Link><Link className="ui-button ui-button--ghost" href={`/admin/users?q=${encodeURIComponent(user.email??userId)}`}>Search users</Link></div>
    {query.notice?<p className="ui-notice ui-notice--success" role="status">{query.notice}</p>:null}
    <section className="ui-card admin-access-summary"><p className="eyebrow">EFFECTIVE ACCESS</p><h2>{access.effective.planName??access.effective.label}</h2><p><strong>{access.effective.label}</strong> · {access.effective.status}</p><p>{access.effective.detail}</p><small>Precedence: paid subscription → paid-through/grace → promotion → leaderboard reward → manual grant/override → Free.</small></section>
    <section><h2>Access sources</h2><div className="data-view"><table className="data-table"><thead><tr><th>Source</th><th>Plan / feature</th><th>Status</th><th>Window</th><th>Explanation</th></tr></thead><tbody>{access.sources.map(source=><tr key={`${source.kind}:${source.id}`}><td data-label="Source"><strong>{source.label}</strong></td><td data-label="Plan / feature">{source.planName??source.detail}</td><td data-label="Status">{source.status}</td><td data-label="Window">{when(source.startsAt)}<small>to {when(source.endsAt)}</small></td><td data-label="Explanation">{source.detail}</td></tr>)}</tbody></table></div></section>
    {canManage?<section className="ui-card admin-access-management"><h2>Grant manual subscription access</h2><p>This creates an explicit subscription grant and policy contract. It never creates a payment order or payment event.</p><form action={grantManualAccessAction} className="admin-access-form"><input type="hidden" name="userId" value={userId}/><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()}/><label>Published plan<select name="planId" required>{plans.map(plan=><option key={String(plan.id)} value={String(plan.id)}>{String(plan.name)} · {String(plan.billing_cycle)}</option>)}</select></label><label>Starts at<input name="startsAt" type="datetime-local" required defaultValue={localInput(now)}/></label><label>Expires at (optional)<input name="endsAt" type="datetime-local" defaultValue={localInput(month)}/></label><label className="admin-access-form__wide">Reason<textarea name="reason" required minLength={8} maxLength={1000} placeholder="Why this access is being granted"/></label><div className="admin-action-preview admin-access-form__wide"><strong>Preview</strong><p>The selected plan will apply for the stated window. The immutable audit record will identify you, the user, plan, reason and dates.</p><label><input type="checkbox" name="confirmed" required/> I reviewed this grant and confirm no payment should be recorded.</label></div><button className="ui-button ui-button--primary admin-access-form__wide">Grant access</button></form></section>:<p className="ui-notice">Manual access changes require an Owner or Parent Owner. This view remains read-only.</p>}
    <section><h2>Manual grant lifecycle</h2>{access.grants.length?<div className="admin-grant-list">{access.grants.map(grant=><article className="ui-card admin-grant" key={grant.id}><header><div><strong>{grant.planName}</strong><small>{grant.state} · {when(grant.startsAt)} to {when(grant.endsAt)}</small></div><code>{grant.id}</code></header><p>{grant.reason}</p>{grant.revokeReason?<p><strong>Revoked:</strong> {grant.revokeReason}</p>:null}{canManage&&grant.state!=="revoked"?<div className="admin-grant-actions"><details><summary>Extend or schedule expiry</summary><form action={changeManualExpiryAction}><input type="hidden" name="userId" value={userId}/><input type="hidden" name="grantId" value={grant.id}/><label>New expiry<input name="endsAt" type="datetime-local" required/></label><label>Reason<textarea name="reason" required minLength={8}/></label><p className="admin-action-preview">Preview: changes only this manual grant and records an immutable event.</p><label><input type="checkbox" name="confirmed" required/> Confirm expiry change</label><button className="ui-button ui-button--secondary">Update expiry</button></form></details><details><summary>Revoke now</summary><form action={revokeManualAccessAction}><input type="hidden" name="userId" value={userId}/><input type="hidden" name="grantId" value={grant.id}/><label>Reason<textarea name="reason" required minLength={8}/></label><p className="admin-action-preview">Preview: access from this grant ends immediately. Existing payment history is untouched.</p><label><input type="checkbox" name="confirmed" required/> Confirm immediate revocation</label><button className="ui-button ui-button--danger">Revoke access</button></form></details></div>:null}</article>)}</div>:<p>No manual access grants.</p>}</section>
    <section><h2>Immutable subscription history</h2><div className="data-view"><table className="data-table"><thead><tr><th>Event</th><th>Plan</th><th>Source</th><th>Window</th><th>Recorded</th></tr></thead><tbody>{access.events.length?access.events.map(event=><tr key={String(event.id)}><td data-label="Event">{String(event.event_type)}</td><td data-label="Plan">{String(event.plan_name)}</td><td data-label="Source">{String(event.source)}</td><td data-label="Window">{when(event.starts_at)}<small>to {when(event.ends_at)}</small></td><td data-label="Recorded">{when(event.created_at)}</td></tr>):<tr><td colSpan={5} data-label="History">No subscription events recorded.</td></tr>}</tbody></table></div></section>
    <section><h2>Payment summary</h2><p>Payment data is displayed separately so administrative grants cannot be mistaken for money received.</p><div className="data-view"><table className="data-table"><thead><tr><th>Order</th><th>Plan</th><th>Amount</th><th>Status</th><th>Paid</th></tr></thead><tbody>{access.payments.length?access.payments.map(payment=><tr key={String(payment.id)}><td data-label="Order"><code>{String(payment.provider_order_id)}</code></td><td data-label="Plan">{String(payment.plan_name)}</td><td data-label="Amount">{String(payment.currency)} {(Number(payment.amount_subunits)/100).toFixed(2)}</td><td data-label="Status">{String(payment.status)}</td><td data-label="Paid">{when(payment.paid_at)}</td></tr>):<tr><td colSpan={5} data-label="Payments">No payment orders recorded.</td></tr>}</tbody></table></div></section>
  </main>;
}
