import type { Metadata } from "next";
import Link from "next/link";
import { LoginRequired } from "@/components/auth/login-required";
import { SubscriptionControls } from "@/components/billing/subscription-controls";
import { Card, CardBody, CardHeader } from "@/components/ui/card";
import { Icon } from "@/components/ui/icon";
import { PageHeader } from "@/components/ui/page-header";
import { getRecurringBillingState } from "@/lib/billing/recurring-service";
import { getBillingModel } from "@/lib/billing/service";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Billing | CA Progress"};
const money=(amount:number,currency:string)=>new Intl.NumberFormat("en-IN",{style:"currency",currency,maximumFractionDigits:2}).format(amount/100);
const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";
function PaymentState({state}:{state?:string}){if(state==="success")return <div className="phase11-notice phase11-notice--success" role="status">Razorpay authenticated the recurring subscription. Access below comes only from server-reconciled provider state.</div>;if(state==="pending")return <div className="phase11-notice phase11-notice--info" role="status">Razorpay authentication is verified, but the subscription is still waiting for its provider lifecycle transition. Signed webhooks can complete it independently.</div>;if(state==="failed")return <div className="phase11-notice phase11-notice--error" role="alert">Subscription authentication failed. No recurring access was granted. <Link href="/pricing">Retry checkout</Link></div>;return null;}

export default async function BillingPage({searchParams}:{searchParams:Promise<{payment?:string}>}){
  const [model,recurring]=await Promise.all([getBillingModel(),getRecurringBillingState()]),query=await searchParams;if(model.mode==="guest")return <div className="phase11-page"><LoginRequired next="/billing" title="Sign in to view billing"/></div>;const plan=model.currentPlan!;
  return <div className="phase11-page"><PageHeader preview={false} eyebrow="Billing" title="Subscription and payment history" description="Recurring products are reconciled against Razorpay. Paid-through access, grace, cancellation and plan transitions are server-enforced and remain separate from manual grants." actions={<div className="phase11-header-links"><Link href="/pricing">Compare plans</Link><Link href="/settings">Settings</Link></div>}/><PaymentState state={query.payment}/>
    <section className="phase11-billing-grid"><Card className="phase11-current-plan"><CardHeader title="Current plan" description="Server-enforced access"/><CardBody><div className="phase11-current-plan__hero"><span><Icon name="shield"/></span><div><small>{plan.tier_key.toUpperCase()}</small><strong>{plan.name}</strong><p>{plan.tagline}</p></div></div><dl className="phase11-current-plan__details"><div><dt>Billing cycle</dt><dd>{plan.billing_cycle}</dd></div><div><dt>Access status</dt><dd>{model.currentSubscription?.status??"Free fallback"}</dd></div><div><dt>Valid from</dt><dd>{date(model.currentSubscription?.starts_at)}</dd></div><div><dt>Active until</dt><dd>{model.currentSubscription?.ends_at?date(model.currentSubscription.ends_at):"No expiry"}</dd></div></dl><Link className="ui-button ui-button--primary" href="/pricing">Compare plans</Link></CardBody></Card>
      <Card><CardHeader title="Renewal state" description="Verified Razorpay subscription lifecycle"/><CardBody>{recurring.mode==="ready"&&recurring.subscription?<><dl className="phase11-current-plan__details"><div><dt>Provider state</dt><dd>{recurring.subscription.status}</dd></div><div><dt>Financial state</dt><dd>{recurring.subscription.financialState}</dd></div><div><dt>Next charge</dt><dd>{date(recurring.subscription.chargeAt)}</dd></div><div><dt>Paid through</dt><dd>{date(recurring.subscription.paidThroughAt)}</dd></div><div><dt>Grace through</dt><dd>{date(recurring.subscription.graceUntil)}</dd></div><div><dt>Successful cycles</dt><dd>{recurring.subscription.paidCount}</dd></div></dl><SubscriptionControls subscription={recurring.subscription} plans={recurring.availablePlans}/></>:<div className="phase11-renewal"><Icon name="clock"/><div><strong>{plan.tier_key==="free"?"No renewal required":"Legacy paid period"}</strong><p>{plan.tier_key==="free"?"Free access has no recurring charge.":"This paid period predates the recurring-subscription lifecycle. Starting a new recurring subscription will not shorten an existing paid-through period."}</p></div></div>}</CardBody></Card>
    </section>
    {recurring.mode==="ready"&&recurring.charges.length?<Card><CardHeader title="Payment history" description="Provider-linked recurring payment history."/><CardBody><div className="data-view"><table className="data-table"><thead><tr><th>Date</th><th>Amount</th><th>Status</th><th>Refund</th><th>Dispute</th><th>Provider reference</th></tr></thead><tbody>{recurring.charges.map(charge=><tr key={charge.paymentId}><td data-label="Date">{date(charge.createdAt)}</td><td data-label="Amount">{money(charge.amountSubunits,charge.currency)}</td><td data-label="Status">{charge.status}</td><td data-label="Refund">{charge.refundState}</td><td data-label="Dispute">{charge.disputeState}</td><td data-label="Provider reference"><code>{charge.paymentId}</code></td></tr>)}</tbody></table></div></CardBody></Card>:null}
    <Card><CardHeader title="Legacy order history" description="Earlier one-time Razorpay orders remain immutable for audit and migration continuity."/><CardBody>{model.payments?.length?<div className="data-view"><table className="data-table"><thead><tr><th>Date</th><th>Plan</th><th>Amount</th><th>Status</th><th>Provider reference</th></tr></thead><tbody>{model.payments.map(payment=>{const paymentPlan=model.plans?.find(item=>item.id===payment.plan_id);return <tr key={payment.id}><td data-label="Date">{date(payment.created_at)}</td><td data-label="Plan">{paymentPlan?.name??"Plan"}</td><td data-label="Amount">{money(payment.amount_subunits,payment.currency)}</td><td data-label="Status">{payment.status}</td><td data-label="Provider reference"><code>{payment.provider_payment_id??payment.provider_order_id}</code></td></tr>;})}</tbody></table></div>:<div className="phase11-empty"><Icon name="shield"/><strong>No paid transactions yet</strong><p>Recurring charges appear in the lifecycle ledger above.</p></div>}</CardBody></Card>
    <Card><CardHeader title="Subscription audit" description="Idempotent grant, extension, pause, resume and cancellation evidence."/><CardBody>{model.events?.length?<div className="phase11-event-list">{model.events.map(event=>{const eventPlan=model.plans?.find(item=>item.id===event.plan_id);return <div key={event.id}><span className="phase11-event-icon"><Icon name="check" size={15}/></span><div><strong>{event.event_type} · {eventPlan?.name??"Plan"}</strong><p>{date(event.starts_at)} → {event.ends_at?date(event.ends_at):"No expiry"}</p></div><time>{date(event.created_at)}</time></div>;})}</div>:<p className="phase11-mini-empty">No subscription access events yet.</p>}</CardBody></Card>
  </div>;
}
