import type { Metadata } from "next";
import Link from "next/link";
import { LoginRequired } from "@/components/auth/login-required";
import { Card, CardBody, CardHeader } from "@/components/ui/card";
import { PageHeader } from "@/components/ui/page-header";
import { getForecastPageModel } from "@/lib/smart-planner/service";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Completion Forecast | CA Progress" };

function statusLabel(status: string) {
  return ({ complete: "Syllabus complete", on_track: "On track", at_risk: "At risk", behind: "Behind pace", no_date: "Date unavailable" } as Record<string, string>)[status] ?? status;
}

export default async function ForecastPage() {
  const model = await getForecastPageModel();
  if (model.mode === "guest") return <div className="phase9-page"><LoginRequired next="/analytics/forecast" title="Sign in to view your completion forecast"/></div>;
  if (model.mode === "setup") return <div className="phase9-page"><PageHeader preview={false} eyebrow="Forecast" title="Complete your academic profile first." description="Forecasting requires a selected CA attempt and applicable syllabus."/><Link href="/settings/profile" className="ui-button ui-button--primary">Review profile</Link></div>;
  return <div className="phase9-page"><PageHeader preview={false} eyebrow="Forecast" title="Syllabus completion forecast" description="A transparent planning estimate based on your applicable chapters, saved completion timestamps and recent pace." actions={<div className="phase9-header-links"><Link href="/planner/today">Today Plan</Link><Link href="/planner/revision-settings">Revision settings</Link></div>}/><div className="phase9-forecast-layout"><div>
    <Card><CardHeader title={model.forecast.attemptLabel} description={model.forecast.dateSource === "verified_exam_date" ? "Verified exam-date anchor" : model.forecast.dateSource === "attempt_month" ? "Selected attempt-month planning anchor" : "No reliable date anchor"}/><CardBody><div className={`phase9-forecast-hero phase9-forecast-status--${model.forecast.status}`}><div><span>Status</span><strong>{statusLabel(model.forecast.status)}</strong><p>{model.forecast.explanation}</p></div><div className="phase9-forecast-percent"><strong>{model.forecast.completionPercent}%</strong><span>syllabus complete</span></div></div><div className="phase9-progress-track phase9-progress-track--large"><span style={{ width: `${Math.min(100, Math.max(0, model.forecast.completionPercent))}%` }}/></div><div className="phase9-forecast-stat-grid"><div><span>Completed chapters</span><strong>{model.forecast.completedChapters}/{model.forecast.totalChapters}</strong></div><div><span>Remaining</span><strong>{model.forecast.remainingChapters}</strong></div><div><span>Recent pace</span><strong>{model.forecast.observedChaptersPerWeek}/week</strong></div><div><span>Recommended pace</span><strong>{model.forecast.requiredChaptersPerWeek}/week</strong></div><div><span>Projected finish</span><strong>{model.forecast.projectedCompletionDate ?? "Not enough pace data"}</strong></div><div><span>Recommended target</span><strong>{model.forecast.targetCompletionDate ?? "Unavailable"}</strong></div></div>{model.forecast.dateSource === "attempt_month" ? <div className="phase9-estimate-banner">The official exam day is not verified in current V2 data. The engine uses the selected attempt month only as a planning estimate and will recalculate safely when verified dates arrive.</div> : null}</CardBody></Card>
    <Card><CardHeader title="Forecast history" description="Planner decisions are stored so changes are explainable and debuggable."/><CardBody>{model.history.length ? <div className="phase9-history">{model.history.map((point) => <div key={point.id}><time>{new Date(point.createdAt).toLocaleString()}</time><span className={`phase9-history-dot phase9-history-dot--${point.status}`}/><strong>{point.totalChapters ? Math.round((point.completedChapters / point.totalChapters) * 100) : 0}%</strong><span>{statusLabel(point.status)}</span><small>{point.projectedCompletionDate ? `Projected ${point.projectedCompletionDate}` : "No projected date"}</small></div>)}</div> : <div className="phase9-mini-empty">No historical forecast snapshots yet. A snapshot is stored on meaningful planner recomputation.</div>}</CardBody></Card>
  </div><aside><Card><CardHeader title="Risk signals" description="Warnings use visible progress and study-history inputs."/><CardBody>{model.warnings.length ? <div className="phase9-warning-stack">{model.warnings.map((warning) => <div className="phase9-warning" key={warning}>{warning}</div>)}</div> : <p className="phase9-mini-empty">No overdue-risk warning is active.</p>}{model.weakSubjects.length ? <div className="phase9-weak-list phase9-weak-list--forecast">{model.weakSubjects.map((subject) => <div key={subject.subjectId}><div><strong>{subject.subjectTitle}</strong><span>{subject.completionPercent}%</span></div><p>{subject.reason}</p></div>)}</div> : <p className="phase9-mini-empty">No weak-subject warning is active.</p>}</CardBody></Card></aside></div></div>;
}
