import "server-only";
import type { AppRole } from "@/lib/authorization/roles";
import { getD1RuntimeDatabase } from "@/lib/data/d1/client";
import { invalidateSharedPublicCache, invalidateUserFeatureCache } from "@/lib/cache/public";

type Actor={userId:string;role:AppRole};
const db=()=>getD1RuntimeDatabase();
const text=(value:unknown,label:string,limit=160)=>{const v=String(value??"").trim();if(!v)throw new Error(`${label} is required.`);if(v.length>limit)throw new Error(`${label} is too long.`);return v;};
const number=(value:unknown,label:string,min=0)=>{const v=Number(value);if(!Number.isFinite(v)||v<min)throw new Error(`${label} is invalid.`);return v;};
const optionalNumber=(value:unknown,label:string)=>String(value??"").trim()===""?null:number(value,label);
const key=(value:unknown,label:string)=>{const v=text(value,label,120);if(!/^[a-z0-9][a-z0-9._-]*$/.test(v))throw new Error(`${label} may contain lowercase letters, numbers, dots, dashes and underscores.`);return v;};
const audit=(database:ReturnType<typeof db>,actor:Actor,action:string,targetId:string,reason:string,previous:unknown,next:unknown,capability="billing.plan.configure")=>database.prepare(`INSERT INTO admin_audit_events(id,actor_user_id,actor_role,capability,action,target_type,target_id,reason,previous_value,new_value,trace_id,reversible,created_at) VALUES(?1,?2,?3,?4,?5,'plan_policy_version',?6,?7,?8,?9,?10,1,?11)`).bind(crypto.randomUUID(),actor.userId,actor.role,capability,action,targetId,reason,JSON.stringify(previous),JSON.stringify(next),crypto.randomUUID(),new Date().toISOString());

export async function listGranularPolicies(){
  const database=db();const [plans,features]=await Promise.all([
    database.prepare(`SELECT sp.id plan_id,sp.tier_key,sp.billing_cycle,sp.active,sp.checkout_enabled,pv.*,CASE WHEN pub.policy_version_id=pv.id THEN 1 ELSE 0 END is_live
      FROM subscription_plans sp JOIN plan_policy_versions pv ON pv.plan_id=sp.id LEFT JOIN plan_policy_publications pub ON pub.plan_id=sp.id ORDER BY sp.sort_order,pv.version DESC`).all<Record<string,unknown>>(),
    database.prepare("SELECT policy_version_id,page_key,feature_key,enabled,quantity_limit,time_limit_minutes,storage_limit_bytes,file_size_limit_bytes,reset_period,retention_days,upgrade_message,dependencies_json FROM plan_policy_features ORDER BY page_key,feature_key").all<Record<string,unknown>>(),
  ]);return{plans:plans.results??[],features:features.results??[]};
}

export async function createPolicyDraft(input:{planId:string;reason:string;actor:Actor}){
  const database=db();const planId=text(input.planId,"Plan",120);const reason=text(input.reason,"Reason",1000);
  const source=await database.prepare(`SELECT pv.* FROM plan_policy_publications pub JOIN plan_policy_versions pv ON pv.id=pub.policy_version_id WHERE pub.plan_id=?1`).bind(planId).first<Record<string,unknown>>();if(!source)throw new Error("Published plan policy was not found.");
  const next=await database.prepare("SELECT COALESCE(MAX(version),0)+1 value FROM plan_policy_versions WHERE plan_id=?1").bind(planId).first<{value:number}>();const id=crypto.randomUUID();
  const pages=await database.prepare("SELECT page_key,enabled FROM plan_policy_pages WHERE policy_version_id=?1").bind(source.id).all<Record<string,unknown>>();const features=await database.prepare("SELECT * FROM plan_policy_features WHERE policy_version_id=?1").bind(source.id).all<Record<string,unknown>>();
  const statements=[database.prepare(`INSERT INTO plan_policy_versions(id,plan_id,version,state,name,description,price_subunits,currency,billing_duration_value,billing_duration_unit,trial_days,grace_days,effective_at,created_by,change_reason) VALUES(?1,?2,?3,'draft',?4,?5,?6,?7,?8,?9,?10,?11,?12,?13,?14)`).bind(id,planId,Number(next?.value??1),source.name,source.description,source.price_subunits,source.currency,source.billing_duration_value,source.billing_duration_unit,source.trial_days,source.grace_days,source.effective_at,input.actor.userId,reason)];
  for(const p of pages.results??[])statements.push(database.prepare("INSERT INTO plan_policy_pages(policy_version_id,page_key,enabled) VALUES(?1,?2,?3)").bind(id,p.page_key,p.enabled));
  for(const f of features.results??[])statements.push(database.prepare(`INSERT INTO plan_policy_features(policy_version_id,page_key,feature_key,enabled,quantity_limit,time_limit_minutes,storage_limit_bytes,file_size_limit_bytes,reset_period,retention_days,upgrade_message,dependencies_json) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12)`).bind(id,f.page_key,f.feature_key,f.enabled,f.quantity_limit,f.time_limit_minutes,f.storage_limit_bytes,f.file_size_limit_bytes,f.reset_period,f.retention_days,f.upgrade_message,f.dependencies_json));
  statements.push(audit(database,input.actor,"plan.policy.draft",id,reason,source,{id,version:next?.value}));const result=await database.batch(statements);if(result.some(r=>r.success===false))throw new Error("Plan draft could not be created atomically.");return id;
}

export async function savePolicyBasics(input:{policyId:string;name:string;description:string;priceRupees:unknown;durationValue:unknown;durationUnit:string;trialDays:unknown;graceDays:unknown;effectiveAt:string;reason:string;actor:Actor}){const database=db();const policyId=text(input.policyId,"Policy",120);const previous=await database.prepare("SELECT * FROM plan_policy_versions WHERE id=?1").bind(policyId).first<Record<string,unknown>>();if(previous?.state!=="draft")throw new Error("Only a draft policy can be edited.");const unit=["day","week","month","year","lifetime"].includes(input.durationUnit)?input.durationUnit:"month";const next={name:text(input.name,"Plan name",80),description:String(input.description??"").trim().slice(0,300),priceSubunits:Math.round(number(input.priceRupees,"Price")*100),durationValue:number(input.durationValue,"Billing duration"),durationUnit:unit,trialDays:number(input.trialDays,"Trial days"),graceDays:number(input.graceDays,"Grace days"),effectiveAt:input.effectiveAt?new Date(input.effectiveAt).toISOString():null};const rows=await database.batch([database.prepare("UPDATE plan_policy_versions SET name=?1,description=?2,price_subunits=?3,billing_duration_value=?4,billing_duration_unit=?5,trial_days=?6,grace_days=?7,effective_at=?8,change_reason=?9 WHERE id=?10 AND state='draft'").bind(next.name,next.description,next.priceSubunits,next.durationValue,next.durationUnit,next.trialDays,next.graceDays,next.effectiveAt,text(input.reason,"Reason",1000),policyId),audit(database,input.actor,"plan.policy.details.save",policyId,input.reason,previous,next)]);if(rows.some(r=>r.success===false))throw new Error("Plan details could not be saved.");}

export async function savePolicyPage(input:{policyId:string;pageKey:string;enabled:boolean;reason:string;actor:Actor}){const database=db();const policyId=text(input.policyId,"Policy",120),pageKey=key(input.pageKey,"Page key"),reason=text(input.reason,"Reason",1000);const policy=await database.prepare("SELECT state FROM plan_policy_versions WHERE id=?1").bind(policyId).first<{state:string}>();if(policy?.state!=="draft")throw new Error("Only a draft policy can be edited.");const previous=await database.prepare("SELECT enabled FROM plan_policy_pages WHERE policy_version_id=?1 AND page_key=?2").bind(policyId,pageKey).first<Record<string,unknown>>();const rows=await database.batch([database.prepare("INSERT INTO plan_policy_pages(policy_version_id,page_key,enabled) VALUES(?1,?2,?3) ON CONFLICT(policy_version_id,page_key) DO UPDATE SET enabled=excluded.enabled").bind(policyId,pageKey,input.enabled?1:0),audit(database,input.actor,"plan.policy.page.save",policyId,reason,previous,{pageKey,enabled:input.enabled})]);if(rows.some(r=>r.success===false))throw new Error("Page access could not be saved.");}

export async function savePolicyFeature(input:{policyId:string;pageKey:string;featureKey:string;enabled:boolean;quantityLimit:unknown;timeLimit:unknown;storageLimitMb:unknown;fileSizeLimitMb:unknown;resetPeriod:string;retentionDays:unknown;dependencies:string;upgradeMessage:string;reason:string;actor:Actor}){
  const database=db();const policyId=text(input.policyId,"Policy",120);const policy=await database.prepare("SELECT state FROM plan_policy_versions WHERE id=?1").bind(policyId).first<{state:string}>();if(policy?.state!=="draft")throw new Error("Only a draft policy can be edited.");
  const pageKey=key(input.pageKey,"Page key"),featureKey=key(input.featureKey,"Feature key"),reason=text(input.reason,"Reason",1000),message=text(input.upgradeMessage,"Upgrade message",300);
  const reset=["daily","weekly","monthly","lifetime"].includes(input.resetPeriod)?input.resetPeriod:"lifetime";let dependencies:unknown;try{dependencies=JSON.parse(input.dependencies||"[]");}catch{throw new Error("Dependencies must be a JSON array.");}if(!Array.isArray(dependencies)||dependencies.some(v=>typeof v!=="string"))throw new Error("Dependencies must be feature keys.");
  const previous=await database.prepare("SELECT * FROM plan_policy_features WHERE policy_version_id=?1 AND feature_key=?2").bind(policyId,featureKey).first<Record<string,unknown>>();
  const next={pageKey,featureKey,enabled:input.enabled,quantityLimit:optionalNumber(input.quantityLimit,"Quantity limit"),timeLimitMinutes:optionalNumber(input.timeLimit,"Time limit"),storageLimitBytes:optionalNumber(input.storageLimitMb,"Storage limit")!*1024*1024||null,fileSizeLimitBytes:optionalNumber(input.fileSizeLimitMb,"File size limit")!*1024*1024||null,resetPeriod:reset,retentionDays:optionalNumber(input.retentionDays,"Retention"),dependencies};
  const rows=await database.batch([database.prepare("INSERT INTO plan_policy_pages(policy_version_id,page_key,enabled) VALUES(?1,?2,1) ON CONFLICT(policy_version_id,page_key) DO NOTHING").bind(policyId,pageKey),database.prepare(`INSERT INTO plan_policy_features(policy_version_id,page_key,feature_key,enabled,quantity_limit,time_limit_minutes,storage_limit_bytes,file_size_limit_bytes,reset_period,retention_days,upgrade_message,dependencies_json) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12) ON CONFLICT(policy_version_id,feature_key) DO UPDATE SET page_key=excluded.page_key,enabled=excluded.enabled,quantity_limit=excluded.quantity_limit,time_limit_minutes=excluded.time_limit_minutes,storage_limit_bytes=excluded.storage_limit_bytes,file_size_limit_bytes=excluded.file_size_limit_bytes,reset_period=excluded.reset_period,retention_days=excluded.retention_days,upgrade_message=excluded.upgrade_message,dependencies_json=excluded.dependencies_json`).bind(policyId,pageKey,featureKey,input.enabled?1:0,next.quantityLimit,next.timeLimitMinutes,next.storageLimitBytes,next.fileSizeLimitBytes,reset,next.retentionDays,message,JSON.stringify(dependencies)),audit(database,input.actor,"plan.policy.feature.save",policyId,reason,previous,next)]);if(rows.some(r=>r.success===false))throw new Error("Feature rule could not be saved atomically.");
}

export async function publishPolicy(input:{policyId:string;reason:string;actor:Actor}){
  const database=db();const policyId=text(input.policyId,"Policy",120),reason=text(input.reason,"Reason",1000);const policy=await database.prepare("SELECT * FROM plan_policy_versions WHERE id=?1").bind(policyId).first<Record<string,unknown>>();if(!policy)throw new Error("Policy was not found.");
  const features=await database.prepare("SELECT * FROM plan_policy_features WHERE policy_version_id=?1").bind(policyId).all<Record<string,unknown>>();const enabled=new Set((features.results??[]).filter(f=>Number(f.enabled)===1).map(f=>String(f.feature_key)));for(const f of features.results??[]){if(Number(f.enabled)!==1)continue;for(const dep of JSON.parse(String(f.dependencies_json||"[]")))if(!enabled.has(dep))throw new Error(`${String(f.feature_key)} requires enabled feature ${dep}.`);}
  const current=await database.prepare("SELECT policy_version_id FROM plan_policy_publications WHERE plan_id=?1").bind(policy.plan_id).first<{policy_version_id:string}>();const now=new Date().toISOString();const statements=[];if(current?.policy_version_id!==policyId)statements.push(database.prepare("UPDATE plan_policy_versions SET state='retired' WHERE id=?1").bind(current?.policy_version_id));statements.push(database.prepare("UPDATE plan_policy_versions SET state='published',published_at=COALESCE(published_at,?1) WHERE id=?2").bind(now,policyId),database.prepare("INSERT INTO plan_policy_publications(plan_id,policy_version_id,published_by,published_at) VALUES(?1,?2,?3,?4) ON CONFLICT(plan_id) DO UPDATE SET policy_version_id=excluded.policy_version_id,published_by=excluded.published_by,published_at=excluded.published_at").bind(policy.plan_id,policyId,input.actor.userId,now),database.prepare("UPDATE subscription_plans SET name=?1,tagline=?2,price_subunits=?3,currency=?4,duration_value=?5,duration_unit=?6,updated_at=?7 WHERE id=?8").bind(policy.name,policy.description,policy.price_subunits,policy.currency,policy.billing_duration_value,policy.billing_duration_unit,now,policy.plan_id));for(const f of features.results??[]){const storage=f.storage_limit_bytes==null?null:Number(f.storage_limit_bytes)/1048576;const value=storage??f.quantity_limit??f.time_limit_minutes??null;const unit=storage!==null?"megabytes":f.time_limit_minutes!=null?"minutes":value==null?"unlimited":"count";statements.push(database.prepare(`INSERT INTO plan_entitlements(id,plan_id,feature_key,enabled,limit_value,limit_unit,reset_period,upgrade_message,metadata,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,'{}',?9) ON CONFLICT(plan_id,feature_key) DO UPDATE SET enabled=excluded.enabled,limit_value=excluded.limit_value,limit_unit=excluded.limit_unit,reset_period=excluded.reset_period,upgrade_message=excluded.upgrade_message,updated_at=excluded.updated_at`).bind(`ent-${String(policy.plan_id)}-${String(f.feature_key)}`,policy.plan_id,f.feature_key,f.enabled,value,unit,f.reset_period==="lifetime"?"never":f.reset_period,f.upgrade_message,now));}statements.push(audit(database,input.actor,current?.policy_version_id===policyId?"plan.policy.publish":"plan.policy.publish_or_rollback",policyId,reason,current,policy));const rows=await database.batch(statements);if(rows.some(r=>r.success===false))throw new Error("Policy could not be published atomically.");await invalidateSharedPublicCache(["pricing"]);
}

export async function grantEntitlementOverride(input:{userId:string;featureKey:string;enabled:boolean;quantityLimit:unknown;expiresAt:string;reason:string;actor:Actor}){const database=db();const id=crypto.randomUUID(),userId=text(input.userId,"User",120),featureKey=key(input.featureKey,"Feature key"),reason=text(input.reason,"Reason",1000);const expires=input.expiresAt?new Date(input.expiresAt).toISOString():null;const rows=await database.batch([database.prepare("INSERT INTO entitlement_overrides(id,user_id,feature_key,enabled,quantity_limit,expires_at,reason,created_by) VALUES(?1,?2,?3,?4,?5,?6,?7,?8)").bind(id,userId,featureKey,input.enabled?1:0,optionalNumber(input.quantityLimit,"Quantity limit"),expires,reason,input.actor.userId),audit(database,input.actor,"entitlement.override.grant",id,reason,null,{userId,featureKey,expires},"entitlements.override")]);if(rows.some(r=>r.success===false))throw new Error("Override could not be granted.");await invalidateUserFeatureCache(userId);}

export async function scheduleUserPlanChange(input:{userId:string;toPlanId:string;effectiveAt:string;reason:string;actor:Actor}){const database=db();const userId=text(input.userId,"User",120),toPlanId=text(input.toPlanId,"Plan",120),reason=text(input.reason,"Reason",1000),effectiveAt=new Date(text(input.effectiveAt,"Effective time",80)).toISOString();const current=await database.prepare("SELECT plan_id FROM user_subscriptions WHERE user_id=?1 ORDER BY starts_at DESC LIMIT 1").bind(userId).first<{plan_id:string}>();const target=await database.prepare("SELECT id FROM subscription_plans WHERE id=?1 AND active=1").bind(toPlanId).first();if(!target)throw new Error("Target plan is unavailable.");const id=crypto.randomUUID();const rows=await database.batch([database.prepare("INSERT INTO scheduled_plan_changes(id,user_id,from_plan_id,to_plan_id,effective_at,reason,created_by) VALUES(?1,?2,?3,?4,?5,?6,?7)").bind(id,userId,current?.plan_id??null,toPlanId,effectiveAt,reason,input.actor.userId),audit(database,input.actor,"plan.change.schedule",id,reason,current,{userId,toPlanId,effectiveAt},"billing.manage")]);if(rows.some(r=>r.success===false))throw new Error("Plan change could not be scheduled.");await invalidateUserFeatureCache(userId);}

export async function createUserPromotion(input:{name:string;policyId:string;userId:string;startsAt:string;endsAt:string;reason:string;actor:Actor}){const database=db();const name=text(input.name,"Promotion name",100),policyId=text(input.policyId,"Policy",120),userId=text(input.userId,"User",120),reason=text(input.reason,"Reason",1000),startsAt=new Date(text(input.startsAt,"Start time",80)).toISOString(),endsAt=new Date(text(input.endsAt,"End time",80)).toISOString();if(Date.parse(endsAt)<=Date.parse(startsAt))throw new Error("Promotion end must be after its start.");const policy=await database.prepare("SELECT id FROM plan_policy_versions WHERE id=?1 AND state='published'").bind(policyId).first();if(!policy)throw new Error("Promotion must use a published policy.");const id=crypto.randomUUID();const rows=await database.batch([database.prepare("INSERT INTO plan_promotions(id,name,policy_version_id,starts_at,ends_at,created_by) VALUES(?1,?2,?3,?4,?5,?6)").bind(id,name,policyId,startsAt,endsAt,input.actor.userId),database.prepare("INSERT INTO plan_promotion_grants(promotion_id,user_id) VALUES(?1,?2)").bind(id,userId),audit(database,input.actor,"plan.promotion.grant",id,reason,null,{name,policyId,userId,startsAt,endsAt},"billing.manage")]);if(rows.some(r=>r.success===false))throw new Error("Promotion could not be created.");await invalidateUserFeatureCache(userId);}

export async function reserveEntitlementUsage(input:{userId:string;featureKey:string;amount:number;limit:number;resetPeriod:"daily"|"weekly"|"monthly"|"lifetime";idempotencyKey:string;now?:Date}){const database=db(),now=input.now??new Date();const bucket=input.resetPeriod==="daily"?now.toISOString().slice(0,10):input.resetPeriod==="monthly"?now.toISOString().slice(0,7):input.resetPeriod==="weekly"?`${now.getUTCFullYear()}-w${Math.ceil((((Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate())-Date.UTC(now.getUTCFullYear(),0,1))/86400000)+new Date(Date.UTC(now.getUTCFullYear(),0,1)).getUTCDay()+1)/7)}`:"lifetime";const amount=number(input.amount,"Reservation amount",0.000001);const prior=await database.prepare("SELECT user_id,feature_key,reserved_value FROM entitlement_reservations WHERE idempotency_key=?1").bind(input.idempotencyKey).first<Record<string,unknown>>();if(prior){if(String(prior.user_id)===input.userId&&String(prior.feature_key)===input.featureKey&&Number(prior.reserved_value)===amount)return{bucket,idempotent:true};throw new Error("Idempotency key was already used for another reservation.");}try{const rows=await database.batch([database.prepare(`INSERT INTO entitlement_usage_buckets(user_id,feature_key,bucket_key,used_value) SELECT ?1,?2,?3,?4 WHERE ?4<=?5 ON CONFLICT(user_id,feature_key,bucket_key) DO UPDATE SET used_value=used_value+excluded.used_value,updated_at=CURRENT_TIMESTAMP WHERE used_value+excluded.used_value<=?5`).bind(input.userId,input.featureKey,bucket,amount,input.limit),database.prepare("INSERT INTO entitlement_reservations(idempotency_key,user_id,feature_key,bucket_key,reserved_value) VALUES(?1,?2,?3,?4,?5)").bind(input.idempotencyKey,input.userId,input.featureKey,bucket,amount)]);const first=rows[0] as {meta?:{changes?:number}}|undefined;if(Number(first?.meta?.changes??0)!==1)throw new Error("This action would exceed the plan allowance.");}catch(error){const raced=await database.prepare("SELECT user_id,feature_key,reserved_value FROM entitlement_reservations WHERE idempotency_key=?1").bind(input.idempotencyKey).first<Record<string,unknown>>();if(raced&&String(raced.user_id)===input.userId&&String(raced.feature_key)===input.featureKey&&Number(raced.reserved_value)===amount)return{bucket,idempotent:true};throw error;}return{bucket,idempotent:false};}

export async function getStudentUsageMeters(userId:string){const result=await db().prepare("SELECT feature_key,bucket_key,used_value,updated_at FROM entitlement_usage_buckets WHERE user_id=?1 ORDER BY updated_at DESC LIMIT 100").bind(userId).all<Record<string,unknown>>();return result.results??[];}
