import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Card, CardBody } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { Icon } from "@/components/ui/icon";
import { requireAdminPageCapability } from "@/lib/authorization/server";
import { hasAdminCapability } from "@/lib/authorization/capabilities.mjs";
import { getAcademicVersionPreview } from "@/lib/academic/query";
import { getAcademicConsistencyOverview, getAcademicResolutionOptions } from "@/lib/academic/consistency";
import { dismissQuarantineAction, resolveQuarantineAction } from "./actions";

export const dynamic = "force-dynamic";

export default async function AdminSyllabusPreviewPage({ searchParams }: { searchParams: Promise<{ notice?: string }> }) {
  const actor = await requireAdminPageCapability("academic.read");
  const canEdit = hasAdminCapability(actor.role,"academic.edit");
  const [versions,consistency,options,query] = await Promise.all([
    getAcademicVersionPreview(),getAcademicConsistencyOverview(),getAcademicResolutionOptions(),searchParams,
  ]);
  return <div className="academic-page academic-admin-page">
    <section className="academic-hero"><div><Badge tone="info">Canonical academic registry</Badge><h1>Syllabus structure</h1><p>Review the level → group → subject → syllabus → module → chapter hierarchy and safely resolve content that could not be mapped.</p></div><div className="academic-source-chip"><Icon name="shield" size={18}/><span><strong>Ambiguity is withheld</strong><small>Unmapped content never enters a student feed automatically.</small></span></div></section>
    {query.notice ? <p role="status" className="ui-notice ui-notice--success">{query.notice}</p> : null}
    <section className="academic-admin-summary"><Card><CardBody><span>Versions</span><strong>{versions.length}</strong><small>Current + historical</small></CardBody></Card><Card><CardBody><span>Modules</span><strong>{consistency.modules}</strong><small>Stable hierarchy nodes</small></CardBody></Card><Card><CardBody><span>Mapped content</span><strong>{consistency.mappedItems}</strong><small>Canonical references</small></CardBody></Card><Card><CardBody><span>Needs review</span><strong>{consistency.pendingItems.length}</strong><small>{consistency.openDuplicateCandidates} duplicate candidates</small></CardBody></Card></section>
    <section><div className="academic-section-heading"><div><span className="eyebrow">Mapping review</span><h2>Unmapped content quarantine</h2><p>Resolve only when the evidence identifies one exact academic destination. Dismiss records that are intentionally global or not student-facing.</p></div><Badge tone={consistency.pendingItems.length ? "warning" : "success"}>{consistency.pendingItems.length ? `${consistency.pendingItems.length} pending` : "Clear"}</Badge></div>
      {consistency.pendingItems.length ? <><div className="academic-quarantine-list">{consistency.pendingItems.map((item) => <Card key={item.id}><CardBody><div className="academic-quarantine-card"><div><Badge tone="warning">{item.reasonCode.replaceAll("_"," ")}</Badge><h3>{item.summary}</h3><p>{item.entityType} · {item.entityId}</p><details><summary>Evidence</summary><pre>{JSON.stringify(item.evidence,null,2)}</pre></details></div></div></CardBody></Card>)}</div>{canEdit ? <Card><CardBody><div className="academic-resolution-console"><form action={resolveQuarantineAction}><h3>Resolve one item</h3><label>Quarantine item<select name="quarantineId" required defaultValue=""><option value="" disabled>Select item</option>{consistency.pendingItems.map((item) => <option key={item.id} value={item.id}>{item.summary} · {item.entityId}</option>)}</select></label><label>Canonical destination<select name="destination" required defaultValue=""><option value="" disabled>Select exact chapter</option>{options.filter((option) => option.chapterId).map((option) => <option key={`${option.syllabusVersionId}:${option.chapterId}`} value={JSON.stringify(option)}>{option.label}</option>)}</select></label><label>Resolution reason<textarea name="reason" required minLength={8}/></label><button className="ui-button ui-button--primary" type="submit">Save canonical mapping</button></form><form action={dismissQuarantineAction}><h3>Dismiss one item</h3><label>Quarantine item<select name="quarantineId" required defaultValue=""><option value="" disabled>Select item</option>{consistency.pendingItems.map((item) => <option key={item.id} value={item.id}>{item.summary} · {item.entityId}</option>)}</select></label><label>Dismissal reason<input name="reason" required minLength={8}/></label><button className="ui-button ui-button--secondary" type="submit">Dismiss as intentionally unscoped</button></form></div></CardBody></Card> : <p>Owner access is required to resolve mappings.</p>}</> : <EmptyState icon="shield" title="No ambiguous content" description="Every reviewed student-facing item has a canonical academic destination."/>}
    </section>
    <section><div className="academic-section-heading"><div><span className="eyebrow">Version registry</span><h2>Academic versions</h2></div><Link href="/syllabus" className="ui-text-link">Open student explorer <Icon name="arrow" size={14}/></Link></div>{versions.length ? <div className="academic-version-table" role="table" aria-label="Syllabus versions"><div className="academic-version-table__head" role="row"><span>Level / subject</span><span>Version</span><span>Structure</span><span>Status</span><span>Source</span></div>{versions.map((version) => <div className="academic-version-table__row" role="row" key={version.id}><span><strong>{version.subjectTitle}</strong><small>{version.levelName} · {version.groupName}</small></span><span><strong>{version.key}</strong><small>{version.effectiveFrom}{version.effectiveTo ? ` → ${version.effectiveTo}` : " → current"}</small></span><span><strong>{version.chapterCount} chapters/units</strong><small>{version.topicCount} indexed topics</small></span><span><Badge tone={version.status === "published" ? "success" : version.status === "superseded" ? "neutral" : "info"}>{version.status}</Badge>{version.supersedesVersionId ? <small>Supersedes {version.supersedesVersionId}</small> : null}</span><span><a href={version.sourceUrl} target="_blank" rel="noreferrer">ICAI <Icon name="arrow" size={13}/></a><small>Verified {new Date(version.sourceVerifiedAt).toLocaleDateString("en-IN")}</small></span></div>)}</div> : <EmptyState icon="book" title="No academic versions" description="The normalized academic registry has no published data yet."/>}</section>
  </div>;
}
