'use client';
import {useEffect,useRef,useState} from 'react';
import type {CheckoutView} from '@/lib/billing/checkout-engine.mjs';
import {clearCheckoutIntent} from '@/lib/billing/checkout-client.mjs';
export function CheckoutRecovery({viewerId,onResume,webCheckoutAllowed}:{webCheckoutAllowed:boolean;viewerId?:string|null;onResume?:(view:CheckoutView)=>Promise<void>}){
  const [view,setView]=useState<CheckoutView|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const guard=useRef(false);
  useEffect(()=>{let disposed=false;fetch('/api/v1/payments/checkout/status',{cache:'no-store'}).then(async response=>response.ok?response.json():null).then(result=>{if(!disposed){setView(result?.checkout??null);if(viewerId&&result?.checkout&&['failed','cancelled','succeeded'].includes(result.checkout.state))clearCheckoutIntent(localStorage,viewerId,result.checkout.requestId);}}).catch(()=>undefined);return()=>{disposed=true;};},[viewerId]);
  async function recover(resume=false){if(!view||guard.current)return;guard.current=true;setBusy(true);setError('');try{const response=await fetch('/api/v1/payments/checkout/recover',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({attemptId:view.attemptId})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Payment status could not be checked. Please try again.');const next=result.checkout as CheckoutView;setView(next);if(viewerId&&['failed','cancelled','succeeded'].includes(next.state))clearCheckoutIntent(localStorage,viewerId,next.requestId);if(resume&&next.resumable&&onResume)await onResume(next);}catch(caught){setError(caught instanceof Error?caught.message:'Recovery is temporarily unavailable.');}finally{guard.current=false;setBusy(false);}}
  if(!view)return null;
  const text=view.accessGranted?'Payment reconciled. Your subscription access is active.':view.state==='failed'?'This checkout failed before subscription creation. You can start a new checkout.':view.state==='cancelled'?'This subscription has ended. Billing shows any remaining paid access.':view.resumable?'Your original checkout is ready to resume with its saved price and payment method.':'Your original payment is still being checked. Keep this attempt while its provider status is confirmed.';
  return <div className="phase11-notice phase11-notice--info" role="status"><p>{text}</p>{view.initialAmount!==null?<p>First charge: ₹{view.initialAmount/100}. Recurring: ₹{Number(view.recurringAmount)/100} · {view.paymentMethod}.</p>:null}{view.totalCount>0?<p>Saved mandate limit: {view.totalCount} scheduled charges. {view.providerEndAt?`Provider end: ${new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeZone:"Asia/Kolkata"}).format(new Date(view.providerEndAt))}.`:""} {view.mandateScheduleVersion==="legacy"?"This existing mandate retains its original duration; review it in Billing before authorizing.":"Fresh authorization is required after the mandate ends."}</p>:null}{webCheckoutAllowed?<><button type="button" className="ui-button ui-button--secondary" disabled={busy} onClick={()=>void recover()}>Check payment status</button>{view.resumable&&onResume?<button type="button" className="ui-button ui-button--primary" disabled={busy} onClick={()=>void recover(true)}>Resume original checkout</button>:null}{view.resumable&&!onResume?<a href="/pricing" className="ui-button ui-button--secondary">Resume from pricing</a>:null}</>:null}{error?<p role="alert">{error}</p>:null}</div>;
}
