-- CA Progress V2 - Phase 0 core schema
-- This migration is intentionally standalone and must only be applied to the isolated V2 database.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.app_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.system_health_log (
  id bigint generated by default as identity primary key,
  component text not null,
  status text not null check (status in ('ok', 'degraded', 'down')),
  details jsonb not null default '{}'::jsonb,
  correlation_id uuid,
  created_at timestamptz not null default now()
);

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger app_settings_set_updated_at
before update on public.app_settings
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.app_settings enable row level security;
alter table public.system_health_log enable row level security;

create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "app_settings_read_public"
on public.app_settings
for select
to anon, authenticated
using (is_public = true);

-- Intentionally no client insert/update/delete policies on app_settings.
-- Intentionally no client policies at all on system_health_log.
-- The service role bypasses RLS and is isolated to server-only code.

insert into public.app_settings (key, value, is_public)
values
  ('app.identity', '{"product":"CA Progress","generation":"v2"}'::jsonb, true),
  ('app.phase', '{"phase":0,"status":"foundation"}'::jsonb, true)
on conflict (key) do nothing;
