-- CA Progress V2 — Phase 12 Operations Admin Platform
-- V2 only. Existing privileged JWT roles are bootstrapped; this migration never invents an operator.

create table public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('moderator','admin','owner','parent_owner')),
  is_active boolean not null default true,
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  actor_role text not null check (actor_role in ('system','moderator','admin','owner','parent_owner')),
  action_key text not null check (char_length(action_key) between 3 and 120),
  entity_type text not null check (char_length(entity_type) between 2 and 80),
  entity_id text,
  request_id uuid not null unique,
  before_state jsonb not null default '{}'::jsonb check (jsonb_typeof(before_state)='object'),
  after_state jsonb not null default '{}'::jsonb check (jsonb_typeof(after_state)='object'),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata)='object'),
  created_at timestamptz not null default now()
);

create table public.feature_flags (
  flag_key text primary key check (flag_key ~ '^[a-z0-9._-]{3,100}$'),
  label text not null,
  description text not null default '',
  enabled boolean not null default true,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.maintenance_settings (
  id boolean primary key default true check (id),
  enabled boolean not null default false,
  message text not null default 'CA Progress is temporarily in maintenance mode.',
  starts_at timestamptz,
  ends_at timestamptz,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or starts_at is null or ends_at > starts_at)
);

create table public.notification_templates (
  id uuid primary key default gen_random_uuid(),
  template_key text not null unique check (template_key ~ '^[a-z0-9._-]{3,100}$'),
  name text not null check (char_length(name) between 1 and 120),
  title text not null check (char_length(title) between 1 and 180),
  body text not null check (char_length(body) between 1 and 4000),
  is_active boolean not null default true,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index admin_users_role_active_idx on public.admin_users(role,is_active,user_id);
create index admin_audit_logs_created_idx on public.admin_audit_logs(created_at desc,id desc);
create index admin_audit_logs_actor_idx on public.admin_audit_logs(actor_user_id,created_at desc);
create index admin_audit_logs_entity_idx on public.admin_audit_logs(entity_type,entity_id,created_at desc);
create index notification_templates_active_idx on public.notification_templates(is_active,updated_at desc);

create trigger admin_users_set_updated_at before update on public.admin_users for each row execute function public.set_updated_at();
create trigger feature_flags_set_updated_at before update on public.feature_flags for each row execute function public.set_updated_at();
create trigger maintenance_settings_set_updated_at before update on public.maintenance_settings for each row execute function public.set_updated_at();
create trigger notification_templates_set_updated_at before update on public.notification_templates for each row execute function public.set_updated_at();

create or replace function public.phase12_reject_audit_mutation()
returns trigger language plpgsql set search_path=public as $$
begin
  raise exception 'Admin audit logs are immutable.' using errcode='42501';
end; $$;
create trigger admin_audit_logs_immutable before update or delete on public.admin_audit_logs for each row execute function public.phase12_reject_audit_mutation();

insert into public.admin_users(user_id,role,is_active,granted_by)
select id, raw_app_meta_data->>'role', true, null
from auth.users
where raw_app_meta_data->>'role' in ('moderator','admin','owner','parent_owner')
on conflict(user_id) do nothing;

insert into public.feature_flags(flag_key,label,description,enabled) values
('community.write','Community writing','Allow members to post new Community messages.',true),
('resources.upload','Resource uploads','Allow members to upload private/shared resources.',true),
('planner.smart','Smart Planner','Allow generation and mutation of Smart Planner recommendations.',true),
('billing.checkout','Paid checkout','Allow creation of new paid Razorpay orders when the selected plan is configured.',true),
('icai.sync','ICAI sync','Allow operations-triggered ICAI synchronization.',true)
on conflict(flag_key) do nothing;

insert into public.maintenance_settings(id,enabled,message) values(true,false,'CA Progress is temporarily in maintenance mode.') on conflict(id) do nothing;

create or replace function public.phase12_role_rank(p_role text)
returns integer language sql immutable set search_path=public as $$
 select case p_role when 'moderator' then 10 when 'admin' then 20 when 'owner' then 30 when 'parent_owner' then 40 else 0 end;
$$;

create or replace function public.phase12_admin_role(p_user_id uuid)
returns text language sql stable security definer set search_path=public,auth,pg_temp as $$
 select role from public.admin_users where user_id=p_user_id and is_active limit 1;
$$;

create or replace function public.phase12_get_my_admin_role()
returns text language sql stable security definer set search_path=public,auth,pg_temp as $$
 select public.phase12_admin_role(auth.uid());
$$;

create or replace function public.phase12_assert_role(p_actor uuid,p_min_rank integer)
returns text language plpgsql stable security definer set search_path=public,auth,pg_temp as $$
declare v_role text;
begin
 select role into v_role from public.admin_users where user_id=p_actor and is_active;
 if v_role is null or public.phase12_role_rank(v_role)<p_min_rank then raise exception 'Admin authorization required.' using errcode='42501'; end if;
 return v_role;
end; $$;

create or replace function public.phase12_bootstrap_parent_owner(p_user_id uuid,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare v_email text;
begin
 if exists(select 1 from public.admin_users where role='parent_owner' and is_active) then raise exception 'An active parent owner already exists.' using errcode='42501'; end if;
 select email into v_email from auth.users where id=p_user_id;
 if v_email is null then raise exception 'Target auth user not found.'; end if;
 insert into public.admin_users(user_id,role,is_active) values(p_user_id,'parent_owner',true)
 on conflict(user_id) do update set role='parent_owner',is_active=true,updated_at=now();
 insert into public.admin_audit_logs(actor_user_id,actor_role,action_key,entity_type,entity_id,request_id,after_state,metadata)
 values(null,'system','admin.bootstrap_parent_owner','admin_user',p_user_id::text,p_request_id,jsonb_build_object('role','parent_owner','active',true),jsonb_build_object('email',v_email));
 return jsonb_build_object('ok',true,'userId',p_user_id);
end; $$;

create or replace function public.phase12_set_admin_role(p_actor uuid,p_target uuid,p_new_role text,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare v_actor_role text; v_target public.admin_users%rowtype; v_before jsonb; v_after jsonb;
begin
 v_actor_role:=public.phase12_assert_role(p_actor,30);
 if p_actor=p_target then raise exception 'Self-demotion or self-role changes are not allowed.' using errcode='42501'; end if;
 if p_new_role not in ('moderator','admin','owner') then raise exception 'parent_owner cannot be assigned through the application.' using errcode='42501'; end if;
 select * into v_target from public.admin_users where user_id=p_target;
 if found and v_target.role='parent_owner' then raise exception 'The parent owner role is protected.' using errcode='42501'; end if;
 if found and public.phase12_role_rank(v_actor_role)<=public.phase12_role_rank(v_target.role) then raise exception 'Operators cannot modify an equal or higher role.' using errcode='42501'; end if;
 if public.phase12_role_rank(v_actor_role)<=public.phase12_role_rank(p_new_role) then raise exception 'Operators cannot grant an equal or higher role.' using errcode='42501'; end if;
 if not exists(select 1 from auth.users where id=p_target) then raise exception 'Target auth user not found.'; end if;
 v_before:=case when found then jsonb_build_object('role',v_target.role,'active',v_target.is_active) else '{}'::jsonb end;
 insert into public.admin_users(user_id,role,is_active,granted_by) values(p_target,p_new_role,true,p_actor)
 on conflict(user_id) do update set role=excluded.role,is_active=true,granted_by=p_actor,updated_at=now();
 v_after:=jsonb_build_object('role',p_new_role,'active',true);
 insert into public.admin_audit_logs(actor_user_id,actor_role,action_key,entity_type,entity_id,request_id,before_state,after_state)
 values(p_actor,v_actor_role,'admin.role_changed','admin_user',p_target::text,p_request_id,v_before,v_after);
 return jsonb_build_object('ok',true,'userId',p_target,'role',p_new_role);
end; $$;

create or replace function public.phase12_set_admin_active(p_actor uuid,p_target uuid,p_active boolean,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare v_actor_role text; v_target public.admin_users%rowtype;
begin
 v_actor_role:=public.phase12_assert_role(p_actor,30);
 if p_actor=p_target then raise exception 'Operators cannot deactivate themselves.' using errcode='42501'; end if;
 select * into v_target from public.admin_users where user_id=p_target;
 if not found then raise exception 'Admin user not found.'; end if;
 if v_target.role='parent_owner' then raise exception 'The parent owner cannot be deactivated.' using errcode='42501'; end if;
 if public.phase12_role_rank(v_actor_role)<=public.phase12_role_rank(v_target.role) then raise exception 'Operators cannot modify an equal or higher role.' using errcode='42501'; end if;
 update public.admin_users set is_active=p_active,updated_at=now() where user_id=p_target;
 insert into public.admin_audit_logs(actor_user_id,actor_role,action_key,entity_type,entity_id,request_id,before_state,after_state)
 values(p_actor,v_actor_role,'admin.access_toggled','admin_user',p_target::text,p_request_id,jsonb_build_object('active',v_target.is_active,'role',v_target.role),jsonb_build_object('active',p_active,'role',v_target.role));
 return jsonb_build_object('ok',true,'active',p_active);
end; $$;

create or replace function public.phase12_list_members(p_actor uuid,p_page integer default 1,p_limit integer default 25,p_search text default null,p_role text default null)
returns table(user_id uuid,email text,display_name text,role text,admin_active boolean,plan_tier text,plan_name text,subscription_ends_at timestamptz,user_created_at timestamptz,total_count bigint)
language plpgsql stable security definer set search_path=public,auth,pg_temp as $$
begin
 perform public.phase12_assert_role(p_actor,20);
 if p_page<1 or p_limit<1 or p_limit>100 then raise exception 'Invalid pagination.'; end if;
 return query
 with members as (
   select u.id,u.email,coalesce(nullif(u.raw_user_meta_data->>'full_name',''),nullif(u.raw_user_meta_data->>'name',''),split_part(coalesce(u.email,''),'@',1)) as display_name,
          au.role,coalesce(au.is_active,false) admin_active,p.tier_key,p.name,
          (select us.ends_at from public.user_subscriptions us where us.user_id=u.id and us.plan_id=p.id and us.status='active' and us.starts_at<=now() and (us.ends_at is null or us.ends_at>now()) order by us.created_at desc limit 1) as subscription_ends_at,
          u.created_at
   from auth.users u
   left join public.admin_users au on au.user_id=u.id
   left join public.subscription_plans p on p.id=public.phase11_current_plan_id(u.id)
   where (p_search is null or p_search='' or lower(coalesce(u.email,'')) like '%'||lower(p_search)||'%' or lower(coalesce(u.raw_user_meta_data->>'full_name',u.raw_user_meta_data->>'name','')) like '%'||lower(p_search)||'%')
     and (p_role is null or p_role='' or coalesce(au.role,'student')=p_role)
 )
 select m.id,m.email,m.display_name,coalesce(m.role,'student'),m.admin_active,coalesce(m.tier_key,'free'),coalesce(m.name,'Free'),m.subscription_ends_at,m.created_at,count(*) over()
 from members m order by m.created_at desc,m.id desc limit p_limit offset ((p_page-1)*p_limit);
end; $$;

create or replace function public.phase12_set_feature_flag(p_actor uuid,p_flag_key text,p_enabled boolean,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare v_role text; v_before public.feature_flags%rowtype;
begin
 v_role:=public.phase12_assert_role(p_actor,30);
 select * into v_before from public.feature_flags where flag_key=p_flag_key; if not found then raise exception 'Feature flag not found.'; end if;
 update public.feature_flags set enabled=p_enabled,updated_by=p_actor,updated_at=now() where flag_key=p_flag_key;
 insert into public.admin_audit_logs(actor_user_id,actor_role,action_key,entity_type,entity_id,request_id,before_state,after_state)
 values(p_actor,v_role,'platform.feature_flag_changed','feature_flag',p_flag_key,p_request_id,jsonb_build_object('enabled',v_before.enabled),jsonb_build_object('enabled',p_enabled));
 return jsonb_build_object('ok',true,'flagKey',p_flag_key,'enabled',p_enabled);
end; $$;

create or replace function public.phase12_set_maintenance(p_actor uuid,p_enabled boolean,p_message text,p_starts_at timestamptz,p_ends_at timestamptz,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare v_role text; v_before public.maintenance_settings%rowtype;
begin
 v_role:=public.phase12_assert_role(p_actor,30); select * into v_before from public.maintenance_settings where id=true;
 if p_message is null or char_length(trim(p_message))<3 or char_length(p_message)>500 then raise exception 'Maintenance message is invalid.'; end if;
 if p_ends_at is not null and p_starts_at is not null and p_ends_at<=p_starts_at then raise exception 'Maintenance window is invalid.'; end if;
 update public.maintenance_settings set enabled=p_enabled,message=trim(p_message),starts_at=p_starts_at,ends_at=p_ends_at,updated_by=p_actor,updated_at=now() where id=true;
 insert into public.admin_audit_logs(actor_user_id,actor_role,action_key,entity_type,entity_id,request_id,before_state,after_state)
 values(p_actor,v_role,'platform.maintenance_changed','maintenance','global',p_request_id,to_jsonb(v_before)-'id'-'created_at'-'updated_at',jsonb_build_object('enabled',p_enabled,'message',trim(p_message),'starts_at',p_starts_at,'ends_at',p_ends_at));
 return jsonb_build_object('ok',true,'enabled',p_enabled);
end; $$;

create or replace function public.phase12_upsert_notification_template(p_actor uuid,p_id uuid,p_template_key text,p_name text,p_title text,p_body text,p_active boolean,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare v_role text; v_id uuid; v_before jsonb:='{}'::jsonb;
begin
 v_role:=public.phase12_assert_role(p_actor,20);
 if p_id is not null then select to_jsonb(t) into v_before from public.notification_templates t where id=p_id; end if;
 if p_template_key !~ '^[a-z0-9._-]{3,100}$' or char_length(trim(p_name))<1 or char_length(trim(p_title))<1 or char_length(p_body)<1 then raise exception 'Template fields are invalid.'; end if;
 if p_id is null then
   insert into public.notification_templates(template_key,name,title,body,is_active,updated_by) values(p_template_key,trim(p_name),trim(p_title),p_body,p_active,p_actor) returning id into v_id;
 else
   update public.notification_templates set template_key=p_template_key,name=trim(p_name),title=trim(p_title),body=p_body,is_active=p_active,updated_by=p_actor,updated_at=now() where id=p_id returning id into v_id;
   if v_id is null then raise exception 'Notification template not found.'; end if;
 end if;
 insert into public.admin_audit_logs(actor_user_id,actor_role,action_key,entity_type,entity_id,request_id,before_state,after_state)
 select p_actor,v_role,'notifications.template_saved','notification_template',v_id::text,p_request_id,v_before,to_jsonb(t) from public.notification_templates t where id=v_id;
 return jsonb_build_object('ok',true,'id',v_id);
end; $$;

create or replace function public.phase12_update_plan(p_actor uuid,p_plan_id uuid,p_price_subunits bigint,p_checkout_enabled boolean,p_active boolean,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare v_role text; v_before public.subscription_plans%rowtype;
begin
 v_role:=public.phase12_assert_role(p_actor,30); select * into v_before from public.subscription_plans where id=p_plan_id; if not found then raise exception 'Plan not found.'; end if;
 if v_before.tier_key='free' then raise exception 'Free plan commercial state is fixed.' using errcode='42501'; end if;
 if p_price_subunits is not null and p_price_subunits<100 then raise exception 'Paid plan price must be at least 100 subunits.'; end if;
 if p_checkout_enabled and (not p_active or p_price_subunits is null) then raise exception 'Checkout requires an active plan with a configured price.'; end if;
 update public.subscription_plans set price_subunits=p_price_subunits,checkout_enabled=p_checkout_enabled,active=p_active,updated_at=now() where id=p_plan_id;
 insert into public.admin_audit_logs(actor_user_id,actor_role,action_key,entity_type,entity_id,request_id,before_state,after_state)
 select p_actor,v_role,'billing.plan_changed','subscription_plan',p_plan_id::text,p_request_id,jsonb_build_object('price_subunits',v_before.price_subunits,'checkout_enabled',v_before.checkout_enabled,'active',v_before.active),jsonb_build_object('price_subunits',p_price_subunits,'checkout_enabled',p_checkout_enabled,'active',p_active);
 return jsonb_build_object('ok',true,'planId',p_plan_id);
end; $$;

create or replace function public.phase12_update_entitlement(p_actor uuid,p_plan_id uuid,p_feature_key text,p_enabled boolean,p_limit_value numeric,p_limit_unit text,p_upgrade_message text,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare v_role text; v_before public.plan_entitlements%rowtype;
begin
 v_role:=public.phase12_assert_role(p_actor,30); select * into v_before from public.plan_entitlements where plan_id=p_plan_id and feature_key=p_feature_key; if not found then raise exception 'Entitlement not found.'; end if;
 if p_limit_unit not in ('unlimited','count','minutes','megabytes') then raise exception 'Invalid entitlement unit.'; end if;
 if (p_limit_unit='unlimited' and p_limit_value is not null) or (p_limit_unit<>'unlimited' and (p_limit_value is null or p_limit_value<0)) then raise exception 'Invalid entitlement limit.'; end if;
 update public.plan_entitlements set enabled=p_enabled,limit_value=p_limit_value,limit_unit=p_limit_unit,upgrade_message=coalesce(p_upgrade_message,''),updated_at=now() where plan_id=p_plan_id and feature_key=p_feature_key;
 insert into public.admin_audit_logs(actor_user_id,actor_role,action_key,entity_type,entity_id,request_id,before_state,after_state)
 values(p_actor,v_role,'billing.entitlement_changed','plan_entitlement',p_plan_id::text||':'||p_feature_key,p_request_id,to_jsonb(v_before),jsonb_build_object('plan_id',p_plan_id,'feature_key',p_feature_key,'enabled',p_enabled,'limit_value',p_limit_value,'limit_unit',p_limit_unit,'upgrade_message',coalesce(p_upgrade_message,'')));
 return jsonb_build_object('ok',true);
end; $$;

create or replace function public.phase12_update_content_state(p_actor uuid,p_entity_type text,p_entity_id text,p_status text,p_verification_status text,p_request_id uuid)
returns jsonb language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare v_role text; v_before jsonb; v_after jsonb;
begin
 v_role:=public.phase12_assert_role(p_actor,20);
 if p_entity_type='syllabus_version' then
   select to_jsonb(s) into v_before from public.syllabus_versions s where id=p_entity_id; if v_before is null then raise exception 'Syllabus version not found.'; end if;
   if p_status not in ('published','superseded','upcoming') then raise exception 'Invalid syllabus status.'; end if;
   update public.syllabus_versions set status=p_status,updated_at=now() where id=p_entity_id; select to_jsonb(s) into v_after from public.syllabus_versions s where id=p_entity_id;
 elsif p_entity_type='exam_attempt' then
   select to_jsonb(a) into v_before from public.exam_attempts a where id=p_entity_id; if v_before is null then raise exception 'Exam attempt not found.'; end if;
   if p_status not in ('scheduled','open','completed','cancelled') or p_verification_status not in ('verified','pending_review','rejected') then raise exception 'Invalid attempt state.'; end if;
   update public.exam_attempts set status=p_status,verification_status=p_verification_status,verification_method='admin_review',updated_at=now() where id=p_entity_id; select to_jsonb(a) into v_after from public.exam_attempts a where id=p_entity_id;
 elsif p_entity_type='icai_resource' then
   select to_jsonb(r) into v_before from public.icai_resources r where id=p_entity_id; if v_before is null then raise exception 'ICAI resource not found.'; end if;
   if p_status not in ('active','removed','replaced') or p_verification_status not in ('verified','pending_review','rejected') then raise exception 'Invalid resource state.'; end if;
   update public.icai_resources set status=p_status,verification_status=p_verification_status,updated_at=now() where id=p_entity_id; select to_jsonb(r) into v_after from public.icai_resources r where id=p_entity_id;
 else raise exception 'Unsupported content entity.';
 end if;
 insert into public.admin_audit_logs(actor_user_id,actor_role,action_key,entity_type,entity_id,request_id,before_state,after_state)
 values(p_actor,v_role,'content.state_changed',p_entity_type,p_entity_id,p_request_id,v_before,v_after);
 return jsonb_build_object('ok',true);
end; $$;

create or replace function public.phase12_realtime_health(p_actor uuid)
returns boolean language plpgsql stable security definer set search_path=public,pg_catalog,pg_temp as $$
begin
 perform public.phase12_assert_role(p_actor,20);
 return exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='community_messages');
end; $$;

alter table public.admin_users enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.feature_flags enable row level security;
alter table public.maintenance_settings enable row level security;
alter table public.notification_templates enable row level security;

-- No direct table policies: privileged data is exposed only through scoped server services/RPCs.
revoke all on public.admin_users,public.admin_audit_logs,public.feature_flags,public.maintenance_settings,public.notification_templates from public,anon,authenticated;
grant select,insert,update,delete on public.admin_users,public.feature_flags,public.maintenance_settings,public.notification_templates to service_role;
grant select,insert on public.admin_audit_logs to service_role;
grant usage,select on sequence public.admin_audit_logs_id_seq to service_role;

revoke all on function public.phase12_role_rank(text) from public,anon,authenticated;
revoke all on function public.phase12_admin_role(uuid) from public,anon,authenticated;
revoke all on function public.phase12_assert_role(uuid,integer) from public,anon,authenticated;
revoke all on function public.phase12_bootstrap_parent_owner(uuid,uuid) from public,anon,authenticated;
revoke all on function public.phase12_set_admin_role(uuid,uuid,text,uuid) from public,anon,authenticated;
revoke all on function public.phase12_set_admin_active(uuid,uuid,boolean,uuid) from public,anon,authenticated;
revoke all on function public.phase12_list_members(uuid,integer,integer,text,text) from public,anon,authenticated;
revoke all on function public.phase12_set_feature_flag(uuid,text,boolean,uuid) from public,anon,authenticated;
revoke all on function public.phase12_set_maintenance(uuid,boolean,text,timestamptz,timestamptz,uuid) from public,anon,authenticated;
revoke all on function public.phase12_upsert_notification_template(uuid,uuid,text,text,text,text,boolean,uuid) from public,anon,authenticated;
revoke all on function public.phase12_update_plan(uuid,uuid,bigint,boolean,boolean,uuid) from public,anon,authenticated;
revoke all on function public.phase12_update_entitlement(uuid,uuid,text,boolean,numeric,text,text,uuid) from public,anon,authenticated;
revoke all on function public.phase12_update_content_state(uuid,text,text,text,text,uuid) from public,anon,authenticated;
revoke all on function public.phase12_realtime_health(uuid) from public,anon,authenticated;
revoke all on function public.phase12_reject_audit_mutation() from public,anon,authenticated;
revoke all on function public.phase12_get_my_admin_role() from public,anon;
grant execute on function public.phase12_get_my_admin_role() to authenticated;

grant execute on function public.phase12_role_rank(text),public.phase12_admin_role(uuid),public.phase12_assert_role(uuid,integer),public.phase12_bootstrap_parent_owner(uuid,uuid),public.phase12_set_admin_role(uuid,uuid,text,uuid),public.phase12_set_admin_active(uuid,uuid,boolean,uuid),public.phase12_list_members(uuid,integer,integer,text,text),public.phase12_set_feature_flag(uuid,text,boolean,uuid),public.phase12_set_maintenance(uuid,boolean,text,timestamptz,timestamptz,uuid),public.phase12_upsert_notification_template(uuid,uuid,text,text,text,text,boolean,uuid),public.phase12_update_plan(uuid,uuid,bigint,boolean,boolean,uuid),public.phase12_update_entitlement(uuid,uuid,text,boolean,numeric,text,text,uuid),public.phase12_update_content_state(uuid,text,text,text,text,uuid),public.phase12_realtime_health(uuid),public.phase12_reject_audit_mutation() to service_role;

insert into public.app_settings(key,value) values('app.phase','{"phase":12,"status":"operations_admin_platform"}'::jsonb) on conflict(key) do update set value=excluded.value,updated_at=now();
insert into public.app_settings(key,value) values('admin.phase12',jsonb_build_object('authorization_source','admin_users','audit','immutable','member_pagination','server_rpc','maintenance_mode',true,'feature_flags',true)) on conflict(key) do update set value=excluded.value,updated_at=now();
