-- CA Progress V2 — CA Mentor / Think Engine Phase 2: Academic Catalog Normalisation
-- Reuses the existing verified academic engine. No source ingestion is added here.
-- Existing chapter_progress/progress_events rows remain untouched; canonical mappings are additive.

create table public.academic_catalog_nodes (
  canonical_id text primary key,
  node_type text not null check (node_type in ('course', 'group', 'subject', 'chapter', 'unit', 'accounting_standard', 'subtopic')),
  parent_canonical_id text references public.academic_catalog_nodes(canonical_id) on delete restrict,
  level_id text not null references public.course_levels(id) on delete restrict,
  group_id text references public.course_groups(id) on delete restrict,
  subject_id text references public.subjects(id) on delete restrict,
  official_code text,
  title text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.academic_catalog_version_items (
  id bigint generated by default as identity primary key,
  canonical_id text not null references public.academic_catalog_nodes(canonical_id) on delete restrict,
  syllabus_version_id text not null references public.syllabus_versions(id) on delete restrict,
  source_entity_type text not null check (source_entity_type in ('subject', 'chapter', 'topic')),
  source_entity_id text not null,
  source_stable_key text,
  source_topic_kind text,
  official_code text,
  display_title text not null,
  applicable_from date not null,
  applicable_to date,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  check (applicable_to is null or applicable_to >= applicable_from),
  unique (syllabus_version_id, source_entity_type, source_entity_id)
);

create table public.academic_catalog_aliases (
  id bigint generated by default as identity primary key,
  canonical_id text not null references public.academic_catalog_nodes(canonical_id) on delete cascade,
  alias_text text not null check (length(trim(alias_text)) > 0),
  normalized_alias text generated always as (
    trim(regexp_replace(lower(alias_text), '[^a-z0-9]+', ' ', 'g'))
  ) stored,
  alias_kind text not null check (alias_kind in ('official_title', 'official_code', 'legacy_title', 'slug', 'stable_key', 'manual')),
  subject_id text references public.subjects(id) on delete restrict,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (canonical_id, normalized_alias)
);

create table public.academic_catalog_lineage (
  predecessor_canonical_id text not null references public.academic_catalog_nodes(canonical_id) on delete restrict,
  successor_canonical_id text not null references public.academic_catalog_nodes(canonical_id) on delete restrict,
  relationship text not null check (relationship in ('renamed_to', 'superseded_by', 'split_into', 'merged_into', 'equivalent_to')),
  effective_from date,
  notes text,
  created_at timestamptz not null default now(),
  primary key (predecessor_canonical_id, successor_canonical_id, relationship),
  check (predecessor_canonical_id <> successor_canonical_id)
);

create index academic_catalog_nodes_parent_idx on public.academic_catalog_nodes (parent_canonical_id, node_type);
create index academic_catalog_nodes_scope_idx on public.academic_catalog_nodes (level_id, group_id, subject_id, node_type);
create index academic_catalog_version_items_canonical_idx on public.academic_catalog_version_items (canonical_id, syllabus_version_id);
create index academic_catalog_version_items_source_idx on public.academic_catalog_version_items (source_entity_type, source_entity_id);
create index academic_catalog_aliases_lookup_idx on public.academic_catalog_aliases (normalized_alias, subject_id);
create index academic_catalog_lineage_successor_idx on public.academic_catalog_lineage (successor_canonical_id);

create trigger academic_catalog_nodes_set_updated_at
before update on public.academic_catalog_nodes
for each row execute function public.set_updated_at();

-- Canonical IDs are CA Progress-owned and deterministic. They reuse immutable IDs/stable_keys
-- already in the academic engine; display titles never define identity.
insert into public.academic_catalog_nodes (
  canonical_id, node_type, parent_canonical_id, level_id, group_id, subject_id, official_code, title, is_active
)
select
  'course:' || l.id,
  'course',
  null,
  l.id,
  null,
  null,
  l.code,
  l.name,
  l.is_active
from public.course_levels l
on conflict (canonical_id) do nothing;

insert into public.academic_catalog_nodes (
  canonical_id, node_type, parent_canonical_id, level_id, group_id, subject_id, official_code, title, is_active
)
select
  'group:' || g.id,
  'group',
  'course:' || g.level_id,
  g.level_id,
  g.id,
  null,
  g.code,
  g.name,
  g.is_active
from public.course_groups g
on conflict (canonical_id) do nothing;

insert into public.academic_catalog_nodes (
  canonical_id, node_type, parent_canonical_id, level_id, group_id, subject_id, official_code, title, is_active
)
select
  'subject:' || s.id,
  'subject',
  'group:' || s.group_id,
  s.level_id,
  s.group_id,
  s.id,
  s.code,
  s.title,
  s.is_active
from public.subjects s
on conflict (canonical_id) do nothing;

with chapter_candidates as (
  select
    'chapter:' || s.id || ':' || c.stable_key as canonical_id,
    'subject:' || s.id as parent_canonical_id,
    s.level_id,
    s.group_id,
    s.id as subject_id,
    c.chapter_number as official_code,
    c.title,
    (sv.status = 'published') as is_active,
    sv.effective_from,
    sv.status
  from public.chapters c
  join public.syllabus_versions sv on sv.id = c.syllabus_version_id
  join public.subjects s on s.id = sv.subject_id
),
chapter_current as (
  select distinct on (canonical_id)
    canonical_id, parent_canonical_id, level_id, group_id, subject_id, official_code, title, is_active
  from chapter_candidates
  order by canonical_id, (status = 'published') desc, effective_from desc
)
insert into public.academic_catalog_nodes (
  canonical_id, node_type, parent_canonical_id, level_id, group_id, subject_id, official_code, title, is_active
)
select
  canonical_id, 'chapter', parent_canonical_id, level_id, group_id, subject_id, official_code, title, is_active
from chapter_current
on conflict (canonical_id) do nothing;

with topic_candidates as (
  select
    'topic:' || s.id || ':' || c.stable_key || ':' || t.stable_key as canonical_id,
    case
      when t.topic_kind = 'accounting_standard' then 'accounting_standard'
      when t.topic_kind = 'unit' then 'unit'
      else 'subtopic'
    end as node_type,
    'chapter:' || s.id || ':' || c.stable_key as parent_canonical_id,
    s.level_id,
    s.group_id,
    s.id as subject_id,
    t.unit_number as official_code,
    t.title,
    (sv.status = 'published') as is_active,
    sv.effective_from,
    sv.status
  from public.topics t
  join public.chapters c on c.id = t.chapter_id
  join public.syllabus_versions sv on sv.id = c.syllabus_version_id
  join public.subjects s on s.id = sv.subject_id
),
topic_current as (
  select distinct on (canonical_id)
    canonical_id, node_type, parent_canonical_id, level_id, group_id, subject_id, official_code, title, is_active
  from topic_candidates
  order by canonical_id, (status = 'published') desc, effective_from desc
)
insert into public.academic_catalog_nodes (
  canonical_id, node_type, parent_canonical_id, level_id, group_id, subject_id, official_code, title, is_active
)
select
  canonical_id, node_type, parent_canonical_id, level_id, group_id, subject_id, official_code, title, is_active
from topic_current
on conflict (canonical_id) do nothing;

-- Bind every historical and current syllabus row to the stable canonical identity.
insert into public.academic_catalog_version_items (
  canonical_id, syllabus_version_id, source_entity_type, source_entity_id, source_stable_key,
  source_topic_kind, official_code, display_title, applicable_from, applicable_to, is_active
)
select
  'subject:' || s.id,
  sv.id,
  'subject',
  s.id,
  s.code,
  null,
  s.code,
  s.title,
  sv.effective_from,
  sv.effective_to,
  (sv.status in ('published', 'upcoming'))
from public.syllabus_versions sv
join public.subjects s on s.id = sv.subject_id
on conflict (syllabus_version_id, source_entity_type, source_entity_id) do nothing;

insert into public.academic_catalog_version_items (
  canonical_id, syllabus_version_id, source_entity_type, source_entity_id, source_stable_key,
  source_topic_kind, official_code, display_title, applicable_from, applicable_to, is_active
)
select
  'chapter:' || s.id || ':' || c.stable_key,
  sv.id,
  'chapter',
  c.id,
  c.stable_key,
  null,
  c.chapter_number,
  c.title,
  sv.effective_from,
  sv.effective_to,
  (sv.status in ('published', 'upcoming'))
from public.chapters c
join public.syllabus_versions sv on sv.id = c.syllabus_version_id
join public.subjects s on s.id = sv.subject_id
on conflict (syllabus_version_id, source_entity_type, source_entity_id) do nothing;

insert into public.academic_catalog_version_items (
  canonical_id, syllabus_version_id, source_entity_type, source_entity_id, source_stable_key,
  source_topic_kind, official_code, display_title, applicable_from, applicable_to, is_active
)
select
  'topic:' || s.id || ':' || c.stable_key || ':' || t.stable_key,
  sv.id,
  'topic',
  t.id,
  t.stable_key,
  t.topic_kind,
  t.unit_number,
  t.title,
  sv.effective_from,
  sv.effective_to,
  (sv.status in ('published', 'upcoming'))
from public.topics t
join public.chapters c on c.id = t.chapter_id
join public.syllabus_versions sv on sv.id = c.syllabus_version_id
join public.subjects s on s.id = sv.subject_id
on conflict (syllabus_version_id, source_entity_type, source_entity_id) do nothing;

-- Seed aliases only from data that already exists in the verified catalog. Historical display
-- titles therefore become aliases automatically when the same stable_key survives a rename.
insert into public.academic_catalog_aliases (canonical_id, alias_text, alias_kind, subject_id)
select n.canonical_id, n.title, 'official_title', n.subject_id
from public.academic_catalog_nodes n
on conflict (canonical_id, normalized_alias) do nothing;

insert into public.academic_catalog_aliases (canonical_id, alias_text, alias_kind, subject_id)
select n.canonical_id, n.official_code, 'official_code', n.subject_id
from public.academic_catalog_nodes n
where n.official_code is not null and length(trim(n.official_code)) > 0
on conflict (canonical_id, normalized_alias) do nothing;

insert into public.academic_catalog_aliases (canonical_id, alias_text, alias_kind, subject_id)
select vi.canonical_id, vi.display_title, 'legacy_title', n.subject_id
from public.academic_catalog_version_items vi
join public.academic_catalog_nodes n on n.canonical_id = vi.canonical_id
on conflict (canonical_id, normalized_alias) do nothing;

insert into public.academic_catalog_aliases (canonical_id, alias_text, alias_kind, subject_id)
select vi.canonical_id, vi.source_stable_key, 'stable_key', n.subject_id
from public.academic_catalog_version_items vi
join public.academic_catalog_nodes n on n.canonical_id = vi.canonical_id
where vi.source_stable_key is not null and length(trim(vi.source_stable_key)) > 0
on conflict (canonical_id, normalized_alias) do nothing;

insert into public.academic_catalog_aliases (canonical_id, alias_text, alias_kind, subject_id)
select 'subject:' || s.id, s.slug, 'slug', s.id
from public.subjects s
on conflict (canonical_id, normalized_alias) do nothing;

insert into public.academic_catalog_aliases (canonical_id, alias_text, alias_kind, subject_id)
select 'subject:' || s.id, s.paper_label, 'official_code', s.id
from public.subjects s
where length(trim(s.paper_label)) > 0
on conflict (canonical_id, normalized_alias) do nothing;

insert into public.academic_catalog_aliases (canonical_id, alias_text, alias_kind, subject_id)
select 'chapter:' || s.id || ':' || c.stable_key, c.slug, 'slug', s.id
from public.chapters c
join public.syllabus_versions sv on sv.id = c.syllabus_version_id
join public.subjects s on s.id = sv.subject_id
where length(trim(c.slug)) > 0
on conflict (canonical_id, normalized_alias) do nothing;

-- Existing syllabus_versions.supersedes_version_id is preserved and exposed in both directions.
create view public.academic_syllabus_lineage
with (security_invoker = true)
as
select
  predecessor.id as predecessor_version_id,
  successor.id as successor_version_id,
  predecessor.subject_id,
  predecessor.version_key as predecessor_version_key,
  successor.version_key as successor_version_key,
  successor.effective_from
from public.syllabus_versions successor
join public.syllabus_versions predecessor on predecessor.id = successor.supersedes_version_id;

-- Item lineage is deliberately not inferred from title similarity. When a future syllabus
-- splits/merges/replaces a concept, the explicit academic_catalog_lineage table records it.

create or replace function public.academic_catalog_resolve_legacy(
  p_entity_type text,
  p_entity_id text,
  p_syllabus_version_id text default null
)
returns text
language sql
stable
set search_path = public, pg_temp
as $$
  select case
    when count(distinct vi.canonical_id) = 1 then min(vi.canonical_id)
    else null
  end
  from public.academic_catalog_version_items vi
  where vi.source_entity_type = p_entity_type
    and vi.source_entity_id = p_entity_id
    and (p_syllabus_version_id is null or vi.syllabus_version_id = p_syllabus_version_id);
$$;

create or replace function public.academic_catalog_is_applicable(
  p_canonical_id text,
  p_attempt_key text
)
returns boolean
language sql
stable
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.academic_catalog_version_items vi
    join public.attempt_syllabus_map asm
      on asm.syllabus_version_id = vi.syllabus_version_id
    where vi.canonical_id = p_canonical_id
      and asm.attempt_key = p_attempt_key
  );
$$;

create or replace function public.academic_catalog_resolve_alias(
  p_alias text,
  p_attempt_key text default null,
  p_subject_id text default null,
  p_node_type text default null
)
returns table (
  canonical_id text,
  node_type text,
  title text,
  official_code text,
  syllabus_version_id text
)
language sql
stable
set search_path = public, pg_temp
as $$
  select distinct
    n.canonical_id,
    n.node_type,
    n.title,
    n.official_code,
    vi.syllabus_version_id
  from public.academic_catalog_aliases a
  join public.academic_catalog_nodes n on n.canonical_id = a.canonical_id
  left join public.academic_catalog_version_items vi on vi.canonical_id = n.canonical_id
  where a.is_active
    and a.normalized_alias = trim(regexp_replace(lower(p_alias), '[^a-z0-9]+', ' ', 'g'))
    and (p_subject_id is null or n.subject_id = p_subject_id)
    and (p_node_type is null or n.node_type = p_node_type)
    and (
      p_attempt_key is null
      or public.academic_catalog_is_applicable(n.canonical_id, p_attempt_key)
    )
  order by n.node_type, n.title, vi.syllabus_version_id nulls last;
$$;

create or replace function public.academic_catalog_resolve_alias_one(
  p_alias text,
  p_attempt_key text default null,
  p_subject_id text default null,
  p_node_type text default null
)
returns text
language sql
stable
set search_path = public, pg_temp
as $$
  select case
    when count(distinct candidate.canonical_id) = 1 then min(candidate.canonical_id)
    else null
  end
  from public.academic_catalog_resolve_alias(p_alias, p_attempt_key, p_subject_id, p_node_type) candidate;
$$;

-- Canonical progress views map old/current chapter IDs without rewriting a single progress row.
create view public.chapter_progress_canonical
with (security_invoker = true)
as
select
  cp.user_id,
  cp.chapter_id,
  vi.canonical_id,
  vi.syllabus_version_id,
  vi.official_code as chapter_number,
  cp.completed_at,
  cp.revision_1_at,
  cp.revision_2_at,
  cp.test_1_at,
  cp.test_2_at,
  cp.created_at,
  cp.updated_at
from public.chapter_progress cp
join public.chapters c on c.id = cp.chapter_id
join public.academic_catalog_version_items vi
  on vi.source_entity_type = 'chapter'
 and vi.source_entity_id = cp.chapter_id
 and vi.syllabus_version_id = c.syllabus_version_id;

create view public.progress_events_canonical
with (security_invoker = true)
as
select
  pe.id,
  pe.user_id,
  pe.chapter_id,
  vi.canonical_id,
  vi.syllabus_version_id,
  vi.official_code as chapter_number,
  pe.stage,
  pe.action,
  pe.previous_state,
  pe.new_state,
  pe.reverts_event_id,
  pe.undone_at,
  pe.created_at
from public.progress_events pe
join public.chapters c on c.id = pe.chapter_id
join public.academic_catalog_version_items vi
  on vi.source_entity_type = 'chapter'
 and vi.source_entity_id = pe.chapter_id
 and vi.syllabus_version_id = c.syllabus_version_id;

alter table public.academic_catalog_nodes enable row level security;
alter table public.academic_catalog_version_items enable row level security;
alter table public.academic_catalog_aliases enable row level security;
alter table public.academic_catalog_lineage enable row level security;

create policy "academic_catalog_nodes_read"
on public.academic_catalog_nodes for select to anon, authenticated using (true);

create policy "academic_catalog_version_items_read"
on public.academic_catalog_version_items for select to anon, authenticated using (true);

create policy "academic_catalog_aliases_read"
on public.academic_catalog_aliases for select to anon, authenticated using (true);

create policy "academic_catalog_lineage_read"
on public.academic_catalog_lineage for select to anon, authenticated using (true);

grant select on
  public.academic_catalog_nodes,
  public.academic_catalog_version_items,
  public.academic_catalog_aliases,
  public.academic_catalog_lineage,
  public.academic_syllabus_lineage
to anon, authenticated;

revoke insert, update, delete, truncate, references, trigger on
  public.academic_catalog_nodes,
  public.academic_catalog_version_items,
  public.academic_catalog_aliases,
  public.academic_catalog_lineage
from anon, authenticated;

grant execute on function public.academic_catalog_resolve_legacy(text, text, text) to anon, authenticated, service_role;
grant execute on function public.academic_catalog_is_applicable(text, text) to anon, authenticated, service_role;
grant execute on function public.academic_catalog_resolve_alias(text, text, text, text) to anon, authenticated, service_role;
grant execute on function public.academic_catalog_resolve_alias_one(text, text, text, text) to anon, authenticated, service_role;

revoke all on public.chapter_progress_canonical from anon;
revoke all on public.progress_events_canonical from anon;
grant select on public.chapter_progress_canonical, public.progress_events_canonical to authenticated, service_role;

insert into public.app_settings (key, value, is_public)
values (
  'mentor.phase2',
  '{"phase":2,"status":"academic_catalog_normalized","identity":"stable","historical_progress":"preserved","source_ingestion":"not_started","next_phase":"not_started"}'::jsonb,
  true
)
on conflict (key) do update
set value = excluded.value,
    is_public = excluded.is_public,
    updated_at = now();
