-- CA Progress V2 - Phase 10 Community V2 & Collaborative Learning
-- V2 only. Phase 7 approved uploads are the only community attachment source.

create table public.community_channels (
  id uuid primary key default gen_random_uuid(),
  channel_key text not null unique check (char_length(channel_key) between 1 and 180),
  slug text not null unique check (char_length(slug) between 1 and 180),
  scope_type text not null check (scope_type in ('global','level','subject')),
  channel_kind text not null check (channel_kind in ('general','announcements','resources','result_talk','general_talk','doubts')),
  level_id text references public.course_levels(id) on delete restrict,
  subject_id text references public.subjects(id) on delete restrict,
  title text not null check (char_length(title) between 1 and 120),
  description text not null default '' check (char_length(description) <= 500),
  write_policy text not null default 'members' check (write_policy in ('members','moderators')),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint community_channel_scope_shape check (
    (scope_type = 'global' and level_id is null and subject_id is null)
    or (scope_type = 'level' and level_id is not null and subject_id is null)
    or (scope_type = 'subject' and subject_id is not null)
  )
);

create table public.community_messages (
  id uuid primary key default gen_random_uuid(),
  sequence_id bigint generated by default as identity unique,
  channel_id uuid not null references public.community_channels(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_label text not null check (char_length(author_label) between 1 and 100),
  body text not null check (char_length(body) between 1 and 2000),
  reply_to_message_id uuid references public.community_messages(id) on delete set null,
  attached_resource_id uuid references public.uploaded_resources(id) on delete set null,
  moderation_status text not null default 'active' check (moderation_status in ('active','moderated','deleted')),
  edited_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.message_reactions (
  message_id uuid not null references public.community_messages(id) on delete cascade,
  channel_id uuid not null references public.community_channels(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  emoji text not null check (emoji in ('👍','❤️','🎯','👏','💡','✅')),
  created_at timestamptz not null default now(),
  primary key (message_id, user_id, emoji)
);

create table public.channel_read_state (
  channel_id uuid not null references public.community_channels(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  last_read_sequence bigint not null default 0 check (last_read_sequence >= 0),
  last_read_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (channel_id, user_id)
);

create table public.pinned_messages (
  channel_id uuid not null references public.community_channels(id) on delete cascade,
  message_id uuid not null references public.community_messages(id) on delete cascade,
  pinned_by uuid not null references auth.users(id) on delete restrict,
  pinned_at timestamptz not null default now(),
  primary key (channel_id, message_id)
);

create table public.message_reports (
  id uuid primary key default gen_random_uuid(),
  message_id uuid not null references public.community_messages(id) on delete cascade,
  channel_id uuid not null references public.community_channels(id) on delete cascade,
  reporter_user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (reason in ('spam','harassment','misinformation','off_topic','other')),
  details text check (details is null or char_length(details) <= 1000),
  status text not null default 'open' check (status in ('open','actioned','dismissed')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (message_id, reporter_user_id)
);

create table public.chat_blocks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  channel_id uuid references public.community_channels(id) on delete cascade,
  blocked_by uuid not null references auth.users(id) on delete restrict,
  reason text not null default 'Chat moderation' check (char_length(reason) between 1 and 500),
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint chat_block_positive_window check (ends_at > starts_at)
);

create table public.moderation_actions (
  id uuid primary key default gen_random_uuid(),
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  actor_role text not null check (actor_role in ('moderator','admin','owner','parent_owner')),
  action_type text not null check (action_type in ('delete_message','restore_message','pin','unpin','block','unblock','dismiss_report','resolve_report')),
  channel_id uuid references public.community_channels(id) on delete set null,
  message_id uuid references public.community_messages(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  report_id uuid references public.message_reports(id) on delete set null,
  reason text check (reason is null or char_length(reason) <= 500),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create table public.community_message_mentions (
  message_id uuid not null references public.community_messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (message_id, user_id)
);

create table public.community_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  notification_type text not null check (notification_type in ('mention','reply','announcement')),
  channel_id uuid not null references public.community_channels(id) on delete cascade,
  message_id uuid not null references public.community_messages(id) on delete cascade,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, notification_type, message_id)
);

create index community_channels_scope_idx on public.community_channels (is_active, scope_type, level_id, subject_id, sort_order);
create index community_messages_channel_sequence_idx on public.community_messages (channel_id, sequence_id desc);
create index community_messages_user_created_idx on public.community_messages (user_id, created_at desc);
create index community_messages_active_search_idx on public.community_messages using gin (to_tsvector('simple', body));
create index message_reactions_channel_idx on public.message_reactions (channel_id, message_id);
create index channel_read_state_user_idx on public.channel_read_state (user_id, channel_id);
create index pinned_messages_channel_idx on public.pinned_messages (channel_id, pinned_at desc);
create index message_reports_status_idx on public.message_reports (status, created_at desc);
create index chat_blocks_user_active_idx on public.chat_blocks (user_id, ends_at desc);
create index moderation_actions_created_idx on public.moderation_actions (created_at desc);
create index community_notifications_user_unread_idx on public.community_notifications (user_id, read_at, created_at desc);

create trigger community_channels_set_updated_at before update on public.community_channels for each row execute function public.set_updated_at();
create trigger community_messages_set_updated_at before update on public.community_messages for each row execute function public.set_updated_at();
create trigger channel_read_state_set_updated_at before update on public.channel_read_state for each row execute function public.set_updated_at();

create or replace function public.phase10_current_role()
returns text
language sql
stable
set search_path = public, auth, pg_temp
as $$
  select case
    when coalesce(auth.jwt() -> 'app_metadata' ->> 'role','student') in ('moderator','admin','owner','parent_owner')
      then auth.jwt() -> 'app_metadata' ->> 'role'
    else 'student'
  end;
$$;

create or replace function public.phase10_is_moderator()
returns boolean
language sql
stable
set search_path = public, auth, pg_temp
as $$
  select public.phase10_current_role() in ('moderator','admin','owner','parent_owner');
$$;

create or replace function public.phase10_channel_visible_to_user(p_channel_id uuid, p_user_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_channel public.community_channels;
  v_profile public.profiles;
  v_level_code text;
  v_group_code text;
begin
  if p_user_id is null then return false; end if;
  select * into v_channel from public.community_channels where id = p_channel_id and is_active = true;
  if not found then return false; end if;
  if v_channel.scope_type = 'global' then return true; end if;
  select * into v_profile from public.profiles where user_id = p_user_id;
  if not found or v_profile.onboarding_completed_at is null then return false; end if;

  if v_channel.scope_type = 'level' then
    select code into v_level_code from public.course_levels where id = v_channel.level_id and is_active = true;
    return v_level_code is not null and v_profile.ca_level = v_level_code;
  end if;

  select cl.code, cg.code
  into v_level_code, v_group_code
  from public.subjects s
  join public.course_levels cl on cl.id = s.level_id and cl.is_active = true
  join public.course_groups cg on cg.id = s.group_id
  where s.id = v_channel.subject_id and s.is_active = true;

  if v_level_code is null or v_profile.ca_level <> v_level_code then return false; end if;
  if v_group_code = 'all' then return true; end if;
  return v_profile.group_choice = 'both' or v_profile.group_choice = v_group_code;
end;
$$;

create or replace function public.phase10_can_view_channel(p_channel_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select auth.uid() is not null
    and (public.phase10_is_moderator() or public.phase10_channel_visible_to_user(p_channel_id, auth.uid()));
$$;

create or replace function public.phase10_is_chat_blocked(p_user_id uuid, p_channel_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select exists (
    select 1 from public.chat_blocks b
    where b.user_id = p_user_id
      and b.starts_at <= now()
      and b.ends_at > now()
      and (b.channel_id is null or b.channel_id = p_channel_id)
  );
$$;

create or replace function public.phase10_can_write_channel(p_channel_id uuid)
returns boolean
language plpgsql
stable
security definer
set search_path = public, auth, pg_temp
as $$
declare v_policy text;
begin
  if auth.uid() is null then return false; end if;
  if not (public.phase10_is_moderator() or public.phase10_channel_visible_to_user(p_channel_id, auth.uid())) then return false; end if;
  if public.phase10_is_chat_blocked(auth.uid(), p_channel_id) then return false; end if;
  select write_policy into v_policy from public.community_channels where id = p_channel_id and is_active = true;
  if v_policy is null then return false; end if;
  return v_policy = 'members' or public.phase10_is_moderator();
end;
$$;

create or replace function public.phase10_sync_community_channels()
returns void
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
begin
  insert into public.community_channels (channel_key,slug,scope_type,channel_kind,title,description,write_policy,sort_order,is_active)
  values ('global:general','general','global','general','General','Community-wide CA student discussion.','members',0,true)
  on conflict (channel_key) do update set title=excluded.title,description=excluded.description,is_active=true;

  insert into public.community_channels (channel_key,slug,scope_type,channel_kind,level_id,title,description,write_policy,sort_order,is_active)
  select 'level:'||cl.id||':'||kind.kind,
         lower(cl.code)||'-'||replace(kind.kind,'_','-'),
         'level',kind.kind,cl.id,kind.title,kind.description,kind.policy,kind.ordering,cl.is_active
  from public.course_levels cl
  cross join (values
    ('announcements','Announcements','Important level-specific announcements.','moderators',10),
    ('resources','Resources','Discuss approved study resources for this level.','members',20),
    ('result_talk','Result Talk','Discuss results, attempts and exam experiences.','members',30),
    ('general_talk','General Talk','Level-specific peer discussion.','members',40)
  ) as kind(kind,title,description,policy,ordering)
  on conflict (channel_key) do update set slug=excluded.slug,title=excluded.title,description=excluded.description,write_policy=excluded.write_policy,sort_order=excluded.sort_order,is_active=excluded.is_active;

  insert into public.community_channels (channel_key,slug,scope_type,channel_kind,level_id,subject_id,title,description,write_policy,sort_order,is_active)
  select 'subject:'||s.id||':doubts',
         lower(cl.code)||'-'||s.slug||'-doubts',
         'subject','doubts',s.level_id,s.id,s.title,'Subject doubts and collaborative problem solving.','members',100+s.sort_order,(s.is_active and cl.is_active)
  from public.subjects s
  join public.course_levels cl on cl.id=s.level_id
  on conflict (channel_key) do update set slug=excluded.slug,level_id=excluded.level_id,subject_id=excluded.subject_id,title=excluded.title,description=excluded.description,sort_order=excluded.sort_order,is_active=excluded.is_active;
end;
$$;

create or replace function public.phase10_reference_channel_sync_trigger()
returns trigger
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
begin
  perform public.phase10_sync_community_channels();
  return coalesce(new,old);
end;
$$;

create trigger phase10_levels_channel_sync after insert or update of code,name,is_active on public.course_levels for each statement execute function public.phase10_reference_channel_sync_trigger();
create trigger phase10_subjects_channel_sync after insert or update of slug,title,level_id,group_id,is_active on public.subjects for each statement execute function public.phase10_reference_channel_sync_trigger();

select public.phase10_sync_community_channels();

alter table public.community_channels enable row level security;
alter table public.community_messages enable row level security;
alter table public.message_reactions enable row level security;
alter table public.channel_read_state enable row level security;
alter table public.pinned_messages enable row level security;
alter table public.message_reports enable row level security;
alter table public.chat_blocks enable row level security;
alter table public.moderation_actions enable row level security;
alter table public.community_message_mentions enable row level security;
alter table public.community_notifications enable row level security;

create policy community_channels_read_visible on public.community_channels for select to authenticated using (public.phase10_can_view_channel(id));
create policy community_messages_read_visible on public.community_messages for select to authenticated using (public.phase10_can_view_channel(channel_id));
create policy message_reactions_read_visible on public.message_reactions for select to authenticated using (public.phase10_can_view_channel(channel_id));
create policy channel_read_state_read_own on public.channel_read_state for select to authenticated using ((select auth.uid())=user_id and public.phase10_can_view_channel(channel_id));
create policy pinned_messages_read_visible on public.pinned_messages for select to authenticated using (public.phase10_can_view_channel(channel_id));
create policy message_reports_read_own on public.message_reports for select to authenticated using ((select auth.uid())=reporter_user_id);
create policy chat_blocks_read_own on public.chat_blocks for select to authenticated using ((select auth.uid())=user_id);
create policy moderation_actions_read_privileged on public.moderation_actions for select to authenticated using (public.phase10_is_moderator());
create policy message_mentions_read_own on public.community_message_mentions for select to authenticated using ((select auth.uid())=user_id);
create policy community_notifications_read_own on public.community_notifications for select to authenticated using ((select auth.uid())=user_id);

revoke all on public.community_channels, public.community_messages, public.message_reactions, public.channel_read_state, public.pinned_messages, public.message_reports, public.chat_blocks, public.moderation_actions, public.community_message_mentions, public.community_notifications from anon;
revoke insert,update,delete,truncate,references,trigger on public.community_channels, public.community_messages, public.message_reactions, public.channel_read_state, public.pinned_messages, public.message_reports, public.chat_blocks, public.moderation_actions, public.community_message_mentions, public.community_notifications from authenticated;
grant select on public.community_channels, public.community_messages, public.message_reactions, public.channel_read_state, public.pinned_messages, public.message_reports, public.chat_blocks, public.moderation_actions, public.community_message_mentions, public.community_notifications to authenticated;
grant all on public.community_channels, public.community_messages, public.message_reactions, public.channel_read_state, public.pinned_messages, public.message_reports, public.chat_blocks, public.moderation_actions, public.community_message_mentions, public.community_notifications to service_role;

grant usage,select on sequence public.community_messages_sequence_id_seq to service_role;

create or replace function public.phase10_list_channels()
returns table (
  id uuid,
  channel_key text,
  slug text,
  scope_type text,
  channel_kind text,
  title text,
  description text,
  level_id text,
  subject_id text,
  write_policy text,
  sort_order integer,
  can_write boolean,
  unread_count bigint,
  latest_sequence bigint,
  latest_body text,
  latest_author text,
  latest_at timestamptz
)
language sql
stable
security definer
set search_path = public, auth, pg_temp
as $$
  select c.id,c.channel_key,c.slug,c.scope_type,c.channel_kind,c.title,c.description,c.level_id,c.subject_id,c.write_policy,c.sort_order,
         public.phase10_can_write_channel(c.id),
         (select count(*) from public.community_messages m
          where m.channel_id=c.id and m.moderation_status='active' and m.user_id<>auth.uid()
            and m.sequence_id>coalesce((select r.last_read_sequence from public.channel_read_state r where r.channel_id=c.id and r.user_id=auth.uid()),0))::bigint,
         latest.sequence_id,latest.body,latest.author_label,latest.created_at
  from public.community_channels c
  left join lateral (
    select m.sequence_id,m.body,m.author_label,m.created_at
    from public.community_messages m
    where m.channel_id=c.id and m.moderation_status='active'
    order by m.sequence_id desc limit 1
  ) latest on true
  where c.is_active=true and public.phase10_can_view_channel(c.id)
  order by c.sort_order,c.title;
$$;

create or replace function public.phase10_list_channel_members(p_channel_key text, p_limit integer default 100)
returns table (user_id uuid, label text)
language plpgsql
stable
security definer
set search_path = public, auth, pg_temp
as $$
declare v_channel_id uuid;
begin
  select c.id into v_channel_id from public.community_channels c where c.channel_key=p_channel_key and c.is_active=true;
  if v_channel_id is null or not public.phase10_can_view_channel(v_channel_id) then raise exception 'Channel access denied.' using errcode='42501'; end if;
  return query
    select p.user_id,coalesce(nullif(btrim(p.display_name),''),'Student')
    from public.profiles p
    where p.onboarding_completed_at is not null and public.phase10_channel_visible_to_user(v_channel_id,p.user_id)
    order by coalesce(nullif(btrim(p.display_name),''),'Student')
    limit greatest(1,least(coalesce(p_limit,100),200));
end;
$$;

create or replace function public.phase10_create_message(
  p_channel_key text,
  p_body text,
  p_reply_to_message_id uuid default null,
  p_attached_resource_id uuid default null,
  p_mention_user_ids uuid[] default '{}'::uuid[]
)
returns uuid
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_channel public.community_channels;
  v_message_id uuid;
  v_author_label text;
  v_reply_user uuid;
  v_mentions uuid[] := coalesce(p_mention_user_ids,'{}'::uuid[]);
begin
  if v_user_id is null then raise exception 'Authentication required.' using errcode='42501'; end if;
  select * into v_channel from public.community_channels where channel_key=p_channel_key and is_active=true;
  if not found or not public.phase10_can_write_channel(v_channel.id) then raise exception 'You cannot write to this channel.' using errcode='42501'; end if;
  p_body := regexp_replace(coalesce(p_body,''),'[[:space:]]+',' ','g');
  p_body := btrim(p_body);
  if char_length(p_body) < 1 or char_length(p_body) > 2000 then raise exception 'Messages must be between 1 and 2000 characters.' using errcode='22023'; end if;
  if coalesce(array_length(v_mentions,1),0) > 10 then raise exception 'A message can mention at most 10 people.' using errcode='22023'; end if;

  if (select count(*) from public.community_messages m where m.user_id=v_user_id and m.created_at>now()-interval '60 seconds') >= 12 then
    raise exception 'Message rate limit reached. Try again in a moment.' using errcode='P0001';
  end if;
  if exists (select 1 from public.community_messages m where m.user_id=v_user_id and m.channel_id=v_channel.id and lower(btrim(m.body))=lower(p_body) and m.created_at>now()-interval '90 seconds' and m.moderation_status='active') then
    raise exception 'Duplicate message blocked.' using errcode='P0001';
  end if;

  if p_reply_to_message_id is not null then
    select user_id into v_reply_user from public.community_messages where id=p_reply_to_message_id and channel_id=v_channel.id and moderation_status='active';
    if v_reply_user is null then raise exception 'Reply target is unavailable.' using errcode='22023'; end if;
  end if;

  if p_attached_resource_id is not null and not exists (
    select 1 from public.uploaded_resources u where u.id=p_attached_resource_id and u.visibility='shared' and u.moderation_status='approved'
  ) then raise exception 'Only approved shared resources can be attached.' using errcode='42501'; end if;

  select coalesce(nullif(btrim(display_name),''),'Student') into v_author_label from public.profiles where user_id=v_user_id;
  v_author_label := coalesce(v_author_label,'Student');

  insert into public.community_messages (channel_id,user_id,author_label,body,reply_to_message_id,attached_resource_id)
  values (v_channel.id,v_user_id,v_author_label,p_body,p_reply_to_message_id,p_attached_resource_id)
  returning id into v_message_id;

  insert into public.community_message_mentions (message_id,user_id)
  select v_message_id,x.user_id
  from (select distinct unnest(v_mentions) as user_id) x
  where x.user_id<>v_user_id and public.phase10_channel_visible_to_user(v_channel.id,x.user_id)
  on conflict do nothing;

  insert into public.community_notifications (user_id,notification_type,channel_id,message_id)
  select mm.user_id,'mention',v_channel.id,v_message_id
  from public.community_message_mentions mm where mm.message_id=v_message_id
  on conflict do nothing;

  if v_reply_user is not null and v_reply_user<>v_user_id then
    insert into public.community_notifications (user_id,notification_type,channel_id,message_id)
    values (v_reply_user,'reply',v_channel.id,v_message_id)
    on conflict do nothing;
  end if;

  if v_channel.channel_kind='announcements' and public.phase10_is_moderator() then
    insert into public.community_notifications (user_id,notification_type,channel_id,message_id)
    select p.user_id,'announcement',v_channel.id,v_message_id
    from public.profiles p
    where p.user_id<>v_user_id and p.onboarding_completed_at is not null and public.phase10_channel_visible_to_user(v_channel.id,p.user_id)
    on conflict do nothing;
  end if;

  return v_message_id;
end;
$$;

create or replace function public.phase10_mark_read(p_channel_key text, p_sequence_id bigint default null)
returns bigint
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare v_user_id uuid:=auth.uid(); v_channel_id uuid; v_sequence bigint;
begin
  if v_user_id is null then raise exception 'Authentication required.' using errcode='42501'; end if;
  select id into v_channel_id from public.community_channels where channel_key=p_channel_key and is_active=true;
  if v_channel_id is null or not public.phase10_can_view_channel(v_channel_id) then raise exception 'Channel access denied.' using errcode='42501'; end if;
  select coalesce(max(sequence_id),0) into v_sequence from public.community_messages where channel_id=v_channel_id and moderation_status='active';
  if p_sequence_id is not null then v_sequence:=least(v_sequence,greatest(p_sequence_id,0)); end if;
  insert into public.channel_read_state (channel_id,user_id,last_read_sequence,last_read_at)
  values (v_channel_id,v_user_id,v_sequence,now())
  on conflict (channel_id,user_id) do update set last_read_sequence=greatest(public.channel_read_state.last_read_sequence,excluded.last_read_sequence),last_read_at=now();
  update public.community_notifications set read_at=coalesce(read_at,now()) where user_id=v_user_id and channel_id=v_channel_id and read_at is null;
  return v_sequence;
end;
$$;

create or replace function public.phase10_toggle_reaction(p_message_id uuid,p_emoji text)
returns boolean
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare v_user_id uuid:=auth.uid(); v_channel_id uuid;
begin
  if v_user_id is null then raise exception 'Authentication required.' using errcode='42501'; end if;
  if p_emoji not in ('👍','❤️','🎯','👏','💡','✅') then raise exception 'Unsupported reaction.' using errcode='22023'; end if;
  select channel_id into v_channel_id from public.community_messages where id=p_message_id and moderation_status='active';
  if v_channel_id is null or not public.phase10_can_view_channel(v_channel_id) then raise exception 'Message access denied.' using errcode='42501'; end if;
  if exists (select 1 from public.message_reactions where message_id=p_message_id and user_id=v_user_id and emoji=p_emoji) then
    delete from public.message_reactions where message_id=p_message_id and user_id=v_user_id and emoji=p_emoji;
    return false;
  end if;
  insert into public.message_reactions (message_id,channel_id,user_id,emoji) values (p_message_id,v_channel_id,v_user_id,p_emoji);
  return true;
end;
$$;

create or replace function public.phase10_report_message(p_message_id uuid,p_reason text,p_details text default null)
returns uuid
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare v_user_id uuid:=auth.uid(); v_channel_id uuid; v_report_id uuid;
begin
  if v_user_id is null then raise exception 'Authentication required.' using errcode='42501'; end if;
  if p_reason not in ('spam','harassment','misinformation','off_topic','other') then raise exception 'Invalid report reason.' using errcode='22023'; end if;
  if p_details is not null and char_length(p_details)>1000 then raise exception 'Report details are too long.' using errcode='22023'; end if;
  select channel_id into v_channel_id from public.community_messages where id=p_message_id and moderation_status='active';
  if v_channel_id is null or not public.phase10_can_view_channel(v_channel_id) then raise exception 'Message access denied.' using errcode='42501'; end if;
  insert into public.message_reports (message_id,channel_id,reporter_user_id,reason,details,status)
  values (p_message_id,v_channel_id,v_user_id,p_reason,p_details,'open')
  on conflict (message_id,reporter_user_id) do update set reason=excluded.reason,details=excluded.details,status='open',reviewed_by=null,reviewed_at=null
  returning id into v_report_id;
  return v_report_id;
end;
$$;

create or replace function public.phase10_moderate(
  p_action text,
  p_message_id uuid default null,
  p_report_id uuid default null,
  p_target_user_id uuid default null,
  p_channel_id uuid default null,
  p_reason text default null,
  p_duration_minutes integer default null
)
returns uuid
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor uuid:=auth.uid();
  v_role text:=public.phase10_current_role();
  v_action_id uuid;
  v_channel_id uuid:=p_channel_id;
  v_target_user uuid:=p_target_user_id;
begin
  if v_actor is null or v_role not in ('moderator','admin','owner','parent_owner') then raise exception 'Moderator access required.' using errcode='42501'; end if;
  if p_reason is not null and char_length(p_reason)>500 then raise exception 'Moderation reason is too long.' using errcode='22023'; end if;

  if p_message_id is not null then
    select channel_id,user_id into v_channel_id,v_target_user from public.community_messages where id=p_message_id;
  end if;

  if p_action='delete_message' then
    if p_message_id is null then raise exception 'Message required.' using errcode='22023'; end if;
    update public.community_messages set moderation_status='moderated',deleted_at=now() where id=p_message_id;
  elsif p_action='restore_message' then
    if p_message_id is null then raise exception 'Message required.' using errcode='22023'; end if;
    update public.community_messages set moderation_status='active',deleted_at=null where id=p_message_id;
  elsif p_action='pin' then
    if p_message_id is null or v_channel_id is null then raise exception 'Message required.' using errcode='22023'; end if;
    if not exists(select 1 from public.community_messages where id=p_message_id and moderation_status='active') then raise exception 'Only active messages can be pinned.' using errcode='22023'; end if;
    insert into public.pinned_messages (channel_id,message_id,pinned_by) values (v_channel_id,p_message_id,v_actor) on conflict do nothing;
  elsif p_action='unpin' then
    if p_message_id is null then raise exception 'Message required.' using errcode='22023'; end if;
    delete from public.pinned_messages where message_id=p_message_id;
  elsif p_action='block' then
    if v_target_user is null then raise exception 'Target user required.' using errcode='22023'; end if;
    if coalesce(p_duration_minutes,0) not in (60,480,1440,2880) then raise exception 'Block duration must be 1, 8, 24 or 48 hours.' using errcode='22023'; end if;
    insert into public.chat_blocks (user_id,channel_id,blocked_by,reason,ends_at)
    values (v_target_user,p_channel_id,v_actor,coalesce(nullif(btrim(p_reason),''),'Chat violation'),now()+make_interval(mins=>p_duration_minutes));
  elsif p_action='unblock' then
    if v_target_user is null then raise exception 'Target user required.' using errcode='22023'; end if;
    update public.chat_blocks set ends_at=now() where user_id=v_target_user and ends_at>now() and (p_channel_id is null or channel_id=p_channel_id);
  elsif p_action in ('dismiss_report','resolve_report') then
    if p_report_id is null then raise exception 'Report required.' using errcode='22023'; end if;
    update public.message_reports set status=case when p_action='dismiss_report' then 'dismissed' else 'actioned' end,reviewed_by=v_actor,reviewed_at=now() where id=p_report_id;
    if not found then raise exception 'Report not found.' using errcode='22023'; end if;
  else
    raise exception 'Unsupported moderation action.' using errcode='22023';
  end if;

  if p_report_id is not null and p_action in ('delete_message','block') then
    update public.message_reports set status='actioned',reviewed_by=v_actor,reviewed_at=now() where id=p_report_id;
  end if;

  insert into public.moderation_actions (actor_user_id,actor_role,action_type,channel_id,message_id,target_user_id,report_id,reason,metadata)
  values (v_actor,v_role,p_action,v_channel_id,p_message_id,v_target_user,p_report_id,p_reason,jsonb_build_object('duration_minutes',p_duration_minutes))
  returning id into v_action_id;
  return v_action_id;
end;
$$;

revoke all on function public.phase10_current_role() from public,anon;
revoke all on function public.phase10_is_moderator() from public,anon;
revoke all on function public.phase10_channel_visible_to_user(uuid,uuid) from public,anon,authenticated;
revoke all on function public.phase10_can_view_channel(uuid) from public,anon;
revoke all on function public.phase10_is_chat_blocked(uuid,uuid) from public,anon,authenticated;
revoke all on function public.phase10_can_write_channel(uuid) from public,anon;
revoke all on function public.phase10_sync_community_channels() from public,anon,authenticated;
revoke all on function public.phase10_reference_channel_sync_trigger() from public,anon,authenticated;
revoke all on function public.phase10_list_channels() from public,anon;
revoke all on function public.phase10_list_channel_members(text,integer) from public,anon;
revoke all on function public.phase10_create_message(text,text,uuid,uuid,uuid[]) from public,anon;
revoke all on function public.phase10_mark_read(text,bigint) from public,anon;
revoke all on function public.phase10_toggle_reaction(uuid,text) from public,anon;
revoke all on function public.phase10_report_message(uuid,text,text) from public,anon;
revoke all on function public.phase10_moderate(text,uuid,uuid,uuid,uuid,text,integer) from public,anon;

grant execute on function public.phase10_current_role() to authenticated,service_role;
grant execute on function public.phase10_is_moderator() to authenticated,service_role;
grant execute on function public.phase10_can_view_channel(uuid) to authenticated,service_role;
grant execute on function public.phase10_can_write_channel(uuid) to authenticated,service_role;
grant execute on function public.phase10_list_channels() to authenticated,service_role;
grant execute on function public.phase10_list_channel_members(text,integer) to authenticated,service_role;
grant execute on function public.phase10_create_message(text,text,uuid,uuid,uuid[]) to authenticated,service_role;
grant execute on function public.phase10_mark_read(text,bigint) to authenticated,service_role;
grant execute on function public.phase10_toggle_reaction(uuid,text) to authenticated,service_role;
grant execute on function public.phase10_report_message(uuid,text,text) to authenticated,service_role;
grant execute on function public.phase10_moderate(text,uuid,uuid,uuid,uuid,text,integer) to authenticated,service_role;

-- Realtime is scoped in the client to the active channel only.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='community_messages') then alter publication supabase_realtime add table public.community_messages; end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='message_reactions') then alter publication supabase_realtime add table public.message_reactions; end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='pinned_messages') then alter publication supabase_realtime add table public.pinned_messages; end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='community_notifications') then alter publication supabase_realtime add table public.community_notifications; end if;
end $$;

insert into public.app_settings (key,value,is_public)
values ('community.phase10','{"pagination":"sequence_cursor","realtime":"active_channel_only","max_message_chars":2000,"rate_limit_per_minute":12,"duplicate_window_seconds":90,"attachments":"approved_phase7_uploads_only","block_durations_minutes":[60,480,1440,2880]}'::jsonb,true)
on conflict (key) do update set value=excluded.value,is_public=excluded.is_public,updated_at=now();

insert into public.app_settings (key,value,is_public)
values ('app.phase','{"phase":10,"status":"community_v2_collaborative_learning"}'::jsonb,true)
on conflict (key) do update set value=excluded.value,is_public=excluded.is_public,updated_at=now();
