-- CA Progress V2 - Phase 2 authentication, profiles and onboarding
-- Apply only to the isolated V2 Supabase project.

alter table public.profiles
  add column ca_level text,
  add column group_choice text,
  add column attempt_key text,
  add column daily_target_minutes integer,
  add column onboarding_step smallint not null default 1,
  add column onboarding_completed_at timestamptz;

alter table public.profiles
  add constraint profiles_ca_level_check check (ca_level is null or ca_level in ('foundation', 'intermediate', 'final')),
  add constraint profiles_group_choice_check check (group_choice is null or group_choice in ('group_1', 'group_2', 'both', 'not_applicable')),
  add constraint profiles_daily_target_check check (daily_target_minutes is null or daily_target_minutes between 15 and 720),
  add constraint profiles_onboarding_step_check check (onboarding_step between 1 and 4);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (user_id, display_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (user_id) do nothing;

  insert into public.user_preferences (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create table public.auth_otp_rate_limits (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('request', 'verify')),
  phone_hash text not null,
  ip_hash text not null,
  requested_at timestamptz not null default now()
);

create index auth_otp_rate_limits_phone_idx
  on public.auth_otp_rate_limits (event_type, phone_hash, requested_at desc);
create index auth_otp_rate_limits_ip_idx
  on public.auth_otp_rate_limits (event_type, ip_hash, requested_at desc);

alter table public.auth_otp_rate_limits enable row level security;
revoke all on public.auth_otp_rate_limits from anon, authenticated;
-- Intentionally no client RLS policies. Phone rate limiting is service-role-only.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'avatars',
  'avatars',
  false,
  2097152,
  array['image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "avatars_select_own"
on storage.objects for select to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy "avatars_insert_own"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy "avatars_update_own"
on storage.objects for update to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

create policy "avatars_delete_own"
on storage.objects for delete to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = (select auth.uid())::text
);

insert into public.app_settings (key, value, is_public)
values (
  'onboarding.attempt_options',
  '{"options":[{"key":"undecided","label":"Not decided yet","kind":"non_academic_placeholder"}],"source":"phase2-bootstrap","note":"Verified academic attempts replace this placeholder in Phase 3."}'::jsonb,
  true
)
on conflict (key) do update set value = excluded.value, is_public = true, updated_at = now();

insert into public.app_settings (key, value, is_public)
values ('app.phase', '{"phase":2,"status":"authentication"}'::jsonb, true)
on conflict (key) do update set value = excluded.value, is_public = true, updated_at = now();
