-- CA Progress V2 - Phase 3 CA Syllabus & Academic Data Engine
-- Apply only to the isolated V2 Supabase project.
-- Seeded academic metadata is tracked separately in supabase/seed/phase3_verified_icai_catalog.sql.

create table public.course_levels (
  id text primary key,
  code text not null unique check (code in ('foundation', 'intermediate', 'final')),
  name text not null,
  sort_order smallint not null check (sort_order > 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.course_groups (
  id text primary key,
  level_id text not null references public.course_levels(id) on delete restrict,
  code text not null,
  name text not null,
  sort_order smallint not null check (sort_order > 0),
  is_default boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (level_id, code),
  unique (level_id, id)
);

create table public.subjects (
  id text primary key,
  level_id text not null references public.course_levels(id) on delete restrict,
  group_id text not null,
  code text not null unique,
  slug text not null unique,
  paper_label text not null,
  title text not null,
  subject_kind text not null default 'standard' check (subject_kind in ('standard', 'combined', 'case_study')),
  sort_order smallint not null check (sort_order > 0),
  is_active boolean not null default true,
  source_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (level_id, group_id) references public.course_groups(level_id, id) on delete restrict
);

create table public.syllabus_versions (
  id text primary key,
  subject_id text not null references public.subjects(id) on delete restrict,
  version_key text not null,
  title text not null,
  effective_from date not null,
  effective_to date,
  status text not null check (status in ('published', 'superseded', 'upcoming')),
  supersedes_version_id text references public.syllabus_versions(id) on delete restrict,
  source_url text not null,
  source_label text not null default 'ICAI Board of Studies',
  source_verified_at timestamptz not null,
  verification_method text not null default 'manual_verified_import' check (verification_method in ('manual_verified_import', 'official_sync')),
  content_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (effective_to is null or effective_to >= effective_from),
  unique (subject_id, version_key),
  unique (subject_id, id)
);

create table public.chapters (
  id text primary key,
  syllabus_version_id text not null references public.syllabus_versions(id) on delete restrict,
  stable_key text not null,
  section_key text,
  chapter_number text not null,
  title text not null,
  slug text not null,
  chapter_kind text not null default 'chapter' check (chapter_kind in ('chapter', 'special_unit')),
  sort_order integer not null check (sort_order > 0),
  source_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (syllabus_version_id, stable_key),
  unique (syllabus_version_id, slug)
);

create table public.topics (
  id text primary key,
  chapter_id text not null references public.chapters(id) on delete restrict,
  stable_key text not null,
  unit_number text,
  title text not null,
  topic_kind text not null default 'unit' check (topic_kind in ('unit', 'accounting_standard', 'case_component', 'section')),
  sort_order integer not null check (sort_order > 0),
  source_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (chapter_id, stable_key)
);

create table public.attempt_syllabus_map (
  id bigint generated by default as identity primary key,
  attempt_key text not null,
  level_id text not null references public.course_levels(id) on delete restrict,
  group_id text not null references public.course_groups(id) on delete restrict,
  subject_id text not null references public.subjects(id) on delete restrict,
  syllabus_version_id text not null,
  created_at timestamptz not null default now(),
  foreign key (subject_id, syllabus_version_id) references public.syllabus_versions(subject_id, id) on delete restrict,
  unique (attempt_key, syllabus_version_id)
);

create table public.academic_change_events (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  summary text not null,
  source_url text,
  created_at timestamptz not null default now()
);

create index course_groups_level_idx on public.course_groups (level_id, sort_order);
create index subjects_level_group_idx on public.subjects (level_id, group_id, sort_order);
create index syllabus_versions_subject_idx on public.syllabus_versions (subject_id, effective_from desc);
create index chapters_version_idx on public.chapters (syllabus_version_id, sort_order);
create index topics_chapter_idx on public.topics (chapter_id, sort_order);
create index attempt_syllabus_lookup_idx on public.attempt_syllabus_map (attempt_key, level_id, group_id, subject_id);
create index subjects_title_lower_idx on public.subjects (lower(title));
create index chapters_title_lower_idx on public.chapters (lower(title));
create index topics_title_lower_idx on public.topics (lower(title));

create trigger course_levels_set_updated_at before update on public.course_levels for each row execute function public.set_updated_at();
create trigger course_groups_set_updated_at before update on public.course_groups for each row execute function public.set_updated_at();
create trigger subjects_set_updated_at before update on public.subjects for each row execute function public.set_updated_at();
create trigger syllabus_versions_set_updated_at before update on public.syllabus_versions for each row execute function public.set_updated_at();
create trigger chapters_set_updated_at before update on public.chapters for each row execute function public.set_updated_at();
create trigger topics_set_updated_at before update on public.topics for each row execute function public.set_updated_at();

alter table public.course_levels enable row level security;
alter table public.course_groups enable row level security;
alter table public.subjects enable row level security;
alter table public.syllabus_versions enable row level security;
alter table public.chapters enable row level security;
alter table public.topics enable row level security;
alter table public.attempt_syllabus_map enable row level security;
alter table public.academic_change_events enable row level security;

create policy "course_levels_read" on public.course_levels for select to anon, authenticated using (true);
create policy "course_groups_read" on public.course_groups for select to anon, authenticated using (true);
create policy "subjects_read" on public.subjects for select to anon, authenticated using (true);
create policy "syllabus_versions_read" on public.syllabus_versions for select to anon, authenticated using (true);
create policy "chapters_read" on public.chapters for select to anon, authenticated using (true);
create policy "topics_read" on public.topics for select to anon, authenticated using (true);
create policy "attempt_syllabus_map_read" on public.attempt_syllabus_map for select to anon, authenticated using (true);

grant select on public.course_levels, public.course_groups, public.subjects, public.syllabus_versions, public.chapters, public.topics, public.attempt_syllabus_map to anon, authenticated;
revoke insert, update, delete, truncate, references, trigger on public.course_levels, public.course_groups, public.subjects, public.syllabus_versions, public.chapters, public.topics, public.attempt_syllabus_map from anon, authenticated;
revoke all on public.academic_change_events from anon, authenticated;

insert into public.app_settings (key, value, is_public)
values ('academic.catalog', '{"source":"ICAI Board of Studies","verification":"manual_verified_import","phase":3}'::jsonb, true)
on conflict (key) do update set value = excluded.value, is_public = true, updated_at = now();

insert into public.app_settings (key, value, is_public)
values ('app.phase', '{"phase":3,"status":"academic_data_engine"}'::jsonb, true)
on conflict (key) do update set value = excluded.value, is_public = true, updated_at = now();
