import Link from "next/link";
import { requireAdminPageCapability } from "@/lib/authorization/server";
import { CONTROL_AREAS, listControlVersions } from "@/lib/admin/control-centre";
import { hasAdminCapability } from "@/lib/authorization/capabilities.mjs";
import { publishVersionAction, saveDraftAction } from "./actions";
export const dynamic="force-dynamic";
const box:React.CSSProperties={padding:18,border:"1px solid var(--border,#e8e5ee)",borderRadius:14,background:"var(--surface,#fff)"};
const field:React.CSSProperties={display:"grid",gap:6};
export default async function ControlPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const actor=await requireAdminPageCapability("admin.dashboard.read"); const p=await searchParams;
  const versions=await listControlVersions({area:p.area,state:p.state,query:p.q});
  return <main style={{maxWidth:1240,margin:"0 auto",padding:"28px 22px 52px"}}>
    <header><p className="eyebrow">OPERATOR CONTROLS</p><h1>Control centre</h1><p>Create a reviewed draft, publish it, or restore an earlier version. Technical details stay inside expandable sections.</p></header>
    {p.notice?<p role="status" className="ui-notice ui-notice--success">{p.notice}</p>:null}
    <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:10,margin:"20px 0"}}>{CONTROL_AREAS.map(a=><Link key={a.key} href={a.href} style={{...box,color:"inherit",textDecoration:"none"}}><strong>{a.label}</strong><div style={{marginTop:6,fontSize:13,color:"var(--muted-foreground,#6f6a78)"}}>Open workspace →</div></Link>)}</section>
    <section style={box}><h2 style={{marginTop:0}}>Preview as student</h2><p>Choose an academic context on the syllabus preview, then open the real student surface without changing any student record.</p><Link className="ui-button ui-button--secondary" href="/admin/syllabus">Select student context</Link></section>
    <form method="get" style={{...box,display:"flex",gap:10,flexWrap:"wrap",marginTop:16}}><input name="q" defaultValue={p.q} placeholder="Search versions"/><select name="area" defaultValue={p.area??""}><option value="">All areas</option>{CONTROL_AREAS.map(a=><option key={a.key} value={a.key}>{a.label}</option>)}</select><select name="state" defaultValue={p.state??""}><option value="">All states</option><option value="draft">Draft</option><option value="published">Published</option><option value="superseded">Previous</option></select><button className="ui-button ui-button--secondary">Filter</button></form>
    {CONTROL_AREAS.some(a=>hasAdminCapability(actor.role,a.capability))?<details style={{...box,marginTop:16}}><summary style={{cursor:"pointer",fontWeight:700}}>Create configuration draft</summary><form action={saveDraftAction} style={{display:"grid",gap:12,marginTop:16}}><label style={field}>Area<select name="area" required defaultValue=""><option value="" disabled>Select area</option>{CONTROL_AREAS.filter(a=>hasAdminCapability(actor.role,a.capability)).map(a=><option key={a.key} value={a.key}>{a.label}</option>)}</select></label><label style={field}>Document key<input name="documentKey" required pattern="[A-Za-z0-9._-]+"/></label><label style={field}>Title<input name="title" required maxLength={120}/></label><label style={field}>Change reason<textarea name="reason" required minLength={8}/></label><label style={field}>Configuration JSON<textarea name="config" required defaultValue="{}" rows={8}/></label><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()}/><button className="ui-button ui-button--primary">Save draft</button></form></details>:null}
    <section style={{display:"grid",gap:10,marginTop:16}}>{versions.length?versions.map(v=>{const area=CONTROL_AREAS.find(a=>a.key===v.area_key);const canPublish=!!area&&hasAdminCapability(actor.role,area.capability);return <article key={String(v.id)} style={box}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>{String(v.title)}</strong><div style={{fontSize:13,marginTop:4}}>{area?.label??String(v.area_key)} · {String(v.document_key)} · version {String(v.version)}</div></div><span className={`ui-badge ui-badge--${Number(v.is_live)===1?"success":v.state==="draft"?"warning":"neutral"}`}>{Number(v.is_live)===1?"Live":v.state==="draft"?"Draft":"Previous"}</span></div><p style={{fontSize:13}}>{String(v.change_reason)}</p><details><summary>Configuration details</summary><pre style={{whiteSpace:"pre-wrap",overflow:"auto"}}>{JSON.stringify(JSON.parse(String(v.config_json)),null,2)}</pre></details>{canPublish&&Number(v.is_live)!==1?<form action={publishVersionAction} style={{display:"flex",gap:8,marginTop:12,flexWrap:"wrap"}}><input type="hidden" name="id" value={String(v.id)}/><input type="hidden" name="area" value={String(v.area_key)}/><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()}/><input name="reason" required minLength={8} placeholder={v.state==="draft"?"Publish reason":"Rollback reason"}/><button className="ui-button ui-button--secondary">{v.state==="draft"?"Publish":"Restore this version"}</button></form>:null}</article>}):<div style={box}>No configuration versions match these filters.</div>}</section>
  </main>;
}
